### PR TITLE
add mmap support and some cleanups to bcm2835 ALSA driver

### PR DESCRIPTION
**Pull request by martinezjavier**
Hello,

This series contains the following improvements to the ALSA bcm2835 driver:
- Use the kernel provided facility to wait for completion instead of an
  ad-hoc implementation using semaphores.
- Add defined constants to specify the deferred action to be processed by the
  driver workqueue instead of using magic numbers.
- Include PCM samples write in the deferred operations handled by the workqueue
- Add mmap support to allow Direct Read/Write transfers.
- Remove unnecessary log when the driver probe function is called if debug is
  not enabled. Also replace printk() usage by more suitable functions.

and fixes these open issues:

raspberrypi/linux#158 "bcm2835 ALSA driver hardware mixing or mmap?"
raspberrypi/firmware#173 "ALSA is not supporting 16 bits signed audio"
raspberrypi/linux#282 "ALSA boot messages"

The following changes since commit 07b8b7dbc2d698114a59c328c5e24681a12da6ca:

  Merge pull request #279 from P33M/rpi-3.6.y (2013-04-22 08:08:49 -0700)

are available in the git repository at:

  git://github.com/martinezjavier/linux-rpi.git rpi-3.6.y-dev

Javier Martinez Canillas (5):
      ALSA: bcm2835: show card and subdev creation msg only on debug
      ALSA: bcm2835: use a completion instead of a semaphore for sync
      ALSA: bcm2835: don't use magic numbers on audio start/stop workqueue
      ALSA: bcm2835: defer bcm2835 PCM write using the workqueue
      ALSA: bcm2835: add memory-mapped I/O mode for audio stream

 sound/arm/bcm2835-pcm.c   |   69 ++++++++++++++++++++++-------------
 sound/arm/bcm2835-vchiq.c |   89 +++++++++++++++++++++++++++++++--------------
 sound/arm/bcm2835.c       |   34 +++++++++---------
 sound/arm/bcm2835.h       |    2 +
 4 files changed, 124 insertions(+), 70 deletions(-)

Thanks a lot and best regards,
Javier

### CODE REVIEW

**Comment by popcornmix** [comment]
With original driver:

```
$ sudo espeak "hello from me"
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_direct.c:877:(snd1_pcm_direct_initialize_slave) slave plugin does not support mmap interleaved or mmap noninterleaved access
ALSA lib pcm_dmix.c:1030:(snd_pcm_dmix_open) unable to initialize slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
```

Lots of complaints, but I hear the audio.

With your patch

```
$ sudo espeak "hello from me"
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
```

and no audio output. Any idea why? (and why so many warnings).

**Comment by popcornmix** [comment]
```
 mplayer  audio/Franz\ Ferdinand\ -\ Take\ Me\ Out.mp3
```

Works correctly without patch. I've had silence, squawks and a hang with the patch.

**Comment by martinezjavier** [comment]
weird, I tested with aplay, mpg123, jackd and this Gstreamer pipeline:

```
$ gst-launch-0.10 -v audiotestsrc ! queue ! audio/x-raw-int, width=16, signed=true ! alsasink
```

all of them worked for me.

I'll test with mplayer and espeak to see why you are having these issues.

Btw, did you remove the /etc/asound.conf that is adding mmap emulation? You shouldn't use that plug-in since the driver now supports it (in fact it won't work when using).

I'm using this asound.conf:

```
pcm.!default {
    type hw
    card 0
}

ctl.!default {
    type hw
    card 0
}
```

But is works when trying with no asound at all too.

**Comment by martinezjavier** [comment]
When you said with your patch, you mean with the patch-set right? or are you testing each patch separately?

These two patches should be applied together:
    ALSA: bcm2835: defer bcm2835 PCM write using the workqueue
    ALSA: bcm2835: add memory-mapped I/O mode for audio stream

Since the later won't work without the former. I tried to keep the changes separated to make it easier to review to you, maybe I should squash these two...

**Comment by popcornmix** [comment]
I was using (I think) the default asound.conf:

```
pcm.mmap0 {
    type mmap_emul;
    slave {
      pcm "hw:0,0";
    }
}

pcm.!default {
  type plug;
  slave {
    pcm mmap0;
  }
}
```

It was still largely working. mplayer worked with a wav file, but not mp3. mpg123 worked with mp3 file.
mame worked, flite worked.

I've just tried with your asound and it works in the two cases I'd reported as not working.
Also works without an asound.conf. What do you recommend?

I think we'll get some confusion with people updating kernel on a standard raspbian image (so using mmap_emul), but perhaps that the price of progress. We'll remove mmap_emul in next official image.

(I'm testing the patch as a whole (286.diff).

**Comment by asb** [comment]
We can sort out asound.conf upon upgrade (for those updating via apt-get
anyway).

**Comment by martinezjavier** [comment]
@popcornmix 

Yes, if you have mmap emulation on your asound.conf and the driver supports mmap then it will work as long as applications are only using ALSA read/write PCM transfer API (snd_pcm_{writei, readi}) but is not going to work if is using mmap direct r/w API  calls (snd_pcm_mmap_{begin, commit, readi, writei})

You can see the difference with aplay:

```
$ aplay test.wav
```

works but

```
$ aplay -M test.wav
```

does not.

I'm not familiarized with asound mmap emulation plug-in but _I guess_ that when an application is trying to use the ALSA mmap API then the PCM is written twice: one by ALSA when snd_pcm_mmap_commit() is called and another time by libasound mmap emulation plug-in that breaks the buffer in many calls to snd_pcm_writei().

Anyway, as you said the solution is to remove mmap_emul.

I don't know what option is better for raspbian, if an asound.conf without mmap emulation should be shipped or no asound.conf at all.

But as @asb said, this can be sorted out for people updating via apt.

**Comment by popcornmix** [comment]
Yes, new images, and apt-get upgrade users will have no problem.
rpi-update (and kernel compilers) may have a problem. I'll go with "sudo rm /etc/asound.conf" as the advice for now.

Thanks for the PR, it looks good.

**Comment by martinezjavier** [comment]
thanks a lot for feedback and testing!

**Comment by popcornmix** [comment]
There's a report of a regression from this patch in espeak:
https://github.com/raspberrypi/linux/issues/304

**Comment by martinezjavier** [comment]
@popcornmix 

Thanks for the notice. I'll take a look at this bug.

Regards

**Comment by popcornmix** [comment]
@martinezjavier 
Did you reproduce the espeak problem?

**Comment by martinezjavier** [comment]
@popcornmix 

Not yet, sorry. This month I've been very busy and didn't have time to work on this issue.

I'll try to get some free time during the weekend to debug this further.

**Comment by popcornmix** [comment]
@martinezjavier 
Any news on the espeak breakage? Another report of problems here:
https://github.com/raspberrypi/linux/issues/388#issuecomment-32478104

**Pull request merged**
