### PR TITLE
Update dvb-usb-ids.h

### PR DESCRIPTION
**Pull request by CandymanRv**
Added CableStar Device

view here:
http://linuxtv.org/wiki/index.php/TechniSat_CableStar_Combo_HD_CI

### CODE REVIEW

**Comment by popcornmix** [comment]
Can you close this PR and include this in #449.

**Comment by CandymanRv** [comment]
well, i would do that, if i know how. i'm sorry, but i'm new in here

**Comment by popcornmix** [comment]
Something like this:

```
git checkout patch-2
git add drivers/media/dvb-core/dvb-usb-ids.h 
git commit --amend
git push -f
```

should make th header file appear in #449.
If that works you can close this PR.

**Comment by CandymanRv** [comment]
I have done my changes through the browser, i have no git repository here on my machine.
I tried to find a solution in the browser, but i think there is no way to do that. :(

**Comment by popcornmix** [comment]
This is now in.

**Pull request closed without merging**
