### PR TITLE
Add BCM2708_UNCOMPRESS_INFO option

### PR DESCRIPTION
**Pull request by kylefrombullex**
Add a configuration option that can enable or disable the
uncompress info on the BCM2708 and BCM2709 family of processors.
Disabling this can be handy if the UART pin is needed for something
else, and the user does not want the info to be sent out on the
UART.

### CODE REVIEW

**Comment by kylefrombullex** [comment]
It looks like the 3.19.y branch changed since I submitted this pull request, because now a whole bunch of new commits are showing. Should I submit this request to the 3.18.y branch instead?

**Comment by popcornmix** [comment]
3.19 tree does get rebased on upstream point updates. You should be able to rebase your patch and force push to fix this PR.

**Comment by kylefrombullex** [comment]
Alright, I rebased. However, this patch is probably applicable to 3.18.y as well, so should I submit to 3.18.y anyway?

**Comment by notro** [comment]
PR #1005 adds uart0 to the Device Tree.
When that PR is pulled, the Uncompress message can be silenced without rebuilding the kernel.
(actually it is possible with the current kernel also using a different overlay, but I haven't tested that)

Firmware, dt-blob.dts: set uart0 pins to input/output, which results in Linux serial output going into the void:

``` diff
-            pin@p14 { function = "uart0";  termination = "no_pulling"; drive_strength_mA = < 8 >; }; // TX uart0
-            pin@p15 { function = "uart0";  termination = "pull_up"; drive_strength_mA = < 8 >; }; // RX uart0
+            pin@p14 { function = "output"; startup_state = "active"; termination = "no_pulling"; drive_strength_mA = < 8 >; }; // TX uart0
+            pin@p15 { function = "input";  termination = "pull_up"; drive_strength_mA = < 8 >; }; // RX uart0

```

Ref: https://www.raspberrypi.org/documentation/configuration/pin-configuration.md

Device Tree overlay to set the uart0 pins back when the driver is probed:

```
/dts-v1/;
/plugin/;

/ {
    compatible = "brcm,bcm2835", "brcm,bcm2708", "brcm,bcm2709";

    fragment@0 {
        target = <&gpio>;
        __overlay__ {
            uart0_pins: uart0_pins {
                brcm,pins = <14 15>;
                brcm,function = <4>; /* alt0 */
            };
        };
    };

    fragment@1 {
        target = <&uart0>;
        __overlay__ {
            /* needed to avoid dtc warning */
            #address-cells = <1>;
            #size-cells = <0>;

            pinctrl-names = "default";
            pinctrl-0 = <&uart0_pins>;
        };
    };
};

```

Ref: https://www.raspberrypi.org/documentation/configuration/device-tree.md

Voila, no more `Uncompressing Linux... done, booting the kernel.` message:

```
[  688.372968] reboot: Restarting system
[    0.000000] Booting Linux on physical CPU 0x0
```

Finally remove `console=ttyAMA0,115200` from /boot/cmdline.txt.

**Comment by popcornmix** [comment]
Closing as I believe the solution @notro has outlined is preferable.

**Pull request closed without merging**
