### PR TITLE
device tree overlay simple audio card for ssm2602 (help wanted)

### PR DESCRIPTION
**Pull request by branch14**
@pelwell thanks for the pointer to simple-audio-card overlay. This is how far we got.

Devices show up. But recording fails with "arecord: set_params:1297: Unable to install hw params".

```
i@raspberrypi:~ $ arecord -L
null
    Discard all samples (playback) or generate zero samples (capture)
dsnooped
default:CARD=ssm2602
    ssm2602, 
    Default Audio Device
sysdefault:CARD=ssm2602
    ssm2602, 
    Default Audio Device
dmix:CARD=ssm2602,DEV=0
    ssm2602, 
    Direct sample mixing device
dsnoop:CARD=ssm2602,DEV=0
    ssm2602, 
    Direct sample snooping device
hw:CARD=ssm2602,DEV=0
    ssm2602, 
    Direct hardware device without any conversions
plughw:CARD=ssm2602,DEV=0
    ssm2602, 
    Hardware device with all software conversions
```

Recording fails.

```
pi@raspberrypi:~ $ arecord -D hw:1 -f S24_LE -c 2
Recording WAVE 'stdin' : Signed 24 bit Little Endian, Rate 8000 Hz, Stereo
arecord: set_params:1297: Unable to install hw params:
ACCESS:  RW_INTERLEAVED
FORMAT:  S24_LE
SUBFORMAT:  STD
SAMPLE_BITS: 32
FRAME_BITS: 64
CHANNELS: 2
RATE: 8000
PERIOD_TIME: 125000
PERIOD_SIZE: 1000
PERIOD_BYTES: 8000
PERIODS: 4
BUFFER_TIME: 500000
BUFFER_SIZE: 4000
BUFFER_BYTES: 32000
TICK_TIME: 0
```

We're using a SSM2603-EVALZ with the following wiring:

```
Pin 03 (I2C SDA1)   - SDA (I2C)
Pin 05 (I2C SCL1)   - SCL (I2C)
Pin 12 (I2S BITCLK) - BCLK (I2S)
Pin 35 (I2S LRCK)   - RECLRC (I2S)
Pin 38 (I2S DIN)    - RECDAT (I2S)
```

### CODE REVIEW

**Comment by pelwell** [comment]
Thanks for being patient. Can you try adding:
```
            codec_dai: simple-audio-card,codec {
                sound-dai = <&ssm2602_codec>;
                system-clock-frequency = <12000000>; // <=== INSERT
             };
```
I'm hoping this is equivalent to the call to snd_soc_dai_set_sysclk in your dedicated driver.

**Comment by branch14** [comment]
@pelwell Thanks for your patience.

Unfortunately, it doesn't seem to have much effect.

```
pi@raspberrypi:~ $ arecord -D hw:0 -f S24_LE -c 2
Recording WAVE 'stdin' : Signed 24 bit Little Endian, Rate 8000 Hz, Stereo
arecord: set_params:1297: Unable to install hw params:
ACCESS:  RW_INTERLEAVED
FORMAT:  S24_LE
SUBFORMAT:  STD
SAMPLE_BITS: 32
FRAME_BITS: 64
CHANNELS: 2
RATE: 8000
PERIOD_TIME: 125000
PERIOD_SIZE: 1000
PERIOD_BYTES: 8000
PERIODS: 4
BUFFER_TIME: 500000
BUFFER_SIZE: 4000
BUFFER_BYTES: 32000
TICK_TIME: 0
```

```
pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: ssm2602 [ssm2602], device 0: bcm2835-i2s-ssm2602-hifi ssm2602-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

```
pi@raspberrypi:~ $ arecord -D hw:0
Recording WAVE 'stdin' : Unsigned 8 bit, Rate 8000 Hz, Mono
arecord: set_params:1233: Sample format non available
Available formats:
- S16_LE
- S24_LE
- S32_LE
```

**Comment by pelwell** [comment]
Hmm. I don't have anything based on the ssm2602, but I do have a few soundcards with I2C-addressable codecs, so I plugged on in and hacked your overlay use the corresponding I2C address. I also hacked the ssm2602 driver to put some debug logging in, and added the codec to the defconfg files (we must make sure your PR does the same).

I expected some part of the setup to fail because of some difference in the I2C register set (it turns out the interface is write-only), or to see a failing attempt to configure the hwparams, but instead I got:
```
pi@raspberrypi ~ $ arecord -D hw:0 -f S24_LE -c 2
Recording WAVE 'stdin' : Signed 24 bit Little Endian, Rate 8000 Hz, Stereo
RIFF$�WAVEfmt @data�

^CAborted by signal Interrupt...
```
It just worked. My kernel log reported:
```
[   15.267462] ssm2602_probe
[   15.267499] ssm2602_probe -> 0
...
[   86.161376] ssm2602_get_coeff(12000000, 8000) -> 13
```
Notice the `system-clock-frequency` value as the first parameter.

The driver is clearly probing for you so you don't need to add that tracing, but can you apply this patch and see what output you get:
```diff
diff --git a/sound/soc/codecs/ssm2602.c b/sound/soc/codecs/ssm2602.c
index 993bde2..aa7322f 100644
--- a/sound/soc/codecs/ssm2602.c
+++ b/sound/soc/codecs/ssm2602.c
@@ -278,6 +278,8 @@ static int ssm2602_hw_params(struct snd_pcm_substream *substream,
        int srate = ssm2602_get_coeff(ssm2602->sysclk, params_rate(params));
        unsigned int iface;
 
+       pr_err("ssm2602_get_coeff(%d, %d) -> %d\n", ssm2602->sysclk,
+              params_rate(params), srate);
        if (srate < 0)
                return srate;
 
```

**Comment by pelwell** [comment]
For comparison, without the system-clock-frequency commit I get:
```
pi@raspberrypi ~ $ arecord -D hw:0 -f S24_LE -c 2
Recording WAVE 'stdin' : Signed 24 bit Little Endian, Rate 8000 Hz, Stereo
arecord: set_params:1297: Unable to install hw params:
ACCESS:  RW_INTERLEAVED
FORMAT:  S24_LE
SUBFORMAT:  STD
SAMPLE_BITS: 32
FRAME_BITS: 64
CHANNELS: 2
RATE: 8000
PERIOD_TIME: 125000
PERIOD_SIZE: 1000
PERIOD_BYTES: 8000
PERIODS: 4
BUFFER_TIME: 500000
BUFFER_SIZE: 4000
BUFFER_BYTES: 32000
TICK_TIME: 0
```
and
```
[   54.490896] ssm2602_get_coeff(0, 8000) -> -22
[   54.490922] ssm2602 1-0068: ASoC: can't set ssm2602-hifi hw params: -22
```

**Comment by branch14** [comment]
@pelwell I applied your patch.

```
pi@raspberrypi:~ $ dmesg | grep ssm26
[    3.438944] asoc-simple-card soc:sound: ssm2602-hifi <-> 3f203000.i2s mapping ok
[    7.130599] ssm2602_get_coeff(0, 44100) -> -22
[    7.130613] ssm2602 1-001b: ASoC: can't set ssm2602-hifi hw params: -22
```

And plenty more of the last two messages.

I don't get the `_probe` messages.

What do you mean by "added the codec to the defconfg files"?

**Comment by pelwell** [comment]
That tracing suggests that the installed overlay doesn't actually contain the system-clock-frequency property. What do you get from running:
```
hexdump /proc/device-tree/soc/sound/simple-audio-card,codec/system-clock-frequency
```

A standard firmware release does not currently include the driver module for the ssm2602 codec. To add it you need to set a kernel config option - CONFIG_SND_SOC_SSM2602_I2C. All of our builds use the config settings in `arch/arm/configs/bcmrpi_defconfig` and `arch/arm/configs/bcm2709_defconfig`, which are generated using the savedefconfig option, but I can show you the changes needed:
```diff
diff --git a/arch/arm/configs/bcm2709_defconfig b/arch/arm/configs/bcm2709_defconfig
index 7f46612..e285f14 100644
--- a/arch/arm/configs/bcm2709_defconfig
+++ b/arch/arm/configs/bcm2709_defconfig
@@ -905,6 +905,7 @@ CONFIG_SND_PISOUND=m
 CONFIG_SND_SOC_ADAU1701=m
 CONFIG_SND_SOC_ADAU7002=m
 CONFIG_SND_SOC_AK4554=m
+CONFIG_SND_SOC_SSM2602_I2C=m
 CONFIG_SND_SOC_WM8804_I2C=m
 CONFIG_SND_SIMPLE_CARD=m
 CONFIG_SOUND_PRIME=m
diff --git a/arch/arm/configs/bcmrpi_defconfig b/arch/arm/configs/bcmrpi_defconfig
index b455404..6804c0d 100644
--- a/arch/arm/configs/bcmrpi_defconfig
+++ b/arch/arm/configs/bcmrpi_defconfig
@@ -899,6 +899,7 @@ CONFIG_SND_PISOUND=m
 CONFIG_SND_SOC_ADAU1701=m
 CONFIG_SND_SOC_ADAU7002=m
 CONFIG_SND_SOC_AK4554=m
+CONFIG_SND_SOC_SSM2602_I2C=m
 CONFIG_SND_SOC_WM8804_I2C=m
 CONFIG_SND_SIMPLE_CARD=m
 CONFIG_SOUND_PRIME=m
```

**Comment by branch14** [comment]
@pelwell Chapeau! I missed those. I ran `make menuconfig` and selected what I deemed to be required modules. I guess that either wasn't enough or I missed this module.

Now it's looking good. :smiley:

```
pi@raspberrypi:~ $ dmesg | grep ssm2602
[    2.822509] asoc-simple-card soc:sound: ssm2602-hifi <-> 3f203000.i2s mapping ok
[    5.805343] ssm2602_get_coeff(12000000, 44100) -> 35
[  198.421743] ssm2602_get_coeff(12000000, 8000) -> 13
```

```
pi@raspberrypi:~ $ arecord -D hw:1 -f S24_LE -c 2
Recording WAVE 'stdin' : Signed 24 bit Little Endian, Rate 8000 Hz, Stereo
RIFF$�WAVEfmt @data�
```

I'll do some more testing with this setup by end of the week.

**Comment by pelwell** [comment]
That's good news. When you're happy everything is working, remove the pr_err debug output and I'll squash and merge it all.

**Comment by branch14** [comment]
I did a quick test. Connected a audio source to line in and a headset to mic (to have signals on both). But the recording only yields perfect silence.

In a subsequent test I played a wave file with content and connected my headphones first to `hp out`, then to `line out`, only silence.

Additionally I don't get those spikes on the head phones which one usually gets when plugging the jack in. This raises my suspicion that the ssm2602 is not properly set up yet, and thus does not route (neither send nor receive) anything yet.

**Comment by branch14** [comment]
@pelwell Is it possible to set registers via I2C in the device tree overlay? Or is that the responsibility of the driver? Reading the ssm2603's data sheet I got the impression that it might need more configuration in order to "know" what to do, as it comes with more options than a simple audio card.

My primary sources of information are

* http://www.analog.com/media/en/technical-documentation/data-sheets/SSM2603.pdf
* https://wiki.analog.com/resources/tools-software/linux-drivers/sound/ssm2602

**Comment by pelwell** [comment]
Manipulating the I2C registers on a codec is the responsibility of the codec driver. ALSA tells the codec driver what it wants, and the driver converts that into I2C transfers. The "simple" card is simple because it assumes that no additional hardware setup (toggling amplifiers, clock control etc.) is required, and that the natural bclk ratio is used.

I suggested using simple-audio-card based on the fact that the soundcard driver in #2005 doesn't do any kind of dynamic configuration. If you revert to using that driver, does audio capture work as expected? If it does then we can narrow down the differences between the two configurations.

**Comment by branch14** [comment]
#2005 didn't work. And frankly I've no idea how far off it is or what it takes to for a working version.

The only platform for which the driver for ssm2602 is working is blackfin. I'll try to find out what it takes in the means of manipulating I2C registers to get the ssm2602 initialized.

As I'll be back to the office mid next week this will take a while.

**Comment by pelwell** [comment]
I would focus on the #2005 driver - simple-audio-card isn't capable of any kind of non-standard configuration.

I'm sorry to have distracted you with the simple overlay, but I assumed that you wouldn't submit a driver that doesn't work to some extent.

**Comment by branch14** [comment]
I contacted @mhennerich from Analog Devices via email, as he seems to be the go to guy for ssm2602 linux support, asking if he is willing to share some insights.

**Comment by dbogdan** [comment]
@branch14, ADI is offering support through the EZ forum (ez.analog.com), so please use it instead of emails.

Usually, if you don't get any errors, but you don't hear anything, it means that you didn't setup a proper routing path or you didn't unmute the volume controls. The routing is configured through ALSA mixer. Can you show us your configuration?

**Comment by branch14** [comment]
@dbogdan Still can record silence, but if I try to use alsamixer on the device I get an error.

```
pi@raspberrypi:~ $ cat /proc/asound/cards 
 0 [ALSA           ]: bcm2835 - bcm2835 ALSA
                      bcm2835 ALSA
 1 [ssm2602        ]: ssm2602 - ssm2602
                      ssm2602
pi@raspberrypi:~ $ arecord -D hw:1 -f S24_LE -c 2
Recording WAVE 'stdin' : Signed 24 bit Little Endian, Rate 8000 Hz, Stereo
RIFF$�WAVEfmt @data�^CAborted by signal Interrupt...
pi@raspberrypi:~ $ alsamixer -c 1
cannot load mixer controls: Input/output error
```

As suggested by @pelwell I'll look into the approach of #2005.

**Comment by JamesH65** [comment]
No activity for over a year. This issue will be closed within 30 days unless further interactions are posted. If you wish this issue to remain open, please add a comment. A closed issue may be reopened if requested.

**Comment by JamesH65** [comment]
Closing due to lack of activity. Please request to be reopened if you feel this issue is still relevant.

**Pull request closed without merging**
