### PR TITLE
.github/workflows: Correct kernel builds artifacts

### PR DESCRIPTION
**Pull request by pelwell**
Modify the kernel build workflow to create artifacts with the correct names and structure, both as an example of what we expect and in case anyone wants to use the output.

Signed-off-by: Phil Elwell <phil@raspberrypi.com>

### CODE REVIEW

**Comment by pelwell** [comment]
This PR currently includes the reversion of a recent commit in order to trigger the build workflow; simply changing the workflow file is not sufficient. The reversion will be dropped before merging.

**Comment by pelwell** [comment]
I think this is good to go now. Can you cast your eye over it, @6by9?

**Comment by 6by9** [comment]
Looks reasonable.

There was a comment made on the initial workflows to use the matrix stuff, but it's not bubbled up the priorities again yet.
https://github.com/nbuchwitz/actions-examples/blob/main/.github/workflows/test1.yml was given as the example that removed almost all the duplication.

**Comment by pelwell** [comment]
It does look better after deduplication (I met @nbuchwitz recently), but I'll save that for another PR.

**Comment by pelwell** [comment]
Matrix build PR here: https://github.com/raspberrypi/linux/pull/5333

**Pull request merged**
