### PR TITLE
add additional overrides to rotary-encoder overlay

### PR DESCRIPTION
**Pull request by shawaj**
Updates to the rotary-encoder overlay to add additional overrides that are possible according to this doc - https://elixir.free-electrons.com/linux/latest/source/Documentation/devicetree/bindings/input/rotary-encoder.txt

See #2331 for more details also

### CODE REVIEW

**Comment by pelwell** [comment]
I've removed the trailing whitespace, but now your overlay seems to be knobless.

**Comment by shawaj** [comment]
Darn! I guess I should change "knob" to "rotary0"?

**Comment by pelwell** [comment]
Or vice versa - as long as everything agrees it doesn't matter.

**Comment by pelwell** [comment]
You also need to think about the types of the properties you are applying the overrides to - currently all the new parameters are declared to target strings.

**Comment by shawaj** [comment]
@pelwell ok fixed that issue. 

about the other thing you have mentioned - i am not entirely sure what you mean. do i need to set the default values up in `fragment@1`?

**Comment by pelwell** [comment]
Although Device Tree contains no real type information - once compiled it is all just arrays of bytes - properties can be written as strings or arrays of integers of various sizes. Device drivers reading the properties then place an interpretation on those arrays of bytes, usually one that matches the way the property was written in the first place but not necessarily so.

The [DT parameter documentation](https://raspberrypi.org/documentation/configuration/device-tree.md#part2.2) describes the various parameter types and how to declare them. The new properties are mainly integers, but there is a boolean property which is true if it exists and false if it doesn't.

**Comment by shawaj** [comment]
i guess linux,axis, steps, steps-per-period need to have `:0` after them as they would be numbers?

For rotary-encoder,relative-axis - that one doesn't appear to have anything with it? It seems as if the driver "defaults" to an absolute axis but then changes to relative if you declare it? So should I remove that from the `fragment@0` part and only declare it in overrides so you can use either?

and there is the wakeup-source one which is boolean - does that work the same that if declared it is true and if not declared anywhere it is false? The rotary-encoder,rollover one seems to be the same also

**Comment by pelwell** [comment]
`rotary-encoder,relative-axis`, `rotary-encoder,rollover` and `wakeup-source` are booleans, which you declare with a `?` at the end. You create a boolean property which defaults to true by just writing the name without the assignment in the overlay - `wakeup-source;`. If it defaults to false - as all of these probably should - then omit the property from the fragment.

I think it is good practice to put the default property values explicitly into the fragments, for ease of understanding and to protect against a change in the driver's defaults - except for false booleans...

**Comment by shawaj** [comment]
is there a way to check if the booleans default to false? it seems from the txt file I linked to above that they are all false, but I just wondered for future?

**Comment by pelwell** [comment]
I was going to say that there's no easy way, and that I'd read the source (which I had), but it's obvious that booleans have to default (in the driver at least) to false, otherwise you can't distinguish an explicit override from leaving it at the default. What we choose to make the overlay default value is up to us.

**Comment by shawaj** [comment]
ok updated - how does that look?

**Comment by shawaj** [comment]
Hold on - spotted some errors already....one minute and I will fix!!

**Comment by shawaj** [comment]
ok - take a look now

**Comment by pelwell** [comment]
I think you forgot to push - the errors I'm expecting you to fix are that boolean properties are referred to as "wakeup-source?" not "wakeup-source:?".

**Comment by pelwell** [comment]
While PRs are under development it is often better to keep updates as separate commits so it is clear what has changed at each step. GitHub allows changes to be viewed by commit or by file, which effectively squashes them to see the sum of all changes, and multiple commits can be squashed at merge time.

**Comment by shawaj** [comment]
ok, have removed the colons now

**Comment by pelwell** [comment]
Merged - thanks.

**Comment by shawaj** [comment]
great, thanks :-)

**Pull request merged**
