### PR TITLE
Add DT support for PinBall board

### PR DESCRIPTION
**Pull request by ghermant**

### CODE REVIEW

**Comment by P33M** [comment]
Thanks for providing what looks to be a self-contained board support package, this is exactly what we would like HAT manufacturers/CM board manufacturers to do.

However I'm not sure of the benefits (to us) of pulling your additions into our tree. Are you intending on shipping these devices with Raspbian installed by default?

**Comment by ghermant** [comment]
Thanks for your feedback.
Yes we would like to pre-flash Raspbian on our devices.

**Comment by popcornmix** [comment]
@ghermant an unmodified raspbian?

**Comment by ghermant** [comment]
with few packages not installed by default.

**Comment by popcornmix** [comment]
I wonder if it makes more sense for you to add the dtb file when adding the packages, rather than adding it here and having an unused file on 5M Raspberry Pi boards...

**Comment by ghermant** [comment]
From a practical point of view it could be interesting to include the pinball dtb in the rpi-linux repository.
What do you mean by '5M Raspberry Pi boards ? The size of the kernel7.img + the size of the rpi & hats device tree blob ?

**Comment by popcornmix** [comment]
I'm saying there are 5 million Raspberry Pi boards in the wild.

If this is accepted, those Pi's will get the extra bcm2708-pinball.dtb file when they next update.
I've got to weigh up the benefit from adding this file to the official repo (appears very little if you are already providing a custom raspbian image which will include this file anyway) against the minor level of confusion caused to a very large number of users from having an unwanted file in the root directory of their sdcard.

**Comment by ghermant** [comment]
Ok but it's almost the same story for the RPi HATs !!!
Anyway could you please tell me if you are ok or not to accept the patch ?
Thanks

**Comment by popcornmix** [comment]
The view here is no for compute module, yes for HATs.

Rationale is that a HAT must be autoconfigured and it could potentially be plugged into any Pi. Compute module products should by definition ship with software already on them.

**Pull request closed without merging**
