### PR TITLE
staging: add FBTFT drivers

### PR DESCRIPTION
**Pull request by notro**
Add the FBTFT drivers as they will appear in Linux 3.20

### CODE REVIEW

**Comment by notro** [comment]
I will make a separate PR for config and overlays.
Ref: #767

**Comment by notro** [comment]
I didn't find an easy way to do a PR on top of this, so I added the config here.
There has been an overlay commit after I made this PR, so I'll wait with overlays until this is pulled, and I can get a clean slate that matches my git skills.

**Comment by notro** [comment]
@popcornmix any chance this can be pulled now?

**Comment by popcornmix** [comment]
I'm okay with this. @pelwell okay with you?

**Comment by pelwell** [comment]
No objections.

**Pull request merged**
