### PR TITLE
enable sht3x module in kernel, add sht3x definition to i2c-sensor dts definition

### PR DESCRIPTION
**Pull request by ubergesundheit**
This pull request enables the `sht3x` kernel module which in turn can be enabled by specifying
```
dtoverlay=i2c-sensor,sht3x
```
in `config.txt`. The `dtoverlay` instruction also supports changing the i2c address which is used to read the sensor.

### CODE REVIEW

**Comment by pelwell** [comment]
That looks fine as far as it goes, but I don't understand your comment:

>  The dtoverlay instruction also supports changing the i2c address which is used to read the sensor.

You can make the address selectable using the `addr` parameter by adding `,<&sht3x>,"reg:0"` to the `addr` `__overrides__` declaration and documenting the fact that the valid addresses are 0x44 and 0x45.

**Comment by pelwell** [comment]
Also, the CONFIG_CRC8 config option is automatically selected when you select CONFIG_SENSORS_SHT3x, so don't include it in the defconfigs.

**Comment by ubergesundheit** [comment]
It seems I had the address changes staged but forgot to commit and push ;)

**Comment by pelwell** [comment]
One final nitpick - can you add SHT3x to the `addr` documentation?

**Comment by ubergesundheit** [comment]
Ah my apologies. I've done this kind of pull request before but forgot everything 😅

**Comment by ubergesundheit** [comment]
Thank you very much!

**Pull request merged**
