### PR TITLE
Change vc4 DSI to being a bridge - rpi-5.16.y

### PR DESCRIPTION
**Pull request by 6by9**
Port #4878 to Rpi 5.16.y

It was only the "Rename bridge to out_bridge" bridge that appeared not to apply cleanly, and that is a simple rename.
Still compile testing, but I expect this to be good.

### CODE REVIEW

**Comment by 6by9** [comment]
Take it back - compile fails. Fixing it.....

**Comment by 6by9** [comment]
Fixed.
It seems I can't do a search/replace :-/

**Comment by aBUGSworstnightmare-rpi** [comment]
want to have it tested on a different DSI target? Let me know and I'll pull and compile it for DSI8x testing.

**Comment by 6by9** [comment]
> want to have it tested on a different DSI target? Let me know and I'll pull and compile it for DSI8x testing.

This is a straight port of the patches from 5.15 to 5.16, so I'm not expecting any difference in behaviour.

**Pull request merged**
