### PR TITLE
add BME680 to i2c-sensor overlay

### PR DESCRIPTION
**Pull request by dremsol**
Tested and working. Question remaining is if bme680 should be configured as a module in kernel configuration?

### CODE REVIEW

**Comment by dremsol** [comment]
changed relevant defconfigs

**Comment by pelwell** [comment]
There were a few issues with this PR (the bmp280 address setting was broken, a README line was too long, and there were whitespace problems in the overlay), but I've patched it up. If you're happy with the result I'll merge it.

**Comment by dremsol** [comment]
Thanks for the feedback. The README is fine. Correct me if I'm wrong, but you've changed a broken address which wasn't broken. the PR adds the `BME680` sensor, not the BMP680

**Comment by pelwell** [comment]
If you diff my version to yours, excluding the whitespace changes, you get:
```diff
diff --git a/arch/arm/boot/dts/overlays/README b/arch/arm/boot/dts/overlays/README
index 41fadb7..917ce60 100644
--- a/arch/arm/boot/dts/overlays/README
+++ b/arch/arm/boot/dts/overlays/README
@@ -1159,8 +1159,8 @@ Name:   i2c-sensor
 Info:   Adds support for a number of I2C barometric pressure and temperature
         sensors on i2c_arm
 Load:   dtoverlay=i2c-sensor,<param>=<val>
-Params: addr                    Set the address for the BME280, BME680, BMP280, DS1621,
-                                HDC100X, LM75, SHT3x or TMP102
+Params: addr                    Set the address for the BME280, BME680, BMP280,
+                                DS1621, HDC100X, LM75, SHT3x or TMP102
 
         bme280                  Select the Bosch Sensortronic BME280
                                 Valid addresses 0x76-0x77, default 0x76
diff --git a/arch/arm/boot/dts/overlays/i2c-sensor-overlay.dts b/arch/arm/boot/dts/overlays/i2c-sensor-overlay.dts
index 96fec93..40881d7 100644
--- a/arch/arm/boot/dts/overlays/i2c-sensor-overlay.dts
+++ b/arch/arm/boot/dts/overlays/i2c-sensor-overlay.dts
@@ -233,7 +233,7 @@
 
 
        __overrides__ {
-               addr =  <&bme280>,"reg:0", <&bme680>,"reg:0", <&tmp102>,"reg:0",
+               addr =  <&bme280>,"reg:0", <&bmp280>,"reg:0", <&tmp102>,"reg:0",
                        <&lm75>,"reg:0", <&hdc100x>,"reg:0", <&sht3x>,"reg:0",
                        <&ds1621>,"reg:0", <&bme680>,"reg:0";
                bme280 = <0>,"+0";
```
The README change just moves the line-wrap, but the overlay change restores the address setting for bmp280 that your patch had broken. Your original patch said:
```diff
        __overrides__ {
-               addr =  <&bme280>,"reg:0", <&bmp280>,"reg:0", <&tmp102>,"reg:0",
+               addr =  <&bme280>,"reg:0", <&bme680>,"reg:0", <&tmp102>,"reg:0",
                        <&lm75>,"reg:0", <&hdc100x>,"reg:0", <&sht3x>,"reg:0",
-                       <&ds1621>,"reg:0";
+                       <&ds1621>,"reg:0", <&bme680>,"reg:0";
```
i.e. you had bme680 in the list twice, once where bmp280 used to be.

**Comment by wremie** [comment]
Weird. Not sure how I screwed this up on my end. However, if I pull bme680 branch from fork everything looks good now. PR could be merged.

**Comment by dremsol** [comment]
weird, not sure how I screwed up on my end. However, when pulling from bme680 branch in fork everything looks fine. PR could be merged.

**Pull request merged**
