### PR TITLE
VEC mono support

### PR DESCRIPTION
**Pull request by 6by9**
Extends #5961 to add support to vc4

@njhollinghurst

### CODE REVIEW

**Comment by 6by9** [comment]
Sent upstream for comment on monochrome support - https://patchwork.freedesktop.org/series/130023/

**Comment by njhollinghurst** [comment]
If the DRM change turns out not to be upstreamable, perhaps we should abandon this or do it by other means. There doesn't seem to be enough user demand for it to justify maintaining separately (especially when we come to implement it for the RP1 VEC which is new and not yet upstreamed at all).

**Comment by 6by9** [comment]
> If the DRM change turns out not to be upstreamable, perhaps we should abandon this or do it by other means. There doesn't seem to be enough user demand for it to justify maintaining separately (especially when we come to implement it for the RP1 VEC which is new and not yet upstreamed at all).

Disabling colour does have its uses, so it would be nice to support.

Selecting it via the kernel command line is the ideal option, with it appearing through DRM UAPI is coincidental.
The core DRM patch is minimal, and is in code that is unlikely to change upstream. It also means we can implement RP1 mono support in the same way, whereas a module parameter will be either vc4.mono_vec or drm-rp1-vec.mono depending on platform.

Unless @popcornmix or @pelwell have strong objections, I'm tempted to say we add the enum value downstream and let mainline do as they wish.

**Comment by pelwell** [comment]
No objection from me.

**Comment by popcornmix** [comment]
I'm okay with this.

**Comment by 6by9** [comment]
Ta. I'll rebase this then, and we just ignore mainline.

**Comment by 6by9** [comment]
Branch is rebased, but Github PRs are having issues (https://www.githubstatus.com/incidents/wcl1sw4mzg60) and this hasn't updated yet.

**Pull request merged**
