### PR TITLE
SPI: enable compiling upstream spi-bcm2835 driver and add overlay to allow us to load the driver

### PR DESCRIPTION
**Pull request by msperl**
note that when we move to generic GPIOs we will need to modify the brcm,function to 1 in spi0_cs_pins
Some of this (especially the separation between spi0_pins and spin0_cs_pins) might get generalized into the "core" device-tree.

### CODE REVIEW

**Comment by msperl** [comment]
See #864 for the discussions around this.

**Comment by msperl** [comment]
@pelwell: you want the overlay named differently? See the discussion around it in #864

**Comment by pelwell** [comment]
That is a "Line comment" attached the line that says:

```
 * Device tree overlay for spm-2835
```

**Comment by msperl** [comment]
fixed

**Comment by pelwell** [comment]
I'll merge if you change the comment to either spi-bcm2835 or bcm2835-spi, and then squash the commits down to one.

**Comment by msperl** [comment]
Done - forced pushing a squash upstream requires lots of memory - the default swap settings of raspbian are not enough...

**Comment by notro** [comment]
> cs-gpios = <&gpio 8 0>, <&gpio 7 0>;

Why this? It's not used by the driver. And also why splitting out the cs pins?

**Comment by msperl** [comment]
well - the reason is that at some point in the future we will have generic GPIOs acting as CS (I got a working prototype), so IMO it makes sense to separate them already...
finally this makes it more easily configurable - the CS are different from the SCK, MISO, MOSI pins.

**Comment by notro** [comment]
I don't know what Phil's policy is, but changes like this isn't accepted in mainline. Having code lying around that might or will get used in the future isn't good. Someone reading the overlay will assume that cs-gpios actually works.
Better add this in when it's needed.

**Comment by msperl** [comment]
I shall remove those cs-gpios then, but I would leave the separation of the GPIOs.
As said somewhere: IMO it actually would make sense to split those on the global device-tree...

**Comment by msperl** [comment]
better now?

**Comment by notro** [comment]
Yes, better.
I have to go now, but can you point me to your cs pin split argument? I can't see how this change in the DT provides any benefit, at the present at least.

**Comment by pelwell** [comment]
Yes, I would also like to understand that.

**Comment by msperl** [comment]
the split is there to avoid changes in the future.
actually there is a risk of merging a later version of the driver from upstream that then only supports gpio-cs and people will expect it to work, that is why I started to include all those things that right now do not make a difference, but will have people complaining if things stop to work in the future.

**Comment by msperl** [comment]
but OK, I will remove also that...

**Comment by msperl** [comment]
done - now it is very minimal

**Comment by pelwell** [comment]
We like minimalism, provided it is functional minimalism.

**Pull request merged**
