### PR TITLE
ARM: dts: Create bcm2711-rpi-cm4s.dts

### PR DESCRIPTION
**Pull request by peterharperuk**
Signed-off-by: Peter Harper <peter.harper@raspberrypi.com>

### CODE REVIEW

**Comment by peterharperuk** [comment]
@pelwell

**Comment by pelwell** [comment]
I have a few minor changes - some bits borrowed from the CM3 DTS which don't apply to CM4S because it isn't based on BCM2710, and the rest to account for recent updates in the other BCM2711 DTs:
```diff
diff --git a/arch/arm/boot/dts/bcm2711-rpi-cm4s.dts b/arch/arm/boot/dts/bcm2711-rpi-cm4s.dts
index 26aa35b4d02d6..4ea3a8f42ef7d 100644
--- a/arch/arm/boot/dts/bcm2711-rpi-cm4s.dts
+++ b/arch/arm/boot/dts/bcm2711-rpi-cm4s.dts
@@ -27,7 +27,7 @@ aliases {
 	};
 
 	leds {
-		act {
+		led-act {
 			gpios = <&virtgpio 0 0>;
 		};
 	};
@@ -110,9 +110,11 @@ &gpio {
 &hdmi0 {
 	clocks = <&firmware_clocks 13>, <&firmware_clocks 14>, <&dvp 0>, <&clk_27MHz>;
 	clock-names = "hdmi", "bvb", "audio", "cec";
+	wifi-2.4ghz-coexistence;
 	status = "okay";
 };
 
+
 &hvs {
 	clocks = <&firmware_clocks 4>;
 };
@@ -163,15 +165,16 @@ &emmc2 {
 };
 
 &pcie0 {
-	pci@1,0 {
+	pci@0,0 {
+		device_type = "pci";
 		#address-cells = <3>;
 		#size-cells = <2>;
 		ranges;
 
 		reg = <0 0 0 0 0>;
 
-		usb@1,0 {
-			reg = <0x10000 0 0 0 0>;
+		usb@0,0 {
+			reg = <0 0 0 0 0>;
 			resets = <&reset RASPBERRYPI_FIRMWARE_RESET_ID_USB>;
 		};
 	};
@@ -229,7 +232,6 @@ aliases {
 		mmc0 = &emmc2;
 		mmc1 = &mmcnr;
 		mmc2 = &sdhost;
-		/delete-property/ i2c2;
 		i2c3 = &i2c3;
 		i2c4 = &i2c4;
 		i2c5 = &i2c5;
@@ -416,13 +418,6 @@ &i2s {
 	pinctrl-0 = <&i2s_pins>;
 };
 
-/ {
-	__overrides__ {
-		/delete-property/ i2c2_baudrate;
-		/delete-property/ i2c2_iknowwhatimdoing;
-	};
-};
-
 // =============================================
 // Board specific stuff here
 
@@ -442,7 +437,7 @@ audio_pins: audio_pins {
 };
 
 &leds {
-	act_led: act {
+	act_led: led-act {
 		label = "led0";
 		linux,default-trigger = "mmc0";
 		gpios = <&virtgpio 0 0>;
```

**Comment by peterharperuk** [comment]
make sense - I'll make those changes and retest

**Comment by pelwell** [comment]
That looks correct. No, wait - pcie should be disabled since it isn't hooked up to anything.

**Comment by peterharperuk** [comment]
Was this the right way to do it?

// =============================================
// Board specific stuff here

&pcie0 {
	status = "disabled";
};

**Comment by pelwell** [comment]
It's not wrong, exactly, but given that's there no way to use PCIe it would be more natural to make that the first and only reference to PCIe, including removing the alias.

**Comment by pelwell** [comment]
I'm happy with that - say when you're ready to merge it.

**Comment by peterharperuk** [comment]
I'm ready for this to be merged

**Pull request merged**
