### PR TITLE
configs: rpi: Compile TSC2007 as module

### PR DESCRIPTION
**Pull request by timonsku**
Compile the TSC2007 touchscreen driver as a module and enable the optional IIO module.
Used by most newer Adafruit products.

### CODE REVIEW

**Comment by timonsku** [comment]
Don't understand why the checkpatch is failing with missing commit description. The commit has a description?

**Comment by pelwell** [comment]
I don't understand either, but we can ignore it if everything else is ok

**Comment by timonsku** [comment]
I think it was missing extra line break, added now. Local checkpatch is happy now

**Comment by pelwell** [comment]
I had to fix the order because it wasn't as it would be generated by make savedefconfig, but otherwise it's fine.

**Comment by timonsku** [comment]
oh will keep that in mind, had it manually inserted for the commit after changing it with menuconfig on the test system

**Comment by pelwell** [comment]
We should add it to the build checks.

**Pull request merged**
