### PR TITLE
cdc_ncm: Add support for moving NDP to end of NCM frame

### PR DESCRIPTION
**Pull request by tranaconda**
This will fix Huawei sticks. See https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=4a0e3e989d66bb7204b163d9cfaa7fa96d0f2023

### CODE REVIEW

**Comment by P33M** [comment]
This appears to have been committed upstream. Which kernel version does it appear in, so we can cherry-pick if necessary?

**Comment by popcornmix** [comment]
Looks to already be in our 4.4 tree.
@tranaconda does `sudo BRANCH=next rpi-update` work for you?

**Comment by tranaconda** [comment]
It does work, but the 4.4 kernel is (at least with my Raspi2) very unstable. I've been using this on 4.1.18 for weeks successfully. It's been merged into the 4.2 kernel upstream, I think. You can just deny the request if you don't need it, but for me it was very helpful (because the sticks appear to work but fail to dial in and it took me quite some research to find out it wasn't working because of the kernel), so I thought I'd share...

**Comment by popcornmix** [comment]
Well, we are planning to switch to 4.4 imminently, so if you have stability issues then it's best to report them soon, because that is what is coming. There is a thread you can report issues in:
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=130429

**Comment by tranaconda** [comment]
It's been a few weeks since I tested it last, maybe my problems are gone now - I will test it again when I find the time. But until then, maybe a few other people could benefit from this, since there are no conflicts and it doesn't touch any vital kernel parts. And - as I said - it's running smoothly for weeks on my Pi2B. You guys decide if you need it, I just wanted to spare other people days of research I had to do :)

**Comment by popcornmix** [comment]
There were reliability problems reported (mainly with USB discs I believe), but those issues seem to have gone with upstream updates.
It would be useful if you confirm if latest 4.4 kernel is stable or not. We will be switching to it very soon.

**Comment by tranaconda** [comment]
OK, if it helps you guys, I'd love to contribute. I just updated it and just got the good old

`systemd-modules-load[2700]: Failed to find module 'bcm2708_rng'`

but that's nothing new. My problem was deterioration - it crashed after a day or two and I couldn't quite find out why. And since it was still unstable I switched back to the stable branch. So I guess I'll be reporting back in a few days to tell you if it's still running or not.

**Comment by popcornmix** [comment]
The 4.4 kernel is used by OSMC which has hundreds of thousands of users, so I'm sure there are no unreliability issues that affect all users. There is always a possibility that less common configurations provoke some issue, but no issues are currently outstanding.

**Comment by tranaconda** [comment]
I'm running Lubuntu 15.10 as a mobile router (hence the 4G stick) / occasional workstation for browsing / occasional mediaplayer. As I said, stable on 4.1.18 - used to crash after some time on 4.4 - could be fixed now, I'm testing it.

But back to topic: will you merge this or is it obsolete?

**Comment by tranaconda** [comment]
OK, no complete crash, but I guess the USB subsystem crashed and reinitialized:
http://pastebin.com/BVgpx0R0

This did not happen on 4.1.18

**Comment by popcornmix** [comment]
@P33M seems to be a dwc_otg allocation/ffree from atomic context issue. Any suggestions?

**Comment by tranaconda** [comment]
It may be important that this happened after 10h uptime. Maybe most OSMC users don't get that much uptime? And it reinitializes right away, so maybe they wouldn't notice? I noticed, because my connection was lost and it didn't dial back in (even though it was supposed to).

**Comment by popcornmix** [comment]
I'm sure most experience uptimes of more than 10h.
I've got an OE that's been up for 14h (I run nightly builds, so I rebooted to update last night) and no errors in dmesg. And I've never hit that error in past.

What is the Huawei stuck you're using - a 3G dongle? Do you get issues when not using that but using ethernet?

**Comment by tranaconda** [comment]
I can unplug it, reboot and try. Yes, it is a 4G stick with an additional microSD slot (hence the fsck warning): http://consumer.huawei.com/en/mobile-broadband/dongles/tech-specs/e3372.htm

I remember this happened randomly on 4.4 a few weeks ago. Never on 4.1.18.

**Comment by P33M** [comment]
Stacktrace in https://github.com/raspberrypi/linux/pull/1303#issuecomment-197861134 is probably the same as https://github.com/raspberrypi/linux/issues/1290 - disabling endpoints with queue elements attached means that coherent memory is freed with interrupts disabled.

**Comment by popcornmix** [comment]
Latest `BRANCH=next rpi-update` kernel includes a fix for the dmesg warning involving dwc_otg_hcd_qh_free. Can you update and test?

**Comment by tranaconda** [comment]
OK, 4.4.5 has been running without any problems for 36h. I will update now as requested and plug-in the 4G stick again.

**Comment by tranaconda** [comment]
Well, it's still happening, but at least it's dialing back in now: http://pastebin.com/FMJtSTqm

**Comment by Ruffio** [comment]
@tranaconda is this PR still relevant? It points to 4.1, but currently we are at 4.4. I think that if it is going to have any chance to be merged then it must point to 4.4...

**Comment by P33M** [comment]
I'm closing the PR as no longer relevant. If there's still random disconnects happening now that weren't on a previous version, then open a new issue with the device listings from lsusb -v and dmesg.

**Pull request closed without merging**
