### PR TITLE
bcm2835_codec fixes

### PR DESCRIPTION
**Pull request by 6by9**
These are from investigating seeking not working with gst-play. It does now.

### CODE REVIEW

**Comment by 6by9** [comment]
@popcornmix I don't know whether these will fix FFmpeg/Kodi as well.

The second patch is working around an issue in GStreamer that has been fixed in 1.16, but I believe is still valid within the V4L2 API, so we ought to support.

**Comment by popcornmix** [comment]
I can test with ffmpeg/kodi.
Do you believe header bytes need to be fed in again after a seek? (i.e. have we flushed decoder in such a way it will have forgotten previous ones)

**Comment by 6by9** [comment]
Not sure - I didn't analyse the packet that GStreamer fed back in after the seek.

We have done a full codec shutdown on the VPU, however video_decode updates an internal structure which may be enough to restore the codec state after the seek.

**Comment by 6by9** [comment]
If FFmpeg doesn't work, then the way I read the [V4L2 M2M spec](https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/dev-decoder.html#seek), as long as it follows the specified procedure then the codec is responsible for remembering the header bytes. That's based on the warning regarding H264 and seeking over a change of SPS/PPS - that wouldn't be necessary if the codec was expected to drop the header bytes.

GStreamer shuts down both OUTPUT and CAPTURE queues on seek, therefore I'd view that as reasonable to forget everything.

**Comment by 6by9** [comment]
Still waiting on tenterhooks to know if worked with Kodi!

**Comment by popcornmix** [comment]
Had some build issues and ended up having to do a clean build.
There's a kodi build on Pi4 and an LE cross-compile in progress. Hopefully one will work.

**Comment by popcornmix** [comment]
Got an LE build running, but no joy. H264 video plays but I don't get any video frames out after a seek.

**Comment by popcornmix** [comment]
Not sure if there's any useful info here, but after a seek, there are complaints in dmesg (not immediately but after a few seconds).
http://ix.io/2uh3

**Comment by timemaster5** [comment]
Hmm, unfortunately, the problem persists. I tested on Raspberry pi 3b+ with youtube playing 1080p video on wpewebkit-fdo platform. Tested on kernel 5.4.59.

**Comment by moritzvieli** [comment]
I don't understand enough details in this topic, but this patch fixed the seeking issue for me: https://github.com/raspberrypi/linux/issues/3325#issuecomment-684040830

**Comment by timemaster5** [comment]
I believe this issue is also related to this one https://github.com/raspberrypi/linux/issues/3791, where I posted the full dmesg

**Pull request merged**
