### PR TITLE
Add support for Pi 5

### PR DESCRIPTION
**Pull request by popcornmix**
Add support for Pi 5.

This supports the new hardware in BCM2712 and RP1.

There are two 64-bit defconfig options.

bcm2711_defconfig will support all 64-bit Pi devices and uses a pagesize of 4K
bcm2712_defconfig switches to a 64K pagesize, and only works on Pi 5.

### CODE REVIEW

**Comment by 6by9** [comment]
@popcornmix We want to drop the top 3 patches marked DNI (Do Not Integrate) that mess with the workflow files.

**Comment by pelwell** [comment]
And the first PCIe reset revert can be replaced with upstream commit 8eb8c2735306526929141052c82bd118a7a2119b.

**Comment by pelwell** [comment]
On the subject of workflow files, as long as we continue to guarantee that the only difference between bcm2712_defconfig and bcm2711_defconfig is the page size, we can omit a Pi 5-specific test build.

**Comment by 6by9** [comment]
> On the subject of workflow files, as long as we continue to guarantee that the only difference between bcm2712_defconfig and bcm2711_defconfig is the page size, we can omit a Pi 5-specific test build.

It probably has some gain though in order to be able to use rpi-update to grab the appropriate build artifacts though (I'm hoping rpi-update looks at that bit of the extension too - I've not checked).

**Comment by pelwell** [comment]
I've bumped `overlaycheck` in the utils repo, so subsequent pushes _should_ pass.

**Comment by pelwell** [comment]
`rpi-update` will need to grow a `WANT_PI5` flag.

**Comment by popcornmix** [comment]
Updated (@pelwell please check pcie-bcmstb.c - it is now not the same as initial PR).

**Comment by popcornmix** [comment]
rpi-firmware will need the additional kernel2712.img built (and rpi-update will need checking that it copies it).
I'll also check what rpi-update from a PR does.

But I think we'll need the additional build artifact - otherwise rpi-update will bump you from a 16K pagesize to a 4K pagesize.

**Comment by pelwell** [comment]
> Updated (@pelwell please check pcie-bcmstb.c - it is now not the same as initial PR).

pcie-brcmstb.c now matches rpi-6.6.y in that respect. I'm happy this part needed changing to sit on top of that upstream change, but perhaps this is the wrong outcome. The question is whether PERST# also needs to be asserted on BCM2712 - the safe thing would be to add that case to the condition, since that matches the old behaviour, and then drop it if we decide it isn't necessary. I'll add a patch to that effect.

> But I think we'll need the additional build artifact - otherwise rpi-update will bump you from a 16K pagesize to a 4K pagesize.

OK - I'll add the build type to the workflow.

**Comment by pelwell** [comment]
> I'll add a patch to that effect.

After discussion with Tim this is currently unnecessary because the bootloader does leave it reset, so I won't add such a patch at this time.

**Comment by popcornmix** [comment]
> After discussion with Tim this is currently unnecessary because the bootloader does leave it reset, so I won't add such a patch at this time.

So current PR is good (wrt pcie-bcmstb.c)?

**Comment by pelwell** [comment]
Yes, I think so.

I've bumped the workflows. There is still some issue with one of the overlays that I'll look at next.

**Comment by pelwell** [comment]
@6by9 in vc4-kms-dsi-7inch-overlay.dts it references ts_i2c_frag, but no such label exists. I think the node you are aiming for is currently labelled frag13, but that doesn't fit with the nice user-friendly labels the rest of that file uses. However, changing edt-ft5406.dtsi could break edt-ft5406-overlay.dts

Would you like me to:
a. add ts_i2c_frag as a second label into edt-ft5406.dti,
b. add ts_i2c_frag as an alias but inside vc4-kms-v3d-pi5-overlay.dts,
c. change vc4-kms-v3d-pi5-overlay.dts to use frag13, or
d. change everything to use ts_i2c_frag instead?

**Comment by 6by9** [comment]
> in vc4-kms-dsi-7inch-overlay.dts it references ts_i2c_frag, but no such label exists. 

See commit d6e6b9afa8 on the private branch. It just missed the cutoff yesterday, and looks like popcornmix hasn't included it in this PR or merged it into "dts: 2712: Update for device tree"

**Comment by 6by9** [comment]
DRM/KMS unit tests failing appears to be a build failure due to part of raspberrypi-gpiomem.c
```
2023-09-28T14:52:58.7457288Z ../drivers/char/raspberrypi-gpiomem.c:104:37: error: implicit declaration of function ‘phys_mem_access_prot’; did you mean ‘phys_mem_access_prot_allowed’? [-Werror=implicit-function-declaration]
2023-09-28T14:52:58.7457878Z [14:49:36] Configuring KUnit Kernel ...
2023-09-28T14:52:58.7500841Z   104 |                 vma->vm_page_prot = phys_mem_access_prot(file, base, len,
2023-09-28T14:52:58.7501241Z Generating .config ...
2023-09-28T14:52:58.7501769Z       |                                     ^~~~~~~~~~~~~~~~~~~~
2023-09-28T14:52:58.7502250Z       |                                     phys_mem_access_prot_allowed
2023-09-28T14:52:58.7503042Z ../drivers/char/raspberrypi-gpiomem.c:104:37: error: incompatible types when assigning to type ‘pgprot_t’ from type ‘int’
```
I'm not totally clear why it's even building gpiomem.

KUnit Tests/VC4 are failing as the test vc4/tests/vc4_test_lbm_size.c needs updating for the lbm_size having moved.
That should be easy to fix.

**Comment by pelwell** [comment]
So, option d then. Cherry-picked.

**Comment by pelwell** [comment]
Upstream build fixup pushed.

**Comment by 6by9** [comment]
VC4 unit tests fixed with https://github.com/6by9/linux/commit/950224c8c28ea11b2642f98f2b59625fe2afc3ca (I'm not sure I can do a push to popcornmix's branch.

**Comment by 6by9** [comment]
drivers/char/Kconfig has ```RASPBERRYPI_GPIOMEM``` default to y. That would explain the build breakage for the generic unit tests, but is that what we want?
I guess if we default to not building it then the defconfig needs updating. As it's providing userspace access it could be a module, and only on 2711/2712 rather than all kernels.

The old BCM2835_DEVGPIOMEM option for bcm2835-gpiomem was a module.

**Comment by pelwell** [comment]
Defaulting the gpiomem to a module makes sense - it's an anomaly that it isn't already.

**Comment by 6by9** [comment]
Commits https://github.com/6by9/linux/commit/430bb5b1f3253abab25bbf059d7b7c0b7e781ed4 and https://github.com/6by9/linux/commit/bde073f4c395ff601c41f3651fc8709c4a134b04 sort the generic unit test CI failure.

430bb5b1f wants to go before "drivers: char: delete bcm2835-gpiomem", and bde073f4c3 fixes up "drivers: char: delete bcm2835-gpiomem".

**Comment by popcornmix** [comment]
I believe I've squashed in commits that have been pushed/mentioned. Anything missing?

**Comment by pelwell** [comment]
Nope - that looks good to me if the checks are passing.

**Pull request merged**
