### PR TITLE
Rpi patches raspbian

### PR DESCRIPTION
**Pull request by ghost**
see http://www.raspberrypi.org/phpBB3/viewtopic.php?p=149799#p149799 
asb from the forum suggested a pull request. The static allocation of the GPIO pin for w1, or maybe any other side effects of the w1-system (it's timing critical) should be no problem, as long as you don't load the module.

### CODE REVIEW

**Comment by popcornmix** [comment]
Can you have a close look at the config patches. You seem to revert lots of our recent changes (e.g. network scheduling).
Also SPI_SPIDEV is already enabled.

**Comment by asb** [comment]
Yes, to prepare a defconfig patch please just clone the current tree, make bcmrpi_defconfig, make menuconfig, then make defconfig to export a new defconfig file.

**Comment by FrankBuss** [comment]
Sorry, you are right, I've used the config from the last image as the base, which reverted lots of changes. Now I merged the latest changes, did a "make bcmrpi_defconfig" then a "make menuconfig" and most of my changes were already enabled, looks like just one request from the forum for the RTC 1-wire DS1307 chip was missing. I enabled it, then I ran a "make savedefconfig" and copied the resulting "defconfig" to bcmrpi_defconfig and as expected, the only diffs are the two for the RTC. Now I'm compiling the new kernel and testing it, if all external hardware devices still works.
I'm new to Github, do I have to create a new pull request after comit and push?

**Comment by FrankBuss** [comment]
Nice, the latest commits where added to the pull requests. The kernel runs without problem and my tests with SPI, 1-wire and I2C work.

**Comment by popcornmix** [comment]
Frank, are you sure this patch has no effect on people who are currently using GPIO 4 for other purposes, assuming they don't modprobe the 1 wire driver?

**Comment by FrankBuss** [comment]
I was pretty sure, but I've just tested it: Accessing the pin like this works when the module is not loaded:
echo "4" > /sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio4/direction
echo "1" > /sys/class/gpio/gpio4/value
echo "0" > /sys/class/gpio/gpio4/value
I can measure the right voltage level at the pin.
"modprobe w1-gpio" fails, if the pin was reserved with 'echo "4" > /sys/class/gpio/export' and trying to allocate it as a GPIO pin fails, if the w1-gpio driver is loaded, so I'm sure there is no side effect for both drivers.

**Comment by popcornmix** [comment]
Sorry Frank, I believe I'd replied to this a few days ago, but I must have lost it somehow.

Can you resubmit the pull request based against the updated 3.2.27 kernel, without the reverts, and I'll accept it.

**Pull request closed without merging**
