### PR TITLE
ALSA: usb-audio: Add Gustard U16/X26 to quirks for native DSD support

### PR DESCRIPTION
**Pull request by montaintop**
ALSA: usb-audio: Add Gustard U16/X26 to quirks for native DSD support

### CODE REVIEW

**Comment by pelwell** [comment]
This patch should go upstream, but first you'll need to fix the issues identified by checkpatch:
```
ERROR: trailing whitespace
#20: FILE: sound/usb/quirks.c:1372:
+ ^Icase USB_ID(0x292b, 0xc4b3): /* Gustard U16/X26 USB Interface */^I$

ERROR: code indent should use tabs where possible
#20: FILE: sound/usb/quirks.c:1372:
+ ^Icase USB_ID(0x292b, 0xc4b3): /* Gustard U16/X26 USB Interface */^I$

WARNING: please, no space before tabs
#20: FILE: sound/usb/quirks.c:1372:
+ ^Icase USB_ID(0x292b, 0xc4b3): /* Gustard U16/X26 USB Interface */^I$

WARNING: please, no spaces at the start of a line
#20: FILE: sound/usb/quirks.c:1372:
+ ^Icase USB_ID(0x292b, 0xc4b3): /* Gustard U16/X26 USB Interface */^I$

ERROR: Missing Signed-off-by: line(s)

total: 3 errors, 3 warnings, 7 lines checked
```
When you are ready, email it to:
```
Jaroslav Kysela <perex@perex.cz>
Takashi Iwai <tiwai@suse.com>
Greg Kroah-Hartman <gregkh@linuxfoundation.org>
alsa-devel@alsa-project.org
```

**Comment by montaintop** [comment]
Hi There

Mr. Iwai approved with slight change,  in the following commit, possible to pull it in here? 

@@ -1657,6 +1657,7 @@ u64 snd_usb_interface_dsd_format_quirks(struct snd_usb_audio *chip,
 	case 0x23ba:  /* Playback Designs */
 	case 0x25ce:  /* Mytek devices */
 	case 0x278b:  /* Rotel? */
 	case 0x292b:  /* Gustard/Ess based devices */
 	case 0x2ab6:  /* T+A devices */
 	case 0x3842:  /* EVGA */
 	case 0xc502:  /* HiBy devices */

https://github.com/tiwai/sound/commit/e2995b95a914bbc6b5352be27d5d5f33ec802d2c

**Comment by pelwell** [comment]
Give me a nudge when it hits linux-next (https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git), which should be tomorrow.

**Comment by montaintop** [comment]
Here comes the nudge:) 

https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=e2995b95a914bbc6b5352be27d5d5f33ec802d2c

**Comment by pelwell** [comment]
See e6be45a7c4a6.

**Pull request closed without merging**
