### PR TITLE
Pull upstream dma backport into rpi 4.6.y

### PR DESCRIPTION
**Pull request by clivem**
This is an 18 patch series, consisting of 16 patches from @msperl (the upstream dma backport) and 2 "fix" patches from @HiassofT

### CODE REVIEW

**Comment by popcornmix** [comment]
Thanks. @msperl @HiassofT confirmation that this works for you would be welcome.

**Comment by msperl** [comment]
@popcornmix : I can not test this right now, as I do only have a rpi with me as access point in the hotel, but no audio/SPI hw attached to that host, so i can not test it...

But as I assume these were just cherry-picked from my branch, it should not be an issue.
For the last 2 patches I can only comment on code and can say that it looks fine.

My guess the first of those patches will go into upstream without questions, but there is a higher chance that discussions around the second commit could be more intensive, so this one may require some rewrite (but that is guesswork).

**Comment by clivem** [comment]
> .... this one may require some rewrite ....

And if that is the case, we just revert the downstream patch and replace it with the upstream accepted version, right? ;)

**Comment by popcornmix** [comment]
> And if that is the case, we just revert the downstream patch and replace it with the upstream accepted version, right? ;)

Yes. Not a big problem. Just something to keep an eye on.

Kernel builds and works with this PR. Let's see if I can test an I2S card...

**Comment by clivem** [comment]
And I wonder if it is worth giving a heads-up to one of those Sonic Pi users...... I'm not familiar with this Millhouse OS, and have no idea if it even includes Sonic Pi?????? But if it does and this PR is included in the nightly build tonight, it might be worth asking @rbnpi  to try the nightly and see if it resolves his stuttering issues with SonicPi and IQAudIO DAC.

**Comment by pelwell** [comment]
Or perhaps someone like @samaaron?

**Comment by popcornmix** [comment]
The Milhouse build is LibreELEC (Kodi media centre).
http://forum.kodi.tv/showthread.php?tid=269814

I've got an IQAudio DAC+ here and it seems fine with kodi using this 4.6 kernel with this PR.
Unless anyone spots an issue, I'm happy to merge this PR this evening so we can get some testing in tonight's Milhouse build.

**Comment by rbnpi** [comment]
Have you tried it with jackd and Sonic Pi? That’s where the issue lies. It worked fine with previous kernel, but not with current release version.

**Comment by pelwell** [comment]
We were hoping to crowdsource some of the testing...

**Comment by samaaron** [comment]
Very happy to test this when I return from Estonia.

**Comment by popcornmix** [comment]
I've got sonic pi running with IQ Audio DAC+ and I'm not hearing any dropouts or glitches when playing some of the live loop demos. Not sure if I need any specific settings to provoke the issue, but it looks good to me.

**Comment by clivem** [comment]
> I'm not hearing any dropouts or glitches when playing some of the live loop demos

can you cat hw_params for the card and tell me the buffer size and period size being used?

**Comment by popcornmix** [comment]
```
$ cat /proc/asound/card0/pcm0p/sub0/hw_params 
access: MMAP_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 2048
buffer_size: 6144
```

**Comment by clivem** [comment]
Hmmm. That wasn't what I expected to see. Was expecting to see large numbers for buffer/period, which would have given a very plausible reason for the cause of the stuttering.....

**Comment by popcornmix** [comment]
I've just reverted this PR and tried the same Sonic Pi usage and it sounds much worse.
Not sure exactly how it is fixed, but this PR does fix something!

**Comment by popcornmix** [comment]
No change in hw_params

```
$ cat /proc/asound/card0/pcm0p/sub0/hw_params 
access: MMAP_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 2048
buffer_size: 6144
```

**Comment by HiassofT** [comment]
I did a few quick tests (playback+recording) on my RPi3 and everything worked fine!

**Comment by popcornmix** [comment]
@HiassofT thanks.
I forgot to merge last night. Should happen at 8:45pm tonight (I've set a reminder) assuming no problems are discovered.

**Comment by popcornmix** [comment]
@clivem feel free to submit PR to 4.4 tree - we'll merge in a day or two if no one complains about the 4.6 kernel.

**Comment by clivem** [comment]
@popcornmix OK. Will do.

**Comment by msperl** [comment]
Note that there is one patch that Eric submitted that may be relevant as well - not sure what the current status is - it is called:
dmaengine: bcm2835: Fix polling for completion of DMA with interrupts masked.

**Comment by clivem** [comment]
I'll post a PR to add that Eric "dma completion" patch to the rpi-4.6.y branch later this evening.

EDIT: No need. @popcornmix has already cherry picked it into rpi-4.6.y. See https://github.com/raspberrypi/linux/pull/1524#issuecomment-225364967

**Pull request merged**
