### PR TITLE
Add support for Dion Audio LOCO DAC-AMP HAT

### PR DESCRIPTION
**Pull request by clivem**
This is a re-submit of https://github.com/raspberrypi/linux/pull/1539 from @miquel83blauw  to add support for the Dion Audio LOCO, combined DAC/AMP HAT.

### CODE REVIEW

**Comment by pelwell** [comment]
Documentation?

**Comment by miquel83blauw** [comment]
At the moment we are working on the documentation for the LOCO.

**Comment by pelwell** [comment]
Can you (or Clive) craft an entry for the overlay in the README? It shouldn't take much creativity.

**Comment by clivem** [comment]
@pelwell Done.

**Comment by clivem** [comment]
@miquel83blauw Miquel, now that support for your board is merged, I have added a patch to the 384k PR, https://github.com/raspberrypi/linux/pull/1460, which adds the one line necessary to your overlay to enable 384k support. If building your own kernel, just apply all 6 patches, from the top of my 384k tree.

**Comment by miquel83blauw** [comment]
Clive, sorry for the delay but thanks. I'll add the line to the overlay. If I build my own kernel I'll let you know how it works.

**Pull request merged**
