### PR TITLE
add Hifiberry DACplusADC PRO version

### PR DESCRIPTION
**Pull request by j-schambacher**
this adds the driver for the Pro version of the Hifiberry soundcard with software controlled PCM1863 ADC

### CODE REVIEW

**Comment by pelwell** [comment]
That looks OK to me. Can you give me (a reply here is fine) a "Signed-off-by:" line?

**Comment by pelwell** [comment]
Ideally, put your PR comment in the commit message along with the Signed-off-by, then `git push -f ...` to update the PR.

**Comment by j-schambacher** [comment]
done

**Comment by pelwell** [comment]
That's really close, but the convention is that you have a short "title" add the first line of the commit, then a blank line, followed by the main body of the message. Titles are meant to be 52 characters or shorter if possible, but we aren't that strict.

**Comment by j-schambacher** [comment]
I hope it's fixed now.

**Comment by pelwell** [comment]
Thanks - that looks much better.

**Pull request merged**
