### PR TITLE
drivers: media: rp1_cfe: Remove PISP specific MBUS formats

### PR DESCRIPTION
**Pull request by naushir**
Remove the MEDIA_BUS_FMT_PISP* format codcs entirely. For the image pad formats, use the 16-bit Bayer format mbus codes instead. For the config and stats pad formats, use MEDIA_BUS_FMT_FIXED.

Remove the format validation check in cfe_video_link_validate(), as there is no 1:1 mapping from mbus codes to V4L2 format fourcc any more.

### CODE REVIEW

**Comment by naushir** [comment]
@tomba this change gets rid of the custom pisp mbus codes.  Note we need an accompanying change in libcamera to keep userland in sync.  I'll merge that once this goes in.

EDIT: The userland tree can be found at https://github.com/raspberrypi/libcamera/tree/next_mbus

**Comment by tomba** [comment]
> Remove the format validation check in cfe_video_link_validate(), as there is no 1:1 mapping from mbus codes to V4L2 format fourcc any more.

If I recall right, in my not-merged CFE series I have code that does checks like these. We can (and should) check that the v4l2 pix format is compatible with the mbus format.

**Comment by naushir** [comment]
> If I recall right, in my not-merged CFE series I have code that does checks like these. We can (and should) check that the v4l2 pix format is compatible with the mbus format.

Agree - i'm in the process of adding it back.

**Comment by naushir** [comment]
> Agree - i'm in the process of adding it back.

Done!

**Review by njhollinghurst — APPROVED** [review]
LGTM

FWIW the data on the CSI2->ISP-FE link are indeed 16-bit Bayer, albeit packed in pairs; and so are internal data in CSI2DMA channels somewhere between unpack and (optional) compress stages.

**Comment by naushir** [comment]
I'm going to merge this one now.  Note that once this goes in, you will need to rebuild libcamera from https://github.com/raspberrypi/libcamera/tree/next to get the enum values to match again.

**Pull request merged**
