### PR TITLE
vc4/drv: Only notify firmware of display done with kms

### PR DESCRIPTION
**Pull request by popcornmix**
fkms driver still wants firmware display to be active

Signed-off-by: Dom Cobley <popcornmix@gmail.com>

### CODE REVIEW

**Comment by popcornmix** [comment]
This is a fix for https://github.com/raspberrypi/linux/issues/4428 but it doesn't currently work as firmware_kms only gets set by the subsequent `component_bind_all` call (which invokes `vc4_fkms_bind`).

@6by9 @pelwell any suggestions for a clean way to make this work?
We don't want to call `component_bind_all` first (as it does write to hvs registers).
I guess we can query DT directly?

**Comment by pelwell** [comment]
I can't find a nice "locate the enabled device node by it's label" function - only the kernel overlay support seems to understand labels. There is no property of the vc4 node that is a refence to the firmwarekms node, so aside from adding one that leaves either absolute paths (awful) or searching by compatible string, which is better.

There are two possible compatible strings - `raspberrypi,rpi-firmware-kms` and `raspberrypi,rpi-firmware-kms-2711`. You can either look for both or, since vc4 knows what platform it is running on, choose the appropriate one. Once you have a device node pointer you can check if it is "available" (enabled):
```
    struct device_node *dn;

    compatible_string = ...;
    dn = of_find_compatible_node(NULL, NULL, compatible_string);
    if (vc4->firmware && !of_device_is_available(dn)) {
        ...
```

**Comment by pelwell** [comment]
Note that calling of_device_is_available() with a NULL pointer returns failure without complaint (as we want), and that I've updated the example code so that it should be a drop in replacement once you've decided how to choose a compatible string.

**Comment by popcornmix** [comment]
Thanks. Updated PR booted on Pi3+ and Pi4 with both kms and fkms. Notify call was working on kms.

**Pull request merged**
