### PR TITLE
Add support for merus-amp soundcard and ma120x0p codec

### PR DESCRIPTION
**Pull request by AMuszkat**
This patch add support for [merus-amp soundcard](https://www.infineon.com/cms/en/product/evaluation-boards/kit_40w_amp_hat_zw/)
and its codec ma120x0p. The code has been tested on a Raspberry pi ZW, pi 3B+ and Raspberry pi 4.
The soundcard consists in a Class-D amplifier HAT with a built-in boost converter.

### CODE REVIEW

**Comment by pelwell** [comment]
I can't give a detailed review yet, but so far:
1. It needs a README entry for the overlay.
2. There are debug printks left that should be deleted.
3. The commit message needs a Signed-off-by line.

**Comment by AMuszkat** [comment]
Thanks for the quick reply Phil. Could you please indicate which is the correct README file to put the entry in?

**Comment by pelwell** [comment]
The one in arch/arm/boot/dts/overlays.

**Comment by pelwell** [comment]
4. Unless register definitions are shared between multiple source files, Linux drivers are expected to put  them at the start of the source file that uses them. In your case this means that the content of ma120x0p.h (or at least those bits that are used) needs to go in ma120x0p.c, and the pointless inclusion of ma120x0p.h in merus-amp.c needs to be deleted.
5. The merus-amp driver looks like it could be replaced with an instance of the simple-audio-card driver - search the existing overlays for "simple-audio-card" for examples of its use.

**Comment by AMuszkat** [comment]
makes sense, will try it and get back asap.

**Comment by pelwell** [comment]
At first glance that's looking much better. I'll run a few checks and get back to you.

**Comment by pelwell** [comment]
In general I'm reasonably happy with this PR. I'd prefer the codec to be upstreamed so we don't have to maintain it, but this wouldn't be the first downstream codec.

The changes I'd like to see are:
1. the addition of the "interrupt" parameter to the README entry (or the removal of the parameter if it isn't useful), and
2. the errors and style warnings from checkpatch fixed (I'm not bothered about the warnings asking for documentation of compatible strings, etc.):
    ```bash
    # First squash the commits together
    $ git rebase -i HEAD~2
    # In the editor, change the instruction for the second commit to "squash" or "fixup" - squash
    # lets you merge the two commit messages, fixup just deletes the second comment - then
    # save and exit.

    # Now check the commit
    $ git format-patch HEAD~1
    $ scripts/checkpatch.pl 0001-*
    # (assuming there is no other file name beginning 0001-)

    # Fix the errors/warnings and repeat the format-patch and checkpatch until only
    # the documentation-like warnings appear.

    # Now push the new version for review - you'll need the -f option
    $ git push -f your-remote-name HEAD:rpi-4.19.y
    # (substituting the real name of your remote)
```

**Comment by pelwell** [comment]
I see you've pushed an update - GitHub doesn't send out notifications for that, so it's always a good idea to add a comment.

That's looking much better, but checkpatch still has a few complaints (I've deleted the ones I don't care about):
```
ERROR: do not set execute permissions for source files
#51: FILE: arch/arm/boot/dts/overlays/merus-amp-overlay.dts

WARNING: Missing or malformed SPDX-License-Identifier tag in line 1
#56: FILE: arch/arm/boot/dts/overlays/merus-amp-overlay.dts:1:
+// Definitions for Infineon Merus-Amp

WARNING: please write a paragraph that describes the config symbol fully
#180: FILE: sound/soc/codecs/Kconfig:635:
+config SND_SOC_MA120X0P

ERROR: trailing whitespace
#1484: FILE: sound/soc/codecs/ma120x0p.c:1269:
+^I^Idev_err(&i2c->dev, $

ERROR: trailing whitespace
#1509: FILE: sound/soc/codecs/ma120x0p.c:1294:
+^I^Iif (ret != 0) $

total: 3 errors, 11 warnings, 1538 lines checked
```

**Comment by AMuszkat** [comment]
Hi Phil,

Except for the error #51 I can not see anything wrong with the rest of them. Içm not sure why they are being checked as errors/warnings. 

On the other hand, on error #56 I can not find any overlay file with SPDX-License Identifier on the first line, which I find it extremely strange too.

Any clues on how I can proceed?

**Comment by pelwell** [comment]
> Except for the error #51 I can not see anything wrong with the rest of them. I'm not sure why they are being checked as errors/warnings.

51. `chmod -x arch/arm/boot/dts/overlays/merus-amp-overlay.dts`
56. Some overlays do have them - I suggest:
    `// SPDX-License-Identifier: GPL-2.0-only`
180. checkpatch seems to want a minimum of 4 lines, excluding the boiler plate. You can ignore this one.
1484. You have a trailing space (` `) on the end of line 1269.
1509. Ditto on line 1294.

**Comment by AMuszkat** [comment]
Done and checked! should I push it again?

**Comment by pelwell** [comment]
Yes please, then I'll merge it if nothing else shows up.

**Comment by AMuszkat** [comment]
Done

**Comment by pelwell** [comment]
Somewhere along the line we seem to have lost your original commit message. I can't change it now without a complete reversion, but if you post something suitable here I'll make sure it is applied to the newer kernels.

**Comment by AMuszkat** [comment]
I'm actually seeing it in the rpi-4.19.y branch:
"Add support for merus-amp soundcard and ma120x0p codec"

**Comment by pelwell** [comment]
Yes, but the body says:
```
correct checkpatch warnings and errors
```

**Comment by AMuszkat** [comment]
ha ok! no problem for me if "Add support for merus-amp soundcard and ma120x0p codec" appears on the new kernels.

**Comment by pelwell** [comment]
Thanks - will do.

**Comment by AMuszkat** [comment]
Hi Phil,

Is there any target date for the next Raspbian update? The current one is still in 4.19.97 kernel and we would like to have support fot this sound card.

Best,
Ariel

**Pull request merged**
