### PR TITLE
bcm2708_fb : Implement blanking support using the mailbox property inter...

### PR DESCRIPTION
**Pull request by trevd**
...face

This implementation uses the userspace request style of an array of unsigned
32bit ints rather the vc_msg/vc_msg_tag which is more confusing to work with.

vcio.h : Added some extra enums to the vcio.h to improve readability
vcio.h : Renamed DEVICE_FILE_NAME to something more appropriate. users of the
vcio api will be unaffected  by this change as the device node as the device node
is created manually in userspace

### CODE REVIEW

**Comment by trevd** [comment]
@popcornmix . I've probably got some other changes for you ... is there any particular process to follow or are you fine with unsolicited pull requests? it seems a little rude/impersonal!

**Comment by popcornmix** [comment]
Can you squash / force push.

PRs are fine. You can email popcornmix at gmail dot com if you have questions before submitting a PR.

**Comment by trevd** [comment]
I think that's a bit cleaner! :)  .. While i'm here then I've got this one https://github.com/trevd/android_kernel_broadcom_rpi/commit/72d889efee2812265694b602afef74faaecb4992 which is Android related as that's what I'm working on, it'll be nice to have it upstream :) also I noticed the main development effort isn't on the latest branch? so would it be advisable to push patches in that direction too ..

thanks

**Comment by popcornmix** [comment]
Official firmware comes from 3.12.y, but I'll cherry-pick commits from wherever they are submitted if they look useful.
Typically just the official (currently 3.12) and latest stable (currently 3.16) should both be maintained with any useful bug fixes or features. (I'll cherry pick this to 3.12 after merging and sanity testing).

https://github.com/trevd/android_kernel_broadcom_rpi/commit/72d889efee2812265694b602afef74faaecb4992 should really be submitted to upstream kernel:
https://www.kernel.org/doc/Documentation/SubmittingPatches
as it's not Pi specific.

**Comment by trevd** [comment]
Thanks. .. After some more research it appears the uapi changes doesn't
belong in the kernel at all. it was renamed in the 3.5 branch and the
android userland was update to match.

**Pull request merged**
