### PR TITLE
Enable vchiq on ARCH_BCM2835

### PR DESCRIPTION
**Pull request by notro**
Tested on Pi1 and Pi2 regular kernel with and without DT + ARCH_BCM2835.

Tested from userspace:

```
$ vcgencmd measure_temp
temp=34.7'C
```

### CODE REVIEW

**Comment by popcornmix** [comment]
Fine by me. @pelwell - this is your code - feel free to merge if happy.

**Comment by pelwell** [comment]
I'm fine with the substance of the change - thanks! - but I'm not keen on the division into multiple commits. I would argue that the first two patches should be combined into one, since the first patch is useless without the second, and causing the kernel to attempt to load what is effectively a non-existent module (because of the lack of a "compatible" string), though harmless, seems like bad form when it could so easily be avoided.

**Comment by notro** [comment]
It is common practice in mainline to split driver commits from device commits. Actually the first commit would probably have been 3 commits in mainline.
If it's a new driver, there would be a separate commit for enabling the module as well.
There is no problem having a device with no matching driver. We already have one device added in the board file without an enabled driver: bcm2835_hwmon_device

Following your logic all three should be squashed.

One problem with having large commits is that it makes it more difficult to browse the git log for changes. This is quite a big project so many people are reading the git log.

But I'll squash the first two if you want it that way.

**Comment by pelwell** [comment]
Any thoughts, @popcornmix?

**Comment by popcornmix** [comment]
I guess it depends on whether we can see these commits being upstreamed.
If they are expected to be upstreamed, then having commits in a form suitable for upstreaming is valid.

If they are not being upstreamed, then I generally prefer the minimal number of commits. It generally makes cherry-picking, rebasing and bisecting simpler if you don't have a long list of dependent commits.

**Comment by pelwell** [comment]
I wouldn't have thought anything of it if the two device commits weren't on opposite sides of the driver commit, but if this is as you would like it to be then I'm not going to be awkward about it.

**Pull request merged**
