### PR TITLE
RFC: drm/vc4: Only update cursor planes once per vblank in FKMS

### PR DESCRIPTION
**Pull request by 6by9**
Rate limit cursor plane updates by only submitting one per vblank
interrupt.

Signed-off-by: Dave Stevenson <dave.stevenson@raspberrypi.org>

### CODE REVIEW

**Comment by 6by9** [comment]
ping @popcornmix

**Comment by JamesH65** [comment]
@6by9 This appears to have a load of stuff in unrelated to the comment - has the change come in by a different route?

**Comment by 6by9** [comment]
It's a WIP branch with popcornmix trying to understand the tearing issues he's seeing.
See also gitlab 538.
The first 12 commits have just been merged via 3103 so can be ignored. I think I just hadn't started from scratch with this branch.

**Comment by pelwell** [comment]
Can this be closed now?

**Pull request closed without merging**
