### PR TITLE
Adding support for additional i2s card/board drivers

### PR DESCRIPTION
**Pull request by BBUK**
As per a request from koalo, I attach the changes I have made to make the 3.8 i2s card/board drivers work with the 3.10 kernel.  This expands on the existing hifiberry support in 3.10 to include some other common i2s boards.

I have only tested the proto board driver (WM8731 chipset) so I can not vouch for the other drivers.  If you prefer, I am happy to reissue the pull request with just the drivers I have tested.

BBUK

### CODE REVIEW

**Comment by koalo** [comment]
Thank you very much!
Unfortunately, you have mangled the indention. Not only for the new code, but for existing code, too. That makes it difficult to see the actual differences.
Please use tabs and no more than 80 characters per line (https://www.kernel.org/doc/Documentation/CodingStyle)
Furthermore, I would prefer to have a pull request for the proto board, only. Especially since your current pull request collides with another one (https://github.com/raspberrypi/linux/pull/471).
If you rebase anyway, it would be great if you split the commit into one for the machine driver (rpi-proto.c) and one for the board file (bcm2708.c).

**Comment by fl4p** [comment]
WM8731 works fine with aplay, arecord and alsaloop, but jackd does not work:

```
ALSA: mmap-based access is not possible for the capture stream of this audio interface
ALSA: cannot configure capture channel
```

It worked with 3.8. Is capture mmap supported in 3.10?

**Comment by koalo** [comment]
That is a known problem: MMAP doesn't work together with 24 bit support. Therefore, in 3.10 24 bit support is enabled and MMAP is disabled. Unfortunately, I currently don't have time for debugging it.

**Comment by BBUK** [comment]
Thanks koalo.  You are right in that I played with the indention in the existing code but I thought I was correcting it (I replaced 8 spaces with a tab in quite a few places).  Nonetheless, I can see that would make the changes difficult to see, so I will redo this pull request for just the proto board with two separate commits (one for rpi-proto.c / Kconfig / Makefile and one for bcm2708.c).

BBUK

BBUK

**Comment by popcornmix** [comment]
No need to close this PR.
Just edit your current commit (with git rebase -i HEAD~4).
Edit/squash/split.
When the commits look good locally, do a "git push -f" and this PR will update.

**Comment by koalo** [comment]
You were absolutely right. If you have found 8 spaces instead of a tab that was my fault and it was good that you have corrected it.

I am just very confused, because if you look at the files in the commit view the indention is 2 spaces, while in the file view it has 8 spaces. Maybe that is a bug in github or I am too stupid to use it.

Anyway, it would be good to have a pull request that only covers the proto patch.

**Pull request closed without merging**
