### PR TITLE
This will add durio sound driver to rpi 3.18.y

### PR DESCRIPTION
**Pull request by pitichai**
Changes to be committed:
    new file:   arch/arm/boot/dts/duriosound-dac-overlay.dts
    new file:   sound/soc/bcm/duriosound-dac.c
 Changes not staged for commit:
    modified:   arch/arm/configs/bcm2709_defconfig
    modified:   arch/arm/configs/bcmrpi_defconfig
    modified:   arch/arm/mach-bcm2708/bcm2708.c
    modified:   arch/arm/mach-bcm2709/bcm2709.c
    modified:   sound/soc/bcm/Kconfig
    modified:   sound/soc/bcm/Makefile
    modified:   sound/soc/bcm/duriosound-dac.c

### CODE REVIEW

**Comment by pitichai** [comment]
This is  driver for Durio Sound base on pcm5102a. I have tested on all RPI A, RPI B, RPI B+, RPI A+, and RPI2 B. All work. Please merge to branch rpi 3.18.y. 

Thank you very much. 
Pitichai

**Comment by pelwell** [comment]
1) The driver module is clearly a copy of Florian Meier's HifiBerry DAC driver, with a few strings changed. It adds nothing new, and actually omits the logic to locate the I2S driver using Device Tree. I am reluctant to merge a clone just to change a few strings. Perhaps what is needed is to remove the strings from the other driver, or to allow them to be extracted from Device Tree.

2) Going forward we won't be accepting patches to the board support code adding some platform devices - that is what DT was created for.

3) The overlay looks fine, but then it should since it is a copy of the one I wrote for the HifiBerry.

**Comment by pitichai** [comment]
Hi Pelwell,
Thank you for your comments. To be honest, I totally accept that I rewrite the code which is written by Florian Meier for RPI-DAC (rpi-dac.c) not for Hifiberry DAC. Due to this Durio Sound DAC is designed base on RPI-DAC (Me and Torsten), but RPI-DAC is using pcm1794a dac chip and durio sound is using pcm5102a. With pcm5102a codec  will allow me to play pcm up 32bit and 192kbps song. And Hifiberry DAC is using pcm5102a.  I do understand to not accept the patch due to the code look pretty like coping and just change the string name. 

For Hifiberry DAC (HW) is available for RPI A and B, and for RPI B+ and RPI2 B will need to go for Hifiberry DAC+. For me I am happy to close the PR, and I can offer the module driver to Durio Sound users on my community support forum, if  they want it. I also told them that Hifiberry DAC is working, but on the previous kernel 3.12.y. Some users said durio sound driver provide sound a bit bigger than Hifiberry DAC driver. 

Secondly, Yes for overlay file I follow the one you wrote for hifiberry. Due to it use i2s port and same dac chip. I just think to use durio name configured in /boot/config.txt will be easier for users. 

Thank you very much, 
Pitichai

**Comment by mi-hol** [comment]
@pitichai, @pelwell I wonder if this is still active or relevant due to the title refering to very old kernel version 'rpi 3.18.y'

**Comment by popcornmix** [comment]
We'll obviously never merge this into the ancient 3.18 kernel, so closing.
If it is still wanted it should be PR'ed against 4.4 kernel.

**Pull request closed without merging**
