### PR TITLE
Add support for the AudioInjector.net Isolated sound card

### PR DESCRIPTION
**Pull request by flatmax**
This patch adds support for the Audio Injector Isolated sound card.

### CODE REVIEW

**Comment by pelwell** [comment]
If you have a moment to port the merged version to 5.4 (there are a few ALSA changes) it would be appreciated.

**Comment by flatmax** [comment]
Sure, I will look into that.

Is there a way to pull a 5.4 kernel to a Pi4 using rpi-update ?

Also can you please confirm these are still the build commands for a Pi4 for the 5.4 kernel branch ?
export KERNEL=kernel7l
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcm2711_defconfig
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- zImage modules dtbs

**Comment by flatmax** [comment]
Oh I see I can pull the latest with rpi-firmware by using the next branch.

I am getting build failures on the rpi-5.4y branch for arm_ssp_per_task_plugin.o

**Comment by flatmax** [comment]
Oh I got it here :
https://github.com/raspberrypi/documentation/pull/1399/commits/6dd374bad56c22820da45e0a8583e33aaa0483b6

**Comment by flatmax** [comment]
I've created a pull request against the 5.4.y branch :
https://github.com/raspberrypi/linux/pull/3533

**Comment by scottyasi** [comment]
Great work Matt! Very kind of you to do this!

**Pull request merged**
