### PR TITLE
added basic docker support

### PR DESCRIPTION
**Pull request by umiddelb**
I've added some switches in the default kernel config which are needed to run docker on the RPi

Kind regards
Uli

### CODE REVIEW

**Comment by popcornmix** [comment]
There are some options here that concern me. E.g. CONFIG_MEMCG_SWAP

> This extension is useful when you want to avoid exhaustion swap but this itself adds more overheads and consumes memory for remembering information. Especially if you use 32bit system or small memory system, please be careful about enabling this.

In general any config changes more intrusive that just adding modules need to be examined carefully. If you could do some testing with and without these options enabled to confirm the impact on memory usage and performance that may help (e.g. check free memory on boot and benchmark like nbench).

I'd also like to know how many users actually want this feature, so if you do then post here.

**Comment by Ferroin** [comment]
IIRC, the overhead from CONFIG_MEMCG_SWAP can be avoided by not enabling it (there is a boot option to disable it at runtime).

I can definitely see the OverlayFS support being generally useful even aside from Docker however.

**Comment by umiddelb** [comment]
Hi @popcornmix 

thank you for the fast reply, I'll reduce the PR to
- CONFIG_CPUSETS=y
- CONFIG_PROC_PID_CPUSET=y
- CONFIG_DM_BIO_PRISON=m
- CONFIG_DM_PERSISTENT_DATA=m
- CONFIG_DM_THIN_PROVISIONING=m
- CONFIG_OVERLAY_FS=m

which is considered to be the minimal set of kernel options. I'll test it and refine the PR.

**Comment by umiddelb** [comment]
OK, compiled the kernel with this new set of options and refined the PR.

**Comment by umiddelb** [comment]
I've run some tests (i.e. time (compile the linux kernel) twice) with both versions
1: rpi-3.18.y
2: rpi-3.18.y with the options enabled mentioned above (scope of the PR)

I haven't found any serious performance impacts, here are the results:
1: 508:09 (445:25, 19:16) and 506:58 (445:44, 19:13)
2: 506:38 (444:41, 19:37) and 507:55 (445:11, 19:52)

**Comment by popcornmix** [comment]
Are they results of running `time ./nbench` ?
What does `free -h` show after boot before and after?

**Comment by umiddelb** [comment]
I've run `time sh make_kernel.sh` where make_kernel.sh contains:

```
export KERNEL=kernel
make bcmrpi_defconfig
make clean
make zImage modules dtbs
sudo make modules_install
sudo cp arch/arm/boot/dts/*.dtb /boot/
sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/
sudo scripts/mkknlimg arch/arm/boot/zImage /boot/$KERNEL.img
```

Output of `free -h` directly after having booted the docker enabled kernel:

```
$ free -h
             total       used       free     shared    buffers     cached
Mem:          482M        75M       407M         0B       9.5M        41M
-/+ buffers/cache:        24M       458M
Swap:          99M         0B        99M
```

Output of `free -h` after having compiled the docker enabled kernel:

```
$ free -h
             total       used       free     shared    buffers     cached
Mem:          482M       467M        15M         0B        29M       377M
-/+ buffers/cache:        59M       423M
Swap:          99M         0B        99M
```

**Comment by stuart-c** [comment]
Hi @popcornmix

It would be handy to get OverlayFS in as well the other bits to allow basic Docker support.

**Comment by djmaze** [comment]
:+1: for Docker support on the Pi. Have long been waiting for it. Also +1 on OverlayFS, since from my experience it is the fastest and least problematic graph driver for Docker.

**Comment by juliancheal** [comment]
:+1:

**Comment by popcornmix** [comment]
ping @pelwell @P33M for comments

**Comment by kennethlimcp** [comment]
:+1:

**Comment by ubergesundheit** [comment]
Docker support? OverlayFS? Count me in!
+1 very much!

**Comment by pelwell** [comment]
I'm not against Docker and OverlayFS in principal, provided it doesn't penalise non-users.

Can someone outline their reasons for wanting it?

**Comment by umiddelb** [comment]
As far as I have run the test, I haven't seen any signs of penalisation. Only two options are included as non-module (CONFIG_CPUSETS, CONFIG_PROC_PID_CPUSET).

The [kernel documentation](https://www.kernel.org/doc/Documentation/cgroups/cpusets.txt) says about cpusets:
...
"The implementation of cpusets requires a few, simple hooks into the rest of the kernel, none in performance critical paths:"
...

**Comment by umiddelb** [comment]
There are many articles reasoning for running docker on the RPi
- https://resin.io/blog/why-port-docker-to-the-raspberry-pi/
- http://blog.xebia.com/2014/08/25/docker-on-a-raspberry-pi/
- ...

**Comment by stuart-c** [comment]
OverlayFS is also useful outside of Docker - being able to merge say a USB drive and the SD/eMMC so you can protect important system software on a RO partition/device but still allow full write access

**Comment by pelwell** [comment]
Can you squash these down to one commit?

**Comment by umiddelb** [comment]
opened a new [PR](https://github.com/raspberrypi/linux/pull/1027) with one single commit

**Comment by pelwell** [comment]
FYI you could have used git push -f to replace the two commits with the squashed one.

**Comment by umiddelb** [comment]
> IIRC, the overhead from CONFIG_MEMCG_SWAP can be avoided by not enabling it (there is a boot option to disable it at runtime).

Even if you compile the kernel with CONFIG_MEMCG_SWAP, it is disabled anyway during boot.

**Pull request closed without merging**
