### PR TITLE
config: Add CONFIG_USB_DWC2 and CONFIG_USB_GADGET

### PR DESCRIPTION
**Pull request by pelwell**
The introduction of CM3 makes gadget mode on 2709 a useful option,
so enable the building of the required modules. Note that these
modules are not loaded by default and must be enabled with a DT
overlay.

### CODE REVIEW

**Comment by ED6E0F17** [comment]
Can you confirm that this enables USB_DWC2_DUAL_ROLE ?

**Comment by popcornmix** [comment]
Yes I see CONFIG_USB_DWC2_DUAL_ROLE=y in .config after building with this change.

**Comment by pelwell** [comment]
I've now added the remaining USB options that were in bcmrpi_defconfig but missing from bcm2709_defconfig.

Any objections to merging this?

**Comment by popcornmix** [comment]
No objection.

**Pull request merged**
