### PR TITLE
fix Hsync and Vsync polarity can't change from negatieve to positief …

### PR DESCRIPTION
**Pull request by Michiiel**
…vc4_hdmi.c

There was a small issue where if you change the polarity from + to -, you could not change back because you never undo the written bit in the register. This is because only | is used, when & is needed to change back to positive (+).

### CODE REVIEW

**Comment by popcornmix** [comment]
Good spot. This can be done more cleanly without the conditionals:

```
	HDMI_WRITE(HDMI_VID_CTL,
		   (HDMI_READ(HDMI_VID_CTL) &~ 
                   (VC4_HD_VID_CTL_VSYNC_LOW | VC4_HD_VID_CTL_HSYNC_LOW)) |
		   VC4_HD_VID_CTL_ENABLE |
		   VC4_HD_VID_CTL_CLRRGB |
		   VC4_HD_VID_CTL_UNDERFLOW_ENABLE |
		   VC4_HD_VID_CTL_FRAME_COUNTER_RESET |
		   VC4_HD_VID_CTL_BLANK_INSERT_EN |
		   (vsync_pos ? 0 : VC4_HD_VID_CTL_VSYNC_LOW) |
		   (hsync_pos ? 0 : VC4_HD_VID_CTL_HSYNC_LOW));
```

**Comment by Michiiel** [comment]
> Good spot. This can be done more cleanly without the conditionals:
> 
> ```
> 	HDMI_WRITE(HDMI_VID_CTL,
> 		   (HDMI_READ(HDMI_VID_CTL) &~ 
>                    (VC4_HD_VID_CTL_VSYNC_LOW | VC4_HD_VID_CTL_HSYNC_LOW)) |
> 		   VC4_HD_VID_CTL_ENABLE |
> 		   VC4_HD_VID_CTL_CLRRGB |
> 		   VC4_HD_VID_CTL_UNDERFLOW_ENABLE |
> 		   VC4_HD_VID_CTL_FRAME_COUNTER_RESET |
> 		   VC4_HD_VID_CTL_BLANK_INSERT_EN |
> 		   (vsync_pos ? 0 : VC4_HD_VID_CTL_VSYNC_LOW) |
> 		   (hsync_pos ? 0 : VC4_HD_VID_CTL_HSYNC_LOW));
> ```

i tested youre new code and it works

**Comment by popcornmix** [comment]
How are you testing this? Are you using an analyser or do you have a display that is unhappy with the incorrect polarity?
What are the hdmi modes you are switching between?

**Comment by Michiiel** [comment]
> How are you testing this? Are you using an analyser or do you have a display that is unhappy with the incorrect polarity? What are the hdmi modes you are switching between?

i have an analyser and as for the hdmi timing i create my own via a drm application i am writing

**Comment by popcornmix** [comment]
Can you provide a "Signed-off-by" message? (`git commit -s` adds this to a commit message).

Or if you agree here, we can add it in when squashing/merging.

**Comment by Michiiel** [comment]
> Can you provide a "Signed-off-by" message? (`git commit -s` adds this to a commit message).
> 
> Or if you agree here, we can add it in when squashing/merging.

we can add it in squashing/merging

**Comment by popcornmix** [comment]
The signed-off message looks like:
```Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>```

Can you provide a name/email to use for that?
Or alternatively I can merge it under my name if you'd prefer.

**Comment by Michiiel** [comment]
> The signed-off message looks like: `Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>`
> 
> Can you provide a name/email to use for that? Or alternatively I can merge it under my name if you'd prefer.

i updated the last commit to have the signed-off-by message. is there anything else i need to do

**Comment by pelwell** [comment]
No, that looks fine - we just don't get notifications for pushes. I'll let popcornmix do the merge.

**Comment by popcornmix** [comment]
This fix should appear in future rpi-update kernels (and later in apt).
Thanks for report. Let us know if you spot anything else that analyser says is incorrect!

**Pull request merged**
