### PR TITLE
lirc: added support for RaspberryPi GPIO

### PR DESCRIPTION
**Pull request by ar0n**
This branch adds lirc capability for a simple receiver/blaster connected to the gpio pins (Details described here: http://aron.ws/projects/lirc_rpi/). Because bcm2708 core support can't be found in the mainline kernel, my patch won't be applied there, but got a promise that when it does it will be applied.

For people who use the RPi for multimedia purposes this adds cheap IR capabilities.

### CODE REVIEW

**Comment by nomis** [comment]
Could this use gpiolib instead of accessing the GPIO registers directly?

I have a driver in my branch that supports GPIO IRQs:
https://github.com/raspberrypi/linux/wiki/How-to-boot-using-device-tree

**Comment by ar0n** [comment]
I didn't know about that, but of course it can! I will modify the code.

Thanks!

**Comment by alexbain** [comment]
@lp0 Is it likely that this pull request will be merged if it's converted to gpiolib?

@ar0n Thanks for spending the time on this improvement!

**Comment by ghost** [comment]
push ... I also would like to see the driver in the kernel. It is really annoying to compile the kernel each time just to get the module back running after updating archlinuxarm. I don't mind if it uses GPIO directly. It's the only device I use on GPIO.

**Comment by cleverca22** [comment]
ive started the libgpio conversion, https://github.com/ar0n/linux/pull/1

**Comment by alexbain** [comment]
What's the status of this pull request? Is the GPIO conversion complete at this point?

**Comment by cleverca22** [comment]
last i heard, ar0n was going to finish it off, but the last commit is from 23 days ago
i could take a look at it in ~1week and see what works and whats left to do

**Comment by ar0n** [comment]
For the receiver part, yes. The transmitter part still needs work to work with gpiolib. I have a working piece of code, but still need to clean it up / calibrate the output etc ... I wil ltry to finish this up next week.

**Comment by cleverca22** [comment]
yeah, i noticed the carrier was off by ~2-3khz, but i didnt bother fixing it once i found out the problem was drive current

**Comment by alexbain** [comment]
Awesome, I can't wait to see this finished up. I'm really looking forward to using a rPi with LIRC.

**Comment by ghost** [comment]
Me too. Even though mine is running with Arons code very well for 
months! But still great news! Hopefully it will then come into the 
distributions.

Am 21.09.2012 19:49, schrieb Alex Bain:

**Comment by ghost** [comment]
A month later, still not finished? What's the problem? Maybe th ecommunity can help?

**Comment by cleverca22** [comment]
i'll see what i do today, ive still got the hardware infront of the tv, just need to rebuild the module and see whats left

Module.symvers is missing from the firmware repo (again), so i'll need to rebuild the whole kernel before i can test things
i'll leave an update later when i get everything compiled and tested

**Comment by cleverca22** [comment]
ok, ive got a working version of the module with everything going thru the lib, no raw register access
https://github.com/cleverca22/linux/commit/02c4ee512fcc59dede22c18014bbc86710cc8927

i'll check for any issues i saw mentioned, like the led being left on, or the carrier freq being off
edit: freq is dead on all the way from 20khz to 60khz
gpio pin is left LOW after transmit ends and after module unloads

whats left?, testing and code quality?

**Comment by ar0n** [comment]
Wow cool, i didn't manage to finish it yet (had to work and finish my studies), but I will test your version today and report back.

**Comment by cleverca22** [comment]
helps when you have no fixed work hours and no school to go to :)

**Comment by popcornmix** [comment]
The patch looks reasonable, but I don't have any hardware to test this, so if a few people can confirm it works I can accept it.

**Comment by alexbain** [comment]
Thank you!

**Comment by AndyPi** [comment]
Hi, 

Ive been hoping for this so had a go, it fails to compile with:

drivers/staging/media/lirc/lirc_rpi.c:32:26: fatal error: linux/sysdev.h: No such file or directory
compilation terminated.

seems to compile with the include commented out though !!

will continue to test

regards

Andy

**Comment by ghost** [comment]
The file sysdev.h must be in your kernel-sources. I have it in
/opt/raspberrypi/linux/include/linux/sysdev.h
where /opt/rsapberrypi is the folder, were I startet to download the kernel via git

**Comment by popcornmix** [comment]
include/linux/sysdev.h is in my 3.2.27 kernel, but it was removed in 3.3 and so isn't there is 3.6.y.
We will be switching to 3.6.y in the future, so moving sysdev.h seems desirable.

**Comment by cleverca22** [comment]
if it builds fine without it, then is it even needed?

it compiles fine against 3.2.27 with that commented out

**Comment by ghost** [comment]
I think you are right, The code does not seem to use any of the functions from sysdev.h
So we can just delete the include.

**Comment by ghost** [comment]
Compiles fine here. I can only test Input with XBMC (Raspbian) but it seems to do just fine. No trouble yet.

**Comment by AndyPi** [comment]
Hi,

tested with my simple IR homebrew reciever and it seems to function well.  Well done !

regards

Andy

**Comment by ar0n** [comment]
Actually the modification have been made to the blasting part, the receiver worked well before cleverca22's latest patch. I've also tested it and it works.

**Comment by cleverca22** [comment]
the receiver side went under some changes just recently, because it was enabling the IRQ somewhat manualy (direct registers)
i switched it over to the irqchip struct, but couldnt really find any docs, so i just read random source files thru-out the whole kernel

**Comment by AndyPi** [comment]
Hi 
yes its true, arons lirc patch has been working well as an ir receiver for ages - Ive been using it and am very grateful (thanks aron).

Im using Openelec and having to patch each time, which is a minor inconvenince particularly when linux version changes.  So I am very pleased that you guys have made such efforts to get the lirc_rpi patch to a stage where it can be merged.

Thanks again,
regards

Andy

I understand that that there has been more change to the blaster side and that the receiver side has been working well for ages.

**Comment by esalgado** [comment]
Hi guys! 

Nice work, I'm going to an electronics shop tomorrow to get a IR Sensor and I will test.

By the way, cloning your repository and making "make menuconfig" the menu shows kernel 3.2.19! Is that right?

Thanks!

**Comment by cleverca22** [comment]
yeah, it threw tons of merge conflicts when i tried to merge with the latest pi linux repo

i just copied the module out to its own dir, and built it fully stand-alone, like you normaly do for non-tree modules
against the official pi linux repo

**Comment by ar0n** [comment]
I will merge it with the new kernel shortly... ;)

**Comment by ghost** [comment]
ehhhmmm and how is it with the 3.2.27+ kernel? And with this pull request? Couldn't this now be merged and closed?

**Comment by ar0n** [comment]
I have actually merged it, but not yet pushed it, because I still need to see if there are no timing issues. I will push it up today ;).

**Comment by esalgado** [comment]
Is the driver lirc_rpi.c the same one in the patch for lirc (http://aron.ws/projects/lirc_rpi/lirc_rpi-0.2.2.patch) ? 

Trying to compile lirc with that patch fails due to 
<code>/home/pi/src/lirc/drivers/lirc_rpi/lirc_rpi.c:318:6: error: 'GPIO_BASE' undeclared (first use in this function)</code>

When I substitute this one with the one in this page it builds fine...

**Comment by cleverca22** [comment]
GPIO_BASE was part of the raw register access, which isnt cross-platform

the new libgpio code in the latest version should (in theory) work on any platform with the required features (1 input pin, 1 output pin, and rise/falling edge interupts)

much more likely that it may even make it into the official kernel branch

and yeah, they are the same file, the patch is just an older version

**Comment by ar0n** [comment]
I will take that patch off, because it only causes confusion ... :/

**Comment by ar0n** [comment]
@esalgado: I've updated the patch on my site.

**Comment by ar0n** [comment]
I've tested the module with the new kernel and I think it's stable and ready to be merged. I have not modified anything functional in cleverca22's patch, just cosmetics so that it complies with the kernel coding style.

**Comment by esalgado** [comment]
Works flawlessly!!! I tried this last version of the patch and tested with several remotes.

Thanks!

**Comment by popcornmix** [comment]
This pull request seems to be for rpi-patches which is no longer used.
Can you submit a pull request against rpi-3.2.27 (ideally squashing the commits).

**Comment by perryflynn** [comment]
The module works perfect.
Many thanks for this!

**Comment by ar0n** [comment]
Closing this, https://github.com/raspberrypi/linux/pull/152

**Pull request closed without merging**
