### PR TITLE
Add .dtbo rule for arm64 dts overlay

### PR DESCRIPTION
**Pull request by kraj**
We now create overlays as .dtbo files.

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by Electron752** [comment]
Hi,

I'm sure you have a really good reason for this change, but I'm curious what it is.  Ideally, I always thought the change to arm64 should be an overlay in itself.   Is this by any chance part of this change?

**Comment by kraj** [comment]
@Electron752 in Yocto we build DT overlays separately from kernel proper build.  This fails to build them since this rule is missing for arm64.

**Comment by kraj** [comment]
Can this be merged ? it helps in compilng 4.9 for rpi3_64

**Comment by pelwell** [comment]
Can you give an example of a command that fails to build the overlays without this commit but works with it?

**Comment by kraj** [comment]
@pelwell in yocto we pass --hash-style=gnu via LDFLAGS e.g. and now it does not appear in linker cmdline for this .so, as a result it uses sysv hash style to link this .so which bombs at runtime, luckily yocto has a QA check for such inconsistencies at build time and it detects this problem. 

No GNU_HASH in the elf binary: '/mnt/a/build/tmp-musl/work/raspberrypi3-oe-linux-musleabi/userland/git-r5/packages-split/userland/usr/lib/libbcm_host.so' [ldflags]

I can verify that LDFLAGS are missing and this has started to happen after 

https://github.com/raspberrypi/userland/commit/aeb5a97143a8ac15aa9d5e717d3a59905f412b2a

**Comment by kraj** [comment]
in yocto the overlays are built separately where it passes a list of .dtb filenames e.g.

   kernel_do_compile
        for DTB in      bcm2708-rpi-b.dtb     bcm2708-rpi-b-plus.dtb     bcm2709-rpi-2-b.dtb     bcm2710-rpi-3-b.dtb     bcm2708-rpi-cm.dtb     bcm2710-rpi-cm3.dtb         overlays/hifiberry-amp.dtbo     overlays/hifiberry-dac.dtbo     overlays/hifiberry-dacplus.dtbo     overlays/hifiberry-digi.dtbo     overlays/i2c-rtc.dtbo     overlays/iqaudio-dac.dtbo     overlays/iqaudio-dacplus.dtbo     overlays/lirc-rpi.dtbo     overlays/pitft22.dtbo     overlays/pitft28-resistive.dtbo     overlays/pps-gpio.dtbo     overlays/rpi-ft5406.dtbo     overlays/w1-gpio.dtbo     overlays/w1-gpio-pullup.dtbo     overlays/pi3-disable-bt.dtbo     overlays/pi3-miniuart-bt.dtbo     overlays/vc4-kms-v3d.dtbo     ; do
                DTB=`normalize_dtb "${DTB}"`
                make ${DTB}
        done

and this fails for arm64

**Comment by pelwell** [comment]
It seems odd not to use the standard "dtbs" and "dtbs_install" make targets, but they probably have their reasons.

**Pull request merged**
