### PR TITLE
i2c-mux and i2c-pwm overlay updates for alternate i2c buses

### PR DESCRIPTION
**Pull request by 6by9**

### CODE REVIEW

**Comment by arduino43** [comment]
Wondering if it would be possible to include support for defining multiple i2c multiplexers? I have had a few situations where this was required due to bus speed limitations.

**Comment by pelwell** [comment]
What makes you think it doesn't work? You'll need to provide different addresses for the muxes (obviously), but it looks like it should work (but I haven't tried it).

**Comment by 6by9** [comment]
You can create as many instances as you fancy as long as they have unique address and bus properties.
```
dtoverlay=i2c-mux,pca9548,addr=0x70
dtoverlay=i2c-mux,pca9548,addr=0x71
dtoverlay=i2c-mux,pca9548,i2c3,addr=0x70
dtoverlay=i2c-mux,pca9548,i2c4,addr=0x71
```
would give you 2 muxes with addresses 0x70 and 0x71 on i2c-1, 1 with address 0x70 on i2c3, and 1 with address 0x71 on i2c-4.

I haven't tried it recently, but have in the past.

If you wish to craft your own overlay then the mux framework will allow cascading muxes to give a tree structure hanging off one parent I2C bus too, eg
```
                            +- devices
                            +- devices
                            +- devices
                            +- devices
                +- mux 0x71 +- devices
                            +- devices
                            +- devices
                            +- devices
							
                            +- devices
                            +- devices
                            +- devices
                            +- devices
                +- mux 0x71 +- devices
                            +- devices
                            +- devices
                            +- devices

                            +- devices
                            +- devices
                            +- devices
                            +- devices
                +- mux 0x71 +- devices
                            +- devices
                            +- devices
                            +- devices
i2c -> mux 0x70 + 
                            +- devices
                            +- devices
                            +- devices
                            +- devices
                +- mux 0x71 +- devices
                            +- devices
                            +- devices
                            +- devices

                            +- devices
                            +- devices
                            +- devices
                            +- devices
                +- mux 0x71 +- devices
                            +- devices
                            +- devices
                            +- devices

                            +- devices
                            +- devices
                            +- devices
                            +- devices
                +- mux 0x71 +- devices
                            +- devices
                            +- devices
                            +- devices

                            +- devices
                            +- devices
                            +- devices
                            +- devices
                +- mux 0x71 +- devices
                            +- devices
                            +- devices
                            +- devices

                            +- devices
                            +- devices
                            +- devices
                            +- devices
                +- mux 0x71 +- devices
                            +- devices
                            +- devices
                            +- devices
```
using 9 pca9548's would give you 64 buses with only 2 addresses having been used on any of them.

You can achieve the same number of buses with 8 pca9548's if you can afford to lose 8 addresses from all of them. That approach is also slightly more efficient on switching as there are fewer commands to send to the muxes.

**Comment by arduino43** [comment]
Perhaps I am misunderstanding:

I have 2 pca9548, 1 connected to i2c1 and 1 connected to i2c3. I was expecting to see 16 i2c devices in /dev but I am only seeing 8 which are picked up on the multiplexer on i2c1. I can set this to any i2cX and it works, but only for the first 8 devices.

Do I need to handle the descriptors? 


/boot/config.txt
dtoverlay=i2c1,pins_2_3
dtoverlay=i2c3,pins_4_5
dtoverlay=i2c-mux,pca9548
dtoverlay=i2c-mux,pca9548,i2c1,addr=0x70
dtoverlay=i2c-mux,pca9548,i2c3,addr=0x70

**Comment by 6by9** [comment]
```dtoverlay=i2c-mux,pca9548``` and ```dtoverlay=i2c-mux,pca9548,i2c1,addr=0x70``` are synonyms - i2c1 and addr 0x70 are the defaults.
Likewise the pins_2_3 is the default for i2c1, so there's no need for the line at all.
```dtoverlay=i2c-mux,pca9548,i2c3``` will enable i2c3, and pins 4&5 are the default there too, so no need for that line at all.

Look in the kernel log for error messages. You should get messages along the lines of ```i2c i2c-3 Added multiplexed i2c bus N```
If the device can't be found, you'll likely get an error message ```pca954x 3-0070: probe failed```. Use ```sudo i2cdetect -y 3``` to confirm that it is responding correctly on i2c-3.
Do you have suitable pull up resistors fitted to i2c-3 on GPIOs 4&5? By default it'll only have the internal ~50k pull ups, which aren't really strong enough for higher speed I2C.

**Comment by arduino43** [comment]
Thanks for the reply. I did notice the unnecessary lines and removed them.

These are my findings so far, but still fiddling with it.

1.) With multiplexers on i2c-1 and i2c-3 I end up with 8 additional i2c devs. These are all attached to  i2c-1
2.) i2c-3 scan shows the multiplexer at 0x70 as expected.
3.) There are error messages in the kernel log regarding i2c devices.
4.) I've tried 50k and 100k, with no difference.

**Comment by 6by9** [comment]
> 3.) There are error messages in the kernel log regarding i2c devices.

What are they?! It's hard to debug an issue with no information.

**Comment by arduino43** [comment]
Ugh, sorry I meant "no errors in log"...

### config.txt
**dtoverlay=i2c-mux,pca9548,i2c1
dtoverlay=i2c-mux,pca9548,i2c4**

### uname
Linux RPI 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

### kern.log
**May  8 00:27:00 MINER-NODE-0016 kernel: [    6.922864] brcmstb-i2c fef04500.i2c:  @97500hz registered in polling mode
May  8 00:27:00 MINER-NODE-0016 kernel: [    6.936187] brcmstb-i2c fef09500.i2c:  @97500hz registered in polling mode**

**May  8 00:27:00 MINER-NODE-0016 kernel: [    7.897204] i2c i2c-1: Added multiplexed i2c bus 22
May  8 00:27:00 MINER-NODE-0016 kernel: [    7.897691] i2c i2c-1: Added multiplexed i2c bus 23
May  8 00:27:00 MINER-NODE-0016 kernel: [    7.898160] i2c i2c-1: Added multiplexed i2c bus 24
May  8 00:27:00 MINER-NODE-0016 kernel: [    7.898631] i2c i2c-1: Added multiplexed i2c bus 25
May  8 00:27:00 MINER-NODE-0016 kernel: [    7.899065] i2c i2c-1: Added multiplexed i2c bus 26
May  8 00:27:00 MINER-NODE-0016 kernel: [    7.899488] i2c i2c-1: Added multiplexed i2c bus 27
May  8 00:27:00 MINER-NODE-0016 kernel: [    7.908574] i2c i2c-1: Added multiplexed i2c bus 28
May  8 00:27:00 MINER-NODE-0016 kernel: [    7.909050] i2c i2c-1: Added multiplexed i2c bus 29**

### /dev entries:

**i2c-1
i2c-20
i2c-21
i2c-22
i2c-23
i2c-24
i2c-25
i2c-26
i2c-27
i2c-28
i2c-29
i2c-4**

### i2cdetect -y 1
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: UU -- -- -- -- -- -- --               
        
### i2cdetect -y 4
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: 70 -- -- -- -- -- -- --

**Comment by arduino43** [comment]
I guess my question is - if you have two multiplexers on two distinct i2c bus, would the expected result be 16 i2c devices created as /dev/i2c-X?

**Comment by 6by9** [comment]
> I guess my question is - if you have two multiplexers on two distinct i2c bus, would the expected result be 16 i2c devices created as /dev/i2c-X?

Yes, there should be 16 additional buses.

I have 2 [Adafruit TCA9548A muxes](https://www.adafruit.com/product/2717) here in the office, on addresses 0x70 and 0x71. These muxes have the benefit of 10k pull up resistors on SDA and SCL (a stronger pull resistor is a smaller value).

Connected both to i2c1 and added 
```
dtoverlay=i2c-mux,pca9548,i2c1
dtoverlay=i2c-mux,pca9548,i2c1,addr=0x71
```
to /boot/config.txt
```
[   10.723396] i2c i2c-1: Added multiplexed i2c bus 22
[   10.758414] i2c i2c-1: Added multiplexed i2c bus 23
[   10.759538] i2c i2c-1: Added multiplexed i2c bus 24
[   10.760443] i2c i2c-1: Added multiplexed i2c bus 25
[   10.763631] i2c i2c-1: Added multiplexed i2c bus 26
[   10.763908] i2c i2c-1: Added multiplexed i2c bus 27
[   10.766603] i2c i2c-1: Added multiplexed i2c bus 28
[   10.767103] i2c i2c-1: Added multiplexed i2c bus 29
[   10.767121] pca954x 1-0071: registered 8 multiplexed busses for I2C switch pca9548
[   10.767846] i2c i2c-1: Added multiplexed i2c bus 30
[   10.768036] i2c i2c-1: Added multiplexed i2c bus 31
[   10.768226] i2c i2c-1: Added multiplexed i2c bus 32
[   10.768432] i2c i2c-1: Added multiplexed i2c bus 33
[   10.775192] i2c i2c-1: Added multiplexed i2c bus 34
[   10.775457] i2c i2c-1: Added multiplexed i2c bus 35
[   10.775737] i2c i2c-1: Added multiplexed i2c bus 36
[   10.775940] i2c i2c-1: Added multiplexed i2c bus 37
[   10.775950] pca954x 1-0070: registered 8 multiplexed busses for I2C switch pca9548
```
So they work.

Change to
```
dtoverlay=i2c-mux,pca9548,i2c1
dtoverlay=i2c-mux,pca9548,i2c3,addr=0x71
```
and rewire to GPIOs 4&5 for the second board. ```sudo i2cdetect -y 3``` runs very slowly (means SCL is held low and it is timing out on clock stretching), and ```raspi-gpio get``` shows GPIOs 4&5 as being inputs still.

Add
```
dtoverlay=i2c3,pins_4_5
```
and i2cdetect -y 3 runs at a sensible speed, and I also get
```
[   10.591457] i2c i2c-1: Added multiplexed i2c bus 22
[   10.591727] i2c i2c-1: Added multiplexed i2c bus 23
[   10.591951] i2c i2c-1: Added multiplexed i2c bus 24
[   10.592196] i2c i2c-1: Added multiplexed i2c bus 25
[   10.592387] i2c i2c-1: Added multiplexed i2c bus 26
[   10.592574] i2c i2c-1: Added multiplexed i2c bus 27
[   10.592766] i2c i2c-1: Added multiplexed i2c bus 28
[   10.592957] i2c i2c-1: Added multiplexed i2c bus 29
[   10.592967] pca954x 1-0070: registered 8 multiplexed busses for I2C switch pca9548
[   10.593596] i2c i2c-3: Added multiplexed i2c bus 30
[   10.602999] i2c i2c-3: Added multiplexed i2c bus 31
[   10.606162] i2c i2c-3: Added multiplexed i2c bus 32
[   10.606553] i2c i2c-3: Added multiplexed i2c bus 33
[   10.606826] i2c i2c-3: Added multiplexed i2c bus 34
[   10.609387] i2c i2c-3: Added multiplexed i2c bus 35
[   10.614925] i2c i2c-3: Added multiplexed i2c bus 36
[   10.615475] i2c i2c-3: Added multiplexed i2c bus 37
[   10.615496] pca954x 3-0071: registered 8 multiplexed busses for I2C switch pca9548
```

So there is a fragment missing from these overlays for enabling i2c3-6 that assigns a pinctrl node to them. Doing so is a pain as you end up adding in the same set of overrides for GPIO selection as the i2c3-6 overlays.

@pelwell Can we add a default pinctrl assignment for i2c3-6 to the base 2711 DT, eg
```
			pinctrl-names = "default";
			pinctrl-0 = <&i2c3_pins>;
```
or does that have issues?

**Comment by pelwell** [comment]
```
dtoverlay=i2c-mux,pca9548,i2c1
```
There is no `i2c1` parameter, but it uses /dev/i2c-1 by default so it doesn't matter.

> Can we add a default pinctrl assignment for i2c3-6 to the base 2711 DT

I can't see why not. I may do the same for the extra SPI and UART nodes as well.

**Comment by 6by9** [comment]
> >    Can we add a default pinctrl assignment for i2c3-6 to the base 2711 DT
>
> I can't see why not. I may do the same for the extra SPI and UART nodes as well.

Ta. It's the equivalent of https://github.com/raspberrypi/linux/blob/rpi-6.1.y/arch/arm/boot/dts/bcm2711-rpi-4-b.dts#L464-L468 that I'm thinking of but for i2c3-6.
Can I leave that with you?

**Comment by pelwell** [comment]
Yup

**Comment by pelwell** [comment]
See #5461 for a potential fix.

**Comment by arduino43** [comment]
I must still be doing something wrong. I finally have i2cdetect seeing both multiplexers, however on i2c-3 I can never get the additional busses to appear. 

Completely removing i2c-1 from /boot/config.txt and trying to enable only i2c-3 as the multiplexer to use, it uses i2c-1.

i2c-1 is working. TCA9548 is detected and 8 busses are added to /dev
i2cdetect -y 1 
70: UU -- -- -- -- -- -- --                         

i2c-3 is not working, but I can see the multiplexer available at 0x70.
i2cdetect -y 3 
70: 70 -- -- -- -- -- -- --          

/boot/config.txt
dtoverlay=i2c1,pins_2_3
dtoverlay=i2c3,pins_4_5
dtoverlay=i2c-mux,pca9548,i2c1
dtoverlay=i2c-mux,pca9548,i2c3

Will keep looking into this. It clearly works for others.

**Comment by jkittner** [comment]
@6by9 I'm trying the very same setup you had in your example above, two TCA9548A, one on the default `0x70` the other set to `0x71` (`A0` + `VIN`).
`config.txt` having this set like that:
```
dtoverlay=i2c-mux,pca9548,i2c1
dtoverlay=i2c-mux,pca9548,i2c1,addr=0x71
```
I am able to see all devices under `/dev/i2c*`
```console
$ ls /dev/i2c-*
/dev/i2c-1   /dev/i2c-21  /dev/i2c-23  /dev/i2c-25  /dev/i2c-27  /dev/i2c-29  /dev/i2c-31  /dev/i2c-33  /dev/i2c-35  /dev/i2c-37
/dev/i2c-20  /dev/i2c-22  /dev/i2c-24  /dev/i2c-26  /dev/i2c-28  /dev/i2c-30  /dev/i2c-32  /dev/i2c-34  /dev/i2c-36
```
the kernel logs also show what I expect

```console
$ dmesg -H | grep -E 'i2c|pca'
[  +0.001757] i2c_dev: i2c /dev entries driver
[  +0.024646] brcmstb-i2c fef04500.i2c:  @97500hz registered in polling mode
[  +0.007624] brcmstb-i2c fef09500.i2c:  @97500hz registered in polling mode
[  +0.017343] i2c i2c-1: Added multiplexed i2c bus 22
[  +0.001278] i2c i2c-1: Added multiplexed i2c bus 23
[  +0.001134] i2c i2c-1: Added multiplexed i2c bus 24
[  +0.000622] i2c i2c-1: Added multiplexed i2c bus 25
[  +0.010452] i2c i2c-1: Added multiplexed i2c bus 26
[  +0.003979] i2c i2c-1: Added multiplexed i2c bus 27
[  +0.000600] i2c i2c-1: Added multiplexed i2c bus 28
[  +0.015745] i2c i2c-1: Added multiplexed i2c bus 29
[  +0.001625] pca954x 1-0071: registered 8 multiplexed busses for I2C switch pca9548
[  +0.008709] i2c i2c-1: Added multiplexed i2c bus 30
[  +0.000600] i2c i2c-1: Added multiplexed i2c bus 31
[  +0.003139] i2c i2c-1: Added multiplexed i2c bus 32
[  +0.001102] i2c i2c-1: Added multiplexed i2c bus 33
[  +0.000538] i2c i2c-1: Added multiplexed i2c bus 34
[  +0.002339] i2c i2c-1: Added multiplexed i2c bus 35
[  +0.002321] i2c i2c-1: Added multiplexed i2c bus 36
[  +0.000631] i2c i2c-1: Added multiplexed i2c bus 37
[  +0.000031] pca954x 1-0070: registered 8 multiplexed busses for I2C switch pca9548
```

I am trying to read 9 sensirion SHT-85 sensors, which all have the same address (`0x44`)

I am using this python script to read them:

```python
from sensirion_i2c_driver import I2cConnection
from sensirion_i2c_driver.linux_i2c_transceiver import LinuxI2cTransceiver
from sensirion_i2c_sht.sht3x import Sht3xI2cDevice

sensors = {
    i: Sht3xI2cDevice(I2cConnection(LinuxI2cTransceiver(f'/dev/i2c-{i}')))
    for i in range(22, 38)
}

for nr, sensor in sensors.items():
    print(f' /dev/i2c-{nr} '.center(79, '='))
    try:
        print(f'serial nr: {sensor.read_serial_number()}')
        temp, hum = sensor.single_shot_measurement()
        print(f'{temp.degrees_celsius},{hum.percent_rh}')
    except Exception as e:
        print(e)
```

The **very first time after reboot** I run the script, everything is fine output like that:
8 sensors are connected to one multiplexer, 1 sensor to the other

```
================================ /dev/i2c-22 =================================
serial nr: 362321833
25.09346150911726,46.21805142290379
================================= /dev/i2c-23 =================================
I2C transceive failed: [Errno 121] Remote I/O error
================================= /dev/i2c-24 =================================
I2C transceive failed: [Errno 121] Remote I/O error
================================= /dev/i2c-25 =================================
I2C transceive failed: [Errno 121] Remote I/O error
================================= /dev/i2c-26 =================================
I2C transceive failed: [Errno 121] Remote I/O error
================================= /dev/i2c-27 =================================
I2C transceive failed: [Errno 121] Remote I/O error
================================= /dev/i2c-28 =================================
I2C transceive failed: [Errno 121] Remote I/O error
================================= /dev/i2c-29 =================================
I2C transceive failed: [Errno 121] Remote I/O error
================================= /dev/i2c-30 =================================
serial nr: 161755322
24.423208972304877,53.089188982986194
================================= /dev/i2c-31 =================================
serial nr: 161746577
24.110780498970016,56.40344853894865
================================= /dev/i2c-32 =================================
serial nr: 161755581
26.17494468604562,47.76989394979782
================================= /dev/i2c-33 =================================
serial nr: 161752320
24.212252994583054,52.77027542534523
================================= /dev/i2c-34 =================================
serial nr: 362320455
24.642175936522463,47.074082551308464
================================= /dev/i2c-35 =================================
serial nr: 362319721
26.47402151522087,43.480582894636456
================================= /dev/i2c-36 =================================
serial nr: 362322667
24.300373846036464,47.66918440527962
================================= /dev/i2c-37 =================================
serial nr: 362320773
24.60746166170749,46.997787441824975
```
However, running this again, results in some collision of addresses

```
================================= /dev/i2c-22 =================================
I2C error: Received wrong checksum 0x06 (expected 0xAA).
================================= /dev/i2c-23 =================================
serial nr: 362320773
24.65018692301824,46.97947661554894
================================= /dev/i2c-24 =================================
serial nr: 362320773
24.620813305867088,47.00083924620432
================================= /dev/i2c-25 =================================
serial nr: 362320773
24.636835278858626,47.00083924620432
================================= /dev/i2c-26 =================================
serial nr: 362320773
24.636835278858626,47.03898680094606
================================= /dev/i2c-27 =================================
serial nr: 362320773
24.636835278858626,46.955062180514226
================================= /dev/i2c-28 =================================
serial nr: 362320773
24.65018692301824,47.00236514839399
================================= /dev/i2c-29 =================================
serial nr: 362320773
24.636835278858626,46.9916838330663
================================= /dev/i2c-30 =================================
serial nr: 161755322
24.40718699931334,53.07545586327917
================================= /dev/i2c-31 =================================
serial nr: 161746577
24.140154116121153,56.385137712672616
================================= /dev/i2c-32 =================================
serial nr: 161755581
26.188296330205233,47.824826428625926
================================= /dev/i2c-33 =================================
serial nr: 161752320
24.238956282902265,52.78400854505226
================================= /dev/i2c-34 =================================
serial nr: 362320455
24.642175936522463,47.08781567101549
================================= /dev/i2c-35 =================================
serial nr: 362319721
26.46066987106127,43.38139925230793
================================= /dev/i2c-36 =================================
serial nr: 362322667
24.287022201876866,47.67986572060731
================================= /dev/i2c-37 =================================
serial nr: 362320773
24.636835278858626,46.9916838330663
```

note the first one receives an invalid checksum, maybe because it's reading from two sensors at the same time? Also not that serial nr `362320773` now appears for every device?

Does anyone have an idea why this is happening?

**Comment by 6by9** [comment]
By default pca9548 is treated as a switch with no off/idle position. Once you've addressed an output of the mux, then it will be left connected to that output until told to connect to a different one.
Your first loop will have therefore left both pca9548s left connected to output 8 as the last one accessed. The second loop comes along and will select output 1 on mux 1, but output 8 is still connected on mux 2. You are therefore talking to 2 devices simultaneously, one on each mux.

There is a device tree property ```i2c-mux-idle-disconnect``` (https://github.com/torvalds/linux/blob/master/Documentation/devicetree/bindings/i2c/i2c-mux-pca954x.yaml#L52) that will set the pca9548 back to not having any outputs selected when idle. This does incur an overhead, but allows your configuration to work.
There's also a more generic idle-state property, as defined in https://github.com/torvalds/linux/blob/master/Documentation/devicetree/bindings/mux/mux-controller.yaml#L85

As a temporary test it appears this is also exposed as ```/sys/devices/platform/soc/fe804000.i2c/i2c-1/1-0071/idle_state``` (this is based on address 0x71 on bus i2c-1 - you'll need to amend the path for your system).
By default it'll be set to -1 (defined as ```MUX_IDLE_AS_IS```), but setting to -2 (```MUX_IDLE_DISCONNECT```) should make it disconnect after every transaction.

**Pull request merged**
