### PR TITLE
w1: slaves: w1_therm: Add temp attribute which outputs current temperature

### PR DESCRIPTION
**Pull request by gorskima**
DS18B20 and it's brothers are pretty popular in the RaspberryPi world when it comes to the temperature measurement. Each tutorial that I've found on the Internet uses the same way of parsing the output of the _<sensor>/w1_slave_ sysfs file. This patch adds a dedicate file/attribute called _temp_, which only returns current temperature. Thus, the parsing is not required anymore.

### CODE REVIEW

**Comment by popcornmix** [comment]
Patches to upstream kernel code should really be submitted upstream where they can be reviewed by people who know the code. Can you do that?
I'll be happy to cherry pick the changes when they are accepted.

**Comment by gorskima** [comment]
@popcornmix : With upstream, do you mean the LKML?

**Comment by popcornmix** [comment]
See: https://www.kernel.org/doc/Documentation/SubmittingPatches

**Comment by popcornmix** [comment]
Closing. Open a new issue when the code is merged upstream.

**Pull request closed without merging**
