### PR TITLE
BCM2708: Add core Device Tree support

### PR DESCRIPTION
**Pull request by notro**
Minimal Device Tree support

### CODE REVIEW

**Comment by notro** [comment]
**Memory usage**

256/256 split

Regular

``` text
# right after boot and login
$ sleep 60; free
             total       used       free     shared    buffers     cached
Mem:        252768      50068     202700          0       7832      22080
-/+ buffers/cache:      20156     232612
Swap:       102396          0     102396
```

CONFIG_BCM2708_DT

``` text
# right after boot and login
$ sleep 60; free
             total       used       free     shared    buffers     cached
Mem:        252696      50684     202012          0       8260      22124
-/+ buffers/cache:      20300     232396
Swap:       102396          0     102396
```

Both builds have DYNAMIC_DEBUG enabled

**Comment by notro** [comment]
With PROC_DEVICETREE enabled:

``` text
$ ls -l /proc/device-tree/
-r--r--r-- 1 root root  4 Jul  9 16:01 #address-cells
drwxr-xr-x 2 root root  0 Jul  9 16:01 aliases
drwxr-xr-x 3 root root  0 Jul  9 16:01 axi
drwxr-xr-x 2 root root  0 Jul  9 16:01 chosen
drwxr-xr-x 2 root root  0 Jul  9 16:01 clocks
-r--r--r-- 1 root root 13 Jul  9 16:01 compatible
-r--r--r-- 1 root root  4 Jul  9 16:01 interrupt-parent
drwxr-xr-x 2 root root  0 Jul  9 16:01 memory
-r--r--r-- 1 root root 13 Jul  9 16:01 model
-r--r--r-- 1 root root  1 Jul  9 16:01 name
-r--r--r-- 1 root root  4 Jul  9 16:01 #size-cells

$ ls -l /proc/device-tree/axi
-r--r--r-- 1 root root  4 Jul  9 16:02 #address-cells
-r--r--r-- 1 root root 11 Jul  9 16:02 compatible
drwxr-xr-x 2 root root  0 Jul  9 16:02 interrupt-controller
-r--r--r-- 1 root root  4 Jul  9 16:02 name
-r--r--r-- 1 root root 12 Jul  9 16:02 ranges
-r--r--r-- 1 root root  4 Jul  9 16:02 #size-cells
```

**Comment by popcornmix** [comment]
When you enable BCM2708_DT (and so USE_OF) a large set of additional options appear.
Do you suggest using defaults for those, or should any be set differently?

**Comment by notro** [comment]
I use the defaults

```
make bcmrpi_defconfig
scripts/config --enable BCM2708_DT
scripts/config --enable DYNAMIC_DEBUG
scripts/config --enable PROC_DEVICETREE
yes "" | make oldconfig
```

**Comment by popcornmix** [comment]
Looks good. Worked for me with BCM2708_DT enabled and disabled.

**Pull request merged**
