### PR TITLE
Fixed latency issue caused by disabling preemption for up to 5 seconds

### PR DESCRIPTION
**Pull request by Himmele**
Setting up the timeout to 5000 by the RPi patch in sdhci_send_command (sdhci.c) is not a good idea.
This blocks everything on the Raspberry Pi for up to 200ms in real world scenarios.
I don't know if my supplied patch if perfectly correct, but it works for my low latency streaming app.

### CODE REVIEW

**Comment by grigorig** [comment]
Good catch, this is another instance of busy waiting in the SDHCI stack that sometimes eats up notable amounts of CPU time. :( I don't know too much about Linux kernel task scheduling, but doesn't it more sense to use msleep() instead of schedule() and mdelay()?

**Comment by popcornmix** [comment]
The preempt_enable does seem a hack. I assume it is only needed because we are holding the spinlock:
  spin_lock_irqsave(&host->lock, flags);

I think the real solution is to release the specific spinlock (if that is determnined to be safe) before sleeping.

**Comment by Himmele** [comment]
I also did the spin_unlock_irqrestore(&host->lock, flags) and spin_lock_irqsave(&host->lock, flags) before. It also worked fine. But I don't know the the SDHCI driver good enough to be sure which solution is the best.

**Comment by popcornmix** [comment]
Hopefull grigorig can comment. 
The spinlock is to protect against ISR and core parts of driver accessing data structures and sdhost peripheral registers at the same time.
My guess is that neither solution is safe without some careful thought.

There is some evidence that this part of the code is responsible for the widespread USB packet loss issues (interrupts being disabled for more than 1ms can result in USB packet loss), so a correct fix could be very valuable.

**Comment by Himmele** [comment]
Another question is why is this timeout adjustment to 5000 necessary at all? This is not included in the vanilla kernel but has been added by the Raspberry Pi developers. Can't this be solved different?

**Comment by grigorig** [comment]
While a read or write is in progress, the SD card is polled to check for progress and end of the transaction. According to the comment in the source code, that is buggy with the Arasan controller. So it sets a large timeout and waits for the end of the transfer, in case the status is polled. That's of course a really terrible solution.

**Comment by grigorig** [comment]
I disabled the missing_status quirk for testing, and this indeed seems to help with both USB packet loss and SD performance. I kept iozone running in the background, and typing was unaffected by this, no repeating or lost keys at all.

So far I haven't seen any issues with SD access without the quirk.

**Comment by Himmele** [comment]
I also disabled the whole 
if(host->ops->missing_status && (cmd->opcode == MMC_SEND_STATUS)) {
    timeout = 5000; // Really obscenely large delay to send the status, due to bug in controller
            // which might cause the STATUS command to get stuck when a data operation is in flow
    mask |= SDHCI_DATA_INHIBIT;
}
block once and had no problems at all.
Does anybody know if the Raspberry Pi hardware is really affected by this? Or is it only for certain SD cards?
Ok, I think then I will also use this solution of disabling the missing_status quirk.

**Comment by popcornmix** [comment]
I've asked. 
"sync_after_dma" is believed to be needed, but myself, lb and others have found it works just fine without.
I think "missing_status" could be the same (I'm seeing no issues).
The workarounds were added more than two years ago, when the testing was on FPGA.
It's possibly the real chip did get a newer release of the Arasan core but at the time it wasn't testing with workarounds removed.

I might push out an update with the workarounds disabled by default (as there is clearly a benefit to most), and see if there are any problems. There will be comand line options to revert to previous behaviour.

**Comment by popcornmix** [comment]
Firmware has been pushed with grigorig's pull request, and new command line parameter.
Please test with:
sdhci-bcm2708.missing_status=0 sdhci-bcm2708.sync_after_dma=0
added to command line. I haven't made these a default yet, but I will soon if no one complains.

**Comment by popcornmix** [comment]
Unfortunately missing_status doesn't seem safe for everyone. I got this report:
Aug 2 04:34:19 raspi kernel: [ 78.096112] mmc0: Controller never released inhibit bit(s).
Aug 2 04:34:19 raspi kernel: [ 78.167406] mmcblk0: unknown error -5 sending read/write command, card status 0x900
Aug 2 04:34:19 raspi kernel: [ 78.167481] end_request: I/O error, dev mmcblk0, sector 212720
Aug 2 04:34:19 raspi kernel: [ 78.167512] Buffer I/O error on device mmcblk0p2, logical block 2270
Aug 2 04:34:19 raspi kernel: [ 78.167528] lost page write due to I/O error on mmcblk0p2
Aug 2 04:39:05 raspi kernel: [ 364.178196] mmc0: Controller never released inhibit bit(s).
Aug 2 04:39:05 raspi kernel: [ 364.221899] mmcblk0: unknown error -5 sending read/write command, card status 0x900
Aug 2 04:39:05 raspi kernel: [ 364.221976] end_request: I/O error, dev mmcblk0, sector 4394776
Aug 2 04:39:05 raspi kernel: [ 364.222007] Buffer I/O error on device mmcblk0p2, logical block 525027
Aug 2 04:39:05 raspi kernel: [ 364.222023] lost page write due to I/O error on mmcblk0p2

@grigorig any thoughts about not doing the timeout wait here, but periodically checking before the next op?

**Comment by grigorig** [comment]
I think the best solution would be to use the DATA_DONE interrupt, but that requires a lot of changes to the SDHCI code.

**Comment by Himmele** [comment]
But maybe the DATA_DONE interrupt is the only correct solution for this controller :-).

**Comment by popcornmix** [comment]
This was a comment on the hardware guy who integrated Arasan IP:
Arasan have chosen to implement their IP with several internal clocks, so they have to do some internal synchronisation.
This results in status registers not being immediately updated and therefore they are not reliable to check if an event has occurred.
It is preferable to use only the interrupt registers when polling whether the Arasan SDhost has finished doing something and then check the status registers to gather the details.
Interrupt registers use a proper handshake but status registers don’t.

**Comment by sulge** [comment]
What do you think about removing this code to fix the problem with USB and then move root and swap partitions to the USB pen drive? So only initialy boot will be made from SD. Is this solution will prevent problems with missing_status?

**Comment by popcornmix** [comment]
@sulge 
Yes. If you are not using sdcard, then you won't have latency problems caused by sdcard.
Booting with rootfs and swap on USB will avoid the problem.

**Comment by sulge** [comment]
Great news!

Is it confirmed that with this options losing USB packets go away? 

Thank you for answer :)

**Comment by popcornmix** [comment]
@sulge 
You'll have to test. Some users have found their problems fixed by this.

**Comment by sulge** [comment]
Unfortunately,  I have the following erros when testing USB:
BUG: scheduling while atomic: testUSB.sh/1155/0x00000002
Modules linked in: ipv6 pl2303 ftdi_sio usbserial
Backtrace: 
Function entered at [<c0011e0c>] from [<c0345530>]
 r6:cd860000 r5:ceb75440 r4:00000000
Function entered at [<c0345518>] from [<c001abb0>]
Function entered at [<c001ab5c>] from [<c0345be0>]
 r4:c0427be0
Function entered at [<c0345890>] from [<c03461d8>]
Function entered at [<c034618c>] from [<c03464f8>]
Function entered at [<c03463a8>] from [<c0346088>]
Function entered at [<c0345f54>] from [<c034616c>]
Function entered at [<c0346158>] from [<c0243bf8>]
Function entered at [<c0243b54>] from [<c0243e10>]
 r8:000000a1 r7:00000000 r6:00000000 r5:00000007 r4:cea707c0
Function entered at [<c0243d48>] from [<bf012bf4>]
Function entered at [<bf012b2c>] from [<bf013678>]
Function entered at [<bf0135f8>] from [<bf009624>]
Function entered at [<bf0095d0>] from [<c01efd78>]
 r8:ceadf840 r7:cd9cdc00 r6:ceaaa634 r5:ceaaa604 r4:cd860000
Function entered at [<c01efcb8>] from [<bf009b90>]
 r8:ceadf840 r7:0bc00000 r6:ceadf840 r5:ceaaa600 r4:cd9cdc00
Function entered at [<bf009b54>] from [<c01e91e8>]
 r6:cd9cdc00 r5:ce9d18e0 r4:ce9d18e4
Function entered at [<c01e9004>] from [<c00982d8>]
Function entered at [<c00981a8>] from [<c0092e70>]
Function entered at [<c0092d18>] from [<c00930d8>]
Function entered at [<c0093074>] from [<c00a2fa4>]
 r7:00000000 r6:00000000 r5:cd861ed0 r4:ce958798
Function entered at [<c00a2e18>] from [<c00a3614>]
Function entered at [<c00a3554>] from [<c00a3a10>]
Function entered at [<c00a39d8>] from [<c0092b28>]
 r8:00000003 r7:ceb16000 r6:000001b6 r5:00020241 r4:00000001
Function entered at [<c0092a2c>] from [<c0092bf4>]
Function entered at [<c0092bd0>] from [<c000e380>]

**Comment by popcornmix** [comment]
@sulge 
What kernel are you running with? Is it cutdown kernel, or a very old one?
The default kernel gives a proper backtrace so we might get some useful information.
Can you switch to latest (non-cutdown) kernel and get the backtrace again?

**Comment by sulge** [comment]
@popcornmix
I use kernel compiled from current git (I compile it by myself). I will try use non-cutdown kernel and reproduce the problem (problem happen from time to time and when happens breaks all USB devices including LAN).

**Comment by sulge** [comment]
@popcornmix 

Please also note that the for my own compiled kernel I applied patch https://dl.dropbox.com/u/3669512/temp/0001-added-microframe-schedule-from-the-linux-denx-tree.dc4.patch. So it seems that this patch does not works correctly. 
How can I help you to improve it?

Errors with kernel from https://github.com/raspberrypi/firmware/:

Jan  1 01:14:26 raspberry-pi kernel: [  866.365772] INFO:: periodic_channel_available: Total channels: 8, Periodic: 4, Non-periodic: 4
Jan  1 01:14:26 raspberry-pi kernel: [  866.365788]
Jan  1 01:14:26 raspberry-pi kernel: [  866.385320] INFO:: schedule_periodic: No host channel available for periodic transfer.
Jan  1 01:14:26 raspberry-pi kernel: [  866.385338]
Jan  1 01:14:26 raspberry-pi kernel: [  866.416409] ERROR::dwc_otg_hcd_urb_enqueue:518: DWC OTG HCD URB Enqueue failed adding QTD. Error status -4008
Jan  1 01:14:26 raspberry-pi kernel: [  866.416427]
Jan  1 01:14:26 raspberry-pi kernel: [  866.785237] INFO:: periodic_channel_available: Total channels: 8, Periodic: 4, Non-periodic: 4
Jan  1 01:14:26 raspberry-pi kernel: [  866.785253]
Jan  1 01:14:26 raspberry-pi kernel: [  866.804780] INFO:: schedule_periodic: No host channel available for periodic transfer.
Jan  1 01:14:26 raspberry-pi kernel: [  866.804800]
Jan  1 01:14:26 raspberry-pi kernel: [  866.836987] ERROR::dwc_otg_hcd_urb_enqueue:518: DWC OTG HCD URB Enqueue failed adding QTD. Error status -4008
Jan  1 01:14:26 raspberry-pi kernel: [  866.837005]
Jan  1 01:14:26 raspberry-pi kernel: [  867.225173] INFO:: periodic_channel_available: Total channels: 8, Periodic: 4, Non-periodic: 4
Jan  1 01:14:26 raspberry-pi kernel: [  867.225188]
Jan  1 01:14:26 raspberry-pi kernel: [  867.244667] INFO:: schedule_periodic: No host channel available for periodic transfer.

**Comment by popcornmix** [comment]
@sulge
I don't think your issues are related to this one.
Can you catch the scheduling whilst atomic panic with the latest default (non-cutdown) kernel so we get a valid backtrace and create a new issue.

**Comment by sulge** [comment]
@popcornmix 
I try many times but only get  " periodic_channel_available: Total channels: 8, Periodic: 4, Non-periodic: 4" :( How can I get the default (not-cutdown) kernel with  mentioned patch (to eliminate the suspicion)?

Ok I know :) I should use bcmrpi_defconfig ;)

**Comment by popcornmix** [comment]
@sulge 
Yes. Start with clean linux tree. Apply patch. Use bcmrpi_defconfg. Report backtrace of panic.

**Comment by sulge** [comment]
@popcornmix 
Something like that:
[  139.859072] BUG: scheduling while atomic: testUSB1.sh/800/0x00000002
[  139.870116] Modules linked in: ipv6 spidev ftdi_sio pl2303 usbserial spi_bcm2708 i2c_bcm2708
[  139.888419] [<c00151e8>](unwind_backtrace+0x0/0xf8) from [<c03f9acc>](dump_stack+0x1c/0x20)
[  139.905623] [<c03f9acc>](dump_stack+0x1c/0x20) from [<c00221b8>](__schedule_bug+0x6c/0x78)
[  139.922730] [<c00221b8>](__schedule_bug+0x6c/0x78) from [<c03fa314>](__schedule+0x4ac/0x63c)
[  139.939990] [<c03fa314>](__schedule+0x4ac/0x63c) from [<c03fa550>](schedule+0x50/0x68)
[  139.956664] [<c03fa550>](schedule+0x50/0x68) from [<c03faea4>](schedule_timeout+0x234/0x38c)
[  139.973877] [<c03faea4>](schedule_timeout+0x234/0x38c) from [<c03faaac>](wait_for_common+0x140/0x198)
[  139.991898] [<c03faaac>](wait_for_common+0x140/0x198) from [<c03faba4>](wait_for_completion_timeout+0x18/0x1c)
[  140.010753] [<c03faba4>](wait_for_completion_timeout+0x18/0x1c) from [<c02d9b24>](usb_start_wait_urb+0xa8/0xd0)
[  140.030236] [<c02d9b24>](usb_start_wait_urb+0xa8/0xd0) from [<c02d9d4c>](usb_control_msg+0xd0/0xf4)
[  140.048165] [<c02d9d4c>](usb_control_msg+0xd0/0xf4) from [<bf049f28>](ftdi_open+0x80/0xe8 [ftdi_sio])
[  140.066307] [<bf049f28>](ftdi_open+0x80/0xe8 [ftdi_sio]) from [<bf00d660>](serial_activate+0x58/0x6c [usbserial])
[  140.085492] [<bf00d660>](serial_activate+0x58/0x6c [usbserial]) from [<c027d4b8>](tty_port_open+0xc4/0x120)
[  140.104236] [<c027d4b8>](tty_port_open+0xc4/0x120) from [<bf00dbe4>](serial_open+0x40/0x6c [usbserial])
[  140.122569] [<bf00dbe4>](serial_open+0x40/0x6c [usbserial]) from [<c02761cc>](tty_open+0x1e8/0x540)
[  140.140441] [<c02761cc>](tty_open+0x1e8/0x540) from [<c00fb2dc>](chrdev_open+0x194/0x26c)
[  140.157426] [<c00fb2dc>](chrdev_open+0x194/0x26c) from [<c00f5bd4>](__dentry_open+0x174/0x370)
[  140.174855] [<c00f5bd4>](__dentry_open+0x174/0x370) from [<c00f5eb8>](nameidata_to_filp+0x68/0x70)
[  140.192618] [<c00f5eb8>](nameidata_to_filp+0x68/0x70) from [<c0106448>](do_last+0x190/0x73c)
[  140.209857] [<c0106448>](do_last+0x190/0x73c) from [<c0106ab8>](path_openat+0xc4/0x3cc)
[  140.226631] [<c0106ab8>](path_openat+0xc4/0x3cc) from [<c0106ec0>](do_filp_open+0x3c/0x90)
[  140.243675] [<c0106ec0>](do_filp_open+0x3c/0x90) from [<c00f5964>](do_sys_open+0x100/0x194)
[  140.260844] [<c00f5964>](do_sys_open+0x100/0x194) from [<c00f5a38>](sys_open+0x28/0x2c)
[  140.277684] [<c00f5a38>](sys_open+0x28/0x2c) from [<c000dfe0>](ret_fast_syscall+0x0/0x48)
[  140.329483] BUG: scheduling while atomic: testUSB1.sh/800/0x00000002
[  140.340380] Modules linked in: ipv6 spidev ftdi_sio pl2303 usbserial spi_bcm2708 i2c_bcm2708
[  140.358095] [<c00151e8>](unwind_backtrace+0x0/0xf8) from [<c03f9acc>](dump_stack+0x1c/0x20)
[  140.375210] [<c03f9acc>](dump_stack+0x1c/0x20) from [<c00221b8>](__schedule_bug+0x6c/0x78)
[  140.392267] [<c00221b8>](__schedule_bug+0x6c/0x78) from [<c03fa314>](__schedule+0x4ac/0x63c)
[  140.409470] [<c03fa314>](__schedule+0x4ac/0x63c) from [<c03fa550>](schedule+0x50/0x68)
[  140.426147] [<c03fa550>](schedule+0x50/0x68) from [<c03faea4>](schedule_timeout+0x234/0x38c)
[  140.443397] [<c03faea4>](schedule_timeout+0x234/0x38c) from [<c03faaac>](wait_for_common+0x140/0x198)
[  140.461425] [<c03faaac>](wait_for_common+0x140/0x198) from [<c03faba4>](wait_for_completion_timeout+0x18/0x1c)
[  140.480225] [<c03faba4>](wait_for_completion_timeout+0x18/0x1c) from [<c02d9b24>](usb_start_wait_urb+0xa8/0xd0)
[  140.499139] [<c02d9b24>](usb_start_wait_urb+0xa8/0xd0) from [<c02d9d4c>](usb_control_msg+0xd0/0xf4)
[  140.517029] [<c02d9d4c>](usb_control_msg+0xd0/0xf4) from [<bf0497fc>](ftdi_set_termios+0x370/0x528 [ftdi_sio])
[  140.535909] [<bf0497fc>](ftdi_set_termios+0x370/0x528 [ftdi_sio]) from [<bf049f40>](ftdi_open+0x98/0xe8 [ftdi_sio])
[  140.555678] [<bf049f40>](ftdi_open+0x98/0xe8 [ftdi_sio]) from [<bf00d660>](serial_activate+0x58/0x6c [usbserial])
[  140.574875] [<bf00d660>](serial_activate+0x58/0x6c [usbserial]) from [<c027d4b8>](tty_port_open+0xc4/0x120)
[  140.593835] [<c027d4b8>](tty_port_open+0xc4/0x120) from [<bf00dbe4>](serial_open+0x40/0x6c [usbserial])
[  140.612187] [<bf00dbe4>](serial_open+0x40/0x6c [usbserial]) from [<c02761cc>](tty_open+0x1e8/0x540)
[  140.630088] [<c02761cc>](tty_open+0x1e8/0x540) from [<c00fb2dc>](chrdev_open+0x194/0x26c)
[  140.647063] [<c00fb2dc>](chrdev_open+0x194/0x26c) from [<c00f5bd4>](__dentry_open+0x174/0x370)
[  140.664512] [<c00f5bd4>](__dentry_open+0x174/0x370) from [<c00f5eb8>](nameidata_to_filp+0x68/0x70)
[  140.682335] [<c00f5eb8>](nameidata_to_filp+0x68/0x70) from [<c0106448>](do_last+0x190/0x73c)
[  140.699602] [<c0106448>](do_last+0x190/0x73c) from [<c0106ab8>](path_openat+0xc4/0x3cc)
[  140.716422] [<c0106ab8>](path_openat+0xc4/0x3cc) from [<c0106ec0>](do_filp_open+0x3c/0x90)
[  140.733557] [<c0106ec0>](do_filp_open+0x3c/0x90) from [<c00f5964>](do_sys_open+0x100/0x194)
[  140.750775] [<c00f5964>](do_sys_open+0x100/0x194) from [<c00f5a38>](sys_open+0x28/0x2c)
[  140.767666] [<c00f5a38>](sys_open+0x28/0x2c) from [<c000dfe0>](ret_fast_syscall+0x0/0x48)
[  140.846628] BUG: scheduling while atomic: testUSB1.sh/800/0x00000002
[  140.857229] Modules linked in: ipv6 spidev ftdi_sio pl2303 usbserial spi_bcm2708 i2c_bcm2708
[  140.874157] [<c00151e8>](unwind_backtrace+0x0/0xf8) from [<c03f9acc>](dump_stack+0x1c/0x20)
[  140.890945] [<c03f9acc>](dump_stack+0x1c/0x20) from [<c00221b8>](__schedule_bug+0x6c/0x78)
[  140.907636] [<c00221b8>](__schedule_bug+0x6c/0x78) from [<c03fa314>](__schedule+0x4ac/0x63c)
[  140.924480] [<c03fa314>](__schedule+0x4ac/0x63c) from [<c03fa550>](schedule+0x50/0x68)
[  140.940798] [<c03fa550>](schedule+0x50/0x68) from [<c000e058>](ret_slow_syscall+0x0/0x10)
[  140.973150] note: testUSB1.sh[800] exited with preempt_count 1
[  140.985802] BUG: scheduling while atomic: testUSB1.sh/800/0x40000002
[  140.996890] Modules linked in: ipv6 spidev ftdi_sio pl2303 usbserial spi_bcm2708 i2c_bcm2708
[  141.016007] [<c00151e8>](unwind_backtrace+0x0/0xf8) from [<c03f9acc>](dump_stack+0x1c/0x20)
[  141.035130] [<c03f9acc>](dump_stack+0x1c/0x20) from [<c00221b8>](__schedule_bug+0x6c/0x78)
[  141.052360] [<c00221b8>](__schedule_bug+0x6c/0x78) from [<c03fa314>](__schedule+0x4ac/0x63c)
[  141.069713] [<c03fa314>](__schedule+0x4ac/0x63c) from [<c0022764>](__cond_resched+0x1c/0x28)
[  141.087153] [<c0022764>](__cond_resched+0x1c/0x28) from [<c03fa6a0>](_cond_resched+0x3c/0x44)
[  141.104876] [<c03fa6a0>](_cond_resched+0x3c/0x44) from [<c00e1070>](unmap_vmas+0x2d0/0x5e0)
[  141.122206] [<c00e1070>](unmap_vmas+0x2d0/0x5e0) from [<c00e3b2c>](exit_mmap+0x114/0x288)
[  141.139446] [<c00e3b2c>](exit_mmap+0x114/0x288) from [<c002ab18>](mmput+0x40/0x110)
[  141.156064] [<c002ab18>](mmput+0x40/0x110) from [<c002f634>](exit_mm+0x150/0x1ac)
[  141.172612] [<c002f634>](exit_mm+0x150/0x1ac) from [<c0031698>](do_exit+0x618/0x818)
[  141.190648] [<c0031698>](do_exit+0x618/0x818) from [<c00318e0>](do_group_exit+0x48/0xe0)
[  141.207730] [<c00318e0>](do_group_exit+0x48/0xe0) from [<c00441b0>](get_signal_to_deliver+0x3e0/0x644)
[  141.226224] [<c00441b0>](get_signal_to_deliver+0x3e0/0x644) from [<c0011004>](do_notify_resume+0xe4/0x5ac)
[  141.245054] [<c0011004>](do_notify_resume+0xe4/0x5ac) from [<c000e050>](work_pending+0x24/0x28)
[  141.292721] BUG: scheduling while atomic: testUSB1.sh/800/0x00000002
[  141.303887] Modules linked in: ipv6 spidev ftdi_sio pl2303 usbserial spi_bcm2708 i2c_bcm2708
[  141.322705] [<c00151e8>](unwind_backtrace+0x0/0xf8) from [<c03f9acc>](dump_stack+0x1c/0x20)
[  141.340125] [<c03f9acc>](dump_stack+0x1c/0x20) from [<c00221b8>](__schedule_bug+0x6c/0x78)
[  141.357588] [<c00221b8>](__schedule_bug+0x6c/0x78) from [<c03fa314>](__schedule+0x4ac/0x63c)
[  141.375268] [<c03fa314>](__schedule+0x4ac/0x63c) from [<c03fa550>](schedule+0x50/0x68)
[  141.392236] [<c03fa550>](schedule+0x50/0x68) from [<c03faea4>](schedule_timeout+0x234/0x38c)
[  141.409918] [<c03faea4>](schedule_timeout+0x234/0x38c) from [<c03faaac>](wait_for_common+0x140/0x198)
[  141.428278] [<c03faaac>](wait_for_common+0x140/0x198) from [<c03faba4>](wait_for_completion_timeout+0x18/0x1c)
[  141.447457] [<c03faba4>](wait_for_completion_timeout+0x18/0x1c) from [<c02d9b24>](usb_start_wait_urb+0xa8/0xd0)
[  141.466674] [<c02d9b24>](usb_start_wait_urb+0xa8/0xd0) from [<c02d9d4c>](usb_control_msg+0xd0/0xf4)
[  141.484869] [<c02d9d4c>](usb_control_msg+0xd0/0xf4) from [<bf04856c>](update_mctrl+0xdc/0x224 [ftdi_sio])
[  141.503589] [<bf04856c>](update_mctrl+0xdc/0x224 [ftdi_sio]) from [<bf048e70>](ftdi_dtr_rts+0xc4/0xe4 [ftdi_sio])
[  141.523215] [<bf048e70>](ftdi_dtr_rts+0xc4/0xe4 [ftdi_sio]) from [<bf00d0a8>](serial_dtr_rts+0x30/0x34 [usbserial])
[  141.542955] [<bf00d0a8>](serial_dtr_rts+0x30/0x34 [usbserial]) from [<c027cb14>](tty_port_lower_dtr_rts+0x28/0x2c)
[  141.562491] [<c027cb14>](tty_port_lower_dtr_rts+0x28/0x2c) from [<c027ce80>](tty_port_close_start+0x1b4/0x280)
[  141.581777] [<c027ce80>](tty_port_close_start+0x1b4/0x280) from [<c027d530>](tty_port_close+0x1c/0x60)
[  141.600372] [<c027d530>](tty_port_close+0x1c/0x60) from [<bf00db78>](serial_close+0x40/0x6c [usbserial])
[  141.619406] [<bf00db78>](serial_close+0x40/0x6c [usbserial]) from [<c02758fc>](tty_release+0x15c/0x4f4)
[  141.638073] [<c02758fc>](tty_release+0x15c/0x4f4) from [<c00f8dac>](fput+0xc4/0x208)
[  141.654892] [<c00f8dac>](fput+0xc4/0x208) from [<c00f54e8>](filp_close+0x74/0x98)
[  141.671591] [<c00f54e8>](filp_close+0x74/0x98) from [<c002f8b4>](put_files_struct+0x110/0x13c)
[  141.689515] [<c002f8b4>](put_files_struct+0x110/0x13c) from [<c002f934>](exit_files+0x54/0x68)
[  141.707269] [<c002f934>](exit_files+0x54/0x68) from [<c0031224>](do_exit+0x1a4/0x818)
[  141.724145] [<c0031224>](do_exit+0x1a4/0x818) from [<c00318e0>](do_group_exit+0x48/0xe0)
[  141.741334] [<c00318e0>](do_group_exit+0x48/0xe0) from [<c00441b0>](get_signal_to_deliver+0x3e0/0x644)
[  141.759898] [<c00441b0>](get_signal_to_deliver+0x3e0/0x644) from [<c0011004>](do_notify_resume+0xe4/0x5ac)
[  141.778706] [<c0011004>](do_notify_resume+0xe4/0x5ac) from [<c000e050>](work_pending+0x24/0x28)

**Comment by sulge** [comment]
How correct add this report to this thread? Because when I edit all info is visible but after saving only [ 141.741334] from.

**Comment by popcornmix** [comment]
Use pastebin and just post a link here?

**Comment by sulge** [comment]
@popcornmix
http://mm.pl/~kozek/backtrace

**Comment by sulge** [comment]
@popcornmix
Looks like 
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/460857

**Comment by rewolff** [comment]
Wasn't the long timeout added because some SD cards require it? So messing with the SD-card timeout will cause failures only for a very small portion of the population that has a "weird" SD card that uses a very long time for some operations.

**Comment by ddv2005** [comment]
I guess that right solution is mask all SD IRQs and restore IRQs via spin_unlock_irqrestore before busy loop. I will try to do that tomorrow.

**Comment by ddv2005** [comment]
Hi,

I did patch that enable hard IRQs while SDHCI driver is working and also it enable kernel preemption in busy loops.
https://gist.github.com/3454406
I did some tests and on my system it work fine for several hours. Could you test it on your systems?

**Comment by sulge** [comment]
Hello,

Whether it makes sense to test this patch only if only my boot partition is located on the SD card?

**Comment by ddv2005** [comment]
Yes. If your root partition not on the SD card then it doesn't make sense.

**Comment by popcornmix** [comment]
Thanks @ddv2005.
I've applied the patch, and nothing's immediately broken.
Any chance you could add a module paramater to enable/disable the new behaviour. That would make it easier to push out for wider testing.

**Comment by ddv2005** [comment]
I'll add a parameter on Monday

**Comment by ddv2005** [comment]
I have updated my patch. To enable low-latency mode just set sdhci-bcm2708.enable_llm=1 in cmdline.txt

**Comment by popcornmix** [comment]
Thanks. I'd not seen any problem with the earlier one, so I'll try pushing this out and suggesting people test it.

**Comment by popcornmix** [comment]
sdhci-bcm2708.enable_llm=1 is now in latest rpi-update firmware, Please test.

**Comment by popcornmix** [comment]
sdhci-bcm2708.enable_llm is now enabled by default.
Use sdhci-bcm2708.enable_llm=0 if you don't want the low latency mode.

**Comment by popcornmix** [comment]
Closing the pull request as an alternative solution is now checked in.
Thanks to @Himmele for highlighting the problem and @ddv2005 for improving it.

**Pull request closed without merging**
