### PR TITLE
Update Synopsys USB OTG driver to v2.94a

### PR DESCRIPTION
**Pull request by ddv2005**
This is update for Synopsys USB OTG driver to version 2.94a. It is very clean and looks much better than the current version.

### CODE REVIEW

**Comment by popcornmix** [comment]
Have you tested this much?
Does this have all patches that have been applied to 2.90 over the last few months?

We did originally get v2.94a working just before the first github kernel release, but at that time we could make it lock up much more easily than the 2.90 driver. (I believe running netcat would make it hang).
Now, there have been numerous fixes to the kernel (both in dwc_otg and outside), the firmware and the distribution (e.g. vm.min_free_kbytes) which may have cured this hang. 

I have been thinking about revisiting this, so the patch is welcome, but it will need some testing.

**Comment by popcornmix** [comment]
Does it build when applied to a clean tree for you? I get:
drivers/usb/host/dwc_otg/dwc_otg_driver.c:51:28: fatal error: dwc_otg_os_dep.h: No such file or directory compilation terminated.

**Comment by ddv2005** [comment]
I did not tested it much but I guess that 2.94 have to be base for all
feature changes. Because current driver is missing many basic locks
and it need so much refactoring to be safe.

I found only 2 patches. I have applied patch to change count of host channels
from 12 to 8. But my patch for USB audio is not necessary
because 2.94 work fine without it.

Could you provide command line to check netcat hang?

I just forgot to add new files. Now new files on place

**Comment by popcornmix** [comment]
I think these fixes are still needed:
Fixed issue with some keyboards giving too much data : f679f0534867d64a3672108d73bed5d349728f73
Fix for DWC OTG HCD URB Dequeue has NULL URB panic: d25ac7af2f62489d600b4ab30513bc283d770769
Fix (hopefully) for DWC_MEMCPY kernel panics: 30b708f9c69a161051e9ddcab7772a35ca8b7b23

**Comment by asb** [comment]
The netcat lockup when we last looked at 2.94 was reproducible like so:

```
$ cat ncrecv
#!/bin/sh
nc -l -p 1234 -v > /dev/null

$ cat ncsend
#!/bin/sh
nc $1 1234 < /dev/zero
```

On the pi: `./ncrev` and on the computer connected to the pi: `./ncsend $RASPI_IP`. This would produce a lockup within 10 minutes or so (likely much less). Neither the smsc95xx.turbo_mode=N or vm.min_free_kbytes would have an effect. I agree that if we can verify this issue either no longer occurs or can fix it, 2.94 is probably a better base for future development.

**Comment by popcornmix** [comment]
The netcat test does fail with this pull request appied.
The sending end just returns. The Pi just hangs. No panic shown, but ctrl-c / ctrl-z don't stop it.

Using sysreq to interrupt it works, and I can see in dmesg log

```
<4>[  417.122159] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
<4>[  417.122209] smsc95xx 1-1.1:1.0: eth0: MII is busy in smsc95xx_mdio_read
<4>[  422.121795] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
<4>[  422.121829] smsc95xx 1-1.1:1.0: eth0: MII is busy in smsc95xx_mdio_read
<4>[  428.221322] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
<5>[  432.410997] nfs: server 10.177.65.68 not responding, still trying
<4>[  433.220955] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000114
<4>[  438.220594] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
<4>[  443.220229] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000118
<4>[  448.219875] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
<4>[  453.219507] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000114
<4>[  458.219135] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
<4>[  463.218777] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000118
<5>[  468.768378] nfs: server 10.177.65.68 not responding, still trying
<4>[  497.176209] ------------[ cut here ]------------
<4>[  497.176271] WARNING: at net/sched/sch_generic.c:255 dev_watchdog+0x2e8/0x308()
<6>[  497.176290] NETDEV WATCHDOG: eth0 (smsc95xx): transmit queue 0 timed out
<4>[  497.176316] Modules linked in: snd_bcm2835 snd_pcm snd_seq snd_timer snd_seq_device snd snd_page_alloc evdev
more>
<4>[  497.176418] [<c0015004>] (unwind_backtrace+0x0/0xfc) from [<c03fb1f0>] (dump_stack+0x20/0x24)
<4>[  497.176474] [<c03fb1f0>] (dump_stack+0x20/0x24) from [<c002e77c>] (warn_slowpath_common+0x5c/0x74)
<4>[  497.176513] [<c002e77c>] (warn_slowpath_common+0x5c/0x74) from [<c002e850>] (warn_slowpath_fmt+0x40/0x48)
<4>[  497.176549] [<c002e850>] (warn_slowpath_fmt+0x40/0x48) from [<c0363d20>] (dev_watchdog+0x2e8/0x308)
<4>[  497.176606] [<c0363d20>] (dev_watchdog+0x2e8/0x308) from [<c003e7e0>] (run_timer_softirq+0x158/0x41c)
<4>[  497.176654] [<c003e7e0>] (run_timer_softirq+0x158/0x41c) from [<c00358d4>] (__do_softirq+0xbc/0x23c)
<4>[  497.176703] [<c00358d4>] (__do_softirq+0xbc/0x23c) from [<c0035f30>] (irq_exit+0xa8/0xb4)
<4>[  497.176750] [<c0035f30>] (irq_exit+0xa8/0xb4) from [<c000ef50>] (handle_IRQ+0x44/0x94)
<4>[  497.176785] [<c000ef50>] (handle_IRQ+0x44/0x94) from [<c00084a0>] (asm_do_IRQ+0x18/0x1c)
<4>[  497.176843] [<c00084a0>] (asm_do_IRQ+0x18/0x1c) from [<c04016b8>] (__irq_svc+0x38/0xd0)
<4>[  497.176865] Exception stack(0xc05d3f38 to 0xc05d3f80)
<4>[  497.176885] 3f20:                                                       c05d4e94 00000000
<4>[  497.176912] 3f40: c05d3f80 00000000 c05d2000 c0603684 c05d902c c08529a0 00004008 410fb767
<4>[  497.176951] 3f60: 005ba91c c05d3f8c c05d3f80 c05d3f80 c000f0cc c000f0d0 60000013 ffffffff
<4>[  497.176994] [<c04016b8>] (__irq_svc+0x38/0xd0) from [<c000f0d0>] (default_idle+0x38/0x3c)
<4>[  497.177029] [<c000f0d0>] (default_idle+0x38/0x3c) from [<c000f30c>] (cpu_idle+0xb8/0xe4)
<4>[  497.177076] [<c000f30c>] (cpu_idle+0xb8/0xe4) from [<c03fa094>] (rest_init+0xa0/0xb8)
<4>[  497.177115] [<c03fa094>] (rest_init+0xa0/0xb8) from [<c05a07a4>] (start_kernel+0x294/0x2e0)
<4>[  497.177138] ---[ end trace 128ecba635631019 ]---
<5>[  509.495403] nfs: server 10.177.65.68 not responding, still trying
<5>[  517.204853] nfs: server 10.177.65.68 not responding, still trying
<5>[  593.099366] nfs: server 10.177.65.68 not responding, still trying
more>
<5>[ 1768.913811] nfs: server 10.177.65.68 not responding, still trying
<5>[ 1796.411805] nfs: server 10.177.65.68 not responding, still trying
```

**Comment by popcornmix** [comment]
What effect does the additional commit have? Can you see the netcat hang, and does this commit help?

**Comment by ddv2005** [comment]
Unfortunately It still hangs but I still trying to find the problem.

**Comment by ddv2005** [comment]
Hi,

I found that it hangs because driver stopped to receive host channel interrupts, but I can't find why it is happened. I have detailed log file and it is look fine https://gist.github.com/3315356.

 1296.983854] [ 1281.254588] <7>[ 1281.254589] DWC_otg: DWC OTG HCD Interrupt Detected gintsts&gintmsk=0x02000000 core_if=ce8f0000
[ 1297.002106] [ 1281.254599] <7>[ 1281.254600] DWC_otg: --Host Channel Interrupt--, Channel 3
[ 1297.017205] [ 1281.254605] <7>[ 1281.254606] DWC_otg: hcint 0x00000023, hcintmsk 0x00000006, hcint&hcintmsk 0x00000002
[ 1297.035009] [ 1281.254610] <7>[ 1281.254611] DWC_otg: --Host Channel 3 Interrupt: Channel Halted--
[ 1297.051095] [ 1281.254615] <7>[ 1281.254616] DWC_otg: --Host Channel 3 Interrupt: Transfer Complete--
[ 1297.067541] [ 1281.254619] <7>[ 1281.254620] DWC_otg: Bulk transfer complete
[ 1297.078514] [ 1281.254831] <7>[ 1281.254832] DWC_otg: DWC_otg: update_urb_state_xfer_comp: IN, channel 3
[ 1297.095195] [ 1281.254839] <7>[ 1281.254840] DWC_otg: hc->xfer_len 18944
[ 1297.105744] [ 1281.254842] <7>[ 1281.254843] DWC_otg: hctsiz.xfersize 610
[ 1297.116246] [ 1281.254845] <7>[ 1281.254846] DWC_otg: urb->transfer_buffer_length 18944
[ 1297.131254] [ 1281.254848] <7>[ 1281.254849] DWC_otg: urb->actual_length 18334
[ 1297.145469] [ 1281.254851] <7>[ 1281.254852] DWC_otg: short_read 1, xfer_done 1
[ 1297.159784] [ 1281.254856] _complete: urb ce9893a0, device 3, ep 1 IN, status=0
[ 1297.170540] [ 1281.254901] dwc_otg_urb_enqueue, urb ce9893a0
[ 1297.179608] [ 1281.254907] Device address: 3
[ 1297.187418] [ 1281.254909] Endpoint: 1, IN
[ 1297.195061] [ 1281.254912] Endpoint type: BULK
[ 1297.203036] [ 1281.254914] Speed: HIGH
[ 1297.210210] [ 1281.254916] Max packet size: 512
[ 1297.218068] [ 1281.254918] Data buffer length: 18944
[ 1297.226306] [ 1281.254920] Transfer buffer: cda50002, Transfer DMA: 4da50002
[ 1297.236614] [ 1281.254924] Setup buffer: (null), Setup DMA: (null)
[ 1297.246395] [ 1281.254927] Interval: 0
[ 1297.253285] [ 1281.254943] <7>[ 1281.254945] DWC_otg: release_channel: channel 3, halt_status 2, xfer_len 18944
[ 1297.269389] [ 1281.254953] <7>[ 1281.254953] DWC_otg: deactivate_qh(ce988000,ce9cfee0,1)
[ 1297.283430] [ 1281.254966] <7>[ 1281.254967] DWC_otg: assign_and_init_hc(ce988000,ce9cfee0) - urb ce9cf2a0, actual_length 0
[ 1297.300574] [ 1281.254980] <7>[ 1281.254981] DWC_otg: dwc_otg_hc_init: Channel 2, Dev Addr 3, EP #1
[ 1297.315687] [ 1281.254987] <7>[ 1281.254988] DWC_otg: Is In 1, Is Low Speed 0, EP Type 2, Max Pkt 512, Multi Cnt 0
[ 1297.332591] [ 1281.254995] <7>[ 1281.254996] DWC_otg: Queue non-periodic transactions
[ 1297.346746] [ 1281.254998] <7>[ 1281.254999] DWC_otg: NP Tx Req Queue Space Avail (before queue): 8
[ 1297.362334] [ 1281.255002] <7>[ 1281.255002] DWC_otg: NP Tx FIFO Space Avail (before queue): 256
[ 1297.377672] [ 1281.255010] <7>[ 1281.255010] DWC_otg: dwc_otg_hc_start_transfer: Channel 2
[ 1297.392571] [ 1281.255014] <7>[ 1281.255015] DWC_otg: Xfer Size: 18944
[ 1297.402820] [ 1281.255018] <7>[ 1281.255019] DWC_otg: Num Pkts: 37
[ 1297.412695] [ 1281.255020] <7>[ 1281.255021] DWC_otg: Start PID: 0
[ 1297.422578] [ 1281.255026] <7>[ 1281.255026] DWC_otg: transfer 2 from core_if ce8f0000
[ 1297.437410] [ 1281.255038] <7>[ 1281.255039] DWC_otg: DWC OTG HCD Finished Servicing Interrupts
[ 1297.453216] [ 1281.255041] <7>[ 1281.255042] DWC_otg: DWC OTG HCD gintsts=0x04600009
[ 1297.468173] [ 1281.255045] <7>[ 1281.255046] DWC_otg: DWC OTG HCD gintmsk=0xf300080e 

At this point we are setup DMA transfer for HC 2. HC interrupts is enabled. Every 1ms it got SOF interrupt but we never got any other HC interrupts for ANY channel. After 10 seconds it got xfer timeout.

[ 1298.598884] [ 1291.271150] <4>[ 1291.271152] WARN::hc_xfer_timeout:2602: hc_xfer_timeout: timeout on channel 2
[ 1298.601855]
[ 1298.617037] [ 1291.271164] <4>[ 1291.271165] WARN::hc_xfer_timeout:2604: start_hcchar_val 0x00d88a00
[ 1298.620010]
[ 1298.634774] DWC_otg: DWC OTG HCD Interrupts
[ 1298.641409] DWC_otg: DWC OTG HCD gintsts=0x04600031
[ 1298.648642] DWC_otg: DWC OTG HCD gintmsk=0xf300080e
[ 1298.655967] WARN::hc_xfer_timeout:2615: Real start_hcchar_val 0x80d88a00 

You can see that interrupts still enabled and not HC interrupts queued (0x2000000 is not set). And HC transfer still enabled (0x80000000 in hcchar).
I don't understand why it stopped. Maybe you have some advice about it.

Best Regards,
Dmitry

**Comment by popcornmix** [comment]
Gray who tried to get 2.94 working some time ago responded:
"I suppose the system is still operational is it?  If not, could we have 
system interrupts disabled still?  Perhaps a lock that was never 
cleared?

(As far as I remember, my investigations suggested that we never 
completed the processing of a transmit(?) queue eventually (minutes) 
leading to a watchdog firing.  Queues are updated under a lock ...

For me the eventual consequence was that the watchdog caused the USB 
driver to tidy up ... which meant that it needed to traverse the queue 
in question ... which meant that it took out the queue's lock 
recursively.  Which wasn't good either.)"

**Comment by ddv2005** [comment]
I checked all locks and everything fine. I compiled kernel with lock detection flags and it can't find any deadlocked locks. You can see that interrupt handler successfully exit  " [ 1281.255038] [ 1281.255039] DWC_otg: DWC OTG HCD Finished Servicing Interrupts" but never enter again except the SOF. Interrupts still enabled and every 1ms it got SOF interrupt in same IRQ handler. In case of deadlock IRQ handler can't finish. It is meant that in this case is no deadlock. 

I have dump of HC registers at time of problem and it is look fine (channels enabled and no pending IRQ):

[ 1577.141978] DWC_otg: DWC OTG HCD gintsts=0x04600031  
[ 1577.149039] DWC_otg: DWC OTG HCD gintmsk=0xf300080e  
[ 1577.156119] WARN::hc_xfer_timeout:2615: Real hcchar_val 0x80d81200  
[ 1577.156131]  
[ 1577.168087] Host Global Registers  
[ 1577.173650] HCFG              @0xCF840400 : 0x00000000  
[ 1577.180021] HFIR              @0xCF840404 : 0x00001D4C  
[ 1577.186426] HFNUM     @0xCF840408 : 0x055838DC  
[ 1577.192731] HPTXSTS   @0xCF840410 : 0xB9080200  
[ 1577.199307] HAINT     @0xCF840414 : 0x00000000  
[ 1577.205721] HAINTMSK  @0xCF840418 : 0x000000FF  
[ 1577.212308] HPRT0     @0xCF840440 : 0x00001005  
[ 1577.218718] Host Channel 0 Specific Registers  
[ 1577.225295] HCCHAR    @0xCF840500 : 0xC09C8801  
[ 1577.231733] HCSPLT    @0xCF840504 : 0x00000000  
[ 1577.238183] HCINT     @0xCF840508 : 0x00000000  
[ 1577.244542] HCINTMSK  @0xCF84050C : 0x00000006  
[ 1577.251144] HCTSIZ    @0xCF840510 : 0x00080001  
[ 1577.257621] HCDMA     @0xCF840514 : 0x4EA69C80  
[ 1577.263999] Host Channel 1 Specific Registers  
[ 1577.270512] HCCHAR    @0xCF840520 : 0x00D88A00  
[ 1577.276901] HCSPLT    @0xCF840524 : 0x00000000  
[ 1577.283184] HCINT     @0xCF840528 : 0x00000000  
[ 1577.289358] HCINTMSK  @0xCF84052C : 0x00000000  
[ 1577.295734] HCTSIZ    @0xCF840530 : 0xC0080262  
[ 1577.301907] HCDMA     @0xCF840534 : 0x4DDF47A0  
[ 1577.308071] Host Channel 2 Specific Registers  
[ 1577.314428] HCCHAR    @0xCF840540 : 0x80D81200  
[ 1577.320612] HCSPLT    @0xCF840544 : 0x00000000  
[ 1577.326768] HCINT     @0xCF840548 : 0x00000000  
[ 1577.332808] HCINTMSK  @0xCF84054C : 0x00000006  
[ 1577.339132] HCTSIZ    @0xCF840550 : 0x0008004E  
[ 1577.345313] HCDMA     @0xCF840554 : 0x4DE80000  
[ 1577.351407] Host Channel 3 Specific Registers  
[ 1577.357717] HCCHAR    @0xCF840560 : 0xE0DC9810  
[ 1577.363923] HCSPLT    @0xCF840564 : 0x00000000  
[ 1577.370080] HCINT     @0xCF840568 : 0x00000000  
[ 1577.376163] HCINTMSK  @0xCF84056C : 0x00000006  
[ 1577.382482] HCTSIZ    @0xCF840570 : 0x40080010  
[ 1577.388660] HCDMA     @0xCF840574 : 0x4EA57680  
[ 1577.394755] Host Channel 4 Specific Registers  
[ 1577.401013] HCCHAR    @0xCF840580 : 0x00D81200  
[ 1577.407251] HCSPLT    @0xCF840584 : 0x00000000  
[ 1577.413371] HCINT     @0xCF840588 : 0x00000000  
[ 1577.419470] HCINTMSK  @0xCF84058C : 0x00000000  
[ 1577.425828] HCTSIZ    @0xCF840590 : 0x4000004E  
[ 1577.431954] HCDMA     @0xCF840594 : 0x4DE80050  
[ 1577.438061] Host Channel 5 Specific Registers  
[ 1577.444351] HCCHAR    @0xCF8405A0 : 0x00D81200  
[ 1577.450525] HCSPLT    @0xCF8405A4 : 0x00000000  
[ 1577.456701] HCINT     @0xCF8405A8 : 0x00000000  
[ 1577.462707] HCINTMSK  @0xCF8405AC : 0x00000000  
[ 1577.469043] HCTSIZ    @0xCF8405B0 : 0x0000004E  
[ 1577.475200] HCDMA     @0xCF8405B4 : 0x4DE80050  
[ 1577.481246] Host Channel 6 Specific Registers  
[ 1577.487535] HCCHAR    @0xCF8405C0 : 0x20DC9810  
[ 1577.493729] HCSPLT    @0xCF8405C4 : 0x00000000  
[ 1577.499875] HCINT     @0xCF8405C8 : 0x00000000  
[ 1577.505948] HCINTMSK  @0xCF8405CC : 0x00000000  
[ 1577.512220] HCTSIZ    @0xCF8405D0 : 0xC0080010  
[ 1577.518389] HCDMA     @0xCF8405D4 : 0x4EA57680  
[ 1577.524505] Host Channel 7 Specific Registers  
[ 1577.530728] HCCHAR    @0xCF8405E0 : 0x80D88A00  
[ 1577.536940] HCSPLT    @0xCF8405E4 : 0x00000000  
[ 1577.543074] HCINT     @0xCF8405E8 : 0x00000020  
[ 1577.549170] HCINTMSK  @0xCF8405EC : 0x00000006  
[ 1577.555525] HCTSIZ    @0xCF8405F0 : 0x00A02C00  
[ 1577.561622] HCDMA     @0xCF8405F4 : 0x4DDF1E00

**Comment by popcornmix** [comment]
I'm afraid I don't know a great deal about this driver, but is it possible to identify the cause of the netcat lockup by gradually merging from 2.90 to 2.94 and find which change breaks netcat?

This is straightforward when all changes are independent. Obviously not all will be, which makes this much tougher to do, but it may be worth considering.

**Comment by ddv2005** [comment]
I am not sure that it is possible. 2.94 have so many core changes. Next week I will try to compare 2.90 and 2.94 logs.

**Comment by ddv2005** [comment]
I hope that I found the problem and now I am testing the fix. It is look like they just remove Broadcom workaround for DMA burst len.

**Comment by popcornmix** [comment]
Interesting! I'm keen to move to this code if testing is good. Fingers crossed...

**Comment by ddv2005** [comment]
7+ hours of testing and ... it still work :-)

**Comment by popcornmix** [comment]
Do you think you can rebase this against latest code?

It seems to have sdcard commits included, which don't apply (a second time).
Also the SOF patch has been reverted, which affects the DWC_OTG code.

**Comment by ddv2005** [comment]
I did it but now I can't compile the kernel because it is required removed __aeabi_uldivmod . Could you revert this patch https://github.com/raspberrypi/linux/commit/9592f718fc300e4b40a0b0f9b7c3c2c901144df5#arch/arm/boot ?

**Comment by ddv2005** [comment]
https://github.com/raspberrypi/linux/pull/83

**Comment by haolongzhang** [comment]
dear ddv2005 
    What is the final solution about  blow log ，Thanks
[33525.261931@0] WARN::hc_xfer_timeout:2647: hc_xfer_timeout: timeout on channel 9
[33525.263649@0] WARN::hc_xfer_timeout:2649:    start_hcchar_val 0x0258a200
[33525.270171@0] WARN::hc_xfer_timeout:2654:    chn-9,ep4-IN:type:2,speed:2,len:4096,addr9

**Pull request closed without merging**
