### PR TITLE
fix warnings for 5.3

### PR DESCRIPTION
**Pull request by teknoraver**

### CODE REVIEW

**Comment by lategoodbye** [comment]
This pull request touches some upstream files (bcm2835-dma, vchiq).
Would be better to fix them upstream first.

**Comment by teknoraver** [comment]
Hi @lategoodbye 

both patches fixes code which is not yet upstream.
It seems that such code was introduced in 00dfb1e4dcdf4f7160700ebe8b928c3cc952186e
for vchiq and dcee296a50fa9fb29cdfe462f4f1ac53ca578ced for bcm2835-dma by @pelwell

**Comment by lategoodbye** [comment]
Okay, in this case only 66c291b25c8c783b4f5bd692c5bf99791446f8ca is left.

**Comment by teknoraver** [comment]
> Okay, in this case only [66c291b](https://github.com/raspberrypi/linux/commit/66c291b25c8c783b4f5bd692c5bf99791446f8ca) is left.

Right. I've sent that patch upstream, I will rebase the PR without such patch.

thanks

**Comment by pelwell** [comment]
Thanks.

**Pull request merged**
