### PR TITLE
rpi-4.7.y enable clock manager and modify all subsystems to use it

### PR DESCRIPTION
**Pull request by clivem**
Placeholder.... This is what I think we have to merge to move all of the subsystems over to using clock manager in rpi-4.7.y.

@msperl I think this is turning more into a "loose ends" to have clock manager enabled by default, and move all of the subsystems over to using it, rather than an "backport upstream clockmgr/I2S" thing. I'm still testing, but I'm not seeing any issues at the moment.

### CODE REVIEW

**Comment by msperl** [comment]
On comment: imo the "bcm2835-i2s: REVERT the reverted patches" patch is slightly ugly - maybe just revert each of the reverts separately to document what actually happened instead of referencing in the comment.

But it is up to @popcornmix to decide what he prefers to merge...

Besides that I guess we should now be good enough to use the clock-framework for everything.
(Besides some intensive testing - especially SMI, as the corresponding patch is untested!)

This finally allows to use vc4 graphics together with i2s.

If this works fine in 4.7, then it should also be possible to cherry-pick these patches in 4.4, but I guess that may be seen as too risky.

**Comment by msperl** [comment]
here the quick branch that just did the reverts individually:
https://github.com/msperl/linux-rpi/commits/rpi-4.7.y-clock-only
This:

```
7064620 Revert "Revert "ASoC: bcm2835: Add S16_LE support via packed DMA transfers""
d53e90d Revert "Revert "ASoC: bcm2835: setup clock only if CPU is clock master""
02771a5 Revert "Revert "ASoC: bcm2835: add 24bit support""
bc5f27c Revert "Revert "ASoC: bcm2835: move to use the clock framework""
b79165f Revert "bcm2835-i2s: get base address for DMA from devicetree"
0abba71 Revert "bcm2835-i2s: add 24bit support, update bclk_ratio to more correct values"
c434816 Revert "bcm2835-i2s: setup clock only if CPU is clock master"
a23e7bf Revert "bcm2835-i2s: Eliminate debugfs directory error"
3f5e417 Revert "bcm2835-i2s: Register PCM device"
f7eabb0 Revert "bcm2835-i2s: Enable MMAP support via a DT property"
2341c37 Revert "bcm2835-i2s: Reduce the TX DREQ threshold"
```

only replaces this:
`d0b57d0 bcm2835-i2s: REVERT the reverted patches`

Note that:
 `git diff remotes/DigitalDreamtimeLtd/rpi-4.7.y-clockmgr3  remotes/origin/rpi-4.7.y-clock-only` produces no output, so the branches are identical in content.

Note: I have not tested this yet - compile is running...

@popcornmix: the question is: do you want a pull request of this patchset?

**Comment by clivem** [comment]
@msperl Yes, I know. I was lazy with the "revert the reverts" patchset, bundling it into one commit. ;)
I figured as they rebase the non-current branches, ie. when 4.7.2->4.7.3, it would matter as the history would disappear, nothing would be reverted to start with, so wouldn't need to revert the reverts. ;)

@msperl I'm thinking I want to ask @popcornmix to also cherry-pick this 2b8dfa3e9046eb617dbe4a10d863e70cb80a096f commit from rpi-4.4.y to rpi-4.7.y. What do you think? (I think any of the other Anholt clock commits are specific to his VC4 stuff and can wait until he rebases his 4.4 code to 4.7.)

**Comment by popcornmix** [comment]
At some point after merging the reverts and "reverts of reverts"  will be dropped.
Individual reverts of each commit will make this slightly easy to pair up, so is preferable, but I imagine I'll deal with it either way.

**Comment by msperl** [comment]
@popcornmix : Created #1629 with reverted reverts instead of the "bulk revert".

Please choose which one you prefer to merge.

**Comment by msperl** [comment]
@clivem : the patch by Eric with regards to DSI/PLL reconfig probably needs to get in when all those DSI patches go in.

In principle I guess the next step would be for eric to update his VC4 patchset for 4.7, but I guess we should be able to cherry-pick the VC4 4.8 patches immediately:

```
git log --oneline v4.8-rc4 ^rpi-4.7.y-clock-only --no-merges  -- ./drivers/gpu/drm/vc4/
63fe9bb drm/vc4: Delete unnecessary checks before two function calls
a20d5fa drm/vc4: Fix a "the the" typo in a comment.
20e48fd drm/vc4: Fix definition of QPU_R_MS_REV_FLAGS
7363cee drm/vc4: Add a getparam to signal support for branches.
6d45c81 drm/vc4: Add support for branching in shader validation.
93aa9ae drm/vc4: Add a bitmap of branch targets during shader validation.
d0566c2 drm/vc4: Move validation's current/max ip into the validation struct.
af71379 drm/vc4: Add a getparam ioctl for getting the V3D identity regs.
deb4765 drm/vc4: remove redundant ret status check
1bf59f1 drm/vc4: Implement precise vblank timestamping.
7a10096 drm/vc4: Bind the HVS before we bind the individual CRTCs.
027a697 gpu: drm: vc4_hdmi: add missing of_node_put after calling of_parse_phandle
9397776 drm: vc4: enable XBGR8888 and ABGR8888 pixel formats
f510f34 drm/vc4: Remove unused connector
398e979 drm/vc4: Remove open-coded drm_connector_register_all()
b2d61d6 drm: vc4: Rely on the default ->best_encoder() behavior
5e84c26 drm/atomic-helper: Massage swap_state signature somewhat
7ea7728 drm/core: Change declaration for gamma_set.
a9402df drm/vc4: clean up error exit path on failed dpi_connector allocation
2f196b7 drm/atomic: Add drm_atomic_crtc_state_for_each_plane_state
833cd78 drm/vc4: Use for_each_plane_in_state
b82caaf drm/vc4: Use lockless gem BO free callback
db36972 drm/vc4: Use drm_gem_object_unreference_unlocked
```

I am not sure if there would be some need for some other (support) patches to make these really work...

**Comment by msperl** [comment]
a quick check (individual cherry pick + conflict check + compile check) shows that this one does not apply cleanly:
- 7ea7728 drm/core: Change declaration for gamma_set.
  - this has the following prerequisites (to apply without issues):
    - 3abb263 drm/cirrus: Drop redundnant gamma size check
    - 6136bfb drm/atomic-helper: Fixup kerneldoc for drm_atomic_helper_legacy_gamma_set
    - 5d943aa6 drm: Consolidate crtc arrays in drm_atomic_state
    - b8b5342 drm: Consolidate plane arrays in drm_atomic_state
    - 63e83c1 drm: Consolidate connector arrays in drm_atomic_state
    - 2e7a570 drm/doc: Appease sphinx
    - be9174a drm/atomic-helper: use for_each_*_in_state more
    - a0909cc drm/atomic: Handle funcs->best_encoder == NULL case
    - f55f170 drm/atomic-helper: Do not call ->mode_fixup for CRTC which will be disabled
- 5e84c26 drm/atomic-helper: Massage swap_state signature somewhat
  - 76c6dcc Merge branch 'virtio-gpu-for-airlied' of git://git.kraxel.org/linux into drm-next
    this is a merge and (probably) produces lots of conflicts...
  - bbbed88 virtio-gpu: switch to atomic cursor interfaces
  - e7cf096 virtio-gpu: add atomic_commit function
  - a288c1e drm/virtio: use drm_crtc_send_vblank_event()

so for the vc4 stuff eric needs to look into it...

But anyway: this is outside the scope of this pull

**Comment by clivem** [comment]
> so for the vc4 stuff eric needs to look into it...

Yes, I'd rather stay well away from anything to do with vc4. I am not going to be able to do any testing with all of my "headless" configurations....

**Comment by clivem** [comment]
Closing, in favour of https://github.com/raspberrypi/linux/pull/1629

**Pull request closed without merging**
