### PR TITLE
Rpi 4.19.y RFC Enable Raspberry Pi voltage monitor

### PR DESCRIPTION
**Pull request by lategoodbye**
@notro [pull request](https://github.com/raspberrypi/linux/pull/2397) has been upstreamed as the Raspberry Pi voltage monitor within the hwmon subsystem and is available since 4.19.

In order avoid having two driver doing the same thing, this pull requests tries to push the Raspberry Kernel more into upstream direction.

"Old" get_trottled sysfs entry:
`/sys/devices/platform/soc/soc:firmware/get_trottled`

"New" hwmon entry:
`/sys/class/hwmon/hwmon0/in0_lcrit_alarm`

Documentation:
https://github.com/raspberrypi/linux/blob/rpi-4.19.y/Documentation/hwmon/raspberrypi-hwmon

### CODE REVIEW

**Comment by notro** [comment]
@lategoodbye thanks for taking this upstream.

This PR needs rebasing, so in the meanwhile here's the link to the commits:
https://github.com/lategoodbye/linux/commits/rpi-4.19.y-hwmon

**Comment by lategoodbye** [comment]
@notro The reason for this pull request is to discuss if the userspace ABI break (different path and different value) is acceptable for Raspbian. I would rebase after final 4.19 is out.

**Comment by popcornmix** [comment]
Is it feasible to switch to the upstream driver and provide a downstream patch that additionally creates ``/sys/devices/platform/soc/soc:firmware/get_throttled``
We warn users that the old node is deprecated and will be removed in a future update.

**Comment by lategoodbye** [comment]
From my understanding the hwmon driver cannot simply create such a file, because the sysfs entries are always relative.

Edit: Okay, i think of a hacky solution with a global variable or to extract the response for the get_throttled within the firmware driver.

**Comment by notro** [comment]
I see now that there's a difference between downstream and mainline in that downstream returns the whole throttled value, wereas mainline only returns the undervoltage bit.

Another difference is that ->last_throttled is set during probe. AFAIU this means that the undervoltage warning won't be reported if undervoltage happened before hwmon probe. The voltage normalise message will show though.

**Comment by lategoodbye** [comment]
> I see now that there's a difference between downstream and mainline in that downstream returns the whole throttled value, wereas mainline only returns the undervoltage bit.

Per hwmon sysfs `in0_lcrit_alarm` must be boolean. In case we need the other bits, we need to look for a matching candidate(s).

> Another difference is that ->last_throttled is set during probe. AFAIU this means that the undervoltage warning won't be reported if undervoltage happened before hwmon probe. The voltage normalise message will show though.

Nice catch. I could add a warning into the probe function.

**Comment by lategoodbye** [comment]
Okay, i added a patch which "restore" the old get_throttled.

**Comment by popcornmix** [comment]
@lategoodbye thanks for this. The backward compatible node seems to work well (the WARN backtrace will probably generate some worried reports, but should identify any significant users of the old node).

I've picked it to rpi-4.19 (dues to conflict after the bump to v4.19) for further exposure (should be an rpi-update kernel with this in very soon).

**Pull request closed without merging**
