### PR TITLE
ASoC: Add support for AudioSense-Pi add-on soundcard

### PR DESCRIPTION
**Pull request by b-ak**
AudioSense-Pi is a RPi HAT based on a TI's TLV320AIC32x4 stereo codec.
_More documentation on the hardware can be found [here](https://gitlab.com/kakar0t/audiosense-pi)_

This hardware provides multiple audio I/O capabilities to the RPi.
The codec connects to the RPi's SoC through the I2S Bus.

The following devices can be connected through a 3.5mm jack
	1. Line-In: Plain old audio in from mobile phones, PCs, etc.,
	2. Mic-In: Connect a microphone
	3. Line-Out: Connect the output to a speaker
	4. Headphones: Connect a Headphone w or w/o microphones

Multiple Inputs:
	It supports the following combinations
	1. Two stereo Line-Inputs and a microphone
	2. One stereo Line-Input and two microphones
	3. Two stereo Line-Inputs, a microphone and
		one mono line-input (with h/w hack)
	4. One stereo Line-Input, two microphones and
		one mono line-input (with h/w hack)

Multiple Outputs:
	Audio output can be routed to the headphones or
		speakers (with additional hardware)

Signed-off-by: b-ak <anur.bhargav@gmail.com>

### CODE REVIEW

**Comment by pelwell** [comment]
At first glance it looks pretty good. I have a few minor niggles we can get out of the way:
1. The standard Pi defconfigs - bcmrpi_defconfig, bcm2709_defconfig and  (optionally) bcmrpi3_defconfig in the arm64 tree - need to define CONFIG_SND_AUDIOSENSE_PI=m, otherwise the codec won't get built. This should go in a separate commit.
2. The overlay needs an entry in the README. Please be careful to follow the strict indentation (no TABs) and line length limits (80 characters).
3. Please put the overlay Makefile entry in strict alphabetical order.

The overall diffs, excluding the README, should look like this:
```diff
diff --git a/arch/arm/boot/dts/overlays/Makefile b/arch/arm/boot/dts/overlays/Makefile
index 120e848..8f5b8a9 100644
--- a/arch/arm/boot/dts/overlays/Makefile
+++ b/arch/arm/boot/dts/overlays/Makefile
@@ -20,8 +20,8 @@ dtbo-$(CONFIG_ARCH_BCM2835) += \
        audioinjector-addons.dtbo \
        audioinjector-ultra.dtbo \
        audioinjector-wm8731-audio.dtbo \
-       audremap.dtbo \
        audiosense-pi.dtbo \
+       audremap.dtbo \
        balena-fin.dtbo \
        bmp085_i2c-sensor.dtbo \
        dht11.dtbo \
diff --git a/arch/arm/configs/bcm2709_defconfig b/arch/arm/configs/bcm2709_defconfig
index 2a64d4f..16658b6 100644
--- a/arch/arm/configs/bcm2709_defconfig
+++ b/arch/arm/configs/bcm2709_defconfig
@@ -904,6 +904,7 @@ CONFIG_SND_BCM2708_SOC_IQAUDIO_DAC=m
 CONFIG_SND_BCM2708_SOC_IQAUDIO_DIGI=m
 CONFIG_SND_BCM2708_SOC_ADAU1977_ADC=m
 CONFIG_SND_AUDIOINJECTOR_PI_SOUNDCARD=m
+CONFIG_SND_AUDIOSENSE_PI=m
 CONFIG_SND_AUDIOINJECTOR_OCTO_SOUNDCARD=m
 CONFIG_SND_DIGIDAC1_SOUNDCARD=m
 CONFIG_SND_BCM2708_SOC_DIONAUDIO_LOCO=m
@@ -1304,7 +1305,6 @@ CONFIG_CIFS=m
 CONFIG_CIFS_WEAK_PW_HASH=y
 CONFIG_CIFS_UPCALL=y
 CONFIG_CIFS_XATTR=y
-CONFIG_CIFS_POSIX=y
 CONFIG_CIFS_ACL=y
 CONFIG_CIFS_DFS_UPCALL=y
 CONFIG_CIFS_FSCACHE=y
diff --git a/arch/arm/configs/bcmrpi_defconfig b/arch/arm/configs/bcmrpi_defconfig
index 8ffab67..062134c 100644
--- a/arch/arm/configs/bcmrpi_defconfig
+++ b/arch/arm/configs/bcmrpi_defconfig
@@ -897,6 +897,7 @@ CONFIG_SND_BCM2708_SOC_IQAUDIO_DAC=m
 CONFIG_SND_BCM2708_SOC_IQAUDIO_DIGI=m
 CONFIG_SND_BCM2708_SOC_ADAU1977_ADC=m
 CONFIG_SND_AUDIOINJECTOR_PI_SOUNDCARD=m
+CONFIG_SND_AUDIOSENSE_PI=m
 CONFIG_SND_AUDIOINJECTOR_OCTO_SOUNDCARD=m
 CONFIG_SND_DIGIDAC1_SOUNDCARD=m
 CONFIG_SND_BCM2708_SOC_DIONAUDIO_LOCO=m
@@ -1297,7 +1298,6 @@ CONFIG_CIFS=m
 CONFIG_CIFS_WEAK_PW_HASH=y
 CONFIG_CIFS_UPCALL=y
 CONFIG_CIFS_XATTR=y
-CONFIG_CIFS_POSIX=y
 CONFIG_CIFS_ACL=y
 CONFIG_CIFS_DFS_UPCALL=y
 CONFIG_CIFS_FSCACHE=y
diff --git a/arch/arm64/configs/bcmrpi3_defconfig b/arch/arm64/configs/bcmrpi3_defconfig
index 6419f4f..f89bda9 100644
--- a/arch/arm64/configs/bcmrpi3_defconfig
+++ b/arch/arm64/configs/bcmrpi3_defconfig
@@ -849,6 +849,7 @@ CONFIG_SND_BCM2708_SOC_IQAUDIO_DAC=m
 CONFIG_SND_BCM2708_SOC_IQAUDIO_DIGI=m
 CONFIG_SND_BCM2708_SOC_ADAU1977_ADC=m
 CONFIG_SND_AUDIOINJECTOR_PI_SOUNDCARD=m
+CONFIG_SND_AUDIOSENSE_PI=m
 CONFIG_SND_DIGIDAC1_SOUNDCARD=m
 CONFIG_SND_BCM2708_SOC_DIONAUDIO_LOCO=m
 CONFIG_SND_BCM2708_SOC_ALLO_PIANO_DAC=m
@@ -1211,7 +1212,6 @@ CONFIG_CIFS=m
 CONFIG_CIFS_WEAK_PW_HASH=y
 CONFIG_CIFS_UPCALL=y
 CONFIG_CIFS_XATTR=y
-CONFIG_CIFS_POSIX=y
 CONFIG_CIFS_ACL=y
 CONFIG_CIFS_DFS_UPCALL=y
 CONFIG_CIFS_FSCACHE=y
```

Once these changes are complete, `git push -f` to your branch and add a comment here.

**Comment by b-ak** [comment]
I will take care of all of those :)

**Comment by pelwell** [comment]
It would also be nicer if the SND_AUDIOSENSE_PI entry was after the SND_AUDIOINJECTOR_OCTO_SOUNDCARD entry in the Kconfig file. If you change Kconfig, move the CONFIG_SND_AUDIOSENSE_PI=m settings in the defconfigs to match.

**Comment by b-ak** [comment]
Yes, that would be perfectly alphabetical :+1: 
I need a little help with finding the README..

**Comment by pelwell** [comment]
It's in the overlays directory, i.e. `arch/arm/boot/dts/overlays/README`.

**Comment by b-ak** [comment]
Oops!! I was searching for it in the documentation.. Sorry for sounding so daft :|

**Comment by b-ak** [comment]
@pelwell Done :)

**Comment by pelwell** [comment]
It's a real shame that the codec doesn't support retrieving the power configuration data from DT, otherwise you could probably manage without a board driver and use simple-card instead.

If you can just add some extra blank lines around your README entry (two blanks are use to separate entries) then I'll merge.

**Comment by b-ak** [comment]
I will do that, but after 8PM-IST :(
And can you please point to the any of the codec implementing the power configuration, I will work on it next.

**Comment by pelwell** [comment]
If you are happy with everything else about the PR I can patch it here and merge manually, if you prefer.

The power configuration I was referring to is the [`power_cfg`](https://github.com/raspberrypi/linux/blob/rpi-4.14.y/include/sound/tlv320aic32x4.h#L49) field in the aic32x4_pdata structure. The driver code [here](https://github.com/raspberrypi/linux/blob/rpi-4.14.y/sound/soc/codecs/tlv320aic32x4.c#L944) uses that data (after it's been copied into the main `aic32x4_priv` structure) to initialise the same codec registers that your board driver is doing itself.

The intention is that this structure is provided by a machine driver as platform data for the codec, but this mechanism isn't used in the case that the device is instantiated from Device Tree - see the two "arms" of the `if` statement [here](https://github.com/raspberrypi/linux/blob/rpi-4.14.y/sound/soc/codecs/tlv320aic32x4.c#L1143). My thought was that `aic32x4_parse_dt` could be extended to also fill in the `power_cfg` field based on the value of a few DT properties.

**Comment by b-ak** [comment]
Yes, I have tested the build and all of the features in the patch. I am OK with any decision you take.

I will look into the power configuration. Thanks a lot for those references :)
I am also working towards getting the codec patches merged in the mainline.

**Comment by pelwell** [comment]
Patched up and merged manually. (I also edited a commit message to remove the references to the dtparams needed to get everything working - they aren't needed.)

**Comment by b-ak** [comment]
Thank you so much :) 
One step closer to the OSHW certification..

**Comment by b-ak** [comment]
@pelwell This is certified and published now [Audiosense-Pi](https://certification.oshwa.org/in000007.html)
Need your help in getting one last patch merged into the RPi tree, [Mic Bias Patch](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/sound/soc/codecs/tlv320aic32x4.c?h=v5.1-rc3&id=04d979d7a7bac2f645cd827ea37e5ffa5b4e1f97)

**Comment by pelwell** [comment]
Applied, along with 13 other patches. Please rebuild and test.

**Comment by b-ak** [comment]
Yes, I'll do that and update here

**Pull request closed without merging**
