### PR TITLE
ASoC: decommissioning driver for 3Dlab Nano soundcard

### PR DESCRIPTION
**Pull request by dev-3Dlab**
The goal of this commit is to remove the 3Dlab Nano driver out of the kernel tree.
Unfortunately this product will never see the light of day, so this driver can be removed.

### CODE REVIEW

**Comment by pelwell** [comment]
I'm sorry it didn't work out for you.

**Comment by dev-3Dlab** [comment]
Thank you very much, good luck for you!

**Comment by dev-3Dlab** [comment]
Hi @pelwell. I have just noticed that this decommissioning pull request has been merged to rpi-4.14.y branch, but not following branches (like rpi-4.19.y). What has to be done so that the same change is applied to every branches ?
Thank you.

Best regards

**Comment by pelwell** [comment]
That's fixed now - there should be no more references to the 3Dlab Nano.

**Comment by dev-3Dlab** [comment]
Indeed I can see it is OK now. Thank you for your help.

**Pull request merged**
