### PR TITLE
support_4inch_DSI_LCD_C-Resolved_11.9inch_touch_orientation_error

### PR DESCRIPTION
**Pull request by waveshare**
The content of PR
1.support waveshare 4inch DSI LCD (C)
2.Resolved waveshare 11.9inch touch orientation error

### CODE REVIEW

**Comment by 6by9** [comment]
Generally fine, but a few comments.

Kernel coding style is to use tabs set to 8 spaces. 

Does the 11.9" panel not need touchscreen-size-x and touchscreen-size-y set?

The `4_0_inch_C` override needs documenting in README.

Please keep dtoverlay changes in separate commits from driver changes. This allows patches to be squashed together more easily.

**Comment by waveshare** [comment]
> Generally fine, but a few comments.
> 
> Kernel coding style is to use tabs set to 8 spaces.
> 
> Does the 11.9" panel not need touchscreen-size-x and touchscreen-size-y set?
> 
> The `4_0_inch_C` override needs documenting in README.
> 
> Please keep dtoverlay changes in separate commits from driver changes. This allows patches to be squashed together more easily.

The GT chip driver will automatically obtain the touch information of the touch chip, then report the maximum value, minimum value of the touch, and the current touch coordinates to the input subsystem, and complete the input mapping.
If the touchscreen-size content in the dts file is not set, it will not affect the touch effect;

**Comment by pelwell** [comment]
The automated checks have spotted that your new parameter (`4_0_inch_C`) is not documented.
I've spotted that its name doesn't match an existing parameter (`7_0_inchC`). Try to be consistent.

**Comment by waveshare** [comment]
> The automated checks have spotted that your new parameter (`4_0_inch_C`) is not documented. I've spotted that its name doesn't match an existing parameter (`7_0_inchC`). Try to be consistent.

ok,changed `4_0_inch_C` to `4_0_inchC`

**Comment by 6by9** [comment]
> The GT chip driver will automatically obtain the touch information of the touch chip, then report the maximum value, minimum value of the touch, and the current touch coordinates to the input subsystem, and complete the input mapping. If the touchscreen-size content in the dts file is not set, it will not affect the touch effect;

Great, I just wasn't aware of that so it looked odd.

**Comment by pelwell** [comment]
So we're just lacking a README entry for the new parameter...

**Comment by waveshare** [comment]
> So we're just lacking a README entry for the new parameter...

OK,added parameter `4_0_inchC` to README

**Comment by Darmur** [comment]
I tried this patch and the touch of the 11.9" display works fine on a RPi5, but it's 1cm off on the vertical axes if the display is connected to a RPi4 or a CM4 with a Waveshare Carrier Board

@waveshare could you please check?

**Pull request merged**
