### PR TITLE
Add CAN_J1939 as module to default build configs

### PR DESCRIPTION
**Pull request by ghost**
This PR adds the Kconfig flag CONFIG_CAN_J1939=m

Abstract:
- there is a CAN protocol named J1939
- support in Linux Kernel since v5.4
- support in Python since v3.9
- header file available in package raspberrypi-kernel-headers since version 1:1.20210430-2 .
- therefore building Python 3.9.5 with J1939 support works now

Problem:
After building Python3.9.5 , the module turns out to be missing in
regular raspberrypi-kernel

```
python -i
Python 3.9.5 (default, May 13 2021, 13:29:45) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> s = socket.socket(socket.AF_CAN, socket.SOCK_DGRAM, socket.CAN_J1939)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 93] Protocol not supported
```

Solution:
- add CONFIG_CAN_J1939=m to relevant build configs

Reference:
- https://www.kernel.org/doc/html/latest/networking/j1939.html

### CODE REVIEW

**Comment by ghost** [comment]
Cross-compile-tested on X86_64, currently running a native build on a pi0w, that is my test device for CAN related stuff.

**Comment by pelwell** [comment]
These new settings have been added in the wrong place - they work as is, but using `make savedefconfig` causes them to move (between `CONFIG_CAN=m` and `CONFIG_CAN_ISOTP=m`, as it happens). Please fix this, and also update `arch/arm64/configs/bcm2711_defconfig` and `arch/arm64/configs/bcmrpi3_defconfig`.

**Comment by ghost** [comment]
ACK

**Comment by ghost** [comment]
Native build complete and verified to be working.

```
python -i
Python 3.9.5 (default, May 13 2021, 13:29:45)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.>>> import socket
>>> s = socket.socket(socket.AF_CAN, socket.SOCK_DGRAM, socket.CAN_J1939)
>>> s.bind(("mcp0", 0, 0x40000, 0x20))
>>> s.sendto(bytes(range(8)), ("", 0, 0x12300, 0x30))
8
```

```
candump mcp0
  mcp0  19233020   [8]  00 01 02 03 04 05 06 07
  mcp0  19233020   [8]  00 11 22 33 44 55 66 77
```

**Pull request merged**
