### PR TITLE
Added support for CS5343/CS5344 ADC connected to the Raspberry Pi

### PR DESCRIPTION
**Pull request by wzab**
I have implemented support for the CS5343/CS5344 98 dB, 96 kHz, Multi-Bit Audio A/D Converter (configured for sampling rate 48 kHz) , connected to the Raspberry Pi I2S interface.
These files were previously submitted to the branch rpi-3.8.y.asocdev in https://github.com/koalo/linux
This version is ported to the new driver for 3.12.y kernel and successfully tested with the real hardware (https://github.com/wzab/raspberry-pi-guitar-system-v1)

### CODE REVIEW

**Comment by popcornmix** [comment]
@koala
Look okay to you?

**Comment by koalo** [comment]
All in all it looks good, thank you!
Two minor comments:
1) I would prefer to have the machine driver (sound/soc/bcm/rpi-cs534x.c and the corresponding module name) named after your board (e.g. rpi-guitar-system). This is common in ASoC, because some day there might be someone who builds a board with a CS534x and needs a modified machine driver (e.g. because he uses an additional amplifier or other codec settings) and then the confusion starts.
2) When you rebase it anyway, please wrap sound/soc/codecs/cs534x.c to 80 characters per line max. This makes it easier to submit this patch upstream (https://www.kernel.org/doc/Documentation/CodingStyle)

**Comment by wzab** [comment]
OK. I'll change both the filename of the driver rpi-cs534x and the module
name.
However, if we want to avoid any future confusions, there is yet another
thing, which must somehow solved.
The CS5343/CS5344 is configured with pullup/pulldown resistors during
powerup.
So the hardware configuration enforces the sampling rate.
My codec driver assumes the particular sampling frequency: 48000 Hz
However someone else can configure his/her hardware in such a way, that the
sampling frequency will be 44100 Hz or 96kHz or 32 kHz.
So maybe the codec implementation in codecs/cs534x,c should report all
possible frequencies, and only the machine driver:
rpi-guitar-system (previously bcm/rpi-cs534x.c) should enforce the one
which s really available?
I'll appreciate any suggestions how to do it optimally.

Regards,
Wojtek

On Fri, Dec 27, 2013 at 10:09 AM, koalo notifications@github.com wrote:

> All in all it looks good, thank you!
> Two minor comments:
> 1) I would prefer to have the machine driver (sound/soc/bcm/rpi-cs534x.c
> and the corresponding module name) named after your board (e.g.
> rpi-guitar-system). This is common in ASoC, because some day there might be
> someone who builds a board with a CS534x and needs a modified machine
> driver (e.g. because he uses an additional amplifier or other codec
> settings) and then the confusion starts.
> 2) When you rebase it anyway, please wrap sound/soc/codecs/cs534x.c to 80
> characters per line max. This makes it easier to submit this patch upstream
> (https://www.kernel.org/doc/Documentation/CodingStyle)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/raspberrypi/linux/pull/471#issuecomment-31253362
> .

## 

Wojciech M. Zabołotny
My GPG/PGP keys:
standard: B191 ACF0 7909 83FA 3F9B  450C 407E 3C4B 4569 D119
confidential: 2BF3 F90F 6EA8 7D35 59FD  5080 78ED 33DE 1312 D8F8

**Comment by koalo** [comment]
That is a very good idea!
I would propose to set all possible sampling frequencies in the codec driver and then use constraints in the machine driver (e.g. snd_pcm_hw_constraint_list as in https://github.com/koalo/linux/blob/rpi-3.8.y-asocdev/sound/soc/bcm2708/rpi-proto.c)

**Comment by wzab** [comment]
I have changed names of my machine driver as suggested by Florian and tested the new version of the driver.
I have also added additional sampling rates in the CS534x codec driver and removed unsupported formats.

**Comment by wzab** [comment]
I have introduced proposed changes to the machine driver and to the codec
driver. Everything seems to work correctly.

The only problem with the new 3.12.y kernel is that the bcm2708-i2s driver
does not implement mmap, and the /proc/cpuinfo does not report CPU clock.
That disallows running of jackd on the Raspberry Pi.
Therefore I had to make tests using arecord, nc and aplay:
On the PC: nc -l -p 3200 | aplay -f S32_LE -c 2 -r 48000 -B 5000
On the Rapsberry Pi: arecord -D hw:1,1 -f S32_LE -c 2 -r 48000 -B5000 | nc
192.168.1.122 3200

Of course it resulted in an enormous latency :-(.
Are there any chances that the new kernel will be jackd compatible?
Regards, Wojtek

On Fri, Dec 27, 2013 at 3:05 PM, koalo notifications@github.com wrote:

> That is a very good idea!
> I would propose to set all possible sampling frequencies in the codec
> driver and then use constraints in the machine driver (e.g.
> snd_pcm_hw_constraint_list as in
> https://github.com/koalo/linux/blob/rpi-3.8.y-asocdev/sound/soc/bcm2708/rpi-proto.c
> )
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/raspberrypi/linux/pull/471#issuecomment-31261277
> .

## 

Wojciech M. Zabołotny
My GPG/PGP keys:
standard: B191 ACF0 7909 83FA 3F9B  450C 407E 3C4B 4569 D119
confidential: 2BF3 F90F 6EA8 7D35 59FD  5080 78ED 33DE 1312 D8F8

**Comment by koalo** [comment]
That MMAP thing is very annoying. It works with an own program, but when I enable it and want to play back 24 bit files only noise is heared. Therefore, I disabled it again. For your application you might want to try to enable it again (add SNDRV_PCM_INFO_MMAP to bcm2708).

Regarding your patch: It looks good to me, thanks.

**Comment by koalo** [comment]
@popcornmix Looks ok to you or do you want him to squash the commits?

**Comment by koalo** [comment]
One thing that I had forgotten: Please add the codec and machine modules to the default config
(https://github.com/koalo/linux/commit/6a6205d2c7b3a55c94bb7818a3b4a212be8e0dcf)

**Comment by popcornmix** [comment]
Yes, please squash the commits together.

**Comment by wzab** [comment]
OK. I have added modules to the default config and squashed commits
As I can see the side effect is that I have lost the history of all my
intermediate changes in my repository.
Is it possible to squash pull request without loosing this history in my
forked repository?

Wojtek

On Mon, Jan 6, 2014 at 5:20 PM, popcornmix notifications@github.com wrote:

> Yes, please squash the commits together.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/raspberrypi/linux/pull/471#issuecomment-31661134
> .

## 

Wojciech M. Zabołotny
My GPG/PGP keys:
standard: B191 ACF0 7909 83FA 3F9B  450C 407E 3C4B 4569 D119
confidential: 2BF3 F90F 6EA8 7D35 59FD  5080 78ED 33DE 1312 D8F8

**Comment by popcornmix** [comment]
Your history is changes is still in your local repo (assuming you kept a copy of the branch or can use git reflog).
There's no need for your history in the raspberrypi repo.
There should be one commit for each self contained block of work. There shouldn't be any development history in a PR.

**Comment by Ruffio** [comment]
@wzab are you going to fixed 'the issues'? If not, please close this PR.

**Comment by Ruffio** [comment]
This PR should be closed as it points to 3.12 and therefore it will never get merged.
It should be resubmitted to 4.4.y if still relevant.

**Comment by wzab** [comment]
Yes, indeed it is obsolete.

**Pull request closed without merging**
