### PR TITLE
Add driver for rpi-proto

### PR DESCRIPTION
**Pull request by wbx-github**
Forward port of 3.10.x driver from https://github.com/koalo
We are using a custom board and would like to use rpi 3.18.x
kernel. Patch works fine for our embedded system.

URL to the audio chip:
http://www.mikroe.com/add-on-boards/audio-voice/audio-codec-proto/

Playback tested with and without devicetree enabled.

### CODE REVIEW

**Comment by popcornmix** [comment]
ping @pelwell

**Comment by pelwell** [comment]
Since enabling device tree support in all RPi kernels, we no longer accept patches to bcm2708.c (and bcm2709.c, which you have omitted) for the sole purpose of creating platform devices.

So:
1) Remove the bcm2708.c patches.
2) Include patches for bcmrpi_defconfig and bcm2709_defconfig that set SND_BCM2708_SOC_RPI_PROTO=m. The right way to do this is to patch a configuration and then use "ARCH=arm make savedefconfig", then diff them against the original configurations to make sure the changes look sensible.
3) Is RPI_PROTO really what you want to call it?

**Comment by wbx-github** [comment]
Hi,

I am really to stupid for github. Do I need to refork and apply the changed patch to add a new pull request?
RPI_PROTO looks okay for me, better then two different names like in the original driver code.

Will fix it tomorrow.

**Comment by pelwell** [comment]
I think you can squash your commits then git push --force .

**Comment by pelwell** [comment]
Aside from that, it looks good.

**Comment by wbx-github** [comment]
Thanks for review and the force push tipp. Didn't know that.

**Comment by pelwell** [comment]
The overlay looks good, the code builds cleanly and although I can't test it, the driver looks plausible.

@popcornmix OK to merge?

**Pull request merged**
