### PR TITLE
drm/panel: Fix default values for Waveshare 7.9 inch DSI touchscreen

### PR DESCRIPTION
**Pull request by ilarrain**
This fixes touchscreen calibration, axis swapping and inversion.

As referenced in https://github.com/raspberrypi/linux/issues/5550

### CODE REVIEW

**Comment by pelwell** [comment]
I've read the other thread, and I see that it fixes the original user's problem - thanks for that. Could you say something about changing the dimensions to 4096? Otherwise it looks ready to squash and merge.

**Comment by 6by9** [comment]
I could have sworn I'd commented on this PR previously, but it seems to have disappeared.

I'd like to confirm what inversions the Waveshare driver uses for the 7.9" panel.
From https://github.com/waveshare/Waveshare-DSI-LCD/blob/main/6.1.21/64/WS_xinchDSI_MAIN.sh#L10 I'm expecting it to be SCREEN_type = 5, which means at https://github.com/waveshare/Waveshare-DSI-LCD/blob/main/6.1.21/64/pi4/WS_xinchDSI.sh#L64 means I'm expecting it to be inverted-x and inverted-y as in the original.
It's possible that Waveshare have an error in their script, but https://github.com/waveshare/Waveshare-DSI-LCD/issues/4#issuecomment-1509490884 largely confirms that was the setting used for that display.

**Comment by 6by9** [comment]
Ah, the PR I'd commented on was https://github.com/ilarrain/linux/pull/1

**Comment by ilarrain** [comment]
> I've read the other thread, and I see that it fixes the original user's problem - thanks for that. Could you say something about changing the dimensions to 4096? Otherwise it looks ready to squash and merge.

With the default config, only a small touch area (about 2x2 cm) was mapped to the whole screen, rendering it unusable.
I started experimenting with the value on each axis, and the touch area was getting bigger and bigger: 400 > 1080 >
2000 > 3000 > 4000 (it was close to perfect, but not quite) > 4200 (it was too big) > 4096 (it was perfect, ok both axis).
That's how I got to 4096. (2^12, 12 bit resolution on each axis).

I don't know if it applies to other panels, but at list on mine, @beletruz and @mbhangui, the patch fixed the issues. Maybe other panel sizes also use 4096 on both axis. I have no way to experiment, as this is the only panel I've got.

> I'd like to confirm what inversions the Waveshare driver uses for the 7.9" panel. From https://github.com/waveshare/Waveshare-DSI-LCD/blob/main/6.1.21/64/WS_xinchDSI_MAIN.sh#L10 I'm expecting it to be SCREEN_type = 5, which means at https://github.com/waveshare/Waveshare-DSI-LCD/blob/main/6.1.21/64/pi4/WS_xinchDSI.sh#L64 means I'm expecting it to be inverted-x and inverted-y as in the original. It's possible that Waveshare have an error in their script, but [waveshare/Waveshare-DSI-LCD#4 (comment)](https://github.com/waveshare/Waveshare-DSI-LCD/issues/4#issuecomment-1509490884) largely confirms that was the setting used for that display.

It is type 5 in the scripts for Wavershare installation, which corresponds to those values, you are correct. I have no way to know if it is an error by the manufacturer, or they are apllying an obscure logic in the overlays or kernel modules, as those are closed source. I just know what values work on my panel (and at least 2 other users).

> Ah, the PR I'd commented on was [ilarrain#1](https://github.com/ilarrain/linux/pull/1)

Sorry about that. I don't know much about git, and ended sending the pull request on the wrong repository. I thought about deleting it, but would have deleted the discussion too.

**Comment by 6by9** [comment]
I went shopping, and you appear to be right that the display manufacturer (or Waveshare as integrator) have done something very weird in their touch configuration, and plausibly emulated a Goodix touch controller rather than actually using one.

@pelwell The second patch is a fixup of the first. I think we can squash the two commits into one whilst merging, dropping the second commit in the process?
Do we care about the lack of SoB on a dtoverlay patch?

**Comment by pelwell** [comment]
Yes, no, and done.

**Pull request merged**
