### PR TITLE
Need CONFIG_CGROUP_PERF to run a container inside docker

### PR DESCRIPTION
**Pull request by umiddelb**
Hi,

I have to admit that I have overseen to include this kernel option as well in my last PR. Without this parameter enabled, the docker daemon will start, but refuses to run a container. I will give this information to the Docker maintainers group as well, since this parameter cannot be considered as optional any more.

Sorry for the noise.

### CODE REVIEW

**Comment by popcornmix** [comment]
A bit like in the previous PR, confirming memory usage and performance is not affected by this config option would be useful before it is merged.

**Comment by umiddelb** [comment]
kernel with CONFIG_CGROUP_PERF=y

```
$ free -h
             total       used       free     shared    buffers     cached
Mem:          482M        69M       412M         0B       9.5M        35M
-/+ buffers/cache:        25M       457M
Swap:          99M         0B        99M
```

```
$ time ./nbench
...
real    4m18.552s
user    4m17.730s
sys     0m0.220s
```

```
$ free -h
             total       used       free     shared    buffers     cached
Mem:          482M        70M       411M         0B       9.5M        35M
-/+ buffers/cache:        24M       457M
Swap:          99M         0B        99M
```

**Comment by popcornmix** [comment]
I think we'll need before and after adding CONFIG_CGROUP_PERF=y. Your numbers are obviously not the same as @pelwell's so can't be compared.

**Comment by umiddelb** [comment]
Yes I now, I'm just compiling a kernel without CONFIG_CGROUP_PERF.

**Comment by umiddelb** [comment]
kernel without CONFIG_CGROUP_PERF

```
$ free -h
             total       used       free     shared    buffers     cached
Mem:          482M        70M       412M         0B       9.7M        35M
-/+ buffers/cache:        25M       457M
Swap:          99M         0B        99M
```

```
$ time ./nbench
...
real    4m18.107s
user    4m17.170s
sys     0m0.330s
```

```
$ free -h
             total       used       free     shared    buffers     cached
Mem:          482M        70M       411M         0B        10M        35M
-/+ buffers/cache:        24M       457M
Swap:          99M         0B        99M
```

**Comment by umiddelb** [comment]
We can close this pull request, since Docker runs fine the standard 4.0.5 kernel and without CONFIG_CGROUP_PERF.

**Pull request closed without merging**
