### PR TITLE
Pispbe/rpi 6.6.y/split jobs handling v2

### PR DESCRIPTION
**Pull request by jmondi**

### CODE REVIEW

**Comment by naushir** [comment]
All changes look reasonable to me.  @jmondi did you test with dual camera running?

**Comment by naushir** [comment]
PS: Sorry for the delay, but I will respond on the linux-media list shortly as well.

**Comment by jmondi** [comment]
> All changes look reasonable to me. @jmondi did you test with dual camera running?

Yup! Same results as v1, I was puzzled that I got the ov5647 running at 10fps and thought it was something related to this patch, but I get the same results with plain rpi-6.6.y

**Comment by naushir** [comment]
LGTM. Merging now.

**Comment by jmondi** [comment]
> LGTM. Merging now.

Or should we wait for comments upstream so that we're merging the same version ?

**Comment by naushir** [comment]
> > LGTM. Merging now.
> 
> Or should we wait for comments upstream so that we're merging the same version ?

Ok sounds sensible.

**Comment by jmondi** [comment]
closing as I've update the original one in #6302

**Pull request closed without merging**
