### PR TITLE
Fix Nuprime dac-10 vendor id

### PR DESCRIPTION
**Pull request by ghost**
Nuprime dac-10 is not recognized as native dsd supported because of the id error. The correct vendor id is "0x16d0, 0x06b2" instead of "0x16b0, 0x06b2".

### CODE REVIEW

**Comment by pelwell** [comment]
That's an unmodified upstream Linux file - we haven't made any changes, so we'd rather not start now. But for such a simple issue like this I'm sure that if you email the maintainers (Jaroslav Kysela <perex@perex.cz> and Takashi Iwai <tiwai@suse.com>) they'll get a patch merged very quickly. When they do, report back here and we can back-port it.

**Comment by ghost** [comment]
> That's an unmodified upstream Linux file - we haven't made any changes, so we'd rather not start now. But for such a simple issue like this I'm sure that if you email the maintainers (Jaroslav Kysela [perex@perex.cz](mailto:perex@perex.cz) and Takashi Iwai [tiwai@suse.com](mailto:tiwai@suse.com)) they'll get a patch merged very quickly. When they do, report back here and we can back-port it.

I got the reply from Takashi Iwai. He has corrected the vendor id.

**Comment by pelwell** [comment]
That's even quicker than I expected. With a bit of luck he's given you a "Reported-by:" credit in the commit header, which means you'll be notified when it gets merged. Once it is, comment here with the commit hash.

**Comment by ghost** [comment]
I just started to learn how to use GitHub. I do see a update one hour ago in tiwai’s commits history called Merge branch 'for-linus' which includes the correction I mentioned. Is this the merge you are talking about? Sorry to bother you.

**Comment by pelwell** [comment]
That's the right commit. I would expect that to be merged into https://kernel.googlesource.com/pub/scm/linux/kernel/git/next/linux-next/+log/refs/heads/master by tomorrow morning.

**Comment by pelwell** [comment]
Your commit appeared [upstream](https://kernel.googlesource.com/pub/scm/linux/kernel/git/next/linux-next/+/547d2c9cf4f1f72adfecacbd5b093681fb0e8b3e) and has been back-ported to the current kernel branches ([rpi-4.19.y](https://github.com/raspberrypi/linux/commit/e7d7c6615834d240b77ac6e8331784a7efa8c0e3), rpi-5.4.y and rpi-5.6.y).

**Pull request closed without merging**
