### PR TITLE
.github/workflows: Switch to a matrix build

### PR DESCRIPTION
**Pull request by pelwell**
Remove the per-build duplication by putting build parameters in a matrix.

Signed-off-by: Phil Elwell <phil@raspberrypi.com>

### CODE REVIEW

**Comment by pelwell** [comment]
This PR won't trigger a build because the workflow explicitly ignores changes to the workflow file, but you can see the results of running a build on exactly the same tree (except with the previous commit reverted to force a build) here: https://github.com/pelwell/linux/actions/runs/3994747733

**Comment by pelwell** [comment]
Any objections?

**Comment by popcornmix** [comment]
+59 / - 234 lines sounds good to me.

**Comment by pelwell** [comment]
I've eyeballed the tar creation logs and they _look_ OK, but obviously I'll fix any issues found down the line (which will be quicker and less error-prone thanks this).

**Pull request merged**
