### PR TITLE
WIP: rpi-5.4.y V4L2 drivers

### PR DESCRIPTION
**Pull request by 6by9**
Clean up the Unicam and V4L2 M2M drivers for upstreaming.

### CODE REVIEW

**Comment by 6by9** [comment]
@popcornmix I think you want
1264277 9c4ebd7 f0d43b4 and dd36df0 to get the V4L2 decoder up and running on this branch. I'll separate those couple of patches out and push them as a new PR as those can be merged now.

**Comment by popcornmix** [comment]
Tested the 4 commits and it worked for me - I could play video with V4L2 driver.
I've pushed those commits.

**Comment by mohit169soni** [comment]
i am having trouble upstreaming my video using browser in raspberry pi, can it be v4l2 error, because i am using arducam for this upstreaming purpose,

**Comment by JamesH65** [comment]
@mohit169soni Best to ask for tech support on the forums rather than this thread which is likely unrelated to your issue.

**Comment by 6by9** [comment]
@mohit169soni 
Your issue has nothing to do with this pull request.
All these changes are related to V4L2 memory to memory devices (codecs, or video scaling/processing), not the camera. 

Please ask on the forums, or if you think you have a genuine bug, then raise an issue.

**Comment by 6by9** [comment]
Most of the changes have been cherry-picked, and the rest have been reworked. Closing.

**Pull request closed without merging**
