### PR TITLE
Make vcio (mailbox) driver available on ARCH_BCM2835

### PR DESCRIPTION
**Pull request by notro**
Move the mailbox driver to drivers/mailbox to make it available on ARCH_BCM2835.

Tested on Pi1 and Pi2 with and without Device Tree (BCM270x).

Mailbox on ARCH_BCM2835 is tested with a hacked up bcm2708_fb and from userspace:

```
$ sudo /opt/vc/src/hello_pi/hello_fft/hello_fft.bin 12
rel_rms_err = 7.8e-07, usecs = 259, k = 0

```

### CODE REVIEW

**Comment by popcornmix** [comment]
How does this compare to bcm2835 mbox driver?
http://lists.infradead.org/pipermail/linux-arm-kernel/2015-March/327098.html

**Comment by notro** [comment]
bcm2835-mailbox can only be used with Device Tree. AFAICT the API is also centered around DT making it difficult to patch locally for use with regular platform devices.

The vcio driver has it's own API which these depending drivers use:
arch/arm/mach-bcm2708/vc_mem.c
arch/arm/mach-bcm2709/power.c
arch/arm/mach-bcm2709/vc_mem.c
arch/arm/mach-bcm2709/vc_support.c
drivers/cpufreq/bcm2835-cpufreq.c
drivers/hwmon/bcm2835-hwmon.c
drivers/misc/vc04_services/interface/vchiq_arm/vchiq_2835_arm.c
drivers/thermal/bcm2835-thermal.c
drivers/video/fbdev/bcm2708_fb.c

This is just transitional work. When we move to ARCH_BCM2835, maybe we could write a module that wraps bcm2835-mailbox providing the legacy API. Unless most of these drivers have been pushed upstream first.

**Comment by popcornmix** [comment]
Okay. I think dropping non-DT support is a matter of when rather than if.
So at some future point when kernel is DT only, we can update drivers to use 2835 mbox driver.

No objections in principle, but I can't test this until after the weekend.

**Comment by notro** [comment]
AFAIK only the firmware driver uses the mailbox, because the mailbox has only one channel.
So drivers will be using the firmware driver to get/set properties.

[PATCH 2/3] ARM: bcm2835: Add the Raspberry Pi firmware driver
http://lists.infradead.org/pipermail/linux-rpi-kernel/2015-April/001638.html

**Comment by popcornmix** [comment]
@pelwell any objections?
I'm not seeing any issues with a mach2709 build.

**Comment by pelwell** [comment]
I was just about to read the commits again, but the 4.0.2 update has meant the PR needs rebasing.

**Comment by popcornmix** [comment]
You can still read the commits here. @notro can you rebase?

**Comment by notro** [comment]
I have rebased.

**Comment by pelwell** [comment]
I want to test the mailbox behaviour to see if I've understood the FIFO status logic, but apart from that and the ATOMIC allocation I have no objections to merging.

**Comment by notro** [comment]
Added commit for GFP_ATOMIC issue.

**Comment by notro** [comment]
Added status register fix

**Comment by popcornmix** [comment]
Can you squash (at least last two, and any more you think are appropriate).

**Comment by notro** [comment]
I have tried to follow mainline philosophy here, one commit per change. Well I skipped that on the checkpatch commit, that one would have to be split in several commits in mainline.
I also did this because the last PR I did had all driver changes squashed, and I realised that it will be impossible to bisect that one should problems arise. Even though the changes "should not" cause problems, experience shows the limits of the human mind when it comes to writing code.

So I don't think squashing any of these is really best practice.
But if you insist I will comply :-)

**Comment by popcornmix** [comment]
Not sure I agree. The last two commits are bug fixes to files introduced by the PR. I see no reason why the bugs and the fixes need to be preserved forever.

The problem is having large numbers of non-upstreamed commits does make rebasing onto new kernel versions harder, both when trying to find commits, and when you get conflicts. Nothing worse than having a file that has a long history of typo/fix/revert commits that later gets an upstream update that means you have to fix conflicts repeatedly when rebasing.

I think at least the last two commits should be squashed.

**Comment by notro** [comment]
> The last two commits are bug fixes to files introduced by the PR.

Both are present in the current vcio driver, so they don't fix a problem introduced by this PR.
This PR doesn't create a new driver, it changes it and moves it.

But I'll squash the last two.

**Comment by popcornmix** [comment]
Okay, I get your point. Technically the last two commits could be a separate fix (e.g. preceding this PR).
You may find that after a 4.1 or later rebase that I remove the original location of the vcio driver and just have the new version, so perhaps the squashing doesn't matter.

**Comment by notro** [comment]
> Technically the last two commits could be a separate fix

Yes. And technically it would have been best that Phil did the status register fix, because he knows the subject matter. I wouldn't know how to do the test he did. This is somewhat similar to the challenge I face when I now try to get Gellert's slave_sg DMA patch into mainline, I know very little about the driver making it impossible to answer technical questions.
But Phil probably has his head into something else, and since I already work on this driver, I just added his comment as the commit message.

> You may find that after a 4.1 or later rebase that I remove the original location of the vcio driver and just have the new version

Yes, I have seen that you sometimes squash on the next cycle.
But having all the commits makes it possible to bisect in this cycle at least, which is good enough.

> so perhaps the squashing doesn't matter

Then I'll happily drop the squashing.

**Comment by pelwell** [comment]
Thank you, notro. I had expected this all to get squashed into one patch. Had I know it would remain a series of patches then I would have happily written the status fix patch myself, and it would have looked exactly like yours.

**Pull request merged**
