### PR TITLE
vc4 gamma fixes

### PR DESCRIPTION
**Pull request by 6by9**
I need to check that Pi3 is happy. Pi4 seems to be.

### CODE REVIEW

**Comment by 6by9** [comment]
#4676

**Comment by popcornmix** [comment]
Tested on Pi4. The `refcount_warn_saturate` warn has gone, but I've still got a bright hdmi display with two monitors connected.
It's actually HDMI0 this time (I've normally seen HDMI1 as the bright one).

**Comment by popcornmix** [comment]
Interestingly leaving the Pi with bright HDMI0 for 30 minutes resulted in both displays blanking for a couple of seconds and they came back without the brightness issue. I wonder if X does send a gamma command after 30 mins (screensaver/screen blanking?). But it didn't remain black.
A reboot and HDMI 0 was bright again.

**Comment by 6by9** [comment]
I need to make sure I've pushed the latest changes (found a couple of other issues at the same time, and testing Pi3 has been awkward).
The latest set should disable gamma such that ```sudo cat /sys/kernel/debug/dri/1/hvs_gamma``` reports such. Are you seeing that?

**Comment by 6by9** [comment]
Branch rebased and latest changes pushed.

I'm not seeing odd gamma tables with that.
- If booting to console, gamma is disabled.
- Load X and it sets a 1:1 gamma LUT. 
- Quit X and it leaves gamma at whatever it was before.
- ``` drm/build/tests/proptest/proptest -M vc4 76 crtc 28 0``` and ``` drm/build/tests/proptest/proptest -M vc4 83 crtc 28 0``` to clear the gamma tables, and we're back to 1:1 with the gamma block disabled.

For Pi0-3, the vc4 docs are not 100% clear whether it is legitimate to enable/disable gamma whilst active, but it seems to behave itself even if you do, so I'm happy enough with the patches as they stand.

**Comment by 6by9** [comment]
Added another patch that validates the gamma LUT blob is of the correct length as I don't believe the framework does it for us. (Rockchip is certainly validating it within the driver).

**Comment by popcornmix** [comment]
I'm still getting bright hdmi0 (until 30 minutes).
```
HVS channel 0:
  red:
  00000000 00000c23 - x 0, c 0, grad 3107
  01500fee 000006d7 - x 21, c 4078, grad 1751
  03a01fbf 0000042f - x 58, c 8127, grad 1071
  07802ff6 000002e8 - x 120, c 12278, grad 744
  0d003ff0 0000022e - x 208, c 16368, grad 558
  14504fe2 000001b8 - x 325, c 20450, grad 440
  1db05ffb 00000166 - x 475, c 24571, grad 358
  29206ffd 0000012c - x 658, c 28669, grad 300
  36c07ff4 00000100 - x 876, c 32756, grad 256
  46c08ff7 000000de - x 1132, c 36855, grad 222
  59309ffa 000000c3 - x 1427, c 40954, grad 195
  6e20aff6 000000ae - x 1762, c 45046, grad 174
  85c0bffd 0000009c - x 2140, c 49149, grad 156
  a000cff7 0000008d - x 2560, c 53239, grad 141
  bd20dffd 00000080 - x 3026, c 57341, grad 128
  dd10effb 00000075 - x 3537, c 61435, grad 117
  green:
  00000000 00000c23 - x 0, c 0, grad 3107
  01500fee 000006d7 - x 21, c 4078, grad 1751
  03a01fbf 0000042f - x 58, c 8127, grad 1071
  07802ff6 000002e8 - x 120, c 12278, grad 744
  0d003ff0 0000022e - x 208, c 16368, grad 558
  14504fe2 000001b8 - x 325, c 20450, grad 440
  1db05ffb 00000166 - x 475, c 24571, grad 358
  29206ffd 0000012c - x 658, c 28669, grad 300
  36c07ff4 00000100 - x 876, c 32756, grad 256
  46c08ff7 000000de - x 1132, c 36855, grad 222
  59309ffa 000000c3 - x 1427, c 40954, grad 195
  6e20aff6 000000ae - x 1762, c 45046, grad 174
  85c0bffd 0000009c - x 2140, c 49149, grad 156
  a000cff7 0000008d - x 2560, c 53239, grad 141
  bd20dffd 00000080 - x 3026, c 57341, grad 128
  dd10effb 00000075 - x 3537, c 61435, grad 117
  blue:
  00000000 00000c23 - x 0, c 0, grad 3107
  01500fee 000006d7 - x 21, c 4078, grad 1751
  03a01fbf 0000042f - x 58, c 8127, grad 1071
  07802ff6 000002e8 - x 120, c 12278, grad 744
  0d003ff0 0000022e - x 208, c 16368, grad 558
  14504fe2 000001b8 - x 325, c 20450, grad 440
  1db05ffb 00000166 - x 475, c 24571, grad 358
  29206ffd 0000012c - x 658, c 28669, grad 300
  36c07ff4 00000100 - x 876, c 32756, grad 256
  46c08ff7 000000de - x 1132, c 36855, grad 222
  59309ffa 000000c3 - x 1427, c 40954, grad 195
  6e20aff6 000000ae - x 1762, c 45046, grad 174
  85c0bffd 0000009c - x 2140, c 49149, grad 156
  a000cff7 0000008d - x 2560, c 53239, grad 141
  bd20dffd 00000080 - x 3026, c 57341, grad 128
  dd10effb 00000075 - x 3537, c 61435, grad 117
HVS channel 1:
  red:
  00000000 00000100 - x 0, c 0, grad 256
  10001000 00000100 - x 256, c 4096, grad 256
  20002000 00000100 - x 512, c 8192, grad 256
  30003000 00000100 - x 768, c 12288, grad 256
  40004000 00000100 - x 1024, c 16384, grad 256
  50005000 00000104 - x 1280, c 20480, grad 260
  60006040 00000100 - x 1536, c 24640, grad 256
  70007040 00000100 - x 1792, c 28736, grad 256
  80008040 00000100 - x 2048, c 32832, grad 256
  90009040 00000100 - x 2304, c 36928, grad 256
  a000a040 00000104 - x 2560, c 41024, grad 260
  b000b080 00000100 - x 2816, c 45184, grad 256
  c000c080 00000100 - x 3072, c 49280, grad 256
  d000d080 00000100 - x 3328, c 53376, grad 256
  e000e080 00000100 - x 3584, c 57472, grad 256
  f000f080 00000104 - x 3840, c 61568, grad 260
  green:
  00000000 00000100 - x 0, c 0, grad 256
  10001000 00000100 - x 256, c 4096, grad 256
  20002000 00000100 - x 512, c 8192, grad 256
  30003000 00000100 - x 768, c 12288, grad 256
  40004000 00000100 - x 1024, c 16384, grad 256
  50005000 00000104 - x 1280, c 20480, grad 260
  60006040 00000100 - x 1536, c 24640, grad 256
  70007040 00000100 - x 1792, c 28736, grad 256
  80008040 00000100 - x 2048, c 32832, grad 256
  90009040 00000100 - x 2304, c 36928, grad 256
  a000a040 00000104 - x 2560, c 41024, grad 260
  b000b080 00000100 - x 2816, c 45184, grad 256
  c000c080 00000100 - x 3072, c 49280, grad 256
  d000d080 00000100 - x 3328, c 53376, grad 256
  e000e080 00000100 - x 3584, c 57472, grad 256
  f000f080 00000104 - x 3840, c 61568, grad 260
  blue:
  00000000 00000100 - x 0, c 0, grad 256
  10001000 00000100 - x 256, c 4096, grad 256
  20002000 00000100 - x 512, c 8192, grad 256
  30003000 00000100 - x 768, c 12288, grad 256
  40004000 00000100 - x 1024, c 16384, grad 256
  50005000 00000104 - x 1280, c 20480, grad 260
  60006040 00000100 - x 1536, c 24640, grad 256
  70007040 00000100 - x 1792, c 28736, grad 256
  80008040 00000100 - x 2048, c 32832, grad 256
  90009040 00000100 - x 2304, c 36928, grad 256
  a000a040 00000104 - x 2560, c 41024, grad 260
  b000b080 00000100 - x 2816, c 45184, grad 256
  c000c080 00000100 - x 3072, c 49280, grad 256
  d000d080 00000100 - x 3328, c 53376, grad 256
  e000e080 00000100 - x 3584, c 57472, grad 256
  f000f080 00000104 - x 3840, c 61568, grad 260
```

**Comment by 6by9** [comment]
> I'm still getting bright hdmi0 (until 30 minutes).

Please confirm details to reproduce? Bullseye or Buster? Presumably X from your earlier description. Booting direct to X or console?

**Comment by popcornmix** [comment]
It's bullseye. Set to boot to desktop with auto login. Two 4kp30 hdmi displays.

**Comment by 6by9** [comment]
The patches appear to have been pushed manually by popcornmix last night, so the merge of this PR actually did nothing. However the changes are in there now.

**Pull request merged**
