### PR TITLE
configs: Enable WireGuard kernel module on armhf configs

### PR DESCRIPTION
**Pull request by MichaIng**
Closes: #3945

### CODE REVIEW

**Comment by pelwell** [comment]
@popcornmix - this option only enables a module to be built - the kernel images with and without differ only in timestamps and a commit hash. Are you happy for me to merge?

**Comment by popcornmix** [comment]
Yes, I'm happy.

**Comment by pelwell** [comment]
I've noticed that enabling WireGuard on ARCH=arm implies `CONFIG_ARM_CRYPTO=y`. Can you use `make ... savedefconfig`s to regenerate them (or just delete the `CONFIG_ARM_CRYPTO=y`) and re-push?

**Comment by MichaIng** [comment]
Ah yes, I was just going to ask as you did the same when adding the module for arm64: https://github.com/raspberrypi/linux/commit/6a69fd5bd5c55dbd468f4aff95eb77b34d8b849e
Jep will delete them and re-push.

**Pull request merged**
