### PR TITLE
configs: Enable CONFIG_ARM_BCM2835_CPUFREQ

### PR DESCRIPTION
**Pull request by popcornmix**
We actually use the 64-bit 2711 kernel on Pi3 too.
It still uses the downstream cpufreq driver in DT.

See: https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=269769&start=100#p1644752
Signed-off-by: popcornmix <popcornmix@gmail.com>

### CODE REVIEW

**Comment by popcornmix** [comment]
TODO: can we use upstream cpufreq driver on Pi3.

**Comment by pelwell** [comment]
> TODO: can we use upstream cpufreq driver on Pi3.

AFAIK the Pi 3 doesn't include that bit of STB hardware, so I don't see how it could work.

**Comment by pelwell** [comment]
Ignore me - crossed wires.

**Comment by pelwell** [comment]
See https://github.com/raspberrypi/linux/pull/3604.

**Pull request merged**
