### PR TITLE
Config : add TCA6416 to module chip

### PR DESCRIPTION
**Pull request by RuffaloLavoisier**
Add a matrix keyboard on I2C.

### CODE REVIEW

**Comment by pelwell** [comment]
Tweaked and merged offline (https://github.com/raspberrypi/linux/commit/20c603213e9c212930a49e86beaf66c8b2c9f49c).

**Comment by RuffaloLavoisier** [comment]
@pelwell Thanks, I checked the merge commit. 🙂 
But why did you close it without merge?

**Comment by pelwell** [comment]
The `*_defconfig` files are created by `make ... savedefconfig`, and the entries are generated in the order in which they are encountered in the Kconfig files. I prefer it that when you do `make ... bcm2711_defconfig` followed by `make ... savedefconfig` that the generated file `defconfig` is identical to `bcm2711_defconfig`. In the case of this PR the TCA6416 line was after the TCA8418 line, but `savedefconfig` put it before, so I swapped them.

**Comment by pelwell** [comment]
i.e. it has been merged, but not through GitHub. It would probably have been possible to force push to your private branch, or add multiple fixing patches and squash them, or just ask you to make the change, but this was quicker. Until I started writing an explanation.

**Comment by RuffaloLavoisier** [comment]
@pelwell Thank you for your kind explanation :)

**Pull request closed without merging**
