### PR TITLE
Revert "net: pskb_trim_rcsum() and CHECKSUM_COMPLETE are friends"

### PR DESCRIPTION
**Pull request by 6by9**
This reverts commit 88078d98d1bb085d72af8437707279e203524fa5.

Various people have been reporting seeing "eth0: hw csum failure"
and callstacks dumped in the kernel log on 4.18, and since 4.14.71,
on both SMSC9514 and LAN7800 adapters.
This commit appears to be the reason, but potentially due to an
issue further down the stack. Revert whilst investigating the
trigger.

https://github.com/raspberrypi/linux/issues/2713
https://github.com/raspberrypi/linux/issues/2659
https://github.com/raspberrypi/linux/issues/2712

Signed-off-by: Dave Stevenson <dave.stevenson@raspberrypi.org>

### CODE REVIEW

**Comment by 6by9** [comment]
@pelwell revert as discussed.

Do we want to defer merging this one until we have a way to reproduce? Fixing 4.14 needs to be a priority as that is our supported kernel, but 4.18 isn't so may lead to someone giving us guaranteed steps to reproduce the issue and investigate.

**Comment by pelwell** [comment]
If we're realistically expecting 4.18 to be used by a significant number of users it should be released to the `next` branch. What do you think, @popcornmix ?

**Comment by 6by9** [comment]
James has found https://patchwork.ozlabs.org/patch/982642/ which might be a candidate for a potential fix on 4.18 instead of revert.

**Comment by 6by9** [comment]
#2718 is a cherry-pick of the mailing list patch applied to 4.18 as an alternative to this revert.
Building/testing it now to see if it works generally even if we can't reproduce the failure.

**Comment by 6by9** [comment]
Seeing as popcornmix has merged the net-dev patch, I'll close this for now.

**Pull request closed without merging**
