### PR TITLE
merge v5.10.44 into rpi-5.10.y

### PR DESCRIPTION
**Pull request by ncopa**
Hi,

I maintain the linux-rpi kernel for alpine linux. Every time there is a new linux stable release I update the alpine linux-lts and linux-rpi kernels.

What I do is: checkout/pull from rpi-5.10.y, run `make -s kernelversion` to check if you had updated to latest, create a new branch for the new release (eg `git checkout -b rpi-5.10.44-alpine`) and then merge the release (`git merge v5.10.44`) 

I notice that I normally do this a few days before the rpi-5.10.y gets synced, so I thought I could contribute this back, and create a pull request for you every time I do this - if you are interested. It would also be good to have another couple of eyes that had a look at conflicts, like in this case.

What do you think?

### CODE REVIEW

**Comment by ncopa** [comment]
Seems like github UI does not give any good visualization of how I resolved the conflicts.

This is how I handled the conflict in `kernel/cgroup/cgroup.c`
```diff
Merge: 9eba2146c899 f2b1fc360fa1
Author: Natanael Copa <ncopa@alpinelinux.org>
Date:   Thu Jun 17 11:19:36 2021 +0200

    Merge tag 'v5.10.44' into rpi-5.10.44-alpine
    
    This is the 5.10.44 stable release

diff --cc kernel/cgroup/cgroup.c
index ea5a1ea68dd8,c8b811e039cc..13019ed268a2
--- a/kernel/cgroup/cgroup.c
+++ b/kernel/cgroup/cgroup.c
@@@ -5665,10 -5665,6 +5665,9 @@@ int __init cgroup_init_early(void
        return 0;
  }
  
- static u16 cgroup_disable_mask __initdata;
 +static u16 cgroup_enable_mask __initdata;
 +static int __init cgroup_disable(char *str);
 +
  /**
   * cgroup_init - cgroup initialization
   *
```

Relevant related commits are:
from `linux-5.10.y`: 5ca472d40e2daebbfd926701902debcab0bbd15c
from `rpi-5.10.y`: 9fc03b7b841a4efb45e8997cedac4896bc1682ab

**Comment by popcornmix** [comment]
I have a script that does this (usually without conflicts).
I think the PR would be more time consuming as I'd have to verify all the commits do match upstream.

**Comment by ncopa** [comment]
That is what I suspected and is why I asked. I wonder how we could cooperate better or if it makes any sense at all. (As mentioned I'm normally a few days ahead)

Would it be helpful if I created an issue with reference to relevant related commits when there are conflicts?

btw, the merge in this PR is bad.
```
/home/ncopa/aports/main/linux-rpi/src/linux-5.10/kernel/cgroup/cgroup.c:5713:2: error: 'cgroup_disable_mask' undeclared (first use in this function); did you mean 'cgroup_enable_mask'?
 5713 |  cgroup_disable_mask &= ~cgroup_enable_mask;
      |  ^~~~~~~~~~~~~~~~~~~
      |  cgroup_enable_mask
/home/ncopa/aports/main/linux-rpi/src/linux-5.10/kernel/cgroup/cgroup.c:5713:2: note: each undeclared identifier is reported only once for each function it appears in
```

I'm on IRC OFTC and libera if you want chat (my nick is ncopa)

**Comment by popcornmix** [comment]
Creating an issue when a rebase has a conflict would be fine.
Suggest what your fix was, and I can confirm I agree when I do it.

**Comment by popcornmix** [comment]
@pelwell could you check https://github.com/raspberrypi/linux/commit/5ca472d40e2daebbfd926701902debcab0bbd15c which causes a conflict with our downstream patch? The fix isn't completely trivial.

**Comment by ncopa** [comment]
9fc03b7b841a4efb45e8997cedac4896bc1682ab needs to be refactored.

**Comment by ncopa** [comment]
So what I did:
- revert 9fc03b7b841a4efb45e8997cedac4896bc1682ab
- merge v5.10.44
- git cherry-pick 9fc03b7b841a4efb45e8997cedac4896bc1682ab and refactor as:

```diff
commit a1036ed6e1d7141dd6d9a4a53128fffe7ea51ae2 (HEAD -> rpi-5.10.44-alpine)
Author: Phil Elwell <phil@raspberrypi.org>
Date:   Mon Nov 27 17:14:54 2017 +0000

    cgroup: Disable cgroup "memory" by default
    
    Some Raspberry Pis have limited RAM and most users won't use the
    cgroup memory support so it is disabled by default. Enable with:
    
        cgroup_enable=memory
    
    See: https://github.com/raspberrypi/linux/issues/1950
    
    Signed-off-by: Phil Elwell <phil@raspberrypi.org>
    (cherry picked from commit 9fc03b7b841a4efb45e8997cedac4896bc1682ab)

diff --git a/kernel/cgroup/cgroup.c b/kernel/cgroup/cgroup.c
index c8b811e039cc..856e90072bae 100644
--- a/kernel/cgroup/cgroup.c
+++ b/kernel/cgroup/cgroup.c
@@ -5665,6 +5665,8 @@ int __init cgroup_init_early(void)
        return 0;
 }
 
+static int __init cgroup_disable(char *str);
+
 /**
  * cgroup_init - cgroup initialization
  *
@@ -5703,6 +5705,9 @@ int __init cgroup_init(void)
 
        mutex_unlock(&cgroup_mutex);
 
+       /* Apply an implicit disable... */
+       cgroup_disable("memory");
+
        for_each_subsys(ss, ssid) {
                if (ss->early_init) {
                        struct cgroup_subsys_state *css =
@@ -6249,6 +6254,30 @@ static int __init cgroup_disable(char *str)
 }
 __setup("cgroup_disable=", cgroup_disable);
 
+static int __init cgroup_enable(char *str)
+{
+       struct cgroup_subsys *ss;
+       char *token;
+       int i;
+
+       while ((token = strsep(&str, ",")) != NULL) {
+               if (!*token)
+                       continue;
+
+               for_each_subsys(ss, i) {
+                       if (strcmp(token, ss->name) &&
+                           strcmp(token, ss->legacy_name))
+                               continue;
+
+                       static_branch_enable(cgroup_subsys_enabled_key[i]);
+                       pr_info("Enabling %s control group subsystem\n",
+                               ss->name);
+               }
+       }
+       return 1;
+}
+__setup("cgroup_enable=", cgroup_enable);
+
 void __init __weak enable_debug_cgroup(void) { }
 
 static int __init enable_cgroup_debug(char *str)
```

I think it builds, but needs runtime testing

**Comment by pelwell** [comment]
@ncopa's refactored implementation looks correct.

**Comment by ncopa** [comment]
I can confirm that it compiles fine, and I have test booted it.

However, when I add `cgroup_enable=memory` to the command line, dmesg says:
```
... cgroup: Enabling memory control group subsystem
... cgroup: Disabling memory control group subsystem
```

Which means that `cgroup_enable()` is called before `cgroup_init()` -> `cgroup_disable("memory")`

This needs better refactoring.

**Comment by ncopa** [comment]
Something like this might work, but feels a bit clumsy. Completely untested:

```diff
diff --git a/kernel/cgroup/cgroup.c b/kernel/cgroup/cgroup.c
index c8b811e039cc..156425c2f05b 100644
--- a/kernel/cgroup/cgroup.c
+++ b/kernel/cgroup/cgroup.c
@@ -5665,6 +5665,23 @@ int __init cgroup_init_early(void)
        return 0;
 }
 
+static u16 cgroup_enable_mask __initdata;
+static int __init cgroup_is_enabled(char *str)
+{
+       struct cgroup_subsys *ss;
+       int i;
+       for_each_subsys(ss, i) {
+               if (strcmp(token, ss->name) &&
+                   strcmp(token, ss->legacy_name))
+                       continue;
+
+               return cgroup_enable_mask & 1 << i;
+       }
+       return 0;
+}
+
+static int __init cgroup_disable(char *str);
+
 /**
  * cgroup_init - cgroup initialization
  *
@@ -5703,6 +5720,10 @@ int __init cgroup_init(void)
 
        mutex_unlock(&cgroup_mutex);
 
+       /* Apply an implicit disable unless it is explicitly enabled */
+       if (!cgroup_is_enabled("memory"))
+               cgroup_disable("memory");
+
        for_each_subsys(ss, ssid) {
                if (ss->early_init) {
                        struct cgroup_subsys_state *css =
@@ -6249,6 +6270,30 @@ static int __init cgroup_disable(char *str)
 }
 __setup("cgroup_disable=", cgroup_disable);
 
+static int __init cgroup_enable(char *str)
+{
+       struct cgroup_subsys *ss;
+       char *token;
+       int i;
+
+       while ((token = strsep(&str, ",")) != NULL) {
+               if (!*token)
+                       continue;
+
+               for_each_subsys(ss, i) {
+                       if (strcmp(token, ss->name) &&
+                           strcmp(token, ss->legacy_name))
+                               continue;
+
+                       cgroup_enable_mask |= 1 << i;
+                       pr_info("Enabling %s control group subsystem\n",
+                               ss->name);
+               }
+       }
+       return 1;
+}
+__setup("cgroup_enable=", cgroup_enable);
+
 void __init __weak enable_debug_cgroup(void) { }
 
 static int __init enable_cgroup_debug(char *str)
```

**Comment by pelwell** [comment]
I came up with this:
```diff
diff --git a/kernel/cgroup/cgroup.c b/kernel/cgroup/cgroup.c
index 3a0161c21b6b..d159dd2f6ca4 100644
--- a/kernel/cgroup/cgroup.c
+++ b/kernel/cgroup/cgroup.c
@@ -5750,6 +5750,9 @@ int __init cgroup_init_early(void)
        return 0;
 }
 
+static u16 cgroup_enable_mask __initdata;
+static int __init cgroup_disable(char *str);
+
 /**
  * cgroup_init - cgroup initialization
  *
@@ -5788,6 +5791,12 @@ int __init cgroup_init(void)
 
        mutex_unlock(&cgroup_mutex);
 
+       /*
+        * Apply an implicit disable, knowing that an explicit enable will
+        * prevent if from doing anything.
+        */
+       cgroup_disable("memory");
+
        for_each_subsys(ss, ssid) {
                if (ss->early_init) {
                        struct cgroup_subsys_state *css =
@@ -6371,6 +6380,10 @@ static int __init cgroup_disable(char *str)
                            strcmp(token, ss->legacy_name))
                                continue;
 
+                       /* An explicit cgroup_enable overrides a disable */
+                       if (cgroup_enable_mask & (1 << i))
+                               continue;
+
                        static_branch_disable(cgroup_subsys_enabled_key[i]);
                        pr_info("Disabling %s control group subsystem\n",
                                ss->name);
@@ -6389,6 +6402,30 @@ static int __init cgroup_disable(char *str)
 }
 __setup("cgroup_disable=", cgroup_disable);
 
+static int __init cgroup_enable(char *str)
+{
+       struct cgroup_subsys *ss;
+       char *token;
+       int i;
+
+       while ((token = strsep(&str, ",")) != NULL) {
+               if (!*token)
+                       continue;
+
+               for_each_subsys(ss, i) {
+                       if (strcmp(token, ss->name) &&
+                           strcmp(token, ss->legacy_name))
+                               continue;
+
+                       cgroup_enable_mask |= 1 << i;
+                       pr_info("Enabling %s control group subsystem\n",
+                               ss->name);
+               }
+       }
+       return 1;
+}
+__setup("cgroup_enable=", cgroup_enable);
+
 void __init __weak enable_debug_cgroup(void) { }
 
 static int __init enable_cgroup_debug(char *str)
```

**Comment by ncopa** [comment]
@pelwell Yeah, that looks better :+1:

**Comment by ncopa** [comment]
on a second though, I'm not sure it work for things like `cgroup_disable=cpu cgroup_enable=cpu`, but I guess it does not matter that much. I'm pretty sure it will work for the `cgroup_enable=memory`.

**Comment by ncopa** [comment]
Doing both should fix that:
```c
                       cgroup_enable_mask |= 1 << i;
                       static_branch_enable(cgroup_subsys_enabled_key[i]);
```

**Comment by pelwell** [comment]
Yes - that should work:
```diff
diff --git a/kernel/cgroup/cgroup.c b/kernel/cgroup/cgroup.c
index 3a0161c21b6b..3fef28ea5f75 100644
--- a/kernel/cgroup/cgroup.c
+++ b/kernel/cgroup/cgroup.c
@@ -5750,6 +5750,9 @@ int __init cgroup_init_early(void)
 	return 0;
 }
 
+static u16 cgroup_enable_mask __initdata;
+static int __init cgroup_disable(char *str);
+
 /**
  * cgroup_init - cgroup initialization
  *
@@ -5788,6 +5791,12 @@ int __init cgroup_init(void)
 
 	mutex_unlock(&cgroup_mutex);
 
+	/*
+	 * Apply an implicit disable, knowing that an explicit enable will
+	 * prevent if from doing anything.
+	 */
+	cgroup_disable("memory");
+
 	for_each_subsys(ss, ssid) {
 		if (ss->early_init) {
 			struct cgroup_subsys_state *css =
@@ -6371,6 +6380,10 @@ static int __init cgroup_disable(char *str)
 			    strcmp(token, ss->legacy_name))
 				continue;
 
+			/* An explicit cgroup_enable overrides a disable */
+			if (cgroup_enable_mask & (1 << i))
+				continue;
+
 			static_branch_disable(cgroup_subsys_enabled_key[i]);
 			pr_info("Disabling %s control group subsystem\n",
 				ss->name);
@@ -6389,6 +6402,31 @@ static int __init cgroup_disable(char *str)
 }
 __setup("cgroup_disable=", cgroup_disable);
 
+static int __init cgroup_enable(char *str)
+{
+	struct cgroup_subsys *ss;
+	char *token;
+	int i;
+
+	while ((token = strsep(&str, ",")) != NULL) {
+		if (!*token)
+			continue;
+
+		for_each_subsys(ss, i) {
+			if (strcmp(token, ss->name) &&
+			    strcmp(token, ss->legacy_name))
+				continue;
+
+			cgroup_enable_mask |= 1 << i;
+			static_branch_enable(cgroup_subsys_enabled_key[i]);
+			pr_info("Enabling %s control group subsystem\n",
+				ss->name);
+		}
+	}
+	return 1;
+}
+__setup("cgroup_enable=", cgroup_enable);
+
 void __init __weak enable_debug_cgroup(void) { }
 
 static int __init enable_cgroup_debug(char *str)
```

**Comment by popcornmix** [comment]
I've reverted, merged 5.10.44 and reapplied the new form of commit.

**Pull request closed without merging**
