### PR TITLE
net: lan78xx: Fix race in tx skb size calculation

### PR DESCRIPTION
**Pull request by lategoodbye**
The skb size calculation in lan78xx_tx_bh is in race with the start_xmit,
which could lead to kernel oopses. So protect the whole skb walk with
a spin lock. As a benefit we can unlink the skb directly.

https://github.com/raspberrypi/linux/issues/2608

### CODE REVIEW

**Comment by JamesH65** [comment]
@lategoodbye Good work. Are you going to send this to netdev for further discussion and upstreaming?

**Comment by lategoodbye** [comment]
Yes, but this will happen next week.

**Comment by pelwell** [comment]
Thanks, gents.

**Comment by lategoodbye** [comment]
Yesterday, i sent the [patch](https://patchwork.ozlabs.org/patch/944086/) to netdev.

**Comment by JamesH65** [comment]
Following on from discussion in linked thread, I seem to be seeing odd behaviour with this patch, with the unplugging of the network cable not being detected. Which makes no sense. Investigating.

**Comment by JamesH65** [comment]
Some minor logging changes indicate that the lan78xx_status function is never called  in the failing case., which would indicate that the interrupt over USB (intr_urb) from the lan78xx is being lost somewhere. Looking at logging in the working case, I get that 'interrupt' every time the cable is removed. However, I cannot think of a sequence invvolving that queue walk that could result in this sort of behaviour.

**Comment by lategoodbye** [comment]
I only want to inform you that this patch has been merged upstream and also go to stable.

**Comment by pelwell** [comment]
Thanks, Stefan. If GitHub had a Super Contributor badge you would get one.

**Pull request merged**
