### PR TITLE
Rpi 6.7.y iommu support

### PR DESCRIPTION
**Pull request by 6by9**
Based the changes on the matching upstream commits, but not tested on hardware yet (it does build now).

### CODE REVIEW

**Comment by 6by9** [comment]
@njhollinghurst FYI

**Comment by njhollinghurst** [comment]
I am surprised that the `count` argument is not used (in the exynos example). It looks like it ought to be important!

**Comment by 6by9** [comment]
> I am surprised that the `count` argument is not used (in the exynos example). It looks like it ought to be important!

The commit text does include
> Trivially update map/unmap to the new interface, which is quite happy for drivers to still process just one page per call.

so I'm assuming it is processing one page per call and hence can ignore `count`.
I was going to try running it today to see if it works.

**Comment by njhollinghurst** [comment]
I see: so that return value suffices to say "I only did one of the pages you asked for"?

Anyway, I think the quick hack / fix-up might be as simple as inserting `bytes *= count;` at the top of the function (since we already have a loop to break the given page size into 4K basic units). That might be more efficient.

I suppose we should handle the (very unexpected) case where only some of the pages fit below `APERTURE_TOP`.

**Comment by 6by9** [comment]
> Anyway, I think the quick hack / fix-up might be as simple as inserting `bytes *= count;` at the top of the function (since we already have a loop to break the given page size into 4K basic units). That might be more efficient.

Probably, I just haven't looked into the API closely enough to determine the detail of it.

**Comment by njhollinghurst** [comment]
Not yet tested... but I might try adding this before `/* large page and write enable flags */`. It doesn't really matter if it goes before or after computing `align`.
```
		/* Handle multiple contiguous pages up to APERTURE_TOP */
		if (bytes && iova + count * bytes > APERTURE_TOP)
			count = (APERTURE_TOP - iova) / bytes;
		bytes *= count;
```
By modifying `bytes` we modify both the loop over `p` and also the return value; hopefully correctly!

**Comment by njhollinghurst** [comment]
I expect the fix-up is fine as it is!  I might try to optimize the count > 1 case at a later date in a separate PR.

**Comment by 6by9** [comment]
Rebased. I'll do a test, but @njhollinghurst has said it works for him.

**Comment by 6by9** [comment]
Checked this tree, and the dlist pointer words include an address up at 0xAxxxxxxxx, which is correct for the iommu virtual address.
libcamera also works, so that checks out RP1 for the CFE, and ISPBE.

I think that makes me happy with this - dropping the Draft tag.

**Comment by njhollinghurst** [comment]
LGTM  (I'll have a go at my subsequent "optimization" later).

**Pull request merged**
