### PR TITLE
V4L2 codec frame rate/timestamp fixes

### PR DESCRIPTION
**Pull request by 6by9**
Should sort the issue reported in https://www.raspberrypi.org/forums/viewtopic.php?f=38&t=240170&p=1465986

Still compile testing in case of bad cherry-pick, hence WIP tag.

### CODE REVIEW

**Comment by 6by9** [comment]
Doh, that serves me right for adding a "trivial" cast that breaks the build.

**Comment by 6by9** [comment]
Build issue fixed.
Good to review now.

**Comment by popcornmix** [comment]
Looks sane to me.
The numerator/denominator swap looked surprising to me, but I guess one uses a frequency base and one uses time base, so it's probably deliberate.

**Comment by 6by9** [comment]
> The numerator/denominator swap looked surprising to me, but I guess one uses a frequency base and one uses time base, so it's probably deliberate.

Correct. V4L2 uses frame interval. MMAL uses frame rate.

**Comment by 6by9** [comment]
Rebased.
Any further comments?

**Comment by 6by9** [comment]
@pelwell Any comments, or can we merge?

**Pull request merged**
