### PR TITLE
allo-boss-dac mute output when changing parameters

### PR DESCRIPTION
**Pull request by alessandromrc**
Since I noticed that sometimes changing sample rates causes some digital quirks and noises, I've changed the function to mute the output before performing the changes and then unmute it when an error occurs or the parameters got set.

Re-opened to add signing and fix all the things mentioned.

### CODE REVIEW

**Comment by pelwell** [comment]
Please remove the trailing whitespace and unnecessary braces, then it will be ready to merge. You can either squash your commits yourself and use `git push --force ...` to update GitHub and this PR, or push it normally as a second commit and we can squash them together in the merge.

**Comment by alessandromrc** [comment]
I guess the action didn't like the sign since it picked up the github email address, will wait for a response, so if there's anything to change I will directly make a new commit with such address and name.

**Comment by alessandromrc** [comment]
I guess the action is still detecting braces wrongly... I think I need to put a space under the goto to make it not see the closing brace

**Comment by pelwell** [comment]
No, it's fine - it's just that the two commits are being checked separately, and the first still contains the braces.

**Comment by alessandromrc** [comment]
I hope this is the run :D

**Pull request merged**
