### PR TITLE
Enable compilation of spi-bcm2835.c from the mainline on a Raspbian Kernel

### PR DESCRIPTION
**Pull request by msperl**
Patch to make it possible to compile the mainline spi-bcm2835.c spi driver on the raspbian kernel, which still does not use device-tree as well as the 2708 Architecture name.

There are some advantages to this code:
- it uses the transfer one message interface and the corresponding "central" queuing mechanism
- the code is much cleaner.

What is still missing:
- the driver currently does not set the alternate functions for the PINs, so one has to load/unload spi-bcm2708 first to set them up
- there is no option to enable real time priorities to the work-queue
- the CS-Polarity bug has not been fixed either...

The last 2 are separate pull requests, so that they can get merged into the mainline as well...

I would also recommend enabling this driver as a module in the default compiles.

Signed-off-by: Martin Sperl kernel@martin.sperl.org

### CODE REVIEW

**Comment by popcornmix** [comment]
I don't use spi, so I'll need to get some input from other spi users.
Is the plan to ship both spi drivers and allow the user to choose which one to enable? (rather than removing the older driver)

**Comment by msperl** [comment]
yes - that is the idea - this way we do not have any compatibility issues.
Anyone who wants to use the newer/faster driver may decide to use it - the default is still there.

Also I will implement the fix for the ChipSelect Polarity bug only in this driver...

Still I would recommend moving to the upstream SPI driver at some point, as it is upstream and the way forward...
But then the patches require "correct" sign-offs to get them applied upstream - or so I have been told...

The alternate pin config is currently "hacked" in like it is in the spi-bcm2708.c driver.
Obviously this needs to get changed, but at least there is no need for load/unload of the bcm2708 driver...

**Comment by msperl** [comment]
Note that there seems to be an issue with the "stock" spi-bcm2708 driver that results in a kernel-panic (and drop into kernel debugger) as soon as a SPI-message gets delivered via an spi_async directly from a interrupt-handler...

The patched spi-bcm-2835.c driver does NOT show this effect!

I hope I find time to rebase this patch soon, so that you can include it more easily...

**Comment by notro** [comment]
@msperl Can you close this please?

**Pull request closed without merging**
