### PR TITLE
Merge v4.14.112 stable release to rpi-4.14.y

### PR DESCRIPTION
**Pull request by pbrkr**
As rpi-4.19.y isn't yet considered stable it's worth continuing to merge stable kernel updates into rpi-4.14.y.

Merge conflict in drivers/i2c/busses/i2c-bcm2835.c is resolved to match the current code in the rpi-4.19.y branch.

Boot tested in 32-bit and 64-bit modes on Raspberry Pi 3 using Yocto Project.

### CODE REVIEW

**Comment by pelwell** [comment]
The idea of bringing the LTS 4.14 branch up-to-date with fixes is find in principal, but I don't like the implementation. Rather than using merge commits to bring in the unmodified 4.14 upstream commits (these aren't back-ports), cherry-picking only those that caused conflicts, you seem to have ended up with a merge of over 1000 cherry-picks - the worst of both worlds.

Is there any chance you could refactor this as outlined above? We could then rebase into rpi-4.14.y, but on the understanding that we haven't tested it.

**Comment by pbrkr** [comment]
@pelwell: These aren't cherry-picks. They're unmodified upstream commits.

Compare https://github.com/raspberrypi/linux/pull/2938/commits/58b454ebf81e5ae9391957d99cf89566d9eec1b1 and https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v4.14.112&id=58b454ebf81e5ae9391957d99cf89566d9eec1b1, the commit hashes are identical.

**Comment by pelwell** [comment]
In that case, where did you resolve the merge conflict?

**Comment by pbrkr** [comment]
In the merge commit itself. I checked out rpi-4.14.y, fetched linux-stable as a remote, did 'git merge v4.14.112', fixed the conflict and committed.

**Comment by pbrkr** [comment]
Running `git show` locally gives sensible output where you can see the merge resolution. The GitHub interface is just a bit dumb.

```
$ git show
commit 8feb0dfcf26f914bc6e76092552293be8bc730c2 (HEAD -> rpi-4.14.y, tag: rpi-4.14.112, origin/rpi-4.14.y, lts/rpi-4.14.y)
Merge: 5f4b16e4a8d6 58b454ebf81e
Author: Paul Barker <paul@betafive.co.uk>
Date:   Wed Apr 17 11:18:06 2019 +0100

    Merge tag 'v4.14.112' into rpi-4.14.y
    
    This is the 4.14.112 stable release
    
    Merge conflict in drivers/i2c/busses/i2c-bcm2835.c is resolved to match
    the current code in the rpi-4.19.y branch.
    
    Signed-off-by: Paul Barker <paul@betafive.co.uk>

diff --cc drivers/i2c/busses/i2c-bcm2835.c
index b7110eb2163e,4d19254f78c8..1426dab2670b
--- a/drivers/i2c/busses/i2c-bcm2835.c
+++ b/drivers/i2c/busses/i2c-bcm2835.c
@@@ -271,9 -189,17 +271,18 @@@ static void bcm2835_i2c_start_transfer(
        bcm2835_i2c_writel(i2c_dev, BCM2835_I2C_A, msg->addr);
        bcm2835_i2c_writel(i2c_dev, BCM2835_I2C_DLEN, msg->len);
        bcm2835_i2c_writel(i2c_dev, BCM2835_I2C_C, c);
 +      bcm2835_debug_add(i2c_dev, ~0);
  }
  
+ static void bcm2835_i2c_finish_transfer(struct bcm2835_i2c_dev *i2c_dev)
+ {
+       i2c_dev->curr_msg = NULL;
+       i2c_dev->num_msgs = 0;
+ 
+       i2c_dev->msg_buf = NULL;
+       i2c_dev->msg_buf_remaining = 0;
+ }
+ 
  /*
   * Note about I2C_C_CLEAR on error:
   * The I2C_C_CLEAR on errors will take some time to resolve -- if you were in
@@@ -382,10 -300,9 +391,13 @@@ static int bcm2835_i2c_xfer(struct i2c_
  
        time_left = wait_for_completion_timeout(&i2c_dev->completion,
                                                adap->timeout);
+ 
+       bcm2835_i2c_finish_transfer(i2c_dev);
+ 
 +      if (debug > 1 || (debug && (!time_left || i2c_dev->msg_err)))
 +              bcm2835_debug_print(i2c_dev);
 +      i2c_dev->debug_num_msgs = 0;
 +      i2c_dev->debug_num = 0;
        if (!time_left) {
                bcm2835_i2c_writel(i2c_dev, BCM2835_I2C_C,
                                   BCM2835_I2C_C_CLEAR);
```

**Comment by pelwell** [comment]
I apologise - the combination of (as you say) GitHub showing EVERYTHING in the merge commit, and me being unable to find the merged commits in either GitHub or my local repo (due to not tracking stable) lead me to jump to the wrong conclusion.

This is indeed a fine commit, implemented as cleanly as possible.

**Comment by pbrkr** [comment]
No problem - All projects should have sceptical maintainers :)

**Comment by stefson** [comment]
has the memory leak been closed in recent 4.19 branch? If not, going for another bump would be great; sadly can't do it on my own because v113 introduced a compile error which is def above my level of expertise to deal with.

**Comment by pbrkr** [comment]
@stefson: I'll give it a look.

**Comment by pbrkr** [comment]
@stefson: See PR #2947.

**Comment by stefson** [comment]
great, compile works now :)

**Pull request merged**
