### PR TITLE
config: Enable CONFIG_MODULE_COMPRESS_XZ

### PR DESCRIPTION
**Pull request by popcornmix**
See: https://github.com/raspberrypi/linux/issues/4966
Signed-off-by: Dom Cobley <popcornmix@gmail.com>

### CODE REVIEW

**Comment by popcornmix** [comment]
On a Pi1
systemd-analyze
No compression:
```
Startup finished in 9.652s (kernel) + 1min 17.366s (userspace) = 1min 27.019s 
multi-user.target reached after 1min 2.625s in userspace
```
xz compression:
```
Startup finished in 9.655s (kernel) + 1min 5.989s (userspace) = 1min 15.645s 
multi-user.target reached after 1min 2.890s in userspace
```

**Comment by popcornmix** [comment]
On a Pi4
systemd-analyze
No compression:
```
Startup finished in 6.706s (kernel) + 14.687s (userspace) = 21.394s 
multi-user.target reached after 14.544s in userspace
```
xz compression:
```
Startup finished in 6.695s (kernel) + 16.458s (userspace) = 23.154s 
multi-user.target reached after 15.896s in userspace
```

**Comment by pelwell** [comment]
For Pi 1 that's a win-win, but I don't think people will thank us for making their Pi 4 boot 8% slower.

**Comment by popcornmix** [comment]
Let me run some more tests. This is a nfs boot and there's some variability in the runs.
Specifically a subsequent reboot seems a few seconds faster (possibly file caching on the nfs server?)

**Comment by popcornmix** [comment]
Doing a "best of 3" on pi4, 5.18 kernel, with force_turbo:
None
```
Startup finished in 5.415s (kernel) + 10.784s (userspace) = 16.200s 
multi-user.target reached after 10.624s in userspace
```
xz
```
Startup finished in 5.434s (kernel) + 10.631s (userspace) = 16.066s 
multi-user.target reached after 10.436s in userspace
```
does better (by 1%)

**Comment by popcornmix** [comment]
Doing a "best of 3" on pi4, 5.18 kernel, without force_turbo:
None
```
Startup finished in 6.428s (kernel) + 14.786s (userspace) = 21.214s 
multi-user.target reached after 14.260s in userspace
```
xz
```
Startup finished in 6.446s (kernel) + 14.893s (userspace) = 21.340s 
multi-user.target reached after 14.521s in userspace
```
none is better but only by 1%

**Comment by popcornmix** [comment]
5.15/Turbo/none
```
Startup finished in 5.546s (kernel) + 11.300s (userspace) = 16.847s 
multi-user.target reached after 11.125s in userspace
```
5.15/Turbo/xz
```
Startup finished in 5.565s (kernel) + 11.209s (userspace) = 16.775s 
multi-user.target reached after 10.986s in userspace
```
5.15/No Turbo/none
```
Startup finished in 6.683s (kernel) + 16.306s (userspace) = 22.990s 
multi-user.target reached after 15.798s in userspace
```
5.15/No Turbo/xz
```
Startup finished in 6.716s (kernel) + 16.724s (userspace) = 23.441s 
multi-user.target reached after 16.315s in userspace
````

**Comment by pelwell** [comment]
I guess that's close enough. Shall I clear the draft status and merge it?

**Comment by popcornmix** [comment]
Removed draft. I'll let you merge. We'll keep an eye on any reports arising.

**Pull request merged**
