### PR TITLE
Add support for adt7410 (module and overlay)

### PR DESCRIPTION
**Pull request by aSmig**
The Analog Devices ADT7410 is a high precision temperature sensor with growing popularity. This PR seeks to add the module and overlay.

### CODE REVIEW

**Comment by aSmig** [comment]
File sizes are fairly small:
2.0K    /boot/firmware/overlays/adt7410.dtbo
4.0K    /lib/modules/6.1.61-v8+/kernel/drivers/hwmon/adt7410.ko.xz
4.0K    /lib/modules/6.1.61-v8+/kernel/drivers/hwmon/adt7x10.ko.xz
10.0K   total

**Comment by pelwell** [comment]
This needs a few small changes:
1. Without an entry in overlays/Makefile it won't be compiled and installed.
2. Don't include `CONFIG_SENSORS_ADT7X10=m` to the defconfigs - it is implied by `CONFIG_SENSORS_ADT7410=m`.

Otherwise it looks good.

**Comment by aSmig** [comment]
Thanks for the quick review! How is this? I appreciate the extra help.

**Comment by pelwell** [comment]
Looks good. I'll let the build checks run, squash them down to two commits, and merge offline.

**Comment by pelwell** [comment]
On second thoughts (first thought, if I'm honest), as this is such a simple overlay for an I2C-attached sensor, I'd rather add it to the `i2c-sensor` overlay. There's a new commit that adds `adt7410` as a parameter - does that work for you?

**Comment by aSmig** [comment]
Putting this into i2c-sensor sounds very reasonable. Unfortunately I haven't been successful at testing this approach on my system.

```
$ sudo dtoverlay i2c-sensor adt7410 addr=0x4a
* Failed to apply overlay '0_i2c-sensor' (kernel)
```

The simpler adt7410.dtbo did load successfully. This is new territory for me so I'm not sure how to debug. I also tried loading i2c-sensors,adt7410,addr=0x4a via config.txt with no luck. I must be doing something wrong when compiling the i2c-sensor overlay, so here are my steps:

 ```
wget https://raw.githubusercontent.com/raspberrypi/linux/5f9c19e21de5ed2a57d5560698a4ce2440518f62/arch/arm/boot/dts/overlays/i2c-sensor-common.dtsi
 cpp -nostdinc -I ~/linux/include -undef -x assembler-with-cpp i2c-sensor-common.dtsi i2c-sensor-common.dtsi.preprocessed
 mv i2c-sensor-common.dtsi.preprocessed i2c-sensor-common.dtsi
 cp ~/linux/arch/arm/boot/dts/overlays/i2c-sensor-overlay.dts .
 dtc -O dtb i2c-sensor-common.dtsi -o i2c-sensor.dtbo
 sudo cp i2c-sensor.dtbo /boot/overlays/
```

If you are confident that everything is fine and will just work with a complete kennel build, no need to help me troubleshoot my broken testing process. I'll trust you. Thanks again for your work!

**Comment by pelwell** [comment]
There was an unwanted underscore in one of the labels, which then ended up being undefined. I've tested and pushed a modified version. Until recently the dtoverlay command (not the config.txt directive) would fail because it lacked support for the newer overlay features - that should all be fixed in the latest version - but I think the i2c-sensor overlay is sufficiently simple that it would work even with older installs.

**Comment by pelwell** [comment]
By the way, I would have written your compilation step like this:
```
dtc -@ -Hepapr -I dts -O dtb -o i2c-sensor.dtbo i2c-sensor-overlay.dts
```
Some of the difference are cosmetic or nice-to-haves, but some of them (the `-@`, using the correct source file) are not.

**Comment by aSmig** [comment]
This is great, thanks! Your updated i2c-sensor-common.dtsi is working on my system when compiled correctly, thanks for the tips. Don't we still need CONFIG_SENSORS_ADT7410=m added to the configs?

**Comment by pelwell** [comment]
You're right - commit 057e09bbfd357 added.

**Comment by aSmig** [comment]
Perfect. Thank you so much!

**Pull request merged**
