### PR TITLE
net:broadcom Set Ethernet LED modes via dt

### PR DESCRIPTION
**Pull request by JamesH65**
Pulls in a patch from 5.3, then adds the DT setting of LED modes over the top.

### CODE REVIEW

**Review by pelwell — CHANGES_REQUESTED** [review]
This looks generally OK - it's just the README that needs changing.

1. The existing `eth_*` and `eee` dtparams are currently 3B+-specific.
2. The LED defaults are board-specific.

**Comment by pelwell** [comment]
That looks better. There's a minor capitalisation difference on 3B+, but otherwise I'm happy to merge once you've removed the `RFC:` tag.

**Comment by JamesH65** [comment]
Cannot figure out how to flag the changes as all done, but changes are all done.

**Comment by pelwell** [comment]
Except for the capitalisation of "Pi3b+".

**Comment by JamesH65** [comment]
Ah, found it. Done.

**Comment by pelwell** [comment]
The changes look good, but GitHub doesn't allow me to squash some commits and not others - it's all or nothing. Can you do the honours?

**Comment by JamesH65** [comment]
Ah, bugger, I edited that change in using github, so it gone in as an extra commit rather than an amend. Will need to figure out how to fix that.

**Comment by JamesH65** [comment]
Looks like a forced push of the change has sorted it out.

**Review by pelwell — APPROVED** [review]

**Pull request merged**
