### PR TITLE
Add SND_RAWMIDI Kconfig selects dep to SND_PISOUND

### PR DESCRIPTION
**Pull request by simonvanderveldt**
Fixes part of #2366

### CODE REVIEW

**Comment by pelwell** [comment]
Can you add a slightly-less-minimal commit message? Even just:
```
See: https://github.com/raspberrypi/linux/issues/2366
```
would be better. Include a "Signed-off-by: " line as well.

**Comment by simonvanderveldt** [comment]
@pelwell Sure :) I've amended the commit.

**Comment by simonvanderveldt** [comment]
@pelwell Thanks!
Small question: Do the changes in the 4.9.x branch get pulled into the other branches automatically?

**Comment by pelwell** [comment]
No, but we try not to let them escape.

**Comment by simonvanderveldt** [comment]
@pelwell Ok, thanks for the info! I'll keep an eye on them then :)

**Pull request merged**
