### PR TITLE
Add overlay and enable support for QCA7000 board

### PR DESCRIPTION
**Pull request by mhei**
The Qualcomm QCA7000 is Homeplug Green PHY powerline chipset for the Internet of Things. It is
connected to a CPU via SPI bus. The Evaluation Board "PLC Stamp micro" (built and distributed
by I2SE) embeds this chip. It also comes with a connector compatible with Raspberry Pi.

This patch set adds a new device tree overlay which can be used with this board and enables the required QCA7000 driver module in the default configurations.

Signed-off-by: Michael Heimpold mhei@heimpold.de

### CODE REVIEW

**Comment by pelwell** [comment]
If you add a section to the overlays/README file, being careful to observe and copy the existing formatting, then squash down to one commit, I'll merge it.

**Comment by mhei** [comment]
Hi @pelwell, thanks for your feedback. I updated the branch, please have a look. Thanks.

**Comment by pelwell** [comment]
Why doesn't the README describe the parameters?

**Comment by mhei** [comment]
Thanks for your patience. I simply overlooked it - seems to be not my day for sending PRs :smile:

**Pull request merged**
