### PR TITLE
Vchiq cache

### PR DESCRIPTION
**Pull request by pelwell**
This series of commits gives the vchiq driver the ability to discern the
correct cache_line_size value in the absence of the cache-line-size
property. The correction of the reg size value doubles as a hint to
the firmware that the kernel includes the updated value.

See: https://github.com/raspberrypi/linux/issues/2643

Signed-off-by: Phil Elwell <phil@raspberrypi.org>

### CODE REVIEW

**Comment by pelwell** [comment]
A preview firmware release that implements the new logic can be downloaded here: https://drive.google.com/file/d/13c66cJkNmCQFMd7_f3GNA_tk5usoK0ZW/view?usp=sharing

**Comment by HiassofT** [comment]
Thanks a lot!

Testing on RPi3B+ with the preview firmware worked fine - tvservice -m showed correct lists of modes.

When using the current official firmware I got a corrupted mode list with this PR - but I guess this is to be expected?

**Comment by pelwell** [comment]
Yes it is. The current firmware assumes that a lack of `cache-line-size` property (strictly, a lack of `cache_line_size` parameter) means it is a very old BCM2835 kernel and therefore requires a 32 byte cache line. I could improve backwards compatibility on a downstream kernel/DTB by retaining a `cache_line_size` parameter that does nothing...

**Comment by pelwell** [comment]
The DT commit has been updated to retain a vestigial `cache_line_size` parameter, which should keep old firmware happy.

**Comment by HiassofT** [comment]
thanks, the updated version works fine with the August 24 firmware

**Comment by mkreisl** [comment]
Confirmed, 4.18.5 works with older firmware (Jul 23)

**Pull request merged**
