### PR TITLE
Cherry-pick Unicam and IMX477 patches

### PR DESCRIPTION
**Pull request by 6by9**
These patches were apparently missed in the rebase. This does mean that the unicam patches are in a slightly different order to earlier branches, but that's not a real problem.

### CODE REVIEW

**Comment by popcornmix** [comment]
I assume unicam is working? Fine by me.

**Comment by 6by9** [comment]
Yes, it was largely working anyway but with a couple of quirks due to the missing patches (I couldn't selected the unpacked bayer formats for example).
IMX477 being totally missing of course meant the HQ camera didn't work!

**Comment by 6by9** [comment]
We do appear to have lost CONFIG_VIDEO_IMX477=m from bcm2711_defconfig though. It's still in 2709 and rpi, and the 64bit configs.

**Comment by popcornmix** [comment]
bcm2711_defconfig was regenerated with make defconfig, so if that option wasn't in tree at the time it would have been removed.

**Pull request merged**
