### PR TITLE
imx296-overlay: clock-frequency defaults to 54MHz but can be overridden

### PR DESCRIPTION
**Pull request by njhollinghurst**

### CODE REVIEW

**Comment by 6by9** [comment]
I'll beat pelwell to saying that the override needs documenting in the README entry.
Otherwise it looks OK to me.

**Comment by pelwell** [comment]
Too late - I said it verbally 10 minutes ago. 8-)

**Comment by njhollinghurst** [comment]
Documented and squashed

**Comment by pelwell** [comment]
and merged.

**Pull request merged**
