### PR TITLE
rpi-5.4.y Update imx219 driver to the version accepted upstream.

### PR DESCRIPTION
**Pull request by 6by9**
Reverts the currently merged version first, then adds the new version.
One small fixup required to the DT overlay which is done as a separate patch.

### CODE REVIEW

**Comment by 6by9** [comment]
@naushir FYI Merging the newer version of this driver.

**Comment by popcornmix** [comment]
Looks like it a needs a rebase.
Always happy to switch to upstream versions of files, so merge if you've seen it working.

**Comment by 6by9** [comment]
Needs a rebase? I see 5 commits and Github reporting no conflicts.

Yes, I've proved it works (although that needs the unicam driver which we haven't merged here yet).

**Comment by naushir** [comment]
Unicam PR is at https://github.com/raspberrypi/linux/pull/3475.  Still needs reviewing and possibly some updates pending my staggered write investigations.

**Pull request merged**
