### PR TITLE
Added CONFIG_JUMP_LABEL=y to defconfigs

### PR DESCRIPTION
**Pull request by Ferroin**
This gives a generic performance boost to numerous parts of the kernel.
Even though this makes compile times slightly longer, native builds on
kernels with this running are faster than building without this option
on the official kernels.

### CODE REVIEW

**Comment by popcornmix** [comment]
Sound interesting.
Can you report any benchmarks that are improved with this change?

**Comment by Ferroin** [comment]
Networking latency is slightly reduced, my ping times drop from ~0.900ms to ~0.480ms with this enabled.  True benchmarking though is kind of tricky because this only directly affects some parts of the kernel code.  I also notice that many of the programs that I use that make lots of syscalls are faster with this enabled, disk I/O latency is slightly improved as well.

**Comment by Ferroin** [comment]
Just finished a bit more testing, boot times are reduced by about half a second on my current setup.
I realize of course that this probably isn't a major improvement, but on a low power system like the Pi, every little bit helps.

**Comment by popcornmix** [comment]
How about iperf?
Any affect on kernel size, or free memory after boot?
Are you aware of anything that runs slower?

**Comment by Ferroin** [comment]
Don't know if anything runs slower or not, I don't think so though.
I can check on iperf, but would need to install it first...
Free memory is about 4k less, kernel size is about 3k more uncompressed (less than 1k increase in zImage), difference is due to kernel memory size needing to be a multiple of page size.

**Comment by popcornmix** [comment]
I included this option on all kernel trees in last update. Thanks for suggestion.

**Comment by Ferroin** [comment]
I'm glad to provide what help I can.

**Pull request closed without merging**
