### PR TITLE
Add firmware driver

### PR DESCRIPTION
**Pull request by notro**
This makes the new firmware driver API available that will replace the old mailbox API.
bcm2835-mailbox will land in v4.2, and the firmware driver will probably land in v4.3

Tested on Pi1 and Pi2 with and without Device Tree + ARCH_BCM2835.

### CODE REVIEW

**Comment by notro** [comment]
I have rebased and removed the one-process-at-a-time restriction on opening /dev/vcio.

**Comment by popcornmix** [comment]
With the PR:
`
pi@raspberrypi:~ $ ls -l /dev/vcio
crw------- 1 root root 249, 0 Jan  1  1970 /dev/vcio
`
It should look like:
`
pi@raspberrypi:~ $ ls -l /dev/vcsm
crw-rw---T 1 root video 246, 0 Jan  1  1970 /dev/vcsm
`
So pi user can use it without root privileges.
That appears with:
/lib/udev/rules.d/10-local-rpi.rules:SUBSYSTEM=="bcm2708_vcio", GROUP="video", MODE="0660"
I guess the SUBSYSTEM name has changed with this PR?

**Comment by notro** [comment]
You're right. This change:

```
SUBSYSTEM=="vcio", GROUP="video", MODE="0660"
```

gave me:

```
$ ls -l /dev/vcio
crw-rw---T 1 root video 249, 0 Jan  1  1970 /dev/vcio

```

**Comment by notro** [comment]
When we have changed all the mailbox clients and can remove bcm2708_vcio, I beleive we can add a MODULE_ALIAS("bcm2708_vcio"); to the vcio module to keep it from breaking userspace until it's fixed there.

**Comment by popcornmix** [comment]
So can the MODULE_ALIAS("bcm2708_vcio") be added to this PR?

**Comment by notro** [comment]
Sorry, I didn't know what I was talking about. MODULE_ALIAS can't be used for this.
I have updated with this change that makes it work:

``` diff
-       /* create sysfs entries */
-       vcio.class = class_create(THIS_MODULE, "vcio");
+       /*
+        * Create sysfs entries
+        * 'bcm2708_vcio' is used for backwards compatibility so we don't break
+        * userspace. Raspian has a udev rule that changes the permissions.
+        */
+       vcio.class = class_create(THIS_MODULE, "bcm2708_vcio");
```

**Comment by popcornmix** [comment]
Can you rebase. We've bumped to 4.1.1 and the configs commit is already in.

**Comment by notro** [comment]
Rebased

**Comment by popcornmix** [comment]
From here: http://marklomas.net/ch-egg/native/native.htm

```
wget http://marklomas.net/ch-egg/downloads/ch-egg-port-sdl-source_v1_1.zip
unzip ch-egg-port-sdl-source_v1_1.zip 
cd ch-egg-port-sdl-source_v1.1/ch-egg/bbcb
gcc -Os -I/usr/include/SDL -c sound.c mode2font.c r6502main.c
ar cr libbbcb.a sound.o r6502main.o mode2font.o
cd ..
gcc -Os -I/usr/include/SDL -I../ execute.c library.c main.c -Lbbcb -lbbcb -lSDL -lm
mv a.out ../ch-egg.elf
```

(there is a build script but it seems a little broken).

**Comment by notro** [comment]
I only get a blank display:

```
$ sudo rpi-update && sudo reboot

$ uname -a
Linux raspberrypi 4.0.7+ #801 PREEMPT Tue Jun 30 18:15:24 BST 2015 armv6l GNU/Linux

$ ./ch-egg-port-sdl-source_v1.1/ch-egg.elf

```

strace log: https://gist.githubusercontent.com/notro/fb0b2a960b6c83197edd/raw/gistfile1.txt

**Comment by popcornmix** [comment]
Yes, something is broken, I'll have a look...

**Pull request merged**
