### PR TITLE
Fix VC4 DRM memory leak 

### PR DESCRIPTION
**Pull request by kaegoorn**

### CODE REVIEW

**Comment by popcornmix** [comment]
Has this come from upstream?

**Comment by kaegoorn** [comment]
Yes, this fix of a simple misprint.
Memory leaking while swap frame to 512 bytes.

**Comment by popcornmix** [comment]
But did you create this fix, or did this some from the upstream kernel tree?
If it didn't come from upstream kernel tree, then it should be submitted there first (and we'll cherry-pick it).

**Comment by lategoodbye** [comment]
I didn't find any similiar patch on dri-devel or in kernel-next.

@lom2k Could you please send a bug report plus this patch to Eric Anholt and dri-devel?

**Comment by anholt** [comment]
@lom2k Could you send the patch with a signed-off-by line to dri-devel?  That way I can get you proper attribution, and we can merge downstream.

**Comment by Ruffio** [comment]
@lom2k what is the status on this one? Have you send to dri-devel?

**Comment by pelwell** [comment]
Fixed in https://github.com/raspberrypi/linux/pull/1677.

**Pull request closed without merging**
