### PR TITLE
Support for cheap Ralink 3070 WiFi plug

### PR DESCRIPTION
**Pull request by martinlbb**
Support for Ralink Media Tek cheap Ralink 3070 WiFi Plug.

Incorrect detection of 3070 chipset.

See http://www.geekamole.com/2013/rt2800usb-fix-for-ralinkmediatek-3070-gentoo-linux/

### CODE REVIEW

**Comment by popcornmix** [comment]
Please close #322 and on branch patch-2 do:
`git add drivers/net/wireless/rt2x00/rt2800.h 
git commit --amend
git push -f`
This PR will update with other file.

**Comment by martinlbb** [comment]
Ok, I did it. I close #322 and group needed files in the same commit.

Thanks for your help :)

**Comment by popcornmix** [comment]
I suggest "git commit --amend" which would squash the commits together.
Do a 
`git rebase -i HEAD~2`
and squaash the second commit into first, then "git push -f"

**Comment by shalecraig** [comment]
Can someone figure out if this should be merged?

I'd love to use my 3070 without having to compile the kernel myself.

I'd be happy to rebase this myself if you want.

**Comment by popcornmix** [comment]
I'm waiting for @martinlbb to squash the commits together.
The first commit doesn't build without the second, so breaks git bisect, for example.

**Comment by shalecraig** [comment]
Understood/agreed.

I'd love to use my 3070 with raspberry pi (without needing to compile it myself). If it isn't updated by the end of Sunday, would you accept a new pull request that does this?

I haven't built it locally, and I _trust_ @martinlbb's change works. I'd just rather that it's in Raspbian.

**Comment by martinlbb** [comment]
Dear all,

I was stuck on commit/mixing process. Using both git and web service 
conducted changes to be a big mess :(

My goal was to share an easy and proved fix, using web site.

Feel free to launch a new pull request (and delete mine), if it can help.

Sorry for all,

Martinlbb

**Comment by popcornmix** [comment]
Added here:
https://github.com/raspberrypi/linux/commit/876ddb40b773c8e29583cb9ec6946b6b5f3d1179
Please try rpi-update and test it works.

**Comment by shalecraig** [comment]
I've run `rpi-update` with no arguments, but I'm not sure how to verify that I have your change.

Based on `ifconfig` not showing any new interfaces, and `iw list` returning nothing at all, I don't think I have it.

For what it's worth, `uname -r` returns `3.6.11+`.

**Comment by martinlbb** [comment]
I all,

I've done a rpi-update.
uname -a:
pi 3.6.11+ #538 PREEMPT Fri Aug 30 20:42:08 BST 2013 armv61

After reboot, I recheck (rpi-update told me firmware is up to date).

But, it's the same error (Invalid chipset 0x3070).

dmesg output following:
bcm2708_spi bcm2708_spi.0: master is unqueued, this is deprecated.
bcm2708_spi bcm2708_spi:0: SPI Controller at 0x20204000 (irq 80)
cfg80211: Calling CRDA to update world regulatory domain
phy0 -> rt2800_init_eeprom: Error - Invalid chipset 0x3070 detected.
phy0 -> rt2x00lib_prove_dev: Error - Failed to allocate device.

All the best,

Martinlbb

**Comment by popcornmix** [comment]
The latest firmware contains this patch:
https://github.com/raspberrypi/linux/commit/876ddb40b773c8e29583cb9ec6946b6b5f3d1179

which looks like this PR to me. Perhaps this PR isn't sufficient?

**Comment by shalecraig** [comment]
Good News Everyone!

I just ran `rpi-update`, and `iw list` returns a ton of stuff.

Based on a quick look, I think that `rpi-update` pulls from compiled (weekly?) builds on another repo.

**Comment by dennisjanssen** [comment]
Any way to test this on Raspbmc as well? I can't seem to run rpi-update.

**Comment by martinlbb** [comment]
Confirmed :)

I did a rpi-update, and it work oob :)

Adapter is recognize, and fully working (tested with WPA PSK network).

Perfect :)

Shalecraig: you are right, it seems that there is some delay between git 
commit and rpi-update availability.

If you're okay, I'll update RPi_USB_Wi-Fi_Adapters wiki page on elinux.

Martinlbb
PS: thanks popcornmix to handle this :)

**Pull request closed without merging**
