### PR TITLE
Accelerate framebuffer copyarea function with DMA and add ioctl to access it from userspace

### PR DESCRIPTION
**Pull request by ssvb**
It is a faster windows dragging and scrolling enabler for the X server. More details and some discussion can be found in the forum: http://www.raspberrypi.org/phpBB3/viewtopic.php?p=371531#p371531

I believe that these patches are reasonably clean and ready for use. But would be glad to fix/update them as seen necessary, hence posting for early review.

### CODE REVIEW

**Comment by popcornmix** [comment]
Looks interesting. I'll give it a test.
Do you have instructions to make it work with X (e.g. prebuilt https://github.com/ssvb/xf86-video-sunxifb)?

**Comment by asb** [comment]
There's some suggested "general" instructions in
https://github.com/ssvb/xf86-video-sunxifb/issues/10

**Comment by ssvb** [comment]
Yes, the instructions provided by @hglm at https://github.com/ssvb/xf86-video-sunxifb/issues/10 work fine for raspbian. The compile time is not a problem, because there are really few sources (configure step is the most time consuming). You just need to get the right branch for testing (with the copyarea support added):

   git clone -b rpi-fb-copyarea-20130617 git://github.com/ssvb/xf86-video-sunxifb.git

And IMHO it is cleaner to copy the xorg.conf file to /etc/X11/xorg.conf as the final step. Once the system is rebooted, have a look into "/var/log/Xorg.0.log", it should have the following line:

   [    26.125](II) SUNXIFB(0): enabled fbdev copyarea acceleration

Regarding the default raspbian software. LXTerminal is using 32bpp color depth and is relatively slow (run "xwininfo", select a window, click on it, and get all the interesting information about the used visual and color depth). Debian Reference in Dillo gets the most benefits (both dragging its window and also scrolling the text inside of the browser window is accelerated). Midori gets fast window dragging, but unfortunately no scrolling acceleration.

Also geany (not installed in raspbian by default) is an interesting application, it gets some speedup from the hardware scrolling, but still needs some optimizations to make it really smooth.

**Comment by hglm** [comment]
I think it should also be mentioned that this feature has an important side effect, namely that for console (non-X) framebuffer scrolling, the kernel also starts using the DMA accelerated CopyArea function, as mentioned in the forum thread, because it detects a hardware accelerated CopyArea function is available.

It seems that at the moment DMA based console scrolling is as fast or a little faster than the normal CPU "imageblit" method, which uses the CPU to write the text bitmaps to the framebuffer. However, this is also due to the (somewhat unexpectedly) relatively unoptimized nature of the kernel fb imageblit functions defined in drivers/video/cfbimgblt.c. I have implemented a fairly straightforward optimization to this function, which makes console text writing/scrolling 50-70% faster on the Allwinner platform (I am in the process of testing this on the RPi, where the gain might be even greater). If confirmed, this may result in DMA based console scrolling being slower than the optimized CPU blit method,

So in short, unless the waiting for DMA function completion is implemented using IRQ instead of busy-waiting, the relative merit of using DMA for framebuffer console scrolling may not yet be fully established for all cases, and it may be wise to make this side-effect optional instead of automatic or at least make it possible to disable it. This only concerns this side-effect, the utilization in the X driver is of course a big win in every way.

Edit: On the RPi with the standard 8x16 font, I am seeing a speed-up of 40% at 16bpp and 50% at 32bpp. The patch is available as https://github.com/hglm/patches/blob/master/kernel-cfbimageblt.patch. Note that this patch is not RPi specific and can help a wide range of devices. Also note that the patch is independent from the DMA CopyArea implementation discussed here and can be complimentary to it; when not used for scrolling it will still be used for any other text writing on the console framebuffer. I may do a pull request later after some more testing.

**Comment by popcornmix** [comment]
Have you tried making DMA wait on an IRQ? It should be straightforward.

**Comment by ssvb** [comment]
> Have you tried making DMA wait on an IRQ? It should be straightforward.

Not yet. I spent the last few days trying to decide which ioctl API to use (the existing dmaer module, the module which provides sunxi g2d emulation or entirely new module) before leaning to the standard framebuffer copyarea implementation. Then it took a bit of time to figure out the "one more row than asked" issue for the 2D DMA transfers. Then experiment with the performance settings (channel 0, burst size, etc.). Then for the copyarea function I tried to investigate why it happens to be not used for the framebuffer console right after the start of the system (apparently logo related). The list of "interesting things to look into" kept accumulating and in the end I just decided to leave out IRQ and some other performance tweaks for a bit later. Otherwise it would take more time before I had something ready for testing.

One more reason not to have IRQ wait added right from the start is stability testing. There are some rumors in the forum (or maybe confirmed problems) which correlate SD card corruption with the use of DMA. We probably need to run some heavy stress tests involving simultaneous use of DMA copyarea and some disk activity to see if anything breaks. Also now I wonder if there is enough locking around copyarea as it is obviously non-reenterant.

**Comment by ssvb** [comment]
@hglm _I have implemented a fairly straightforward optimization to this function, which makes console text writing/scrolling 50-70% faster on the Allwinner platform (I am in the process of testing this on the RPi, where the gain might be even greater)_

I like when people don't miss possible optimization opportunities and do fair evaluation of alternative solutions. Looking forward to see your patches (maybe as a separate git branch / pull request).

**Comment by popcornmix** [comment]
I've built and have:

```
$ ls -l /usr/lib/xorg/modules/drivers/
total 280
-rw-r--r-- 1 root root  18688 May 22  2012 fbdev_drv.so
-rwxr-xr-x 1 root root    955 Jun 19 13:10 sunxifb_drv.la
-rwxr-xr-x 1 root root 261339 Jun 19 13:10 sunxifb_drv.so
```

and have:

```
$ cat /etc/X11/xorg.conf
# This is a minimal sample config file, which can be copied to
# /etc/X11/xorg.conf in order to make the Xorg server pick up
# and load xf86-video-sunxifb driver installed in the system.
#
# When troubleshooting, check /var/log/Xorg.0.log for the debugging
# output and error messages.
#
# Run "man sunxifb" to get additional information about the extra
# configuration options for tuning the driver.

Section "Device"
        Identifier      "Allwinner A10/A13 FBDEV"
        Driver          "sunxifb"
        Option          "fbdev" "/dev/fb0"
EndSection
```

I've rebooted and ran startx. But:

```
$ cat  "/var/log/Xorg.0.log" |grep SUN
$ cat  "/var/log/Xorg.0.log" |grep enabled
[   117.105] (==) AIGLX enabled
[   117.392] (==) FBDEV(0): DPMS enabled
[   117.395] (==) RandR enabled
```

http://pastebin.com/4X4TkxjZ

**Comment by ssvb** [comment]
@popcornmix This is strange. Yesterday I tried these step-by-step instructions with the freshly installed 2013-05-25-wheezy-raspbian.img image and it worked. Maybe you have a higher priority config file somewhere in the system, which enforces the use of fbdev driver? It may make sense to check /usr/share/X11/xorg.conf.d/ directory.

**Comment by hglm** [comment]
```
[   116.833] (==) Using config file: "/etc/X11/xorg.conf"
[   116.839] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
```

Looks like the config files in /usr/share/X11/xorg.conf.d take precedence over /etc/X11/xorg.conf. I just tested it. Deleting any /usr/share/X11/xorg.conf.d/99-*.conf file works, or copying /etc/X11/xorg.conf to /usr/share/X11/99-sunxifb.conf.

**Comment by popcornmix** [comment]
I've removed
/usr/share/X11/xorg.conf.d/01-fbdev-rpi.conf
(which I think came from testing teh_orph's accelerated driver) and the log looks better:
http://pastebin.com/5kL3JPrn

I get the "SUNXIFB(0): enabled fbdev copyarea acceleration" line.

Dragging windows seems pretty smooth.

**Comment by popcornmix** [comment]
I've added a flag to dma driver to request bulk channel (i.e. dma channel 0)
https://github.com/raspberrypi/linux/commit/5516fc22be28d00b719015e907514e5ec4f21a00

Can you update PR to use that channel, and adjust the burst length down:
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=63&t=45746&start=25#p372890

**Comment by popcornmix** [comment]
@hglm 
I've tested your cfbimageblt patch and it seems fine. Do you want to PR it?

**Comment by hglm** [comment]
@popcornmix 

OK, I'll make a pull request for it.

**Comment by asb** [comment]
Fwiw, there's a start at dmaengine support in
https://github.com/koalo/linux/commit/b1574ea9d4f08007e53f16ed7673b62905c26ece
(used by the ALSA ASoC patch
http://blog.koalo.de/2013/05/i2s-support-for-raspberry-pi.html). lp0
also added some sort of support
https://github.com/lp0/linux/blob/rpi-linear/drivers/dma/bcm2708_dma.c

**Comment by popcornmix** [comment]
@ssvb 
Can you update PR to use channel 0, and adjust the burst length down:
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=63&t=45746&start=25#p372890

Currently this PR causes lockups.

**Comment by popcornmix** [comment]
This has been cherry-picked into 3.12 kernel.

**Pull request closed without merging**
