### PR TITLE
rtl8192cu port from https://github.com/pvaret/rtl8192cu-fixes

### PR DESCRIPTION
**Pull request by fran6co**
Ports the changes

### CODE REVIEW

**Comment by popcornmix** [comment]
I assume you have tested this and it works fine on Pi? Any observed change in behaviour?
@MrEngman any comments?

**Comment by fran6co** [comment]
Closing for now, I'll recreate the PR using git apply to honor the original commiters.

**Comment by popcornmix** [comment]
You don't have to create a new PR.
Just fixup your rtl branch to look correct locally, then `git push -f` and this PR will update.

**Comment by fran6co** [comment]
Sorry about that, I didn't knew when I was going to have some time to actually do it that's why I closed it.

**Pull request closed without merging**
