### PR TITLE
Xin Mo Dual Controller

### PR DESCRIPTION
**Pull request by VladislavVesely**
Noget and multi input fix for Xin Mo Dual arcade controller.

### CODE REVIEW

**Comment by popcornmix** [comment]
Has this patch been submitted upstream?
http://kernelnewbies.org/UpstreamMerge/SubmittingPatches

**Comment by VladislavVesely** [comment]
Oh sorry i did not know how this works. This is my first time fixing something in kernel, so no. It was not.

**Comment by popcornmix** [comment]
In general if a kernel patch is not pi specific, it should be submitted upstream. Once accepted we can cherry-pick it.

We want to avoid keeping a large number of custom patches in our linux tree that haven't been reviewed by the upstream kernel maintainers.

And if you submit it upstream, then all linux platforms benefit, rather than just pi users.

**Comment by clownfish360** [comment]
How do we submit this to get is fixed?  I have the same issue that needs to be fixed.

**Comment by joolswills** [comment]
did this get submitted upstream ? Please could someone provide a link.

**Comment by P33M** [comment]
Closing as no activity from OP. Submit the patch upstream (link provided in this thread) and once it's accepted then we can cherry-pick to whichever stable branch that needs it.

**Pull request closed without merging**
