### PR TITLE
media: i2c: imx477: Extend support to include the imx378 sensor

### PR DESCRIPTION
**Pull request by davidplowman**
The Sony imx378 is very nearly identical to the im477 and with a very
small number of extra register writes can share the same driver.

Signed-off-by: David Plowman <david.plowman@raspberrypi.com>

### CODE REVIEW

**Comment by davidplowman** [comment]
@6by9 @naushir 
This resolves the problems with the imx378 sensor over the imx477 - do you think what I've done would be "acceptable"?

**Comment by 6by9** [comment]
Do those registers cause issues on IMX477? Could we send them unconditionally?
Does the tuning need to change between them, so is the name important?

If we do need to distinguish between them, then it really ought to be done in device tree in case further deviation is required.
Add an extra compatible string, and add a pointer to a ```struct imx477_variant``` which contains the sensor ID for that variant, and any special registers. The overlay can then include an override on the compatible string, or we have two overlays that include a common back-end

See imx290.c for an example as it handles a mono and colour variant through that route.
imx290-overlay.dts also does almost the above in including imx290_327-overlay.dtsi, but I never wrote the imx327-overlay.dts variant as we don't support any of the functionality that is 290 specific (1080p120 10bit).

**Comment by naushir** [comment]
> Do those registers cause issues on IMX477? Could we send them unconditionally?

I'd be cautious about doing this without Sony's OK.

**Comment by davidplowman** [comment]
Thanks for the comments!

> Do those registers cause issues on IMX477? Could we send them unconditionally?

The 3ff9 register is documented and wouldn't make any difference to us, though it might do to someone else who knew what it was for. But maybe we don't care. The other two are undocumented. I suspect they'd have no effect - I could do the experiment, though that's not a cast-iron guarantee....

> Does the tuning need to change between them, so is the name important?

Really I think it's more of a libcamera problem because we have no way of distinguishing between modules based on the same sensor. So whilst a different name is convenient we could just indulge in the usual clunky workarounds that libcamera currently forces on us.

> 
> If we do need to distinguish between them, then it really ought to be done in device tree in case further deviation is required.
> Add an extra compatible string, and add a pointer to a `struct imx477_variant` which contains the sensor ID for that variant, and any special registers. The overlay can then include an override on the compatible string, or we have two overlays that include a common back-end
> 
> See imx290.c for an example as it handles a mono and colour variant through that route.
> imx290-overlay.dts also does almost the above in including imx290_327-overlay.dtsi, but I never wrote the imx327-overlay.dts variant as we don't support any of the functionality that is 290 specific (1080p120 10bit).

Understood. I was kinda hoping that if you can tell automatically from the device itself what you need to do then forcing people to mess around with device trees seems rather cruel! (In the imx290 case, I'm guessing that it's only through the device tree that you figure out what you you're dealing with?)

Maybe I'll go and perform that experiment on the imx477 and report back.

**Comment by davidplowman** [comment]
> > Do those registers cause issues on IMX477? Could we send them unconditionally?
> 
> I'd be cautious about doing this without Sony's OK.

Well, we could ask... :)

**Comment by 6by9** [comment]
It is true that with imx290 you have no other choice than DT as there is no ID register to query.

Configuring imx378 via an imx477 compatible just feels wrong. Even if the register set were identical, it'd be tempting to add both compatibles in case they diverged in future. Those who then took the easy option out and used the other compatible have only themselves to blame.

**Comment by pelwell** [comment]
+1 for adding an IMX378 compatible string and checking that the device matches.

**Comment by naushir** [comment]
I'll look to see if it is feasible to set the Y plane alignment to 64 bytes for YUV420.  This will correctly set the U/V plane alignments to 32.  Will need a simultaneous change to kernel + firmware.

**Comment by 6by9** [comment]
> I'll look to see if it is feasible to set the Y plane alignment to 64 bytes for YUV420. This will correctly set the U/V plane alignments to 32. Will need a simultaneous change to kernel + firmware.

Did you mean to comment on https://github.com/raspberrypi/libcamera-apps/issues/42 ?
Changing the bytesperline_align at https://github.com/raspberrypi/linux/blob/rpi-5.10.y/drivers/staging/vc04_services/bcm2835-isp/bcm2835-isp-fmts.h#L51 to 64 should do it with just a kernel change. Firmware will do as it's told then.

**Comment by naushir** [comment]
> Did you mean to comment on [raspberrypi/libcamera-apps#42](https://github.com/raspberrypi/libcamera-apps/issues/42) ?
> Changing the bytesperline_align at https://github.com/raspberrypi/linux/blob/rpi-5.10.y/drivers/staging/vc04_services/bcm2835-isp/bcm2835-isp-fmts.h#L51 to 64 should do it with just a kernel change. Firmware will do as it's told then.

Sorry yes, wrong window!

**Pull request closed without merging**
