### PR TITLE
According to 5713 pdf doc CLOCK_CTRL is a readonly status register, a…

### PR DESCRIPTION
**Pull request by hlauer0**
…nd it behaves so. Remove useless setting of the register.

### CODE REVIEW

**Comment by pelwell** [comment]
It looks like you may be correct (although the datasheet I've found could be clearer on the subject). Any comments, @Hifiberry?

**Comment by hifiberry** [comment]
Good question. Unfortunately I don't have a test setup here right now at the older Amp+ only works with Pi2 or earlier (this has nothing to do with the driver, just power requirements).

**Comment by hifiberry** [comment]
Had a short look at the data sheet and it really seems to bet read-only. Let's remove this.

**Comment by pelwell** [comment]
Thanks.

**Pull request merged**
