### PR TITLE
Added Device IDs for August DVB-T 205

### PR DESCRIPTION
**Pull request by abzieher**
Support for August DVB-T205 USB-Stick.

### CODE REVIEW

**Comment by popcornmix** [comment]
Interesting. I've got one of these dongles, and tried a patch just like yours. It detected the device, and I could scan for channels successfully, but I never got any data from /dev/dvb. I wasn't sure if the driver required more changes, or there was a problem with my setup.

I've just tried your patch and get:

```
[    9.378702] dvb-usb: found a 'AUGUST DVB-T205' in warm state.
[    9.834165] dvb-usb: will pass the complete MPEG2 transport stream to the software demuxer.
[   10.145763] DVB: registering new adapter (AUGUST DVB-T205)
[   10.339547] dvb-usb: no frontend was attached by 'AUGUST DVB-T205'
[   10.563074] input: IR-receiver inside an USB DVB receiver as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3.4/rc/rc0/input3
[   10.747815] rc0: IR-receiver inside an USB DVB receiver as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3.4/rc/rc0
[   10.863728] dvb-usb: schedule remote query interval to 400 msecs.
[   10.901438] dvb-usb: AUGUST DVB-T205 successfully initialized and connected.
[   10.925302] usbcore: registered new interface driver dvb_usb_rtl28xxu

ls /dev/dvb/adapter0/
demux0  dvr0  net0

w_scan -c GB -f t -X >~/.tzap/channels.conf
w_scan version 20120605 (compiled for DVB API 5.4)
using settings for UNITED KINGDOM
DVB aerial
DVB-T GB
scan type TERRESTRIAL, channellist 6
output format czap/tzap/szap/xine
WARNING: could not guess your codepage. Falling back to 'UTF-8'
output charset 'UTF-8', use -C <charset> to override
Info: using DVB adapter auto detection.
main:3220: FATAL: ***** NO USEABLE TERRESTRIAL CARD FOUND. *****
Please check wether dvb driver is loaded and
verify that no dvb application (i.e. vdr) is running.
```

Is this working for you?

**Comment by abzieher** [comment]
Yes, it is working. I use tvheadend stream the services to the clients.
You could try to reinserting the stick while the RPi is running. In your case it couldn't find the tuner.

```
# ls /dev/dvb/adapter0/
demux0  dvr0  frontend0  net0

# dmesg|tail -n12
[   73.060226] dvb-usb: found a 'AUGUST DVB-T205' in warm state.
[   73.109329] dvb-usb: will pass the complete MPEG2 transport stream to the software demuxer.
[   73.138450] DVB: registering new adapter (AUGUST DVB-T205)
[   73.185143] rtl28xxu: rtl2832u_frontend_attach: FC0012 tuner found
[   73.225735] DVB: registering adapter 0 frontend 0 (Realtek RTL2832 (DVB-T))...
[   73.273198] fc0012: Fitipower FC0012 successfully attached.
[   73.291898] Registered IR keymap rc-empty
[   73.318932] input: IR-receiver inside an USB DVB receiver as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2.1/rc/rc0/input0
[   73.361509] rc0: IR-receiver inside an USB DVB receiver as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2.1/rc/rc0
[   73.401936] dvb-usb: schedule remote query interval to 400 msecs.
[   73.449845] dvb-usb: AUGUST DVB-T205 successfully initialized and connected.
[   73.485289] usbcore: registered new interface driver dvb_usb_rtl28xxu

# w_scan -cDE -ft -X>/tmp/channels.conf
w_scan version 20121111 (compiled for DVB API 5.9)
using settings for GERMANY
DVB aerial
DVB-T Europe
scan type TERRESTRIAL, channellist 4
output format czap/tzap/szap/xine
Info: using DVB adapter auto detection.
    /dev/dvb/adapter0/frontend0 -> TERRESTRIAL "Realtek RTL2832 (DVB-T)": good :-)
Using TERRESTRIAL frontend (adapter /dev/dvb/adapter0/frontend0)
-_-_-_-_ Getting frontend capabilities-_-_-_-_
Using DVB API 5.6
frontend 'Realtek RTL2832 (DVB-T)' supports
INVERSION_AUTO
QAM_AUTO
TRANSMISSION_MODE_AUTO
GUARD_INTERVAL_AUTO
HIERARCHY_AUTO
FEC_AUTO
FREQ (174.00MHz ... 862.00MHz)
-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
[...]
dumping lists (8 services)
Done.
```

**Comment by popcornmix** [comment]
Got nothing from scan with default antenna, but tried one with a booster (which can get pictures on a real TV) and get:

```
cat .tzap/channels.conf
ITV:498000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:520:521:8258
ITV2:498000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:530:531:8325
Channel 4:498000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:560:561:8384
E4:498000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:570:571:8448
More 4:498000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:590:591:8442
Channel 4+1:498000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:580:581:8452
Channel 5:498000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:540:541:8500
ITV +1:498000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:600:601:8357
BBC ONE:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:101:102:4173
BBC TWO:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:201:202:4287
BBC NEWS:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:501:502:4352
CBBC Channel:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:301:302:4608
CBeebies:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:401:402:4672
BBC Parliament:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:601:602:4736
BBC R5L:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:0:1402:5632
BBC R5SX:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:0:1502:5696
BBC 6 Music:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:0:1602:5760
BBC Radio 4 Ex:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:0:1702:5824
BBC R1X:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:0:1802:5888
BBC Asian Net.:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:0:1902:5952
BBC World Sv.:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:0:2002:6016
BBC Radio 1:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:0:1002:6720
BBC Radio 2:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:0:1102:6784
BBC Radio 3:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:0:1202:6848
BBC Radio 4:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:0:1302:6912
301:522000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_2_3:FEC_NONE:QAM_64:TRANSMISSION_MODE_8K:GUARD_INTERVAL_1_32:HIERARCHY_NONE:901:951:7168
```

which looks good. 

```
tzap ITV
using '/dev/dvb/adapter0/frontend0' and '/dev/dvb/adapter0/demux0'
reading channels from file '/home/pi/.tzap/channels.conf'
tuning to 498000000 Hz
video pid 0x0208, audio pid 0x0209
status 00 | signal 5757 | snr 0000 | ber 00000000 | unc 00000000 |
status 1f | signal 5050 | snr 0000 | ber 00000000 | unc 00000000 | FE_HAS_LOCK
status 1f | signal 5050 | snr 0000 | ber 00000000 | unc 00000000 | FE_HAS_LOCK
...
```

also looks good. But 
cat /dev/dvb/adapter0/dvr0
produces nothing. Should that produce data?

**Comment by popcornmix** [comment]
I built tvheadend and I get video/audio data streamed from it. Not great quality, but that may be the indoor aerial.

**Pull request merged**
