### PR TITLE
New driver for the G2 labs TDA1543 v2 DAC.

### PR DESCRIPTION
**Pull request by McDaisy**

### CODE REVIEW

**Comment by renlopes** [comment]
Why so much PR for this?

**Comment by McDaisy** [comment]
Hi

Sorry its my first time to use github pull request. I didnt know how to merge or create one pull request for the driver. I see that i managed to create one request for each new or edited file...


Should I start over?

Thanks!


Br
George

**Comment by renlopes** [comment]
All changes can be commited in one PR to facilitate analysis. Check others PRs here and github manual.
See ya.

**Comment by 6by9** [comment]
As already noted if this is all related to adding one driver then all files should be committed in a single commit.
It must be possible to build the kernel from any commit, which isn't true with your current set of patches (eg you updated the DTS overlays makefile before adding the overlay file)

Several of the files have 

> Author:	Florian Meier <florian.meier@koalo.de>

in the copyright header. Are these genuinely files written by Florian, or are you the author based on some other file by Florian? If the latter then you are the author but add the comment "Based on file XXX by Florian Meier".

None of the patches have a "signed off" line. ```git commit -s``` will add that for you.

**Pull request closed without merging**
