### PR TITLE
rpi-5.10.y fixups

### PR DESCRIPTION
**Pull request by juergh**
Two minor self-explanatory fixups.

### CODE REVIEW

**Comment by popcornmix** [comment]
These look correct to me.

**Comment by pelwell** [comment]
For the sdhci patch, a full reversion of the original and a one line replacement seems cleaner.

**Comment by juergh** [comment]
I wasn't sure how you wanted this. Borrowed your commit message, feel free to amend as necessary.

**Comment by pelwell** [comment]
Thanks - I tweaked the commit message, mainly to make it different.

**Pull request merged**
