### PR TITLE
Fix kernel oops in l2cap_chan_destroy. 

### PR DESCRIPTION
**Pull request by rwg0**
3.6.11 oopses under certain situations when using bluetooth - see http://www.raspberrypi.org/phpBB3/viewtopic.php?f=28&t=37265

I found a fix for this in the mainline kernel source and backported it to rpi-3.6.y

Based on https://github.com/torvalds/linux/commit/4af66c691f4e5c2db9bb00793669a548e9db1974

### CODE REVIEW

**Comment by popcornmix** [comment]
Sorry, this got forgotten about. Is it confirmed this fixes the problem reported in thread?

**Comment by rwg0** [comment]
Well I certainly had the same stacktrace in the kernel oops before applying the fix and haven't had a problem since appying it.

Robin

**Comment by foocode** [comment]
Please fix this ASAP... My RaspPi has been useless in the year since I received it without working bluetooth support!

**Comment by popcornmix** [comment]
PR looks equivalent to upstream change, it builds, and there seems some demand for it, so it's accepted.
I'll push out a firmware update later today.

**Comment by foocode** [comment]
Just wondering, did this happen? I performed an rpi-update this evening however my device showed same problem.

**Comment by popcornmix** [comment]
Firmware is now updated.

**Comment by funky81** [comment]
Thanks for updating the firmware. But it seems somehow this NULL pointer bug when using bluetooth havent solved yet. There's no changes after and before update the firmware. How can I help you to troubleshoot this?

Thanks

**Comment by foocode** [comment]
Unfortunately the issue still remains on my Pi too.

**Comment by funky81** [comment]
Currently, I'm using wheezy. Will it solved if I change the OS to such as as Pidora/RiscOS?

**Comment by popcornmix** [comment]
Might be worth trying the "next" firmware branch:
sudo BRANCH=next rpi-update

**Comment by funky81** [comment]
Thanks for your advice @popcornmix but still doesnt work :(

**Comment by foocode** [comment]
As above, I'm afraid. Still no fix when using 'BRANCH=next'.

**Comment by funky81** [comment]
Could anyone tell me how to debug it?
I can't press more if the bug comes out
I'm using usb keyboard
maybe the bug affect it.

On Sun, Jul 7, 2013 at 11:39 AM, foocode notifications@github.com wrote:

> As above, I'm afraid. Still no fix when using 'BRANCH=next'.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/raspberrypi/linux/pull/283#issuecomment-20565600
> .

## 

http://hobby.keluargareski.net
Sent from Sony VAIO notebook

**Pull request merged**
