### PR TITLE
w1-gpio,bcm2708:  Disable 1-wire pull-up by default and expose parameters to modules

### PR DESCRIPTION
**Pull request by ajlennon**

### CODE REVIEW

**Comment by ajlennon** [comment]
For details see #601

**Comment by popcornmix** [comment]
Thanks!

**Comment by popcornmix** [comment]
I merged this into 3.14.y kernel, but it seems things have changed with this upstream commit using devm_ functions:
https://github.com/raspberrypi/linux/commit/d27f25c9c216dc9f9a320fe78f729aebdebcae50

Can you check if this still looks (and works) okay?
https://github.com/raspberrypi/linux/commit/e095b2b3838e79acb105f748d2504c5ddf98b9f6

**Comment by ajlennon** [comment]
Ah, yes - I had a quick chat with Evgeniy and Ville about some of the questions (e.g. querying the missing GPIO free in there) and they did mention something about use of devm in the newer kernels meaning this was no longer a concern.

What about I have a look at regenerating a patch for 3.14.y and check it builds here.

**Comment by popcornmix** [comment]
Okay.

**Comment by ajlennon** [comment]
Sorry - bit slow here today. You just took out the additional gpio_free() from the patch for 3.14.y?

Yes that's what I would have done. I'll give it a quick run up with a 1-wire sensor with insmod/rmmod but within my understanding of devm (non-existent) if devm now handles freeing resources then that looks fine to me.

**Comment by popcornmix** [comment]
There were a couple of conflicts, and it appeared that removing the free was the correct solution (by looking at the upstream commit that added devm_).

But I was only 80% sure, and it's untested, so would be good if you can confirm it looks okay and still works.

**Comment by ajlennon** [comment]
I wouldn't disagree with that point of view. I too tend to feel if I've not seen it work then it can be assumed not to, and if I have... well it probably still doesn't, but in a more ambiguous way.

I've now built a0e9f880c off rpi-3.14.y and all seems to work on the RPi here.
- modprobe'd w1-gpio
- rmmod'd it
- modprobed it again with a gpiopin=10 (default being 4)
- can see my dallas temp. sensor popping up on gpio10 and can get data from it

**Comment by popcornmix** [comment]
Thanks.

**Comment by alevikpes** [comment]
Hello!

I did not understand from this conversation if it is possible to fix the camera problem. Could you please explain in simple how to do this then? Or is the camera dead already?

**Pull request merged**
