### PR TITLE
Multichannel pcm

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by popcornmix** [comment]
Thanks. Would be better submitted to rpi-4.0.y as that is now default kernel (through rpi-update, but also for apt-get next time packages are updated). But that's not critical, these files won't have changed significantly.

I'd like to do some testing and see if there are any simple changes on the firmware side that will make things easier. Removing the need for gencmd though a new audioserv message is the obvious one.

I'd like to know exactly what the noise is with multichannel analogue. I wouldn't expect it to work, but it may be straightforward to output say the first two (or perhaps FL/FR) channels.

There may be a similar issue with HDMI. TV's typically only support two channels. I suspect you will just get first two channels when outputting multichannel (although noise or any other behaviour is possible).

I'll have a think about an automatic downmix and automatic padding of non-power of 2 channels, but it may be a little while before I have time.

**Comment by ghost** [comment]
> Would be better submitted to rpi-4.0.y as that is now default kernel 

Maybe I'll rebase tomorrow. Recompiling the entire kernel takes a while...

> Removing the need for gencmd though a new audioserv message is the obvious one.

Yes, I'm hoping for this one.

Other potential improvements include reordering the channels on the GPU, instead of forcing the application to add padding channels.

> There may be a similar issue with HDMI. TV's typically only support two channels. I suspect you will just get first two channels when outputting multichannel (although noise or any other behaviour is possible).

We've already concluded that the EDID isn't good enough, so I guess that's just how things are.

**Comment by ghost** [comment]
PS: One remaining issue is that my receiver apparently doesn't get audio in the CEA 0x08 layout correctly (what I like to call `quad`). Channels are missing or mismatched. I don't know what's the cause for this. From my end everything looks like it's setup correctly. (I've mentioned this in the multichannel PCM issue.)

**Comment by popcornmix** [comment]
Can you describe what user code you are using to test mulitchannel alsa?
Kodi/omxplayer use CEA 0x8 layout. All the kodi/omxplayer modes were tested with a hdmi analyser that reports speaker name and level (with a speakertest wav file), so I'd expect that to be correct.
I don't currently have access to that, but have a Yamaha AV receiver, so if you tell me what to test I can see if I get the same result.

**Comment by ghost** [comment]
> Can you describe what user code you are using to test mulitchannel alsa?

I use mpv git master and these files: https://github.com/mpv-player/random-stuff/tree/master/speaker_test/ (not quite ideal and some of the more obscure layouts are actually wrong)

Just playing them (maybe with `--loop`) should be sufficient. Without the kernel patch applied, it'll always play stereo.

> All the kodi/omxplayer modes were tested with a hdmi analyser that reports speaker name and level (with a speakertest wav file), so I'd expect that to be correct.

I've tried to duplicate the general kodi/omxplayer logic for setting the `hdmi_channel_map` parameter, but I might have made mistakes. It also could be that the command is not sent at the right time.

Are there any cheap hdmi analyzers? From what I've seen they tend to be expensive.

**Comment by popcornmix** [comment]
The hdmi analyser belonged to Broadcom and no doubt was expensive.
In theory a hdmi capture card could do much of this, but I'm not sure there's any freely available software for capturing multichannel audio and the audio info frame.

**Comment by ghost** [comment]
Rebased. Unfortunately, github doesn't seem to let me change the base branch on this PR, so it's displaying a huge load of nonsense.

**Comment by ghost** [comment]
I've tried it with kodi (latest OpenElec beta release). It played only half of the video of my crappy channel layout test files (as if video froze towards the end), so I'm unable to confirm anything.

I never had much success with omxplayer, but when I tried again, I realized it appears to downmix to stereo by default. At least the back channels stayed silent. Running `omxplayer -o hdmi --layout 5.1  random-stuff/speaker_test/speaker_test_quad.avi`, I can confirm that it has the same issue as my ALSA PCM code: one back channel remains silent all the time (I think the right one), while the other channel seems to drive both speakers.

Also, the omxplayer `--loop` option doesn't seem to work - it doesn't wait until all video and audio has been played.

**Comment by ghost** [comment]
Replaced by PR #1166. Since github doesn't let me change the base branch to get rid of the unrelated commits it displays, creating a new PR is apparently the only way.

**Pull request closed without merging**
