### PR TITLE
Ported pcie-brcmstb bounce buffer implementation to ARM64.

### PR DESCRIPTION
**Pull request by yaroslavros**
This enables full 4G RAM usage on Raspberry Pi in 64-bit mode.
This addresses https://github.com/raspberrypi/linux/issues/3093

### CODE REVIEW

**Comment by pelwell** [comment]
Thank you. Do you have a "Signed-off-by: name <email>" I can add for you?

**Comment by yaroslavros** [comment]
Added a commit d1e0a4c368c28a4f929977bb850e51b95823fa94 with "Signed-off-by"

Sorry about missing this

**Comment by yaroslavros** [comment]
I left a diagnostic trace message in arch/arm64/mm/dma-mapping.c
This is rectified  by 6e7a2b8b5786159b5130660f722cc8e5a4f5d3d7

**Comment by pelwell** [comment]
Thanks - that should all squash down when it is time to merge.

**Comment by agherzan** [comment]
@yaroslavros all we need now is a squash to one commit so we can merge it. Do you think you can do that soon?

**Comment by pelwell** [comment]
No need - I can squash and merge if you've had a chance to test it.

**Comment by agherzan** [comment]
I see. I'll give it a spin tomorrow. Will update as soon as.

**Comment by sakaki-** [comment]
Very nice - seems to work well (in the very basic testing I have done anyhow)!

I have [added](https://github.com/sakaki-/bcm2711-kernel-bis/blob/e71e745094024ef283b651386f88822626dcd033/patch_kernel.sh#L51-L53) this PR to my [bcm2711-kernel-bis](https://github.com/sakaki-/bcm2711-kernel-bis) weekly autobuild pro tem, until it is merged upstream. A prebuilt release tarball may be downloaded [here](https://github.com/sakaki-/bcm2711-kernel/releases/tag/4.19.65.20190814).

Screenshot (64-bit Gentoo userland, also has #3063 applied for V3D):

screenshot

Thanks, sakaki

**Comment by pY4x3g** [comment]
I tested the current kernel with the bounce buffer implementation on arm64. After the ram went over 1GB most of the programs are not usable anymore, network broke down and I was not able to shutdown the system at all. More or less the same as before the merge. I see errors in dmesg like in issue #3120 is this to be expected with a 32bit userspace? Sorry for asking, I dont know much about kernels.

Edit: after using the kernel from sakaki the problem is not present anymore. Maybe I compiled the kernel wrong... (used the introduction from https://andrei.gherzan.ro/linux/raspbian-rpi-64/)

**Comment by agherzan** [comment]
@pY4x3g How have you tested this? I just ran some stress tools and I was able to go above 3G without any obvious issues.

```
root@raspberrypi4-64:~# free -m
              total        used        free      shared  buff/cache   available
Mem:        3780536     3269616      447608       10784       63312      468548
Swap:             0           0           0
```

This is on a full 64bit distro (kernel + userspace).

**Comment by pelwell** [comment]
It's all looking good here, with just `arm_64bit=1` in config.txt.

**Comment by pY4x3g** [comment]
@agherzan I started a self compiled go program (siacoin - arm64), after 1 GB of memory was used the system was not usable anymore. I actually do not know what I did wrong, but with the compiled kernel as mentioned above all is working fine now with usage at full 4GB (-300M for GPU) memory and swapping of 2 GB. System is running stable since yesterday. Using the official 32bit raspbian userspace.

**Comment by sakaki-** [comment]
@agherzan, see @pY4x3g's edit to the original message:
> Edit:  after using the kernel from sakaki the problem is not present anymore.  Maybe I compiled the kernel wrong... (used the introduction from https://andrei.gherzan.ro/linux/raspbian-rpi-64/)

So I guess just a localized build issue originally?

**Comment by sakaki-** [comment]
Ooops - our posts just crossed @pY4x3g, apologies ^-^

**Comment by agherzan** [comment]
Gotcha. Thanks for clarifying. Looks good!

**Comment by WayneSan** [comment]
Is this patch included in 5.3.0.1008.4 kernel package?

> linux-headers-raspi2/eoan-updates 5.3.0.1008.4 arm64 [upgradable from: 5.3.0.1007.3]
> linux-image-raspi2/eoan-updates 5.3.0.1008.4 arm64 [upgradable from: 5.3.0.1007.3]
> linux-raspi2/eoan-updates 5.3.0.1008.4 arm64 [upgradable from: 5.3.0.1007.3]

I've already upgraded the above packages and tried to remove the workaround setting.

But the USB device is still not working after rebooting.

**Comment by pelwell** [comment]
Is that an Ubuntu package? It's certainly not one of ours.

**Comment by WayneSan** [comment]
Oh... thanks for the reply. And sorry for the confusion.

**Comment by HardWareHacker9753** [comment]
how do you apply / install this in an image please just give a short simple guide for those new to Linux and eager to learn

**Comment by pelwell** [comment]
Just grab the latest firmware builds from here: https://github.com/raspberrypi/firmware/tree/master/boot

The kernel8.img includes this patch.

**Comment by hadyanq1** [comment]
Hi @pelwell, thank you very much for your work to fix this issue. I may be missing something obvious here, but could you please elaborate what to do with the kerne8.img, do I have to rebuild the image and reflash my SD card? Is it possible to appy the fix to an already running system with desktop environment?

**Comment by pelwell** [comment]
I recommend that you use the `rpi-update` utility (https://github.com/Hexxeh/rpi-update). It will download and install the latest firmware, kernels and associated modules.

**Pull request merged**
