### PR TITLE
[lirc] add original xbox dvd playback remote dongle support

### PR DESCRIPTION
**Pull request by s7mx1**

### CODE REVIEW

**Comment by s7mx1** [comment]
Sorry about so many "null" commits. The last one should be good.

**Comment by richo** [comment]
Can you rebase them together?

**Comment by s7mx1** [comment]
rebased.

**Comment by ghollingworth** [comment]
Has this come from upstream?  If not push upstream and we'll take it

**Comment by P33M** [comment]
Closing as no activity from owner. If you want this device to be supported (if it isn't already by now), submit a patch to the relevant upstream kernel maintainer and once it's accepted we can cherry-pick.

**Pull request closed without merging**
