### PR TITLE
Create driver for Waveshare DSI screens

### PR DESCRIPTION
**Pull request by 6by9**

### CODE REVIEW

**Comment by belliash** [comment]
I don't want to make trash here. Just wanted to mention, that this does not seem to work with my 7" C. You can find details here: https://github.com/waveshare/Waveshare-DSI-LCD/issues/4

**Comment by 6by9** [comment]
Dropping WIP tag as this has been confirmed to work on a the majority of the panels supported.
I know I haven't done a DT binding or MAINTAINERS entry, but I have limited motivation in trying to upstream them.

I can't work out what is upsetting the dtoverlaycheck. It complains of
```
2023-04-24T08:48:23.5159425Z Can't use an undefined value as an ARRAY reference at /home/runner/work/linux/linux/utils/overlaycheck/overlaycheck line 376, <$fh> line 4523.
2023-04-24T08:48:23.5162505Z * Missing params for overlay vc4-kms-dsi-waveshare-panel (4523)
```
but I've been staring at the two files and can't see what I've missed.

**Comment by pelwell** [comment]
It's not a great error/message, but you've dropped the "Params:" section heading.

**Comment by 6by9** [comment]
> It's not a great error/message, but you've dropped the "Params:" section heading.

Doh, thanks!
Updated so hopefully it'll be happy now.

**Comment by beletruz** [comment]
The latest 6.1.20 doesn't work with the latest raspberry pi os with this display https://www.waveshare.com/wiki/7.9inch_DSI_LCD#Overview by adding dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch   the display stays off and the led blinks but it does work (it lights up, it displays as it should) except for the touchscreen with android running on the pi (this android https://konstakang.com/devices/rpi4/LineageOS20 )
Using the  "dtoverlay=vc4-kms-dsi-waveshare-panel,7_9_inch"  and "goodix" for touch this is what it reports about the touchscreen
[ 3.486535] Goodix-TS 1-0014: supply AVDD28 not found, using dummy regulator
[ 3.493801] Goodix-TS 1-0014: supply VDDIO not found, using dummy regulator
[ 3.597518] Goodix-TS 1-0014: Error reading 1 bytes from 0x8140: -5
[ 3.629484] Goodix-TS 1-0014: Error reading 1 bytes from 0x8140: -5
[ 3.661185] Goodix-TS 1-0014: I2C communication failure: -5
[ 3.667235] Goodix-TS: probe of 1-0014 failed with error -5
[ 3.674567] i2c i2c-22: Added multiplexed i2c bus 0
[ 3.679906] Goodix-TS 10-0014: supply AVDD28 not found, using dummy regulator
[ 3.687263] Goodix-TS 10-0014: supply VDDIO not found, using dummy regulator
[ 3.695975] Goodix-TS 10-0014: ID 9271, version: 1070
[ 3.718404] input: Goodix Capacitive TouchScreen as /devices/platform/soc/fe205000.i2c/i2c-22/i2c-10/10-0014/input/input0

I would like to run the display with that android img on the pi and now the only problem is the touch part

Thanks

**Comment by 6by9** [comment]
Please open a new issue. following the template offered. Commenting on a merged PR is the way that issues will get lost.

**Comment by beletruz** [comment]
Ok, I'll do that

**Pull request merged**
