### PR TITLE
Fixes for modetest helpers for 5.13

### PR DESCRIPTION
**Pull request by mripard**
Hi,

This is the same PR than #4672, for 5.13

### CODE REVIEW

**Comment by pelwell** [comment]
As of September 2021, 5.13 is EOL upstream - we've stopped updating rpi-5.13.y.

**Comment by mripard** [comment]
Ok, that was one of the thing I wasn't really sure :) This is the kernel used by Canonical for Ubuntu 21.10, what is our stand here? Use either 5.10 or 5.15?

**Comment by pelwell** [comment]
That would be our preference. I'm not completely against merging this and #4674, but that would leave the kernel lacking several commits that have gone into rpi-5.10.y and rpi-5.15.y - _caveat emptor_.

**Comment by popcornmix** [comment]
https://en.wikipedia.org/wiki/Ubuntu_version_history#Table_of_versions
Ubuntu use a number of EOL kernels. They maintain their own kernel tree and cherry-pick security (and other critical bugs).
I suspect they prefer the kernel to match an Ubuntu release on all platforms, so are unlikely to switch the Pi kernel to match what we are using.

I'm happy to merge fixes here, which will make it easier for Ubuntu to cherry-pick.
But as you say, this is a largely untested tree, so it patches may be useful, but no promises.

**Comment by juergh** [comment]
Thanks guys, I really appreciate this. Untested is fine but it does help me understand better what we might be missing.

**Pull request merged**
