### PR TITLE
Update rtl28xxu.c

### PR DESCRIPTION
**Pull request by robertovic**
Added device id EXAGERATE DVB-T UB396 (Hamlet).
File line 1415

### CODE REVIEW

**Comment by popcornmix** [comment]
What devices use this chipset?
I'm not getting many hits on google for "EXAGERATE DVB-T UB396".
Anyone else using this?

**Comment by robertovic** [comment]
sorry,
i am not english.

the device name is XDVBT900BK. 

I use this device now.
http://www.ciao.it/Hamlet_eXagerate_XDVBT900BK__1466925

When I plug the device in ubuntu and typing lsusb in the terminal I see this: ID 1b80: D396 Afatech UB396-T [RTL2832U] I assigned the incorrect name of the device.What can I do?
I tested the device and it works well.
Sorry.

**Comment by robertovic** [comment]
what name  assign to device?
i am mechanic  of truck and i not have fully experience in programming
Small experience linux,rpi,pic,arduino.
please can you rename the correct name of device?
i can release my rpi dmesg for your help.
I am not sure  of  named device.

I have tested dvb device  on rpi and it works well.
bye
thank

**Comment by robertovic** [comment]
Can i have response?
this is mi first work on linux driver , is important for me and any people  have this device.

I have added another device IDs for this kernel the name is Pinnacle 77e 
I have tested pinnacle 77e device on rpi and it works well.

I can release this modification if anyone help me for named device.

I'm not english.
Bye and thank at all.

**Comment by popcornmix** [comment]
In general we don't maintain out of tree patches without a strong reason.
They create a maintenance headache when moving to newer firmware versions, and it's hard to predict if they will cause any problems for other users.
The correct solution is for this patch to go into the upstream linux kernel. Experts there can decide if it is correct, and once merged I'll be happier to cherry-pick it.
If I can be shown evidence that there are dozens or hundreds of users requesting this patch, then I'll reconsider.
Anyone who uses this chipset on a Pi please comment here.

**Comment by popcornmix** [comment]
Closing. The patch should be submitted upstream.

**Pull request closed without merging**
