### PR TITLE
Configure GPIOs for I2S based on revision/card settings

### PR DESCRIPTION
**Pull request by hifiberry**
With RPi model B+, assignment of the I2S GPIO pins has changed.
This patch uses the board revision to auto-detect the GPIOs used
for I2S. It also allows sound card drivers to set the GPIOs that
should be used. This is especially important with the Compute
Module.

### CODE REVIEW

**Comment by popcornmix** [comment]
I get a build error:

```
sound/soc/bcm/bcm2708-i2s.c:51:12: error: conflicting types for ‘system_rev’
 extern int system_rev;
            ^
In file included from /home/dc4/projects/linux/arch/arm/include/asm/system.h:6:0,
                 from /home/dc4/projects/linux/arch/arm/include/asm/jump_label.h:7,
                 from include/linux/jump_label.h:63,
                 from include/linux/static_key.h:1,
                 from include/linux/tracepoint.h:20,
                 from include/linux/module.h:18,
                 from sound/soc/bcm/bcm2708-i2s.c:37:
/home/dc4/projects/linux/arch/arm/include/asm/system_info.h:19:21: note: previous declaration of ‘system_rev’ was here
 extern unsigned int system_rev;
                     ^
```

BTW, you never need to close a PR.
Just edit the commit on your branch and force push.

E.g. make edits.

```
git add -u
git commit --amend
git push -f
```

If you need to split/merge commits, then :

```
git rebase -i HEAD~3
```

is the command.

Also always best to create a PR from a newly created topic branch, rather than the default branch (rpi-3.12.y). There's always a chance you'll want to make a second PR before the first is merged, and any changes to the branch you PR-ed will affect the PR.

**Comment by hifiberry** [comment]
Ok, I have to look at this compile error. I didn't get it. Can you send me your .config?

**Comment by popcornmix** [comment]
I just use

```
make ARCH=arm bcmrpi_defconfig
```

to create .config. It may be because I'm using gcc 4.8.
The bug is obvious,  system_rev is being declared as both:
extern unsigned int system_rev;
extern int system_rev;

If you add unsigned it will probably fix it (although it appears removing it should work as it's being declared in an included header).

**Comment by hifiberry** [comment]
Interestingly when compiling with GCC 4.6, I don't get the error. Removing it also does not work, as the original header file "asm/system_info.h" is not included. I will remove the definition and include the original header file with this definition.

**Comment by hifiberry** [comment]
I've corrected the problems and pushed it again. Anything else I have to do?

**Comment by popcornmix** [comment]
Thanks - looks good to me now.

**Comment by hifiberry** [comment]
Thank you. Have a nice weekend.

**Comment by pitichai** [comment]
I am a newbie here. I would like to report a bug and the fix that I use for getting by. 
I found this patch is working with model B+ but I found system_rev on model B showing as 
bcm2708.boardrev=0x100000e   and it would not work with Model B with RPI-DAC-RCA. I have to change line 340 of file "sound/soc/bcm/bcm2708-i2s.c" from
if (system_rev >= 0x10) {
      to
if (system_rev == 0x10) {

However, I am not sure it may just my model B report boardrev==0x100000e  . To not recomplie kernel I need to pass bcm2708.boardrev=0xe into /boot/cmdline.txt 

Best Regards,
Pitichai

**Comment by popcornmix** [comment]
Ah - I see the issue. The top byte of the system_rev is used for flags like the warranty bit.
I believe the correct check should be:
if ((system_rev & 0xffffff) >= 0x10) {

Can you test that?

**Comment by pitichai** [comment]
Ok. I will change that and test for you. I will get back to you after it 
is done.
Thank you.
Best Regards,
Pitichai

**Comment by pitichai** [comment]
I confirmed with

if ((system_rev & 0xffffff) >= 0x10) {

is working on both Model B and Model B+

Thank you,
PP

**Comment by hifiberry** [comment]
Thank you for this fix.

**Comment by pitichai** [comment]
Hi popcornmix, 
I have couple question to asking which may not relate with this issue. 
1. Is the "HAT" already implemented and used in the Raspberry Pi Linux kernel? (or when will it be in and a "must" to support "HAT"?)
2. How to deal with different, several boards using the same I2C flash device (how to avoid Slave Address CONFLICTS on I2C bus)?
3. Is there in addition to the Linux Device Tree already a spec. about the content (e.g. start address where Device Tree has to be located) of the I2C flash device?

How I figure out how HAT, EEPROM and PINMUX tree work so that I can make and interface to them. Is there any documents or this or It still have to do manually ? 

Or which channel I should send question too ? May I have your email ? 
Thank you and Best Regards,
Pitichai

**Comment by popcornmix** [comment]
Some info on HAT here:
https://github.com/raspberrypi/hats
http://www.raspberrypi.org/introducing-raspberry-pi-hats/

I'm not really involved  with HAT, so am not the best person to ask.
I don't believe HAT is supported in firmware/kernel yet.
Probably best to ask in the forum where gsh/James Adams/ShiftPlusOne may be able to help.
http://www.raspberrypi.org/forums/viewforum.php?f=100

**Comment by pitichai** [comment]
Thank you very much for the information.
Best Regards,
Pitichai

**Comment by pitichai** [comment]
Hi Popcornmix, 
I have submit a driver from Duriosound-dac for sound driver on pull request #697. Can you suggest me that I have done correctly ?  I am not quite sure I have done pull request process right ? 
Best Regards,
Pitichai

**Pull request merged**
