### PR TITLE
More imports from 4.9.y

### PR DESCRIPTION
**Pull request by pelwell**
@anholt @6by9 Can you confirm that your respective commits in this PR are still required and correctly ported?

### CODE REVIEW

**Comment by 6by9** [comment]
"bcm2835-camera: Correct port_parameter_get return value" not required.
Upstream implemented it slightly differently - f7d51372 I think covered it all.

**Comment by anholt** [comment]
I think we want all of those.  We should probably double check that vc4 probes well with and without panel attached with that overlay change.

**Comment by pelwell** [comment]
It works OK without a DSI panel, but running with it (and no HDMI) I get a crash:
```
[    5.994558] Unable to handle kernel NULL pointer dereference at virtual address 00000008
[    6.009062] uart-pl011 3f201000.serial: no DMA platform data
[    6.010289] pgd = 80004000
[    6.016799] [00000008] *pgd=00000000
[    6.024333] Internal error: Oops: 17 [#1] SMP ARM
[    6.032714] Modules linked in: panel_raspberrypi_touchscreen joydev brcmfmac brcmutil vc4 drm_kms_helper cfg80211 rfkill drm snd_bcm2835(C) snd_soc_core snd_compress snd_pcm_dmaengine syscopyarea snd_pcm sysfillrect i2c_gpio sysimgblt fb_sys_fops i2c_algo_bit i2c_bcm2835 snd_timer snd evdev rpi_backlight rpi_ft5406 fixed uio_pdrv_genirq uio i2c_dev ip_tables x_tables ipv6
[    6.086699] CPU: 1 PID: 15 Comm: kworker/1:0 Tainted: G         C      4.14.18-v7+ #89
[    6.099579] Hardware name: BCM2835
[    6.107610] Workqueue: events output_poll_execute [drm_kms_helper]
[    6.118843] task: ba530f00 task.stack: ba52e000
[    6.127978] PC is at handle_conflicting_encoders+0x110/0x2bc [drm_kms_helper]
[    6.140034] LR is at drm_mode_object_put+0x50/0x94 [drm]
[    6.149966] pc : [<7f3ffd08>]    lr : [<7f1f6ff8>]    psr: 60000013
[    6.161391] sp : ba52fc28  ip : ba52fbe0  fp : ba52fc6c
[    6.171313] r10: 00000001  r9 : b986c8c0  r8 : 00000000
[    6.181166] r7 : 00000000  r6 : 00000002  r5 : 00000000  r4 : b64dfc30
[    6.181173] r3 : 00000000  r2 : b986c840  r1 : 00000000  r0 : b64dfc30
[    6.181187] Flags: nZCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment user
[    6.181193] Control: 10c5383d  Table: 39ba806a  DAC: 00000055
[    6.181200] Process kworker/1:0 (pid: 15, stack limit = 0xba52e210)
[    6.181206] Stack: (0xba52fc28 to 0xba530000)
[    6.181216] fc20:                   ba52fc84 ba52fc38 807780c8 7f1e7290 ba52fc6c ba52fc48
[    6.181227] fc40: b6438400 b64dfc30 b65cac00 b986c8c0 b7734010 00000054 b7485c00 00000003
[    6.181238] fc60: ba52fcc4 ba52fc70 7f400030 7f3ffc04 ba52fca4 ba52fc88 7f1f708c 00000002
[    6.181249] fc80: 7f2150cc 0000002b 00000005 b6438400 b6439c10 b6438538 ba530f00 b986c8c0
[    6.181260] fca0: b6438400 00000003 b7742d80 b6438400 b986c8c0 00000003 ba52fce4 ba52fcc8
[    6.181271] fcc0: 7f401484 7f3ffec0 7f401464 b7734010 00000001 00000003 ba52fd54 ba52fce8
[    6.181282] fce0: 7f1f0d10 7f401470 b6439c24 7f1f065c ba52fd24 ba52fd08 7f1f708c 7f1e0c98
[    6.181295] fd00: 7f2150cc 0000002b b7742c00 b7734010 ba52fd44 ba52fd28 7f1f065c 7f401d18
[    6.181306] fd20: 7f214358 b7742c00 00000044 3fffffff b986c8c0 b6438400 b64385d4 b99c86c0
[    6.181317] fd40: b76e6f50 00000003 ba52fd74 ba52fd58 7f1f1050 7f1f0a1c 00000001 3fffffff
[    6.181328] fd60: 00000001 b986c8c0 ba52fdd4 ba52fd78 7f404534 7f1f103c b76e6f50 00000002
[    6.181338] fd80: b6438400 00000001 b986c444 ba530f00 00000008 00000022 00000000 b773703c
[    6.181348] fda0: b9fade38 00000000 00000000 7f40f020 00000000 b99c86c0 00000001 b99c8754
[    6.181359] fdc0: b6438524 00000002 ba52fe0c ba52fdd8 7f4045d8 7f4043c4 000001e0 000002d0
[    6.181369] fde0: 00000000 807790b0 7f40f020 00000000 b99c86c0 00000001 b99c8754 b6438524
[    6.181381] fe00: ba52fe34 ba52fe10 7f4074b0 7f4045ac 00000000 00000000 00000000 b99c8754
[    6.181391] fe20: 00000001 b6438400 ba52fe4c ba52fe38 7f407334 7f407468 00000002 b99c86c0
[    6.181401] fe40: ba52fe6c ba52fe50 7f40740c 7f407300 00000001 b6438400 00000001 00000000
[    6.181412] fe60: ba52fe7c ba52fe70 7f407458 7f407370 ba52fe8c ba52fe80 7f407bbc 7f407430
[    6.181423] fe80: ba52fe9c ba52fe90 7f43f614 7f407ba8 ba52feb4 ba52fea0 7f3f6db4 7f43f600
[    6.181433] fea0: 00000000 b643860c ba52fefc ba52feb8 7f3f7890 7f3f6d8c baae7940 baae7940
[    6.181444] fec0: b7742f1c baae7940 00000000 00000000 ba52fefc ba4d1300 b643860c baae7940
[    6.181454] fee0: baaea900 00000000 00000008 00000000 ba52ff34 ba52ff00 801370d8 7f3f7800
[    6.181465] ff00: baae7958 80c02d00 00000008 baae7940 ba4d1318 baae7940 baae7958 80c02d00
[    6.181475] ff20: 00000008 ba4d1300 ba52ff7c ba52ff38 80137438 80136f8c ba52ff5c 00000000
[    6.181486] ff40: 80c02d00 80c02d00 80c81a0a ba52e038 ba43d69c ba43d680 00000000 ba43d600
[    6.181497] ff60: ba4d1300 801373d4 ba43d69c ba4eddd0 ba52ffac ba52ff80 8013d4a8 801373e0
[    6.181507] ff80: ffffffff ba43d600 8013d36c 00000000 00000000 00000000 00000000 00000000
[    6.181517] ffa0: 00000000 ba52ffb0 8010812c 8013d378 00000000 00000000 00000000 00000000
[    6.181527] ffc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[    6.181537] ffe0: 00000000 00000000 00000000 00000000 00000013 00000000 aeaafcb2 bbef3aa8
[    6.181800] [<7f3ffd08>] (handle_conflicting_encoders [drm_kms_helper]) from [<7f400030>] (drm_atomic_helper_check_modeset+0x17c/0xae0 [drm_kms_helper])
[    6.182024] [<7f400030>] (drm_atomic_helper_check_modeset [drm_kms_helper]) from [<7f401484>] (drm_atomic_helper_check+0x20/0x88 [drm_kms_helper])
[    6.182391] [<7f401484>] (drm_atomic_helper_check [drm_kms_helper]) from [<7f1f0d10>] (drm_atomic_check_only+0x300/0x620 [drm])
[    6.182852] [<7f1f0d10>] (drm_atomic_check_only [drm]) from [<7f1f1050>] (drm_atomic_commit+0x20/0x68 [drm])
[    6.183189] [<7f1f1050>] (drm_atomic_commit [drm]) from [<7f404534>] (restore_fbdev_mode_atomic+0x17c/0x1e8 [drm_kms_helper])
[    6.183411] [<7f404534>] (restore_fbdev_mode_atomic [drm_kms_helper]) from [<7f4045d8>] (restore_fbdev_mode+0x38/0x168 [drm_kms_helper])
[    6.183635] [<7f4045d8>] (restore_fbdev_mode [drm_kms_helper]) from [<7f4074b0>] (drm_fb_helper_restore_fbdev_mode_unlocked+0x54/0xa4 [drm_kms_helper])
[    6.183856] [<7f4074b0>] (drm_fb_helper_restore_fbdev_mode_unlocked [drm_kms_helper]) from [<7f407334>] (drm_fb_helper_set_par+0x40/0x70 [drm_kms_helper])
[    6.184081] [<7f407334>] (drm_fb_helper_set_par [drm_kms_helper]) from [<7f40740c>] (drm_fb_helper_hotplug_event.part.7+0xa8/0xc0 [drm_kms_helper])
[    6.184305] [<7f40740c>] (drm_fb_helper_hotplug_event.part.7 [drm_kms_helper]) from [<7f407458>] (drm_fb_helper_hotplug_event+0x34/0x38 [drm_kms_helper])
[    6.184528] [<7f407458>] (drm_fb_helper_hotplug_event [drm_kms_helper]) from [<7f407bbc>] (drm_fbdev_cma_hotplug_event+0x20/0x24 [drm_kms_helper])
[    6.184707] [<7f407bbc>] (drm_fbdev_cma_hotplug_event [drm_kms_helper]) from [<7f43f614>] (vc4_output_poll_changed+0x20/0x24 [vc4])
[    6.184883] [<7f43f614>] (vc4_output_poll_changed [vc4]) from [<7f3f6db4>] (drm_kms_helper_hotplug_event+0x34/0x38 [drm_kms_helper])
[    6.185104] [<7f3f6db4>] (drm_kms_helper_hotplug_event [drm_kms_helper]) from [<7f3f7890>] (output_poll_execute+0x9c/0x1a0 [drm_kms_helper])
[    6.185230] [<7f3f7890>] (output_poll_execute [drm_kms_helper]) from [<801370d8>] (process_one_work+0x158/0x454)
[    6.185251] [<801370d8>] (process_one_work) from [<80137438>] (worker_thread+0x64/0x5b8)
[    6.185267] [<80137438>] (worker_thread) from [<8013d4a8>] (kthread+0x13c/0x16c)
[    6.185283] [<8013d4a8>] (kthread) from [<8010812c>] (ret_from_fork+0x14/0x28)
[    6.185295] Code: e5992014 e1530002 ba00003e e5943310 (e5937008) 
[    6.185423] ---[ end trace fde467cac9861d39 ]---
```
I'll merge the other commits and leave the overlay until you've had time to look at it, unless you have a suggestion now.

**Comment by pelwell** [comment]
I think it's crashing here (https://github.com/raspberrypi/linux/blob/rpi-4.14.y/drivers/gpu/drm/drm_atomic_helper.c#L156) because connector->state (r3) is NULL.

**Comment by anholt** [comment]
Are we still paying attention to 4.9?  Should I look into this?

**Comment by timofonic** [comment]
@anholt @6by9 @pelwell Excuse me my ignorance and disturbance due to my naive curiosity. Does this mean 4.9.y code isn't still merged in newer kernels or backporting code to 4.9.y. If the second: Why living in the past? There's enough shame with rpi3 in ARMv8-A 64bit mode not having the full features of ARMv7 32bit one, why not focus on things like this and better VC4 acceleration?

**Comment by JamesH65** [comment]
4.9 is still the release kernel, although we should be moving to 4.14 soon. But I believe we will only backport bug fixes now, and probably not fixes for this driver, since its beta anyway, but only for other areas (i.e. we just backported a network driver fix).

**Comment by 6by9** [comment]
@anholt This PR is pulling patches that are in the 4.9 branch but missing from 4.14, so popcornmix's reported issue is on 4.14 with these patches.
As discussed elsewhere, I should be investigating KMS/GL stuff this coming week, so I'll have a look at it (although any pointers gratefully accepted)

**Pull request closed without merging**
