### PR TITLE
added basic docker support

### PR DESCRIPTION
**Pull request by umiddelb**
as discussed [here](https://github.com/raspberrypi/linux/pull/1020)

### CODE REVIEW

**Comment by pelwell** [comment]
Running free -h and nbench before:

```
$ free -h
             total       used       free     shared    buffers     cached
Mem:          736M        43M       693M         0B        20K        17M
-/+ buffers/cache:        25M       711M
Swap:          99M         0B        99M
$ time ./nbench
...
real    4m16.786s
user    4m16.430s
sys     0m0.090s
$ free -h
             total       used       free     shared    buffers     cached
Mem:          736M        43M       693M         0B        20K        18M
-/+ buffers/cache:        24M       711M
Swap:          99M         0B        99M
```

and after:

```
$ free -h
             total       used       free     shared    buffers     cached
Mem:          736M        42M       694M         0B        20K        18M
-/+ buffers/cache:        24M       712M
Swap:          99M         0B        99M
$ time ./nbench
real    4m15.989s
user    4m15.560s
sys     0m0.100s
$ free -h
             total       used       free     shared    buffers     cached
Mem:          736M        43M       693M         0B        20K        18M
-/+ buffers/cache:        24M       712M
Swap:          99M         0B        99M
```

merging the PR, so a very small performance loss and no real change in free space.

**Comment by DieterReuter** [comment]
Well done, @umiddelb!

**Comment by djmaze** [comment]
Thanks! That finally means Docker for everybody ;)

**Comment by chris-kobrzak** [comment]
Fantastic news, huge thanks to everyone involved!

**Comment by umiddelb** [comment]
@popcornmix @pelwell How can I see, if the [default raspbian image](http://downloads.raspberrypi.org/raspbian_latest) will be shipped with this or a newer kernel version?

**Comment by popcornmix** [comment]
The raspbian download has a release date (https://www.raspberrypi.org/downloads/).
New images ship with pretty much the latest firmware/kernel, so I'm sure the next update will include this. Can't say when that will happen though.

**Pull request merged**
