### PR TITLE
8192cu: CONFIG_AP_MODE hardcoded in autoconf.h

### PR DESCRIPTION
**Pull request by syntheticpp**
See https://github.com/raspberrypi/linux/commit/0ed1e9cb588e99bbeb745668101e0b134889b294

### CODE REVIEW

**Comment by syntheticpp** [comment]
When committing to 3.18 also cherry-pick into 4.0.

**Comment by popcornmix** [comment]
@MrEngman does this commit fix your issue?

**Comment by MrEngman** [comment]
Yes, thank you

**Comment by popcornmix** [comment]
Cherry-picked to rpi-4.0.y

**Pull request merged**
