### PR TITLE
I have fixed many grammatical errors in files in  Documentation/admin-guide

### PR DESCRIPTION
**Pull request by Abhigyankrsingh**
I have checked and fixed many grammatical errors in Documentation /admin-guide

### CODE REVIEW

**Comment by pelwell** [comment]
That's an amazing effort, but unfortunately these corrections should be sent to the main Linux maintainers so that everyone benefits, not just Raspberry Pi users. Because the kernel devs are working on 5.10 now, you may also find that some of this documentation has already been changed.

**Comment by Abhigyankrsingh** [comment]
@pelwell  , Sir how can I send these contributions to the main Linux maintainers? Sir, could you please add me as a collaborator in Linux so, that I can easily work in these repositories and contribute in the future because I want to work so much for Linux repositories. and Sir, could you please merge these contributions in raspberrypi. Thank you so much for your time, sir.

**Comment by JamesH65** [comment]
See the kernel submission docs here https://www.kernel.org/doc/html/latest/process/submitting-patches.html That should tell you everything you need to know.

Once contributions are accepted upstream by the kernel devs, we will get them in to the Raspberry pi tree as part of our updating procedure.

**Comment by Abhigyankrsingh** [comment]
@JamesH65   Sir, https://www.kernel.org/doc/html/latest/process/submitting-patches.html it is  little complicated because I have fixed errors in many files. but I will try my best sir. Thanks for your time, sir

**Comment by Abhigyankrsingh** [comment]
Thanks, @pelwell  and @JamesH65  for your time

**Pull request closed without merging**
