### PR TITLE
i2c-bcm2708: fixed baudrate

### PR DESCRIPTION
**Pull request by brabl2**
Fixed issue where the wrong CDIV (Clock Divider) register value was set for baudrates below 3815 Hz (for 250MHz bus clock). In that case the computed CDIV value was more than 0xffff. However the CDIV register width is only 16 bits. This resulted in incorrect setting of CDIV and higher baudrate than intended. 
Example: baudrate=3500Hz -> CDIV=0x11704 -> CDIV(16bit)=0x1704 -> baudrate=42430Hz

### CODE REVIEW

**Comment by popcornmix** [comment]
Presumably with your fix, you get:
Example: baudrate=3500Hz -> CDIV=0x11704 -> CDIV(16bit)=0xffff -> baudrate=3815Hz
So, I agree it is better, but still may be a problem?

**Comment by brabl2** [comment]
With limited Clock Divider there is not any clean solution of the low baudrate problem.
When the CDIV > 0xffff there are two possible solutions:
1) Use the CDIV = 0xffff and give the information that the i2c module is working using different baudrate than intended.
2) Or completely cancel the i2c module initialization.
The patch for number 1) is above.

**Comment by popcornmix** [comment]
Yes, logging the actual baudrate is better. Can you squash the two commits, force push,  and I'll merge.

**Comment by brabl2** [comment]
It is ready.

**Pull request merged**
