### PR TITLE
Sound drivers for Dion Audio Kiwi streamer

### PR DESCRIPTION
**Pull request by miquel83blauw**
updated files. Kernel compiled and tested.

### CODE REVIEW

**Comment by pelwell** [comment]
That's much better, but there are still a few minor issues:
* The README entry needs 2 blank lines between entries.
* You still don't need a Kconfig entry - nothing is using it.
* Alphabetical order in the Makefile too, please.

**Comment by miquel83blauw** [comment]
The code has been modified. Thank you for the quick replies.

**Comment by pelwell** [comment]
That now passes my tests (I removed the extra Kconfig whitespace), but the commits are a mess. If you are working on a local git branch (and you really ought to - it will save you a lot of time in the long run) then you need to do a `git reset origin/rpi-5.15.y` (which leaves the changes but loses the commits), then use `git add -p` or `git add <file>` to create commits - one for the rpi-simple-audiocard change and one for the overlay. Then `git push -f` to update your branch on GitHub, which will also update the PR.

**Comment by pelwell** [comment]
Do say if that sounds too difficult - just give me a "Signed-off-by:" and I can prepare the commits on your behalf.

**Comment by miquel83blauw** [comment]
:) Since software engineering is all new to me, everything is indeed a bit difficult, but we are never too old to learn.

Signed-off-by: Miquel Blauw

Thank you for your help!

**Comment by pelwell** [comment]
Do you have an email address I can include in that Signed-off-by?

**Comment by miquel83blauw** [comment]
Ow yes, that's miquelblauw@hotmail.com.

**Comment by pelwell** [comment]
Thanks - that's all done. The GitHub documentation should help you get started with using git on the command line: https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories

**Pull request merged**
