### PR TITLE
dts: 2712: Drop some numa options from bootargs

### PR DESCRIPTION
**Pull request by popcornmix**
iommu_dma_numa_policy=interleave is not valid in the current tree It generates an unknown setting will be passed to usespace warning

system_heap.max_order=0 is wanted when numa is enabled, but may not be when it is disabled.

Add it on firmware side when we know if `numa=fake=<n>` is used.

### CODE REVIEW

**Comment by popcornmix** [comment]
Draft until bootloader side is merged and available.

**Comment by popcornmix** [comment]
Bootloader should [now do this](https://github.com/raspberrypi/rpi-eeprom/commit/3eecae99756865406bf30693ee2e7c20dad8f947), so marking this as ready.

**Comment by pelwell** [comment]
You'll need to resolve the merge conflict.

**Comment by popcornmix** [comment]
Rebased

**Pull request merged**
