### PR TITLE
Audio

### PR DESCRIPTION
**Pull request by VT-Github-Raspberrypi**

### CODE REVIEW

**Comment by VT-Github-Raspberrypi** [comment]
commit ca6469b536c06ad5d944ad0203a15b7864aa85d7
Author: VT-Github-Raspberrypi <github.raspberrypi@votarytech.com>
Date:   Mon Aug 7 15:24:52 2017 +0530

    ARM64: bcm2837: enable sdhost in device tree for the
    Raspberry Pi 3
    branch rpi-4.12.y
    
    Fix for https://github.com/raspberrypi/linux/issues/2151
    
    Signed-off-by: VT-Github-Raspberrypi <github.raspberrypi@votarytech.com>

**Comment by pelwell** [comment]
It looks like you didn't prepare your patch against our tree - you need to rebase (at least).

**Review by VT-Github-Raspberrypi — COMMENTED** [review]
it looks good to me.

**Comment by pelwell** [comment]
> Commits 187

and

> Files changed 629

don't look right to me.

**Pull request closed without merging**
