### PR TITLE
Google VoiceHAT fixups

### PR DESCRIPTION
**Pull request by 6by9**
Fixed issue flagged from https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=224931 of not reading the sdmode GPIO from DT.

Cleaned up all checkpatch issues whilst I was there.

### CODE REVIEW

**Comment by popcornmix** [comment]
Looks plausible to me.
@HiassofT does it look okay to you?

**Comment by 6by9** [comment]
I have a VoiceHAT sitting here if you wanted to try it.

**Comment by HiassofT** [comment]
Yes, looks fine, looking at DT overlay gpio was definitely grabbed from the wrong device / node. Puzzling how this could have worked before...

**Comment by 6by9** [comment]
I don't think it did work under 4.18 after the conversion from codec to component https://github.com/raspberrypi/linux/commit/dd71d79267b30682132b7602f399ae76c07f14f6 
The forum report initially said it was failing on 4.18 and there are no other changes in that area that I could see based on a quick look.

**Comment by popcornmix** [comment]
I cherry picked this to 4.18 as it looks like it is needed there too.
I'll bump the branch=next kernel and see if it resolved the reported issue.

**Comment by HiassofT** [comment]
Ah, yes, that makes sense. It was codec before in 4.14 and should then be component in 4.17+. "card" seems to have accidentally sneaked in

**Pull request merged**
