### PR TITLE
drm: rp1: rp1-dpi: Fix optional dependency on RP1_PIO

### PR DESCRIPTION
**Pull request by njhollinghurst**
Add optional dependency to Kconfig, and conditionally compile PIO-dependent code. Add a mode validation function to reject interlaced modes when RP1_PIO is not present.

### CODE REVIEW

**Comment by njhollinghurst** [comment]
Purported fix for #6529, in testing with various defconfigs...

**Comment by 6by9** [comment]
I think you want [`IS_REACHABLE`](https://elixir.bootlin.com/linux/v6.12.4/source/include/linux/kconfig.h#L65).
Simple use of ifdef has a tendency to do bad things if one half gets built-in and the other half is a module.

**Comment by njhollinghurst** [comment]
Ah yes, I think I do want that.

At the Kconfig level, this [documentation](https://github.com/raspberrypi/linux/blob/rpi-6.6.y/Documentation/kbuild/kconfig-language.rst#optional-dependencies) suggests there's already a trap for built-in depending on module (though it's far from obvious from the syntax how it achieves that...)

**Review by pelwell — APPROVED** [review]

**Comment by 6by9** [comment]
LGTM

**Comment by njhollinghurst** [comment]
Tested and works as expected with `CONFIG_RP1_PIO=m`, `y` and undefined.

**Pull request merged**
