### PR TITLE
spi: Migrate bcm2708 to generic queueing

### PR DESCRIPTION
**Pull request by hkallweit**
The bcm2708 spi driver still uses an own queueing what is considered
deprecated. The generic spi code therefore prints a warning
"master is unqueued, this is deprecated"
This patch migrates the driver to using the generic queueing.

Signed-off-by: Heiner Kallweit hkallweit1@gmail.com

### CODE REVIEW

**Comment by popcornmix** [comment]
Ping @msperl

**Comment by msperl** [comment]
I recommend using spi-bcm2835 instead - it comes with the foundation kernel already and there exists an overlay to use that driver instead of the spi-bcm2708.

On top of that spi-bcm2835 contains a lot of other optimizations and features that are not found in spi-bcm2708 (less interrupts, 3 wire mode, more distinct clock frequencies,...)

There is a patch to that driver that already uses DMA for longer spi-transfers (3ecd37edaa2a6ba3246e2c35714be9316b1087fe, 7e52be0d576e8f7bc99a606f07b9d000c4340f04 and 29ad1a7a9e08f1d2b6795c5278a0c0fd23679ded) - which has been merged into spi/for-next and that means that as soon as the merge window for 4.2 opens (and it has been accepted by Linux) we can create a request to merge that into the foundation kernels as well.

Finally the patch only implements the transfer_one_message interface and not the transfer_one interface which is the new interface that people should be use to code drivers (and which will also get depreciated eventually).

**Comment by hkallweit** [comment]
OK. Meanwhile I switched to bcm-2835 by activating the overlay.
Not sure why it's not the default. Thanks for the additional insight.

**Comment by msperl** [comment]
If you look at the original ticket for the overlay then the idea was for a gradual move.
First just enable it as an overlay and if there are no issues then make it the default with the fallback to the old.

The question is when we want to make this change... 
@popcornmix when should we change it?

**Comment by popcornmix** [comment]
If you say that switching to spi-bcm2835 is unlikely to break things for existing spi users and is a better driver, then I've no objections.
@pelwell okay with you?

**Comment by msperl** [comment]
For reference see these for the original discussion:
https://github.com/raspberrypi/linux/issues/864
https://github.com/raspberrypi/linux/pull/866

In principle we have spi-bcm2708 as a fallback for issues not seen.

I am only using spi-bcm2835 now with 4 different devices (2 mcp2515, enc28j60, mmc_spi, fbtft) and all are active at the same time without any issues...

**Comment by pelwell** [comment]
I'm not really an SPI user so I'm going to have to take it on trust that the new driver is good, but providing we have an overlay to revert to the old driver should people have problems then I think we should make the switch.

**Comment by msperl** [comment]
Shall I create an overlay for spi-bcm2708 and change the default in the device-tree to spi-bcm2835?
As there are people using the spi-bcm2835-overlay I guess we will need to keep that one...

**Comment by msperl** [comment]
created #987 to activate spi-bcm2835 by default.
I have only created a merge request for 4.0.y as I assume this is the most likley candidate for release...

**Comment by pelwell** [comment]
@hkallweit Now that #987 has been merged for a while and in a few firmware updates, are you happy to close this?

**Comment by hkallweit** [comment]
Yes, can be closed.

**Pull request closed without merging**
