### PR TITLE
FKMS - correct possible_crtcs flags, and increase the number of planes

### PR DESCRIPTION
**Pull request by 6by9**

### CODE REVIEW

**Comment by 6by9** [comment]
@pelwell @popcornmix Any comment on this one?

**Comment by pelwell** [comment]
What's wrong with something like:
```
	for (i = 0; i < PLANES_PER_CRTC; i++) {
		planes[i] = vc4_fkms_plane_init(drm,
						(i == 0) ? DRM_PLANE_TYPE_PRIMARY :
						(i == PLANES_PER_CRTC -1) ? DRM_PLANE_TYPE_CURSOR :
						DRM_PLANE_TYPE_OVERLAY,
						display_ref,
						i + (display_idx * PLANES_PER_CRTC)
					       );
		if (IS_ERR(planes[i])) {
			dev_err(dev, "failed to construct plane\n");
			ret = PTR_ERR(planes[i]);
			goto err;
		}
	}
```
?

**Comment by 6by9** [comment]
Rebased and reworked so that the commits make more sense. Increase the number of planes, and then fix the possible_crtcs flags.

**Comment by pelwell** [comment]
It's hard to argue with code like that.

**Pull request merged**
