### PR TITLE
Checkpatch cleanup of bcm2708_fb.c

### PR DESCRIPTION
**Pull request by JamesH65**
Mostly whitespace stuff, but some minor change to function - 
remove a use of in_atomic, plus replacing various debug messages
that manually specify the function name with ("%s",.__func__)

### CODE REVIEW

**Comment by JamesH65** [comment]
@popcornmix @pelwell This is the checkpatch cleanup with the in_atomic also removed.

**Comment by pelwell** [comment]
Checkpatch still objects to this patch:
```
WARNING: A patch subject line should describe the change not the tool that found it
#4: 
Subject: [PATCH] Checkpatch cleanup of bcm2708_fb file

WARNING: 'noticable' may be misspelled - perhaps 'noticeable'?
#125: FILE: drivers/video/fbdev/bcm2708_fb.c:363:
+		 * currently bcm2708_fb_set_par takes noticable time when

ERROR: Missing Signed-off-by: line(s)
```

**Comment by JamesH65** [comment]
Hmm, that's the difference between checkpatch.pl <file> and checkpatch -f <file>...! Will fix the spellings, which I thought I had already fixed...

**Comment by pelwell** [comment]
And a Signed-off-by line?

**Comment by pelwell** [comment]
Ta.

**Pull request merged**
