### PR TITLE
V4L2 tweaks, and GPIO expander driver

### PR DESCRIPTION
**Pull request by 6by9**
1st patch is a slightly bizarre one.
The timestamp on any inline header bytes of an H264 stream comes back as 0. This patch now gives them the same timestamp as the previous frame to the header bytes.
On the VPU the header bytes are detached from any "job", and only the job has a timestamp. It might be possible to work around that and provide timestamps from the VPU, but it's an interesting question as to what the appropriate timestamp should be.

2nd is tagging keyframes correctly at the V4L2 level. The MMAL buffers already had the flags set.

3rd is as reviewed by Phil already to add a new driver to control the FXL6408 GPIO expander via the mailbox service. Supports state and direction control, and has plumbed through the power LED via DT.

### CODE REVIEW

**Comment by 6by9** [comment]
@popcornmix Happy to merge?
Phil had reviewed the gpio-exp driver and was happy. The other two are relatively trivial V4L2 fixes.

**Comment by JamesH65** [comment]
They all looked OK to me.


On 23 February 2017 at 11:28, 6by9 <notifications@github.com> wrote:

> @popcornmix
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_popcornmix&d=DwMCaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=TRVAbn9poIN5NwUJ7tkaLnf2AKLiXi4zADhdIsRNW2o&s=-aC900KPT1dVEAcwRB3iknf9gpNqNEZWRJcwVqrJBkA&e=>
> Happy to merge?
> Phil had reviewed the gpio-exp driver and was happy. The other two are
> relatively trivial V4L2 fixes.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_raspberrypi_linux_pull_1852-23issuecomment-2D281967689&d=DwMCaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=TRVAbn9poIN5NwUJ7tkaLnf2AKLiXi4zADhdIsRNW2o&s=bP-K3cR2iEQ0zCb7aGJGTSwhbhLsLof9zoHHHgTUC1c&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADqrHSXyRarLe-5F33g7dk8f8sMsvsh0Ffks5rfW1TgaJpZM4MIi3L&d=DwMCaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=TRVAbn9poIN5NwUJ7tkaLnf2AKLiXi4zADhdIsRNW2o&s=3xmd6IP-TRVipDt3AGOhqzrl5mBfuxBlv8YnrR9RNC0&e=>
> .
>



-- 
James Hughes
Principal Software Engineer,
Raspberry Pi (Trading) Ltd

**Comment by Electron752** [comment]
@6by9: Any plans to send the expander driver upstream?  I know video on the RPI 3 is quite broken at the moment since HDMI connection detection isn't possible.  For upstream testing, I've had to rely on the trick that simplefb gets loaded first and keep vc4 out of the config.  Either that, or hack the vc4 driver to fake an always connected connection.

**Comment by 6by9** [comment]
> Any plans to send the expander driver upstream? I know video on the RPI 3 is quite broken at the moment since HDMI connection detection isn't possible.

I had no real intentions of submitting upstream, but I'd hope it was in a state that can be accepted without too much change. I was going to send a message to the rpi-linux list once this was merged just to say it was available and let them make the call over it.

**Comment by 6by9** [comment]
@pelwell Anything else you want to see in here? You've already reviewed the GPIO driver.
Or are you waiting on popcornmix?

**Comment by pelwell** [comment]
I couldn't really comment on the v4l2 changes, but with @JamesH65 behind it how could I say no?

**Comment by 6by9** [comment]
OK, I'm happy to wait on popcornmix to have a quick look at the V4L2 changes.

**Comment by JamesH65** [comment]
I am, quite literally, behind him, but that should not be regarded as
gospel.

On 27 February 2017 at 15:47, 6by9 <notifications@github.com> wrote:

> OK, I'm happy to wait on popcornmix to have a quick look at the V4L2
> changes.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_raspberrypi_linux_pull_1852-23issuecomment-2D282758098&d=DwMCaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=oUkANKJYf14Cb-ZaJXAU3gEK7NCQaYHXt5iM2uhh2oo&s=TOj9VZEjOpCW9vNohqFKnhG7kvOpBkDkz_przTRxb-A&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADqrHclFec6i9LOstiVnK1YBQvVcYEmJks5rgvAdgaJpZM4MIi3L&d=DwMCaQ&c=DpyQ_ftY536pf7wCBQXXU58xADDRY77THQzJu1OmzOo&r=w09_2ePv8G3zRjoV19Wm1Q6rI7CDlOns4PuRv2hHkek&m=oUkANKJYf14Cb-ZaJXAU3gEK7NCQaYHXt5iM2uhh2oo&s=coZhYjqW8TL9BY7C4MkrD-zkuDBxXs_7-YLTVGg18yI&e=>
> .
>



-- 
James Hughes
Principal Software Engineer,
Raspberry Pi (Trading) Ltd

**Comment by pelwell** [comment]
Ping @popcornmix.

**Pull request merged**
