### PR TITLE
BCM2708: use pinctrl-bcm2835

### PR DESCRIPTION
**Pull request by notro**
See #747

### CODE REVIEW

**Comment by popcornmix** [comment]
@pelwell okay with you?

**Comment by pelwell** [comment]
I have no objections in principle, but I haven't tested the changes.

**Comment by popcornmix** [comment]
Currently running with this PR applied and seems fine.
Would you expect exporting gpios to work?

I've tried removing bcm2708_gpio_request/bcm2708_gpio_free with no change in behaviour.

**Comment by pelwell** [comment]
That's not something I have experience of, but provided this patch doesn't make it worse then I think we should merge it anyway.

**Comment by pelwell** [comment]
Exporting GPIOs is working for me on 3.18.y:

```
pi@raspberrypi:/sys/class/gpio$ echo 17 > export
pi@raspberrypi:/sys/class/gpio$ ls -l
total 0
-rwxrwx--- 1 root gpio 4096 Jan  2 16:33 export
lrwxrwxrwx 1 root gpio    0 Jan  2 16:31 gpio18 -> ../../devices/soc/20200000.gpio/gpio/gpio18
lrwxrwxrwx 1 root gpio    0 Jan  1  1970 gpiochip0 -> ../../devices/soc/20200000.gpio/gpio/gpiochip0
-rwxrwx--- 1 root gpio 4096 Jan  1  1970 unexport
```

If you see the problem again, please record the error message, which modules are loaded, and anything else you think might be relevant.

**Pull request merged**
