### PR TITLE
Migrate to the Common Clock Framework

### PR DESCRIPTION
**Pull request by notro**
As part of moving towards using Device Tree, the Common Clock Framework
has to be used instead of the BCM2708 clock implementation.

### CODE REVIEW

**Comment by popcornmix** [comment]
Currently running with this PR in place. No problems observed so far.

**Comment by notro** [comment]
Another observation I did, is that there seem to no users of this clock:

```
    clk = bcm2708_clk_register("osc_clk", 500000000);
    bcm2708_register_clkdev(clk, "bcm2708_usb");
```

Looking through [drivers/usb/host/dwc_otg/dwc_otg_driver.c](https://github.com/raspberrypi/linux/blob/rpi-3.15.y/drivers/usb/host/dwc_otg/dwc_otg_driver.c) I couldn't find that it uses this clock.

**Comment by popcornmix** [comment]
Possibly something left over from long ago.
@P33M okay to remove that?

**Comment by P33M** [comment]
The OTG driver doesn't use the Linux clock framework, so it should be safe to remove.

It should be made to do so in future - the PHY input clock in particular is used for several calculations.

**Comment by notro** [comment]
I just tried removing it, and I couldn't see any ill effects.

@popcornmix 
Can I add a another commit to this PR, or do you want me to redo the whole PR?

**Comment by popcornmix** [comment]
Just add a commit to your clock branch and (force) push.

**Pull request merged**
