### PR TITLE
vcio rewrite

### PR DESCRIPTION
**Pull request by pelwell**
#4620 identified a problem with kernel startup ordering that can break the vcio device. This PR avoids the problem by making vcio a platform device, instantiated from Device Tree.

Note that using the new driver will require a corresponding udev rule change (backwards-compatible):
```
KERNEL=="vcio", GROUP="video", MODE="0660"
```
(was `SUBSYSTEM=="bcm2708_vcio", ...`)

### CODE REVIEW

**Comment by pelwell** [comment]
@vianpl @waveform80 @Dark-Sky @graysky2 I'd like to merge this PR soon but also want to warn you about the possible need to update your udev rules as shown above. If you are make that change, I would recommend also changing the rule for vchiq in the same way:
```
KERNEL=="vcio", GROUP="video", MODE="0660"
KERNEL=="vchiq", GROUP="video", MODE="0660"
```

**Comment by vianpl** [comment]
@mbgg :arrow_up: 
@pelwell Thanks for letting us know! :slightly_smiling_face:

**Comment by graysky2** [comment]
@pelwell - Thanks for the heads-up

**Comment by pelwell** [comment]
I should also have mentioned that it is safe to make the udev changes now - they are backwards compatible.

**Comment by graysky2** [comment]
@pelwell - For Arch ARM, I believe this change only affects a single line.  Can you view the above mentioned commit in my udev rules for kodi for sanity?

**Comment by pelwell** [comment]
That looks fine (although it doesn't need the extra space).

The vchiq change is only in linux-next at the moment, so you have plenty of time to roll out your patch.

**Comment by graysky2** [comment]
Thanks, if it is backwards compatible I will just work it in sooner than later or else I might forgot :smile:

**Comment by Dark-Sky** [comment]
@pelwell Thank you very much for the heads up!

**Comment by pelwell** [comment]
Thank you all - this PR has now been merged. Send any complaints in my direction.

**Comment by pelwell** [comment]
P.S. RPiOS users can install the updated udev rule with:
```
$ sudo apt update
$ sudo apt install libraspberrypi0
```

**Pull request merged**
