### PR TITLE
Add support for wm8750 for Raspberry Pi

### PR DESCRIPTION
**Pull request by GTrannoy**

### CODE REVIEW

**Comment by pelwell** [comment]
There are a number of problems with this PR:
1) It doesn't look finished. It is changing while I type this.
2) It contains too many commits - I'd be happy with a single initial commit introducing a new module.
3) It doesn't include Pi2 support.
4) We are no longer accepting additions to the board support code that add platform devices - you need to use Device Tree instead.

These are really only three, since the solution to 3 is to remove the explicit Pi1 support and create a Device Tree overlay instead.

You can find lots of examples of overlays in arch/arm/boot/dts/*-overlay.dts, and documentation [here](https://www.raspberrypi.org/documentation/configuration/device-tree.md).

It may look overwhelming to start with, but I think that if you take hifiberry-dac-overlay.dts and change names and compatible string that it should do what you want. You then need to edit the Makefile in that folder so that the .dtb gets built. Finally, squash (git rebase -i) the commits into one and use "git push -f" to resubmit your squashed commit.

**Comment by GTrannoy** [comment]
Thank you for your suggestions and advices.
I agree with problems you mentioned and I will do wm8750 support by Device Tree Overlay..
I am discovering git and apologize for bad practices of PR or commits.

**Comment by pelwell** [comment]
No apology needed. And FYI, you could have left this open and used "git push -f" had you wanted to.

**Comment by GTrannoy** [comment]
Thx. I try to squash the commits but it's a little complicated as i made change directly on github.com...

Just a question, please : I want make a dts overlay to endorse the audio codec. For example, in "rpi-proto-overlay.dts" this is a link to hardware description (compatible) which relies on specific codec wm8731 as I can see in "rpi-proto.c".
Can I use same 'compatible' in 'target = <&sound>;' and just overlay the codec in another fragment ?

**Comment by pelwell** [comment]
The compatible string in the <&sound> fragment identifies the sound card, so in your case it should be `"rpi,rpi-wm8750"`.

The <&i2s> fragment remains the same.

The <&i2c1> fragment must be changed for the wm8750. If you change `wm8731` to `wm8750`, and change `1a` (including `0x1a`) to the I2C address of the codec, it should work.

Build your overlay using the "dtbs" kernel make target, and when testing it you might want to add `dtdebug=1` to your config.txt, then use `sudo vcdbg log msg` to see information about the Device Tree processing in the firmware.

**Comment by GTrannoy** [comment]
Ok, I'll try that and tell you.

**Comment by GTrannoy** [comment]
@pelwell ,
For information, I have rewrite a 'rpi-wm8750.c' on the base of the 'rpi-proto.c' and can enable it thanks to the Device Tree.
I can see the codec, but no sound. When I check with an oscilloscope the BCLK which would be on GPIO28, this is no signal.

I search why ?
Normally i2s master on the wm8750, like on the wm8731 with rpi-proto, but no clock. I have the MCLK of the device ok, i2c seems to operate the codec, but i2s not responding. I think it a problem on the bcm2708 part.
I have tested in the "bcm2708-rpi-cm.dtb' to change default i2s pins with:
i2s {
                brcm,pins = <0x1c 0x1d 0x1e 0x1f>;
                brcm,function = <0x4>;
                                ...
In which brcm, function was changed to <0x6>, because I believe it is for the ALT2 function.
But nothing...

I feel I must be near the solution... :-s

I'll tell you when it works. And don't hesitate if you have a suggestion.

**Comment by pelwell** [comment]
What does your overlay look like? And what does the final device tree look like?

If you upload your -overlay.dts and the output of:

```
dtc -I fs
```

somewhere (gist, pastebin, sprunge etc.) and post a link then I'll take a look.

**Comment by GTrannoy** [comment]
Thx for your help.

My overlay [http://pastebin.com/DF77UwyA](http://pastebin.com/DF77UwyA)
And result of _dtc -I dtb_ (I suppose it was _dtb_ because error with _fs_) [http://pastebin.com/mEeXtRix](http://pastebin.com/mEeXtRix).

I investigate too the 'bcm2708-i2c.c' in which i2s pins is auto assigned:

```
    /* I2S pin configuration */
    static int bcm2708_i2s_gpio=BCM2708_I2S_GPIO_AUTO;
```

I think it is set for pins 18, 19, 20, 21:

```
    if (bcm2708_i2s_gpio==BCM2708_I2S_GPIO_AUTO) {  
            if ((system_rev & 0xffffff) >= 0x10) {
                /* Model B+ */
                pinconfig=BCM2708_I2S_GPIO_PIN18;
            } else {
                /* original */
                pinconfig=BCM2708_I2S_GPIO_PIN28;
            }
        } else {
            pinconfig=bcm2708_i2s_gpio;
        }
```

But I believed we can specify how 'bcm2708-i2c.c' configure pins with the declaration of sound dai link (0:auto, 1=pins 18:21, 2=pins 28:31):

```
    static struct snd_soc_dai_link snd_rpi_wm8750_dai[] = {
    {
        .name       = "WM8750",
        .stream_name    = "WM8750 HiFi",
        .cpu_dai_name   = "bcm2708-i2s.2",
        .codec_dai_name = "wm8750-hifi",
        .platform_name  = "bcm2708-i2s.2",
        .codec_name = "wm8750.1-001a", /* .bus-address */
        .dai_fmt    = SND_SOC_DAIFMT_I2S
                    | SND_SOC_DAIFMT_NB_NF
                    | SND_SOC_DAIFMT_CBM_CFM,
        .ops        = &snd_rpi_wm8750_ops,
    },
    };
```

I test with '.2' like code just above.
I try changing 'bcm2708-i2c.c' pin configuration too:

```
    static int bcm2708_i2s_gpio=BCM2708_I2S_GPIO_PIN28;
```

On oscilloscope, I cannot see signals on i2s pins (28, 29, 30, 31) like if interface isn't enabled, even if codec is configured in master mode to provide clock on the bus.
But when I spy I2C commands, codec is correctly configured in master mode. I can see I2C trames.

**Comment by pelwell** [comment]
Sorry, that should have said:

```
dtc -I fs /proc/device-tree
```

If that doesn't work, update dtc:

```
sudo apt-get update
sudo apt-get install device-tree-compiler
```

And I presume you mean "bcm2708-i2s.c"

You could also install the new raspi-gpio:

```
sudo apt-get install raspi-gpio
```

and then use

```
sudo raspi-gpio get
```

to see the GPIO states.

**Comment by GTrannoy** [comment]
Ok, this is the result of dtc [http://pastebin.com/UvJ3iWvB](http://pastebin.com/UvJ3iWvB)

And for GPIOs which seem good [http://pastebin.com/ixvrhQWA](http://pastebin.com/ixvrhQWA)

Yes you are right, I meant 'bcm2708-i2s.c'

**Comment by GTrannoy** [comment]
I tried to change in slave mode (SND_SOC_DAIFMT_CBS_CFS) and I can see clocking on i2s. But no sound.

aplay command give an error "aplay: set_params:1145: Unable to install hw params:" and nothing.

mplayer seems to play music now, but I can't hear anything. In "alsamixer" I can enable speaker and adjust volume but no sound. 
i2c frames are ok on my oscilloscope with good parameters in register.

Why it doesn't play music ?
Maybe a problem in wm8750.c codec and a register is badly configured.

And why no clock in master mode ? (MCLK on the codec is ok, 12.288MHz).
Pb in register too ?

Do you know if parameters in alsamixer could apply with other players like mplayer ?
I suppose because it seems being no other frames on i2c to configured parameters like volume.

Do you think if codec in slave mode is bad for audio ? (I think having read on a forum that it is bad for audio quality, but not sure...)

I feel solution is near... ;-)

**Comment by pelwell** [comment]
Having the codec in slave mode is theoretically worse because the clock is likely to have more jitter, but many audio cards work in that way because it is easier without any obvious problems. I'm sorry I can't be more help with the lack of sound - your files didn't reveal anything unusual.

Does the driver support the bit depth and sample rate of the file you are trying to play?

**Comment by GTrannoy** [comment]
Thx very much for your help. I understand it is complex and even more with custom hardware you don't know and you can't test physically.
Moreover I began to believe that it is a problem with the codec IC and probably with registers.
On the RPi side it seems operational.

Good idea to investigate a problem of data format.

I'll tell you when it works and maybe we could add wm8750 support for others.
This codec is relatively common and versatile with speaker/headphone and 3 line in, although a little old...

**Comment by GTrannoy** [comment]
Hi,
For info, it works !
I don't know why but the speaker volume become efficient at the end of the range, above val~=110 of a range [0:127] + difficult configuration to enable correct analog path and others parameters. But I have sound.
I need again some work to run microphones. I have parasitic pulse on the codec side. Probably a bad configuration somewhere...

Just to say I have successfully implemented the wm8750 support. Maybe later, when more reliable and if this is an interest, it could be added to the raspbian release...

Thank you for your help !

**Pull request closed without merging**
