### PR TITLE
HVS Gamma LUT support for the RPi4

### PR DESCRIPTION
**Pull request by mripard**
Hi,

Here's a PR to implement the gamma lut property on the rpi4. This is work that has mostly been done by @6by9 and Juerg Haefliger from Canonical.

Maxime

### CODE REVIEW

**Comment by juergh** [comment]
Patch #1 and #2 should really be authored by @6by9 since they're mostly his work. Also, we should drop the register write retries since they are no longer necessary thanks to patch #3. I think. I'll do some testing to verify that.

**Comment by mripard** [comment]
I've changed the authorship to have @6by9 and you as the main author, and removed the register write retries.

**Comment by juergh** [comment]
I have tested this patchset successfully on top of the current rpi-5.10.y branch (commit 03ab8875d1fc756bd6d2fd8fdb211532eff33062). I also verified that LUT register rewrites are indeed no longer necessary and writes always seem to stick. What's a little concerning though is that the screen blanks for ~2 secs for each update of the LUT (96 register writes). FWIW, doing 100 subsequent LUT updates blanks the screen for ~7 secs. I don't know how GNOME or other tools implement the nightlight feature and how many LUT updates at what intervals are performed but it could result in a significant disturbance. As I understand it, this is a HW limitation and IMO it will trigger bug reports.

**Comment by 6by9** [comment]
Sorry, I totally missed @mripard's update.

Slightly weird wording in commit 3's commit text
```
Since the pixelvalve cannot have its assigned channel without stalling
unless it's disabled as well, in our case that means forcing a full
disable / enable cycle on the pipeline.
```
Missing the word "changed", or "halted"?

Other than that, the patches look fine.

> FWIW, doing 100 subsequent LUT updates blanks the screen for ~7 secs. I don't know how GNOME or other tools implement the nightlight feature and how many LUT updates at what intervals are performed but it could result in a significant disturbance. As I understand it, this is a HW limitation and IMO it will trigger bug reports.

It is a hardware limitation, so it's the choice of either blanking, or not supporting the gamma controls.

**Comment by juergh** [comment]
Ok. Then I'd rather have support and let the user choose (and deal with the consequences :-)).

**Comment by mripard** [comment]
I've just pushed a new version with the commit log changed like you suggested (and rebased on the current branch)

**Comment by 6by9** [comment]
LGTM

@mripard can I ask you to upstream that if you're happy with it?

**Comment by mripard** [comment]
Yep, sure

**Comment by 6by9** [comment]
So X seems to throw a load of calls through drm_crtc_legacy_gamma_set which always replaces the gamma property blob.

I'm just seeing if there is a quick way to do a memcmp before the replace.

**Pull request merged**
