### PR TITLE
added driver and dtoverlay to support Pi2Media csb503hta headphone am…

### PR DESCRIPTION
**Pull request by Pi2Design**
added driver and dtoverlay to support Pi2Media csb503hta headphone amp board.
I rebased and changed branch names so I have to make this new pull request I guess.

### CODE REVIEW

**Comment by Pi2Design** [comment]
So where we left off user @DigitalDreamtime was suggesting using a simple-audio-card approach. See discussion here:  [https://github.com/DigitalDreamtimeLtd/linux/commit/c74365758ba2520b2ae24071ceba1afba17a128b](https://github.com/DigitalDreamtimeLtd/linux/commit/c74365758ba2520b2ae24071ceba1afba17a128b)

and @pelwell said: 

What you've done looks correct - you'll have to rebase and resolve a few conflicts though - but this is yet another clone of Florian Meier's original driver. There are no substantive changes - just a pointless renaming.

Why not use "hifiberry,hifiberry-dac" as the compatible string in your overlay? Your users will still the pi2media-csb503hta overlay name (which I would prefer to be called pi2media-csb503hta-audio to follow the new convention).

**Comment by Ruffio** [comment]
@Pi2Design is this PR going to be updated according to @pelwell descriptions/requirements ? If not, then I don't think this PR will ever be accepted.

**Comment by Ruffio** [comment]
@Pi2Design is this PR going to be updated according to @pelwell descriptions/requirements and there is a conflict to resolve. If not, then I don't think this PR will ever be accepted.

**Comment by pelwell** [comment]
Closing for lack of activity.

**Pull request closed without merging**
