### PR TITLE
DT: Add overlays to configure I2C pins

### PR DESCRIPTION
**Pull request by 6by9**
Lifted from
https://www.raspberrypi.org/forums/viewtopic.php?f=107&t=120938&p=825883
so not claiming this to be my own work.
Adds overlays i2c0-bcm2708 and i2c1-bcm2708 that allow the pin
allocations for i2c-0 and i2c-1 to be changed.

Done as overlays as discussed under #1315.

### CODE REVIEW

**Comment by pelwell** [comment]
I've merged this, after fixing a typo and tweaking the formatting.

**Comment by 6by9** [comment]
Thanks Phil.
Is it worth pulling those to the 4.1 and/or other branches? :-)

**Comment by pelwell** [comment]
It will happen.

**Comment by pelwell** [comment]
And it has.

**Pull request closed without merging**
