### PR TITLE
Pull upstream dma backport into rpi 4.4.y

### PR DESCRIPTION
**Pull request by clivem**
This is an 18 patch series, consisting of 16 patches from @msperl (the upstream dma backport) and 2 "fix" patches from @HiassofT

### CODE REVIEW

**Comment by clivem** [comment]
Added 19th patch to this dma set, from Eric Anholt, "dmaengine: bcm2835: Fix polling for completion of DMA with interrupts masked". See https://github.com/raspberrypi/linux/pull/1522#issuecomment-225324579

**Comment by popcornmix** [comment]
I've cherry-picked Eric's patch to 4.6 for further testing.

**Comment by clivem** [comment]
> I've cherry-picked Eric's patch to 4.6 for further testing.

Cool. I won't be submitting a new PR for rpi-4.6.y branch then.......

**Comment by popcornmix** [comment]
@samaaron or any other testers, this PR is in latest rpi-update kernel/firmware.

**Comment by clivem** [comment]
Ping.... @rbnpi and @stuzog Can you please rpi-update your kernel and see if it resolves your stuttering issues with Sonic Pi and IQAudIO DAC+?

**Comment by stuzog** [comment]
Yes! Updating the kernel using rpi-update did the trick. Clear audio 
through HiFiBerry DAC+, no stuttering.

Many thanks!
Stuart

**Comment by clivem** [comment]
> Yes! Updating the kernel using rpi-update did the trick. Clear audio
> through HiFiBerry DAC+, no stuttering.

Thanks for the feedback. And if in real life you ever happen to cross paths with a man called Martin Sperl, buy him a beer. He's the person to thank.

**Pull request merged**
