### PR TITLE
dwc_otg: use align_buf for small IN control transfers

### PR DESCRIPTION
**Pull request by P33M**
The hardware will do a 4-byte write to memory on any IN packet received
that is between 1 and 3 bytes long. This tramples memory in the uvcvideo
driver, as it uses a sequence of 1- and 2-byte control transfers to
query the min/max/range/step of each individual camera control and
gives us buffers that are offsets into a struct.

Catch small control transfers in the data phase and use the align_buf
to bounce the correct number of bytes into the URB's buffer.

In general, short packets on non-control endpoints should be OK as URBs
should have enough buffer space for a wMaxPacket size transfer.

See: https://github.com/raspberrypi/linux/issues/3148

### CODE REVIEW

**Comment by LF85** [comment]
Unfortunately this commit seems to breaks correct enumeration when using many usb devices. We habe a setup with multiple hubs and about 15+ devices (mostly cp210x based serial-to-usb converters)
and since this patch we regularly encounter  ERROR::assign_and_init_hc:1408: assign_and_init_hc: Failed to allocate memory to handle non-dword aligned buffer case

Could the default buffer size of 4096 be so small in that case (I'm sorry but I'm not yet familiar with the details of the usb-subsystem) ?  

We are running a RPi 3B+ on Raspbian Buster 4.19.69 (but it's not working since .66)

**Comment by P33M** [comment]
One tedious thing about the driver is that align_bufs are allocated atomically. The memory has to come from a dedicated coherent pool which has a size set at boot.

What happens if you add coherent_pool=2M to the end of the parameter list in /boot/cmdline.txt (and reboot)?

**Comment by LF85** [comment]
Thanks a lot. 
Adding  coherent_pool=2M  to the cmdline.txt seems to fix the issue.

**Comment by floion** [comment]
Hi, so the proper fix for issues such as https://github.com/raspberrypi/linux/pull/3150#issuecomment-529796579 is adding the `coherent_pool=2M` param to cmdline.txt?

**Comment by P33M** [comment]
It's a workaround, not a fix. The current allocation method is inefficient (one coherent buffer per endpoint that needs it). This could be changed to an up-front allocation of one align_buf per host channel instead, but this means there would be a large initial coherent allocation (number of channels * channel max transfer size = 8*2^19 = 4MB).

**Comment by floion** [comment]
Thanks for the details @P33M 
Is there a bug on this that we could monitor?

**Pull request merged**
