### PR TITLE
Add support for 3.5" display by tinylcd.com

### PR DESCRIPTION
**Pull request by notro**
The display has optional touchpanel, rtc and keypad.

### CODE REVIEW

**Comment by notro** [comment]
The gpio-keys module makes it easy to turn gpio switches/keys into a Linux keyboard.
This can be combined with the triggerhappy daemon to run scripts on key press: https://github.com/notro/fbtft-spindle/wiki/GPIO-keyboard#triggerhappy-thd

**Comment by pelwell** [comment]
The overlay looks fine to me. Two RTCs seems like overkill - are there two board variants?

**Comment by notro** [comment]
I guess so. The latest display use PCF8563. They had a rtc option on the old display also, so maybe that was ds1307.

**Comment by pelwell** [comment]
@popcornmix OK to merge?

**Pull request merged**
