### PR TITLE
Rpi 4.1.y spi bcm2835 patches clock-polarity issues 

### PR DESCRIPTION
**Pull request by msperl**
merge from 4.3-pre back to 4.1 to fix #1077.

### CODE REVIEW

**Comment by msperl** [comment]
@notro: please check

**Comment by pelwell** [comment]
Looks OK to me.

**Comment by notro** [comment]
I haven't got time to actually test it now, but it looks like what I tested previously.
Thanks for getting this fixed Martin. This means that I don't have to provide a prebuilt spi-dma kernel for the fbtft users anymore :-)

**Comment by msperl** [comment]
@notro: it is exactly what you have tested before - it is exactly upstream, so it should work...

**Comment by msperl** [comment]
It may be valuable to push this into 4.2 as well, as it will only show up officially in 4.3!

**Comment by popcornmix** [comment]
Was ahead of you there: https://github.com/raspberrypi/linux/tree/rpi-4.2.y

**Pull request merged**
