### PR TITLE
staging/bcm2835-camera: Add support for V4L2_MPEG_VIDEO_BITRATE_MODE_CQ

### PR DESCRIPTION
**Pull request by soyersoyer**
Add support for constant quality mode. In this mode the quality can be set via V4L2_CID_MPEG_VIDEO_CONSTANT_QUALITY.

### CODE REVIEW

**Comment by 6by9** [comment]
Reality is that the 62.5Mbit/s limit of level 4.2 isn't achievable by the hardware, at least not in realtime. As bcm2835-camera is only fed by the camera and is therefore only realtime, then it makes little sense increasing the limit.

For bcm2835-codec where we may be transcoding in non-realtime, then there would be a case for it.

**Comment by soyersoyer** [comment]
I am playing with this a bit more. If I set the bitrate to 0, setting the MMAL_PARAMETER_VIDEO_ENCODE_MIN_QUANT, MMAL_PARAMETER_VIDEO_ENCODE_MAX_QUANT doesn't have any effect. But setting the MMAL_PARAMETER_VIDEO_ENCODE_INITIAL_QUANT works.

What is the best way to express this behaviour in v4l2?
Set the INITIAL_QUANT and MIN_QUANT in the H264_MIN_QP control too?
Map the INITIAL_QUANT to H264_I_FRAME_QP or other unused control?
If the bitrate is 0, force the H264_MIN_QP to be equal TO H264_MAX_QP (and INITIAL_QUANT)?

**Comment by 6by9** [comment]
This is why I hate getting involved in overriding Qp as it gets involved as to what the dependencies are.

I'd need to have a serious dig through the code as to the dependencies between bitrate, min/max qp, initial qp, bitrate mode, and possibly a number of other parameters. There's no guarantee that they match with the expectations of V4L2, and even that may not be clearly specified.

Rereading https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/ext-ctrls-codec.html
```V4L2_CID_MPEG_VIDEO_FRAME_RC_ENABLE```` implies totally fixed if disabled, but aiming at the bitrate but within min/max qp if enabled. What do you do if the bitrate exceeds the target with max qp? Just ignore it and keep going?

And it really needs to set the min and max for I and P frames (we don't support B frames), but I'd need to look again at the firmware code to work out whether that is supported (it looks like it may take one value and have a weighting between I and P frame QP)

**Comment by soyersoyer** [comment]
Is the V4L2_CID_MPEG_VIDEO_FRAME_RC_ENABLE mandatory? I mean if the user can't set it, because the driver doesn't support it, it's just unset, not disabled.

**Pull request closed without merging**
