### PR TITLE
dwc_otg: more robust interrupt handling

### PR DESCRIPTION
**Pull request by P33M**
This PR fixes issues such as the error message

```
ERROR::handle_hc_chhltd_intr_dma:2537: handle_hc_chhltd_intr_dma: Channel 7, DMA Mode -- ChHltd set, but reason for halting is unknown, hcint 0x00000002, intsts 0x04400001
```

popping up in the log since
https://github.com/raspberrypi/linux/commit/db4fad7380c83b6e1b62dfb3fd61e55d031a04fc. 
I would prefer a round of testing by people that have seen this issue before merging for general consumption, I will advertise as necessary in the relevant places.

### CODE REVIEW

**Comment by P33M** [comment]
I can say that this patch definitely squashes the issues that I've seen at least - I can artificially create endpoints that are very lossy (via the world's worst 10-port hub and several pendrives) which completely breaks USB with plenty of the above error message, and will continuously reset/probe/error/reset devices (as it should do for dodgy connections) after the patch.

**Comment by popcornmix** [comment]
I'm testing now, and no problems so far. I'll keep you updated.

**Comment by popcornmix** [comment]
I just got this:

```
<4>[17013.296896] ERROR::handle_hc_chhltd_intr_dma:2574: handle_hc_chhltd_intr_dma: Channel 6, DMA1
<5>[17024.229527] nfs: server 10.177.71.57 not responding, still trying
<5>[17059.541002] nfs: server 10.177.71.57 not responding, still trying
```

http://pastebin.com/NNB78K9K

```
$ uname -a
Linux raspberrypi 3.6.11+ #492 PREEMPT Sun Jul 14 00:04:59 BST 2013 armv6l GNU/Linux
```

I'd booted from nfs and had xbmc running in the background, but idle.

I also get these failures without this PR.

**Comment by P33M** [comment]
The pastebin chopped off the registers in that error which is the important bit. Can you still get at the message log?

How frequent are these errors now vs before?
There's also a bluetooth dongle in there - can I get a lsusb -v for that. It may be a full-speed device which could result in interesting things for the same sort of error happening on split transactions.

**Comment by popcornmix** [comment]
No sign of "handle_hc_chhltd_intr_dma" in /var/log/*
I'll catch it next time.

I would say it used to occur every couple of hours (with work setup).
It's happened once today (although it's not been heavily used). No evidence that it is worse.

No bluetooth - this is what I had (and still have) connected:

```
$ lsusb -v

Bus 001 Device 002: ID 0424:9512 Standard Microsystems Corp.
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0 Unused
  bDeviceProtocol         2 TT per port
  bMaxPacketSize0        64
  idVendor           0x0424 Standard Microsystems Corp.
  idProduct          0x9512
  bcdDevice            2.00
  iManufacturer           0
  iProduct                0
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           41
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                2mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0 Unused
      bInterfaceProtocol      1 Single TT
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0001  1x 1 bytes
        bInterval              12
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       1
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0 Unused
      bInterfaceProtocol      2 TT per port
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0001  1x 1 bytes
        bInterval              12

Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0 Unused
  bDeviceProtocol         1 Single TT
  bMaxPacketSize0        64
  idVendor           0x1d6b Linux Foundation
  idProduct          0x0002 2.0 root hub
  bcdDevice            3.06
  iManufacturer           3
  iProduct                2
  iSerial                 1
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           25
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0 Unused
      bInterfaceProtocol      0 Full speed (or root) hub
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0004  1x 4 bytes
        bInterval              12

Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp.
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass          255 Vendor Specific Class
  bDeviceSubClass         0
  bDeviceProtocol         1
  bMaxPacketSize0        64
  idVendor           0x0424 Standard Microsystems Corp.
  idProduct          0xec00
  bcdDevice            2.00
  iManufacturer           0
  iProduct                0
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           39
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                2mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           3
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0
      bInterfaceProtocol    255
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               4

Bus 001 Device 004: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0 Unused
  bDeviceProtocol         2 TT per port
  bMaxPacketSize0        64
  idVendor           0x0424 Standard Microsystems Corp.
  idProduct          0x2514 USB 2.0 Hub
  bcdDevice            0.00
  iManufacturer           0
  iProduct                0
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           41
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                2mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0 Unused
      bInterfaceProtocol      1 Single TT
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0001  1x 1 bytes
        bInterval              12
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       1
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0 Unused
      bInterfaceProtocol      2 TT per port
      iInterface              0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0001  1x 1 bytes
        bInterval              12

Bus 001 Device 005: ID 413c:2107 Dell Computer Corp.
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0         8
  idVendor           0x413c Dell Computer Corp.
  idProduct          0x2107
  bcdDevice            5.02
  iManufacturer           1
  iProduct                2
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           34
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower               70mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      65
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              10
```

**Comment by P33M** [comment]
The only alternative could be something similar happening with a split transaction.

I did specifically test this before and after with a FS device known to produce 2 data toggle errors on the first transaction after a reset, result was negative for this error before and after which led me to believe that split transactions weren't affected. Data toggle errors halt the channel in split transactions and they are now handled exactly like HS transaction errors, so I used this as an example repeatable test.

**Comment by P33M** [comment]
3 positives from forum users:

http://www.raspberrypi.org/phpBB3/viewtopic.php?f=28&t=49223&start=25
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=28&t=49902

I have now tested split transactions using the same tactic as I generated multiple errors for USB2.0 devices - I have not seen any FS/LS devices cause the error condition to appear.

**Comment by popcornmix** [comment]
I've not had the handle_hc_chhltd_intr_dma message repeat.
I believe I was seeing the issue more frequently without the patch.
I'm seeing no new problems.

I'm happy to accept this PR, and produce updated firmware for wider testing.
Agree?

**Comment by ghollingworth** [comment]
Yep,

It's clearly an improvement

Gordon

**Comment by popcornmix** [comment]
I caught it again:

```
<4>[  200.089014] ERROR::handle_hc_chhltd_intr_dma:2579: handle_hc_chhltd_intr_dma: Channel 4, DMA Mode -- ChHltd set, but reason for halting is unknown, hcint 0x00000002, intsts 0x04600021
<5>[  209.324850] nfs: server 192.168.4.41 not responding, still trying
<5>[  213.734972] nfs: server 192.168.4.41 not responding, still trying
<5>[  218.145112] nfs: server 192.168.4.41 not responding, still trying
<5>[  222.555243] nfs: server 192.168.4.41 not responding, still trying
<5>[  226.965369] nfs: server 192.168.4.41 not responding, still trying
<5>[  231.375507] nfs: server 192.168.4.41 not responding, still trying
<6>[  237.180411] SysRq : DEBUG
```

Running on latest "next" kernel:

```
Linux version 3.9.10+ (dc4@dc4-arm-01) (gcc version 4.7.2 20120731 (prerelease) (crosstool-NG linaro-1.13.1+bzr2458 - Linaro GCC 2012.08) ) #508 PREEMPT Fri Jul 19 20:55:21 BST 2013
```

**Comment by P33M** [comment]
Hm

I suspect that what's happening in this case is the delay between ack/xfercomp and chhltd is becoming large. I suspect that the dwc DMA controller is having a lot of work to do because of an NFS root which delays the halt - provoking the race between the FIQ and the IRQ.

Given that the bogus channel halt isn't really a disaster, I should probably add a retry mechanism similar to what I did for split data toggle errors...

**Pull request merged**
