### PR TITLE
Add dt param to use HiFiBerry DAC+ Pro in slave mode

### PR DESCRIPTION
**Pull request by clivem**
Add 'slave' dt param to use HiFiBerry DAC+ Pro in slave mode, with Pi as master
for bit and frame clock.

@hifiberry Daniel, you OK with this?

### CODE REVIEW

**Comment by pelwell** [comment]
Why would a user want to do this? Isn't the advantage of the Pro that the codec is the master with a low jitter clock, making this effectively dumbing it down?

**Comment by clivem** [comment]
How can I put this delicately...... Some users have found the Pi's "jittered to hell" clock to sound better. Who'd have thought it! ;)

Secondly, there is an issue at the moment with the DAC+Pro in master mode, supporting 384k. (Which I'm looking into.) 352k8 and 384k sample rates, have been working in slave mode, (with my 384k patch set, for which a PR is imminent), for as long as I can remember.

It's about choice, not dumbing down. I'm not changing the defaults, just giving the user a choice. By default a DAC+Pro will work as master, user adds "slave" dt param, it's up to them.

**Comment by hifiberry** [comment]
I'm ok with it. If somebody really wants to to this, why not.

**Comment by clivem** [comment]
I'll push a new patchset to my rpi-4.4.y-384k branch later. DAC+Pro working in master mode for sample rates <=384k.

```
[01:00:24.097928] test_open:332 Testing ALSA device... OPENING
[01:00:24.113640] test_open:355 minimum supported sample rate: 8000
[01:00:24.113791] test_open:366 maximum supported sample rate: 384000
[01:00:24.113880] test_open:376 supported sample rate: 384000
[01:00:24.113961] test_open:376 supported sample rate: 352800
[01:00:24.114035] test_open:376 supported sample rate: 192000
[01:00:24.114158] test_open:376 supported sample rate: 176400
[01:00:24.114237] test_open:376 supported sample rate: 96000
[01:00:24.114310] test_open:376 supported sample rate: 88200
[01:00:24.114381] test_open:376 supported sample rate: 48000
[01:00:24.114452] test_open:376 supported sample rate: 44100
[01:00:24.114519] test_open:376 supported sample rate: 32000
[01:00:24.114586] test_open:376 supported sample rate: 24000
[01:00:24.114657] test_open:376 supported sample rate: 22500
[01:00:24.114726] test_open:376 supported sample rate: 16000
[01:00:24.114797] test_open:376 supported sample rate: 12000
[01:00:24.114866] test_open:376 supported sample rate: 11025
[01:00:24.114931] test_open:376 supported sample rate: 8000
[01:00:24.115435] log_formats:321 supported formats: S16_LE, S24_LE, S32_LE
[01:00:24.116560] test_open:387 Testing ALSA device... CLOSED
```

A minor kludge in your hifiberry_dacplus driver, but better a kludge there than me spending the next 3 months arguing with Broonie about modifying the constraint handling in the pcm512x codec driver.

**Comment by pelwell** [comment]
Checkpatch has a few issues with this commit:

```
WARNING: Possible unwrapped commit description (prefer a maximum 75 chars per line)
#8:                                                                             
Add 'slave' param to use HiFiBerry DAC+ Pro in slave mode, with Pi as master    

ERROR: do not initialise statics to false                                       
#62: FILE: sound/soc/bcm/hifiberry_dacplus.c:50:                                
+static bool slave = false;                                                     

total: 1 errors, 1 warnings, 53 lines checked                                   
```

But otherwise I'm happy with it.

**Pull request merged**
