### PR TITLE
ARM64: Make camera and vchiq work

### PR DESCRIPTION
**Pull request by Electron752**
Here are the minimum changes needed to get VCHIQ on arm64 to work with 32 bit applications, and the needed changes to get the V4L2 plugin for the camera to work on arm64.

I also undated the config for arm64.

Except for the config, these were pulled from linux-next.

### CODE REVIEW

**Comment by Electron752** [comment]
I think these changes got eventually merged into mainline upstream.  Since having specific changes here doesn't appear to have sparked any interest, perhaps it's best to just close the pull request.

**Comment by Minipada** [comment]
I am facing issues with a custom OS made with Yocto, aarch64 but with upstream kernel and trying to make a camera work.
I am testing [capture-example](https://github.com/gjasny/v4l-utils/blob/master/contrib/test/capture-example.c) software from v4l-utils 1.10 and got the [timeout error](https://github.com/gjasny/v4l-utils/blob/master/contrib/test/capture-example.c#L197). This is the most minimalistic example of test application for a camera I could find. It's using the uvc driver.

Note that this camera works fine in a 32 bits environment, raspbian and also Yocto with the same system components including v4l-utils and kernel.

I just noticed this PR and was wondering if these changes were into upstream as mentioned above and if you could point them out to me since I couldn't find them.

Thanks

**Comment by Electron752** [comment]
On Tue, 2018-01-09 at 06:31 -0800, David Bensoussan wrote:
> I am facing issues with a custom OS made with Yocto, aarch64 but with
> upstream kernel and trying to make a camera work.
> 
> I am testing capture-example software from v4l-utils 1.10 and got the
> timeout error. This is the most minimalistic example of test
> application for a camera I could find. It's using the uvc driver.
> 
> Note that this camera works fine in a 32 bits environment, raspbian
> and also Yocto with the same system components including v4l-utils
> and kernel.
> 
> I just noticed this PR and was wondering if these changes were into
> upstream as mentioned above and if you could point them out to me
> since I couldn't find them.
> 
> Thanks
> 
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.

Please check these patches which are in mainline.
7e8dbea410322092af3d2c0635da5a3341b1999881b2cbdbf34f6696c2e2b657873c624
89ef1f7734e6bafdfb9f394d2d7fdffcf9b489a0c747fda3bad428fc0af2eed6f2fe7fa
51a7ffca5746cef1a34fe08093094e5f6b360f143a299f46ac551695ddc45fe9c65742a
75b6fada7a2153aa2f8bea0d6dd7beb354f8560d8c3ce035af4013e035ac06196c23fd4
674fc41a3e6a4b85287f9eb407c246ecf09c68aeab51063a8e7fd4c0b05dc9eeef085fa
01fa074369b5f22b72a4b4fd38a12f36251d38c02283185b1ac7359366e7386fb593427
ee3e981e0652592367eb3fbeb2eb97bd96427cb203fd34c3a8a1b6fcd1f55359125348f
81f4d1b409cd5b391c523e4
Some changes have been made by others as well.   I tested the camera
with cheese and ffmpeg.
If it is no longer working, you will probably need to fix it yourself
and submit a change to upstream.

> 
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/raspberry
> pi/linux","title":"raspberrypi/linux","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in GitHub","url":"https://gi
> thub.com/raspberrypi/linux"}},"updates":{"snippets":[{"icon":"PERSON"
> ,"message":"@Minipada in #1919: I am facing issues with a custom OS
> made with Yocto, aarch64 but with upstream kernel and trying to make
> a camera work.\r\nI am testing [capture-example](https://github.com/g
> jasny/v4l-utils/blob/master/contrib/test/capture-example.c) software
> from v4l-utils 1.10 and got the [timeout error](https://github.com/gj
> asny/v4l-utils/blob/master/contrib/test/capture-example.c#L197). This
> is the most minimalistic example of test application for a camera I
> could find. It's using the uvc driver.\r\n\r\nNote that this camera
> works fine in a 32 bits environment, raspbian and also Yocto with the
> same system components including v4l-utils and kernel.\r\n\r\nI just
> noticed this PR and was wondering if these changes were into upstream
> as mentioned above and if you could point them out to me since I
> couldn't find them.\r\n\r\nThanks"}],"action":{"name":"View Pull
> Request","url":"https://github.com/raspberrypi/linux/pull/1919#issuec
> omment-356299636"}}}

**Comment by Electron752** [comment]
Here is the list again as github messed it up when I replied.

BTW, this is a closed PR.  If you are still having issues, please open a new topic.

7e8dbea410322092af3d2c0635da5a3341b19998
81b2cbdbf34f6696c2e2b657873c62489ef1f773
4e6bafdfb9f394d2d7fdffcf9b489a0c747fda3b
ad428fc0af2eed6f2fe7fa51a7ffca5746cef1a3
4fe08093094e5f6b360f143a299f46ac551695dd
c45fe9c65742a75b6fada7a2153aa2f8bea0d6dd
7beb354f8560d8c3ce035af4013e035ac06196c2
3fd4674fc41a3e6a4b85287f9eb407c246ecf09c
68aeab51063a8e7fd4c0b05dc9eeef085fa01fa0
74369b5f22b72a4b4fd38a12f36251d38c022831
85b1ac7359366e7386fb593427ee3e981e065259
2367eb3fbeb2eb97bd96427cb203fd34c3a8a1b6
fcd1f55359125348f81f4d1b409cd5b391c523e4

**Comment by Minipada** [comment]
Thanks a lot. I will

**Pull request closed without merging**
