### PR TITLE
V4L2 stateful decode update

### PR DESCRIPTION
**Pull request by 6by9**
A couple of fixes for the stateful decode (wants fw 1239).

Also adds support for H&V flips to the ISP wrapper.

### CODE REVIEW

**Comment by popcornmix** [comment]
I tested this (along with firmware changes) with kodi, and didn't see any issues (no observable change).

**Comment by 6by9** [comment]
Added one further commit that resolves a refcounting issue should you reuse the same MMAL component instance after a timeout returning buffers. That makes Chromium happier.

**Comment by 6by9** [comment]
Rebased and tweaked some patches. Added WIP tag as John needs to test under Chromium.
FFmpeg and GStreamer seem happy.

**Comment by 6by9** [comment]
Updated again as we've resolved the Chromium issue.

If @popcornmix could check against Kodi that would be useful, otherwise I think we're good to go.

**Comment by popcornmix** [comment]
Kodi appears fine with this PR (and latest firmware) in a quick test.

**Comment by popcornmix** [comment]
Okay to merge?

**Comment by 6by9** [comment]
Thank popcornmix.
I've tested against Chromium with both Buster and Bullseye, FFmpeg (predominantly Bullseye), and GStreamer. That covers most of the main clients.

**Pull request merged**
