### PR TITLE
Add device tree config for htu21

### PR DESCRIPTION
**Pull request by rumpelsepp**

### CODE REVIEW

**Comment by pelwell** [comment]
That's a good start. Can you:
1. Keep the sensors in alphabetical order.
2. Add htu21 to the README (try `dtoverlay -h i2c-sensor` in a shell). Stick the the strict whitespace rules - no TABs, same indentation.

If you fix those in one or more follow-up commits we can squash them when merging.

**Comment by rumpelsepp** [comment]
Updated.

**Comment by pelwell** [comment]
Your README entry says the _default_ address is 0x40. Can the device have other addresses? If so, we should make the addresses selectable through a parameter. If not, you should remove the word "default".

**Comment by rumpelsepp** [comment]
> Your README entry says the default address is 0x40. Can the device have other addresses? If so, we should make the addresses selectable through a parameter. If not, you should remove the word "default".

I will check this and report back, can't remember it atm.

**Comment by rumpelsepp** [comment]
It seems, that the address is hardcoded: https://cdn-shop.adafruit.com/datasheets/1899_HTU21D.pdf

I will remove the address configuration opportunity.

**Comment by pelwell** [comment]
You need the parameter, otherwise there is no way to select your sensor. Put the parameter back, leave everything else as it is and I'll merge it.

**Comment by pelwell** [comment]
The i2c-sensor overlay has now been restructured internally, breaking your PR. I'll patch it up and merge by hand.

**Comment by rumpelsepp** [comment]
Oh nice, thanks! Then I can close this?

**Comment by pelwell** [comment]
I'll do it when I've finished - give me a few minutes.

**Comment by rumpelsepp** [comment]
No need to hurry. :) thanks!

**Comment by pelwell** [comment]
Merged manually.

**Pull request closed without merging**
