### PR TITLE
Include tsl4531, veml6070 and hdc100x dtoverlay

### PR DESCRIPTION
**Pull request by ubergesundheit**
This pull request adds the needed kernel config keys and extends the
i2c-sensor-overlay.dts file with the needed definitions.

I am unsure though with the overlay definitons.
Everything works on a Pi3, when I enable everything in `config.txt` with
```
dtparam=i2c_arm=on
dtoverlay=i2c-sensor,hdc100x,addr=0x43
dtoverlay=i2c-sensor,bmp280,addr=0x77
dtoverlay=i2c-sensor,veml6070
dtoverlay=i2c-sensor,tsl4531
```

I would love to hear some feedback and see this eventually merged, so I don't have to use a custom compiled kernel.

### CODE REVIEW

**Comment by 6by9** [comment]
You need to add the config options to bcmrpi_defconfig as well, otherwise the overlays can only work on a Pi2 or Pi3.

**Comment by ubergesundheit** [comment]
Ok, done!

What about the dts files? Are they ok?

**Comment by pelwell** [comment]
They DTS looks OK at first glance, but I'll check it tomorrow. You can add hdc100x to the description of the addr parameter.

**Comment by pelwell** [comment]
I shortened a few lines in the README and mentioned HDC100X in the `addr` parameter as discussed, but otherwise it was fine. Merged.

**Comment by ubergesundheit** [comment]
Thank you very much! When can I expect these changes live for everyone?

**Comment by pelwell** [comment]
rpi-update releases are irregular but relatively frequent - about once a week on average, the last being three days ago - depending on the quantity and importance of the new content. Raspbian apt-get package updates are far less frequent - usually months apart.

**Comment by ubergesundheit** [comment]
Thank you very much again!

**Pull request merged**
