### PR TITLE
Adding rtl8192eu support

### PR DESCRIPTION
**Pull request by jpostma**

### CODE REVIEW

**Comment by popcornmix** [comment]
Not sure the subproject is something that can be merged as you've done it.
E.g.

```
ARCH=arm make
drivers/net/wireless/Kconfig:282: can't open file "drivers/net/wireless/rtl8192eu/Kconfig"
make[1]: *** [bcmrpi_defconfig] Error 1
make: *** [bcmrpi_defconfig] Error 2
```

**Comment by jpostma** [comment]
I've removed the subproject and added the new files. I hope that would work for you,

**Comment by cheelio** [comment]
Confirmed this working on a €4,99 Maxxter Wifi dongle against kernel version 3.18.9+.

**Comment by popcornmix** [comment]
It's unlikely we'll merge this. Really this needs to be submitted upstream:
https://www.kernel.org/doc/Documentation/SubmittingDrivers
https://www.kernel.org/doc/Documentation/SubmittingPatches
If it is accepted, then we can cherry-pick the commits.

**Comment by cheelio** [comment]
Mmm, I guess that'll also be unlikely:
https://lists.fedoraproject.org/pipermail/users/2014-November/455246.html

**Comment by popcornmix** [comment]
Let us know if this is accepted upstream and we can pull it in.

**Pull request closed without merging**
