### PR TITLE
BCM270X_DT: add PCA9632 support

### PR DESCRIPTION
**Pull request by staroselskii**
Exports 3 leds in /sys/class/leds. Needs the CONFIG_LEDS_PCA963X to be set.

### CODE REVIEW

**Comment by pelwell** [comment]
I've fixed up a few basic errors in the PR, but I think you should extend the overlay to expose all four LEDs and with more generic names - something like "pca0", "pca1", etc. You could then add parameters to allow the labels to be set:

```
// Definitions for NXP PCA963X I2C PWM controller on ARM I2C bus.

/dts-v1/;
/plugin/;

/ {
        compatible = "brcm,bcm2708";

        fragment@0 {
                target = <&i2c_arm>;
                __overlay__ {
                        #address-cells = <1>;
                        #size-cells = <0>;
                        status = "okay";

                        pca: pca@62 {

                                compatible = "nxp,pca9632";
                                reg = <0x62>;
                                status = "okay";
                                #address-cells = <1>;
                                #size-cells = <0>;

                                pca_0: led0@0 {
                                    label = "pca0";
                                    reg = <0>;
                                    linux,default-trigger = "none";
                                };
                                pca_1: led2@1 {
                                    label = "pca1";
                                    reg = <1>;
                                    linux,default-trigger = "none";
                                };
                                pca_2: led2@2 {
                                    label = "pca2";
                                    reg = <2>;
                                    linux,default-trigger = "none";
                                };
                                pca_3: led3@3 {
                                    label = "pca3";
                                    reg = <3>;
                                    linux,default-trigger = "none";
                                };
                        };
                };
        };

        __overrides__ {
            addr = <&pca>,"reg:0";
            label0 = <&pca_0>,"label";
            label1 = <&pca_1>,"label";
            label2 = <&pca_2>,"label";
            label3 = <&pca_3>,"label";
        };

};

**Comment by Ruffio** [comment]
@staroselskii are you going to update PR according to @pelwell then it looks like to be ready to merged...

**Comment by staroselskii** [comment]
@Ruffio 
Yeah, sure. I'm going to update it as soon as I get a little time to make test it properly.

**Comment by JamesH65** [comment]
@staroselskii Is this PR still relevant?

**Comment by JamesH65** [comment]
No activity for over a year. This issue will be closed within 30 days unless further interactions are posted. If you wish this issue to remain open, please add a comment. A closed issue may be reopened if requested.

**Comment by pelwell** [comment]
It's two years old...

**Pull request closed without merging**
