### PR TITLE
Rpi 4.4.y msperl i2s/clockmgr backport

### PR DESCRIPTION
**Pull request by clivem**
This is another of my PR's that isn't actually a PR.

@msperl Martin, I've just quickly hacked your last unmerged backport, (obviously sans the dma patchset, that is already in rpi-4.4.y)....... Is there still any interest in trying to get this back into 4.4.y? 

@pelwell / @popcornmix How much longer do you expect rpi-4.4.y to remain the "stable" release? Will rpi-4.6.y be the next "stable"? How far away is that?

### CODE REVIEW

**Comment by popcornmix** [comment]
We have no shortterm plan to move stable from 4.4.
We'll continue to provide newer kernel source trees as they tend to be used by more bleeding edge distributions (e.g. LibreELEC) due to better support for wifi/dvb/remotes.

But we'll obviously the bump the stable kernel eventually. I suspect the arm side graphics driver may get harder to support the further we are away from mainline where the patches are going, which would be one reason for bumping. But we'll also keep an eye out for requested features/drivers/bug fixes that are present in newer kernels. But nothing planned in next few months.

**Comment by clivem** [comment]
@popcornmix I'm a little confused. Just looking to rebase my audio patchsets from rpi-4.4.y to rpi-4.6.x, and the patches I thought I'd need to drop, ie, the ones that there wont be any need for, because bcm2835-i2s will be using the clockmgr by default now, you've reverted clock manager in your 4.6 tree, back to pre-clockmgr code. ie. https://github.com/raspberrypi/linux/commit/42cb68af7a2efbc223c9d979e9b3aa9eee028197

Is there a reason why you don't want to move forward with clockmgr?

**Comment by popcornmix** [comment]
Only that reports were that I2S audio wasn't working. I believe @pelwell fixed it up by reverting back so we could carry on using the tree.

If you have it working on 4.6 then we're quite happy to move forward again.

BTW 4.6 is already EOL upstream, so 4.7 may be a more useful tree to work on.

**Comment by clivem** [comment]
OK, makes sense. I'll take a look at 4.7.y tree tomorrow. We probably want to merge most of the patches in this PR anyway, converting everything downstream to use the clkmgr framework, not just I2S and the Anholt GPU driver using clockmgr.... I haven't looked yet, but I'm hoping anything from Anholt for the vc4 driver that has been backported to rpi-4.4.y, is already in the rpi-4.7.y tree....

**Comment by msperl** [comment]
4.7 should have most of those patches already in place (but some may have been reverted for i2s-bcm2835).

The main thing that remains are;
- device-tree changes
- the SMI patch to use the clock framework

These patches are the ones that are already upstream in 4.7:
- clock: https://github.com/torvalds/linux/commits/v4.7/drivers/clk/bcm/clk-bcm2835.c
- i2s: https://github.com/torvalds/linux/commits/v4.7/sound/soc/bcm/bcm2835-i2s.c

So most of it should be there...

Also note that there was some talk about a LTS release for 4.8 or 4.9 (can't remember the details and can not find the announcement at this very moment) and the foundation will probably want to move to that LTS release.

**Comment by popcornmix** [comment]
Yes, LTS kernels always seem to be a bit of secret until kernel.org lists them.
We're obviously more likely to pick an LTS kernel just to avoid the issue of going EOL unexpectedly (like 4.6).

**Comment by msperl** [comment]
LTS is probably 4.9: https://plus.google.com/+gregkroahhartman/posts/DjCWwSo7kqY

But Ubuntu will use 4.8: http://www.techworm.net/2016/06/linux-kernel-4-8-power-upcoming-ubuntu-16-10-yakkety-yak.html

So what should the target be for now?

As said: it is mostly the device-tree (+ SMI) that needs to get fixed - all the clock stuff + DMA + most of i2s is in 4.7 already.

Martin

**Comment by popcornmix** [comment]
I'd say 4.7 would be my preference. It's being used by LibreELEC nightly builds, so will get reasonable testing for I2S audio. Hopefully it will apply to 4.8 and 4.9 without too much grief.

**Comment by clivem** [comment]
I'm probably about an hour away from making the PR to get all of the clockmgr stuff into rpi-4.7.y. Just testing now.......

**Comment by clivem** [comment]
https://github.com/DigitalDreamtimeLtd/linux/commits/rpi-4.7.y-clockmgr

I've run out of time to do any more testing today. PR tomorrow.

**Comment by msperl** [comment]
Just going over the list of patches quickly - some notes (some with regards to what is upstream and what the policies there are): 
- do not apply hands-off - this is still in discussion upstream as to if it should get applied or not.
- there are also some patches upstream to limit clock selection in the code alone, so - for the moment do not apply those "ARM: bcm2835: select OSC and PLLC_PER as PCM parent clocks" and corresponding patches (I believe Eric has a patch for that and it is upstream)
- the patched version of downstream spi-bcm2835aux may not work with these: "ARM: bcm2708: fix register range of spi-aux" - it may require to revert that portion in the driver as well to work correctly.
- also do not use "clk: bcm2835: mark enabled clocks with CLK_IS_CRITICAL" - again Eric had an alternative implementation that is in code alone.

**Comment by clivem** [comment]
@msperl With the greatest respect..... I'm OUT. The stuff you are saying "do not apply", is the very stuff that needs to be applied for there to be any chance of any sort of reliability. 

I would suggest that @pelwell sticks with the reverting the bcm2835-i2s upstream until this whole clock mess gets sorted out upstream and trickles downstream!

**Comment by msperl** [comment]
Sorry to have frustrated you - i have just summarized what is likely also to go in upstream and what is in doubt and for which other solutions have been chosen by Eric upstream.

Popcornmix prefers things that go upstream,so I am mentioning that...

I had thought that these patches made it into 4.7. But it seems as if these have not made it into 4.7...
I would need to check the status.

Your work is a good basis and (after seeing those plld things not going in) understand your frustration.

I can try to have a look at those patches of Eric when I find more time in September...

**Comment by msperl** [comment]
Note that this is the patchset I have been talking about:
"[PATCH v3 0/4] clk: bcm2835: critical clocks and parent selection"
dated 1st of June - see: https://lkml.org/lkml/2016/6/1/710)
-  clk: bcm2835: Mark the VPU clock as critical
-  clk: bcm2835: Mark GPIO clocks enabled at boot as critical
-  clk: bcm2835: Mark the CM SDRAM clock's parent as critical
-  clk: bcm2835: Skip PLLC clocks when deciding on a new clock parent 

That should put away most of the grievances that we have had without all those out of tree patches.

Unfortunately there never was any followup on those, so maybe Eric can elaborate on the status?

**Comment by popcornmix** [comment]
While coming from upstream is desirable, working reliably is more important.
If the PR appears to be reliable and reduces upstream reverts and reduces the number of downstream patches I wont object even if some non-upstream patches are required (ideally temporarily until upstream finalises).

**Comment by clivem** [comment]
> That should put away most of the grievances that we have had without all those out of tree patches.

I'll spin a build dropping HAND_OFF et all and I'll do some testing including Eric's 4x patches you referenced, and see if that resolves the issues that were resolved with the patches you'd rather not see applied, ie. never choosing PLLC as a parent and not disabling clocks, when reference count drops to zero, which are still needed, and causes hard-lock, something that CRITICAL was meant to resolve but never did.......

I fully understand why it is always preferable to go via upstream..... Yep, I get that. But in this instance, specifically I2S HAT's, (clocks are make or break to either a bullet-proof implementation or it not working at all), I've said it before and I'll say it again...... No-one (well maybe aside from you and one other) is using the upstream kernel with any of the I2S HAT boards. 1000's of users are using the downstream kernel for this purpose. Which brings me back to, this stuff needs to be refined and perfected downstream, before the "reference" implementation is submitted back upstream and the loop is closed. That's my opinion.....

**Comment by msperl** [comment]
I also started on working on the patchset again - I guess there are 2 things:
- one is the changes inside the DT to use the clocks
- the other is to bring on the clocks with the required featureset and limitations (Erics patch and maybe some more)

The point why I am advocating against hands off and such is because the hands-off approach was voted down - similarly the "clock selection policy in devicetree" (argument there: dt should describe HW not policy - configfs may be the right place to apply policies).

As you were frustrated I started to work also on a new patchset that tries to first handle the first point, then adds the second point (erics patches) and then let us see what is still missing for I2S - that then we can try to upstream.

Note that while going over the patchset of yours I also found some totally unrelated patchsets with regards to USB, so these should not be part of this clock switch.

I should be able to come up with something tomorrow as well - we then can compare notes...

**Comment by clivem** [comment]
Confused..... USB patches..... You are looking at my rpi-4.7.y-clockmgr branch, right?
https://github.com/DigitalDreamtimeLtd/linux/commits/rpi-4.7.y-clockmgr

Only USB patches I can think of are the "quirk" patches for native DSD endpoint support. But unless I've done something stupid they should be in another branch.

**Comment by msperl** [comment]
These patches show up in the history:
- snd-bcm2835: Use bcm2835_hw params in preallocate
- dwc_otg: Use kzalloc when suitable

**Comment by clivem** [comment]
@msperl This is where I am at now, testing Eric x4 patch set.
https://github.com/DigitalDreamtimeLtd/linux/commits/rpi-4.7.y-clockmgr2

Just did a quick "sanity" test on a 3B.... No lock-ups, music playing at wrong rates, etc. etc. So about to start rolling this out for thorough testing to Zero, B, B+, 2B.... 

32 bit samples, bclk ratio=64

```
Aug 31 17:45:01 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=32000, bclk_ratio=64, target_freq=2048000, actual_freq=2048000, parent=osc, parent_freq=19200000
Aug 31 17:45:16 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=44100, bclk_ratio=64, target_freq=2822400, actual_freq=2822396, parent=plld_per, parent_freq=499599994
Aug 31 17:45:30 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=48000, bclk_ratio=64, target_freq=3072000, actual_freq=3072000, parent=osc, parent_freq=19200000
Aug 31 17:45:36 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=88200, bclk_ratio=64, target_freq=5644800, actual_freq=5644792, parent=plld_per, parent_freq=499599994
Aug 31 17:45:38 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=96000, bclk_ratio=64, target_freq=6144000, actual_freq=6144000, parent=osc, parent_freq=19200000
Aug 31 17:45:41 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=176400, bclk_ratio=64, target_freq=11289600, actual_freq=11289585, parent=plld_per, parent_freq=499599994
Aug 31 17:45:43 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=192000, bclk_ratio=64, target_freq=12288000, actual_freq=12287950, parent=plld_per, parent_freq=499599994
Aug 31 17:45:45 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=352800, bclk_ratio=64, target_freq=22579200, actual_freq=22579046, parent=plld_per, parent_freq=499599994
Aug 31 17:45:47 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=384000, bclk_ratio=64, target_freq=24576000, actual_freq=24575901, parent=plld_per, parent_freq=499599994
```

32 bit samples, bclk ratio=100 for multiples of 8k

```
Aug 31 16:41:41 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=32000, bclk_ratio=100, target_freq=3200000, actual_freq=3200000, parent=osc, parent_freq=19200000
Aug 31 16:41:56 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=44100, bclk_ratio=64, target_freq=2822400, actual_freq=2822396, parent=plld_per, parent_freq=499599994
Aug 31 16:42:10 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=48000, bclk_ratio=100, target_freq=4800000, actual_freq=4800000, parent=osc, parent_freq=19200000
Aug 31 16:42:25 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=88200, bclk_ratio=64, target_freq=5644800, actual_freq=5644792, parent=plld_per, parent_freq=499599994
Aug 31 16:42:40 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=96000, bclk_ratio=100, target_freq=9600000, actual_freq=9600000, parent=osc, parent_freq=19200000
Aug 31 16:42:55 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=176400, bclk_ratio=64, target_freq=11289600, actual_freq=11289585, parent=plld_per, parent_freq=499599994
Aug 31 16:43:10 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=192000, bclk_ratio=64, target_freq=12288000, actual_freq=12287950, parent=plld_per, parent_freq=499599994
Aug 31 16:43:24 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=352800, bclk_ratio=64, target_freq=22579200, actual_freq=22579046, parent=plld_per, parent_freq=499599994
Aug 31 16:43:39 Akkordion3B1 kernel: bcm2835-i2s 3f203000.i2s: bcm2835_i2s_hw_params: clk_set_rate: sample_freq=384000, bclk_ratio=64, target_freq=24576000, actual_freq=24575901, parent=plld_per, parent_freq=499599994
```

**Comment by clivem** [comment]
> These patches show up in the history:
> 
> ```
> snd-bcm2835: Use bcm2835_hw params in preallocate
> dwc_otg: Use kzalloc when suitable
> ```

Nothing to do with me. I pulled from rpi-4.7.y. Talk to @popcornmix. They were committed by Dom to the rpi-4.7.y tree.

**Comment by msperl** [comment]
My error - they just showed at the same date, so I had assumed...
Sorry!

Besides that:
"Music plays at wrong rates" means: wrong clock selected under some circumstances?

So what is missing in principle - compared to the old i2s driver?

**Comment by msperl** [comment]
If the patches by Eric resolve most things then we should add an asked/tested to them so that they can get merged for 4.9

**Comment by clivem** [comment]
> "Music plays at wrong rates" means: wrong clock selected under some circumstances?

Yes, without your "only use OSC and PLLD patches", PLLC used to be selected for some frequencies, with the obvious results to music playback speed, when turbo engaged/disengaged. Obviously one of Erics patches specifically deals with that now.

> So what is missing in principle - compared to the old i2s driver?

Nothing. I think we are good to go. But as that original patch set (complete with the "bastard" patches) had several months testing, on every piece of Pi hardware known to man, with DAC boards in master and slave, at all known sample rates, and sample depth combos..... on my 20 machine I2S "farm" and I have people in the wild using it, with my "private" Fedora kernel builds, I'll reserve my thumbs-up temporarily until I've thoroughly tested where we are at now..... I've barely kicked the tires. 

> If the patches by Eric resolve most things then we should add an asked/tested to them so that they can get merged for 4.9

Sure. I'll add a Tested-By when I've finished testing.

**Comment by clivem** [comment]
@msperl Now I really am getting confused. Those 4x Anholt patches are already in rpi-4.4.y, but not rpi-4.7.y and not upstream........

**Comment by popcornmix** [comment]
@anholt has submitted some PR's to 4.4 to get upstream graphics driver fixes into raspbian.
These were non-trivial to apply to later trees. See:
https://github.com/raspberrypi/linux/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20author%3Aanholt%20

**Comment by msperl** [comment]
Well, I guess that most of those should already be in 4.7 - minus the clock things, most of which I had reported and provided fixes for, but which have not been accepted by Eric and he provided alternative patches instead...

So if this works out fine I guess I will need to walk over all the devices on my cm and check if they work as expected. Then we can merge them into 4.7 for wider testing.

**Comment by clivem** [comment]
> has submitted some PR's to 4.4 to get upstream graphics driver fixes into raspbian.

OK, can you please cherry pick the 4x Anholt clock patches (we are discussing here) from rpi-4.4.y to rpi-4.7.y, that were included in his vc4 PR's. They do apply cleanly.

52afecf832a9b123a955b237dc73fff697c9b7c8
376ce6dbad79f3906a8089cbbb1c89a8f204d029
a4a763bcd565621247b738b0832156377f4ec89a
3ac11dcf893a2d41cf08150d93cd9097b68f1dce

**Comment by clivem** [comment]
> So if this works out fine I guess I will need to walk over all the devices on my cm and check if they work as expected.

SDCARD: tick. 
3B BRCM wifi: tick. 
I2S: tick. 
I2C: tick. 
Main UART: tick. 

I've not yet tested aux UART.
PWM not tested. 
SPI not tested.

**Comment by popcornmix** [comment]
@clivem commits added.

**Comment by clivem** [comment]
> commits added.

Thank you.

**Comment by msperl** [comment]
Tested i2s + spi FB device on spi-bcm2835 - working fine

**Comment by msperl** [comment]
aux-uart working fine

**Comment by clivem** [comment]
> aux-uart working fine

Yes, I also verified that on a 3B, with both serial console and BT working at the same time, whilst outputting I2S, but....

In the interests of disclosure, and I won't be able to investigate until this evening..... There may be a problem with the Zero. (Whether that's the clockmgr patches or something it doesn't like in 4.7, don't know at the moment.) None of the 3x Zero's (headless and remote location) came back up, after I put my 4.7.2 build on them and rebooted. Hopefully, it's nothing to do with the clockmgr stuff! ;) The B and B+, in use last night, were working just fine! The B+ that was left looping a high-res playlist last night, is still playing just fine 12 hours later, with nothing in the logs, no anomolies, nothing to investigate....

**Comment by clivem** [comment]
Re-opening to force push update rpi-4.4.y patchset.

**Pull request closed without merging**
