### PR TITLE
I2c

### PR DESCRIPTION
**Pull request by swarren**
This is a driver for the BCM2708's HW I2C controller

### CODE REVIEW

**Comment by bootc** [comment]
Hah, I knew this would happen :-( I also have an I2C driver in https://github.com/bootc/linux/tree/rpi-i2cspi

**Comment by swarren** [comment]
Hmm. I like some things better from each driver. I can update my version to incorporate the good parts from your branch, and either issue a new pull request or replace this one, depending on whether I get done before this gets pulled in or not.

BTW, is anyone planning on pushing bcm2708 core support into the mainline kernel? I was tempted to start working on that myself unless someone is already doing it.

**Comment by bootc** [comment]
As I already 'publish' my kernel (http://www.bootc.net/) I'd really appreciate it if you could either comment on what you'd like to see different in my code or send over patches / pull requests. I'd be perfectly happy for our drivers to end up looking identical with bits from yours and bits from mine.

And as for the second question - yes, there is an effort to get the arch/mach code into mainline. Simon Arlott is currently leading this effort (lp0 here on GitHub) and there's a small group of us working on it. Sadly we mostly had to wipe the slate clean and start again for this as there are requirements to use device tree, etc...

You may want to take a look at https://github.com/lp0/linux/tree/rpi-linear

I should mention I'm currently working on forward-porting my SPI driver into that branch, doing the device tree conversion as well as updating it for queued submission as required by the new SPI core.

HTH,
Chris

**Comment by swarren** [comment]
Sure, I'll take a look at that.

**Comment by popcornmix** [comment]
Thanks swarren, but I'll close this pull request, as lp0/bootc are working on what I hope will be the upstreamable kernel we use in the future. Please send any pull requests to bootc.

If there's demand for bootc's I2C/SPI drivers to be merged into this kernel in the interim, then that's a option.

**Comment by bootc** [comment]
Let me know if you want the SPI/I2C drivers and I can get them cleaned up and tested against the 3.1.9 kernel.

**Comment by popcornmix** [comment]
Yes, that would be great.

**Pull request closed without merging**
