### PR TITLE
Added NXP PCF8523 real time clock chip driver.

### PR DESCRIPTION
**Pull request by adnan-aj**
First attempt to patch in the NXP PCF8523 RTC chip driver as a module.

### CODE REVIEW

**Comment by popcornmix** [comment]
We generally don't accept out of tree drivers, unless there is significant demand (e.g. the rtl8192 wifi driver which had a forum thread with a thousand posts).
Out of tree drivers make merging with newer kernel versions more difficult, and there could be stability issues.

If there is interest in this, please comment here.

**Comment by rebroad** [comment]
Will this pull request get rid of the "drivers/rtc/hctosys.c: unable to open rtc device (rtc0)" error upon bootup?

**Comment by adnan-aj** [comment]
No, the drivers/rtc/hctosys.c relies on two parts: a clock chip driver (like mine above, but must be compiled into the kernel, not as a module) and then, this former device-driver device-registration somewhere in arch/arm/bcm2708.c as i2c_register_board_info() as part of the board initialisation process. An excerpt to this patched file would look like:

...
static struct i2c_board_info raspyjuice_i2c_devices[] = {
       {
               I2C_BOARD_INFO("pcf8523", 0x68),
       },
};

void __init bcm2708_init(void)
 {
...
     i2c_register_board_info(0, raspyjuice_i2c_devices,
                             ARRAY_SIZE(raspyjuice_i2c_devices));
 }
...

This was to be my second phase of patching so that the hctosys.c in the kernel bootup can read the clock chip and set the time.
But I have my reservations on the 'style' of patching directly into the bcm2708.c because the file is quite neat dealing only with intrinsic device-controllers of the bcm2708. I was going to suggest a separate file for expansion-board related peripherals, after I've brought my clock hip driver 'upstream'.

**Comment by adnan-aj** [comment]
A similar but improved NXP PCF8523 RTC clock chip driver is now available in linux-3.8 release candidates. I think I'll just wait until that linux version becomes prevalent/popular.

I don't know if it is worth backporting the above (release candidate) PCF8523 driver back into this linux-3.2.27. 

I am closing this pull request. Thanks, anyway.

**Pull request closed without merging**
