### PR TITLE
media: i2c: Move Kconfig entry for IMX477 to the camera sensor section

### PR DESCRIPTION
**Pull request by naushir**
It was accidentally placed in the audio decoder section.

### CODE REVIEW

**Comment by 6by9** [comment]
LGTM

**Review by pelwell — APPROVED** [review]
Approved, with follow-up patch to update the defconfig files.

**Comment by naushir** [comment]
> Approved, with follow-up patch to update the defconfig files.

Shouldn't they remain the same?

**Comment by pelwell** [comment]
No - the structure of the defconfig file follows the structure of the Kconfig files.

**Pull request merged**
