### PR TITLE
Fixups for ADV7180/728x on Pi5

### PR DESCRIPTION
**Pull request by 6by9**
@naushir for error handling on CFE.

The others add the required information for ADV7180, but I've not got it streaming yet (yes I have set all the media-ctl links, just no buffers).

### CODE REVIEW

**Comment by 6by9** [comment]
Added a couple of other patches for cleaning up the CFE formats table.

16bit formats is being queried on https://github.com/raspberrypi/libcamera/issues/99 and looks to be missing the csi_dt value, so presumably metadata will be dropping into the CFE.

**Comment by 6by9** [comment]
Not setting the csi_dt for 16bit formats does appear to be an issue. Hacking imx708 to say that it produces RGGB16 produces random noise with the current kernel tree, and the anticipated kernel WARN from cfe.c:855 of `WARN_ON(!fmt->csi_dt);`
```
[   41.261207] source of link 'rp1-cfe-fe_config':0->'pisp-fe':1 is not a V4L2 sub-device, driver bug!
[   41.261257] ------------[ cut here ]------------
[   41.261259] WARNING: CPU: 0 PID: 986 at drivers/media/platform/raspberrypi/rp1_cfe/cfe.c:855 cfe_start_streaming+0x860/0x8c8 [rp1_cfe]
[   41.261272] Modules linked in: rfcomm snd_seq_dummy snd_hrtimer snd_seq snd_seq_device algif_hash algif_skcipher af_alg bnep vc4 dw9807_vcm imx708 spidev snd_soc_hdmi_codec drm_display_helper binfmt_misc brcmfmac_wcc hci_uart cec btbcm drm_dma_helper aes_ce_blk brcmfmac bluetooth drm_kms_helper aes_ce_cipher brcmutil ghash_ce gf128mul sha2_ce sha256_arm64 snd_soc_core rp1_cfe sha1_ce ecdh_generic cfg80211 rpivid_hevc(C) pisp_be v4l2_mem2mem snd_compress v4l2_fwnode ecc snd_pcm_dmaengine v4l2_async videobuf2_dma_contig raspberrypi_hwmon snd_pcm libaes videobuf2_memops videobuf2_v4l2 videodev rfkill snd_timer videobuf2_common snd v3d mc gpio_keys spi_bcm2835 i2c_brcmstb gpu_sched i2c_designware_platform raspberrypi_gpiomem i2c_designware_core drm_shmem_helper rp1_adc nvmem_rmem uio_pdrv_genirq uio i2c_dev drm fuse drm_panel_orientation_quirks backlight dm_mod ip_tables x_tables ipv6
[   41.261341] CPU: 0 PID: 986 Comm: rpicam-hello Tainted: G         C         6.6.8-v8+ #2
[   41.261345] Hardware name: Raspberry Pi 5 Model B Rev 1.0 (DT)
[   41.261346] pstate: 60400009 (nZCv daif +PAN -UAO -TCO -DIT -SSBS BTYPE=--)
[   41.261350] pc : cfe_start_streaming+0x860/0x8c8 [rp1_cfe]
[   41.261356] lr : cfe_start_streaming+0x3c4/0x8c8 [rp1_cfe]
[   41.261361] sp : ffffffc081bc3aa0
[   41.261363] x29: ffffffc081bc3aa0 x28: ffffff81046df480 x27: ffffff8104524000
[   41.261367] x26: ffffff8104521508 x25: ffffff810314b480 x24: ffffff8104520000
[   41.261370] x23: ffffff8104524000 x22: ffffff810391be00 x21: 0000000000000000
[   41.261374] x20: ffffff8104520c90 x19: ffffff8104520000 x18: 0000000000000000
[   41.261377] x17: 0000000000000000 x16: ffffffd084cff668 x15: 0000007f6c047f30
[   41.261381] x14: 0000000000000000 x13: 0000000000000000 x12: 0000000000000000
[   41.261384] x11: 0000000000000000 x10: 0000000000000000 x9 : ffffffd016e377a4
[   41.261387] x8 : 0000000000000000 x7 : 0000000000000001 x6 : 0000000000000510
[   41.261390] x5 : 0000000000000900 x4 : 000000000000301d x3 : ffffffd016e40478
[   41.261394] x2 : ffffffd016e40700 x1 : 0000000000000018 x0 : 0000000000000000
[   41.261397] Call trace:
[   41.261399]  cfe_start_streaming+0x860/0x8c8 [rp1_cfe]
[   41.261405]  vb2_start_streaming+0x74/0x170 [videobuf2_common]
[   41.261415]  vb2_core_streamon+0x120/0x1e8 [videobuf2_common]
[   41.261423]  vb2_streamon+0x24/0x80 [videobuf2_v4l2]
[   41.261432]  vb2_ioctl_streamon+0x58/0x70 [videobuf2_v4l2]
[   41.261438]  v4l_streamon+0x2c/0x40 [videodev]
[   41.261462]  __video_do_ioctl+0x18c/0x408 [videodev]
[   41.261478]  video_usercopy+0x334/0x768 [videodev]
[   41.261495]  video_ioctl2+0x20/0x40 [videodev]
[   41.261511]  v4l2_ioctl+0x48/0x70 [videodev]
[   41.261527]  __arm64_sys_ioctl+0xb0/0x100
[   41.261533]  invoke_syscall+0x4c/0x118
[   41.261538]  el0_svc_common.constprop.0+0x48/0xf0
[   41.261542]  do_el0_svc+0x24/0x38
[   41.261545]  el0_svc+0x48/0x100
[   41.261549]  el0t_64_sync_handler+0xc0/0xc8
[   41.261551]  el0t_64_sync+0x190/0x198
[   41.261553] ---[ end trace 0000000000000000 ]---
```

Adding the csi_dt value gives me an error within libcamera of
```
rpicam-hello: ../src/ipa/rpi/controller/histogram.cpp:50: double RPiController::Histogram::interBinMean(double, double) const: Assertion `binHi > binLo' failed.
```
binHi = 1023, binHi = 1023. 
It still has the kernel message
```
[   32.645447] source of link 'rp1-cfe-fe_config':0->'pisp-fe':1 is not a V4L2 sub-device, driver bug!
```
This has been introduced by 55f1ecb1199000932cf82e357841cc7498ac904f.

**Comment by naushir** [comment]
No objections to the changes, LGTM.

**Comment by naushir** [comment]
> Adding the csi_dt value gives me an error within libcamera of
> 
> ```
> rpicam-hello: ../src/ipa/rpi/controller/histogram.cpp:50: double RPiController::Histogram::interBinMean(double, double) const: Assertion `binHi > binLo' failed.
> ```
> 
> binHi = 1023, binHi = 1023.

This may be explained by the CSI2/FE thinking things are 16-bits and doing no shifts on the pixel data causing the stats to not add up correctly.

**Comment by naushir** [comment]
> It still has the kernel message
> 
> ```
> [   32.645447] source of link 'rp1-cfe-fe_config':0->'pisp-fe':1 is not a V4L2 sub-device, driver bug!
> ```
> 
> This has been introduced by [55f1ecb](https://github.com/raspberrypi/linux/commit/55f1ecb1199000932cf82e357841cc7498ac904f).

But the link here is between a device node entity and a v4l2-subdev entity IIRC.  Surely that has to be a valid configuration?

**Comment by 6by9** [comment]
> > It still has the kernel message
> > ```
> > [   32.645447] source of link 'rp1-cfe-fe_config':0->'pisp-fe':1 is not a V4L2 sub-device, driver bug!
> > ```
> >   
> > This has been introduced by [55f1ecb](https://github.com/raspberrypi/linux/commit/55f1ecb1199000932cf82e357841cc7498ac904f).
> 
> But the link here is between a device node and a v4l2-subdev entity IIRC. Surely that has to be a valid configuration?

I'd agree, but the core code is currently objecting to it since 6.4.

**Comment by 6by9** [comment]
@naushir Any other comments on this one, or can we merge?

**Comment by naushir** [comment]
Nope, LGTM.  Happy to merge it.

**Pull request merged**
