### PR TITLE
configs: add CONFIG_IR_TOY=m

### PR DESCRIPTION
**Pull request by davidschillerJKU**
This enables support for the Infrared Toy / Irdroid series of infrared
transceivers.

I think it would be quite useful to have this built by default.

### CODE REVIEW

**Comment by popcornmix** [comment]
Looks reasonable.

**Comment by pelwell** [comment]
It's fine, except it omits the 64-bit defconfigs.

**Comment by davidschillerJKU** [comment]
Sorry, I amended the commit now to include the 64 bit configs.

**Comment by pelwell** [comment]
Thanks!

**Pull request merged**
