### PR TITLE
Merge v4.14.114 stable release to rpi-4.14.y

### PR DESCRIPTION
**Pull request by pbrkr**
Backport commit 45fd8679ea86bffb352132a1df4917c3d11375aa, introduced in v4.14.114, renamed 'SDHCI_ACMD12_ERR' to 'SDHCI_AUTO_CMD_STATUS' and so the initial merge causes a compile error in the bcm2835-mmc driver. I've added an additional commit caa653325d58e5062907ec378269e77e6018f2ee to follow the rename and get things working again.

Boot tested on Raspberry Pi 3 in both 32-bit & 64-bit modes using a Yocto Project image.

### CODE REVIEW

**Comment by pbrkr** [comment]
@pelwell: Are there any automated tests you usually run on upstream kernel merges?

**Comment by pelwell** [comment]
No, not in a formal way beyond testing that it boots. We pull in all changes on the current branches and patch up problems as they are found. Pure upstream problems are relatively rare, with interactions between upstream changes and downstream code being more common sources of problems.

**Comment by pelwell** [comment]
Thanks - looks good to me.

**Comment by pelwell** [comment]
Merged offline - I'm not sure any of GitHub's merge options would do the right thing (rebase the merge  commit and the fixup, let the rest be covered by the merge), based on their descriptions.

**Pull request merged**
