### PR TITLE
configs: Drop V4L2 camera and codec drivers from bcmrpi3_defconfig

### PR DESCRIPTION
**Pull request by 6by9**
They rely on mmal_vchiq, which in turn wants vc-sm-cma.
vc-sm-cma needs some attention for 64 bit, so drop it for now.

Signed-off-by: Dave Stevenson <dave.stevenson@raspberrypi.org>

### CODE REVIEW

**Comment by 6by9** [comment]
Temporarily solves #3024 for Pi3.

**Comment by pelwell** [comment]
For some values of "Solves".

**Comment by 6by9** [comment]
I'm working on vc-sm-cma still, so will address 64bit support when I get there.

It's not just the cache ioctls - mmal_vchiq can't see some of the functions exported from vc-sm-cma for some reason. I suspect it's related to vc-sm-cma being a bool vs module. Too much black magic in there for a bear of very little brain.

**Comment by agherzan** [comment]
@pelwell should we remove V4L2 for `bcm2711_defconfig` as well?

**Comment by 6by9** [comment]
arm64/bcm2711_defconfig hasn't been a supported platform, therefore not building isn't a regression. 
arm64/bcmrpi3_defconfig not working was a regression.

I know what the issue is with vc-sm-cma. It's working but not quite in a shape to push.
Fixing that is the end goal rather, not dropping features.

**Comment by agherzan** [comment]
I agree, but the "solved" comment points to an issue that is raised against RPI4 which uses `bcm2711_defconfig`. I don't think it hurts to just have it in both places just for people who want to have an initial try.

**Comment by 6by9** [comment]
Earlier comment updated.

**Comment by pelwell** [comment]
@agherzan Yes - see 9d1deec.

**Comment by agherzan** [comment]
Thanks @pelwell . I really appreciate it.

**Pull request merged**
