### PR TITLE
Added support for Hauppauge NOVA HD DVB-S/S2 USB

### PR DESCRIPTION
**Pull request by dezi**
To whom it may concern:

I have taken the SU3000 USB DVB-S dw2102.c, ds3000.c and ts2020.c drivers from www.kernel.org, 3.9-rc6 and backported them into RPI kernel 3.6.y.

Plus I made additions to dw2102.c to recognize Hauppage USB DVB-S device with vendor ID 0x2040 and product ID 0xd900 to be a SU3000 / DS3000 device.

Tested and works well.

Cheers
dezi

### CODE REVIEW

**Comment by hvenzke** [comment]
exelent !!

**Comment by sepperl** [comment]
no frontend attached :-(

**Comment by sepperl** [comment]
copied the dw2102.c file to the suse kernel sources 3.11.0-rc2-2.g3fb567f-desktop and compiled the modules in drivers/media/usb/dvb-usb new and copied the files to /lib/modules/...
modprobe --force dvb-usb-dw2102 loads the module and is working together with me-tv and w_scan, kaffeine finds all transponders, but no image or sound
Without the force option results the modprobe command a "Invalid module format"
Seems that the failures are caused by other problems, dw2102.c for nova hd usb2  seems to be ok. Please attach to standard kernel sources!!!

**Comment by sepperl** [comment]
after recompiling the hole kernel with modules the driver is installed automaticaly by modprobe. Installing additional xine files solves the problem with kaffeine. Great Job!!!

**Comment by P33M** [comment]
Mainline is now 4.0.y - dw2102 is now available by default.

**Pull request closed without merging**
