### PR TITLE
Fix cfg80211 for kernel >= 4.7

### PR DESCRIPTION
**Pull request by fran6co**
Fixes https://github.com/raspberrypi/linux/pull/1525#issuecomment-243542945

### CODE REVIEW

**Comment by fran6co** [comment]
@popcornmix, this should be all.

**Comment by clivem** [comment]
@fran6co Francisco, I have given that a quick test on both my 2708 and 2709 rpi-4.7.y builds (on top of your previous patch sets) with 8188CUS and 8192CU. Thumbs up! Thanks.

**Comment by popcornmix** [comment]
Thanks. I tried cherry-picking to 4.8, but there is an additional issue:

```
drivers/net/wireless/realtek/rtl8192cu/os_dep/linux/ioctl_cfg80211.c: In function 'rtw_cfg80211_indicate_scan_done':
drivers/net/wireless/realtek/rtl8192cu/os_dep/linux/ioctl_cfg80211.c:1818:4: error: incompatible type for argument 2 of 'cfg80211_scan_done'
    cfg80211_scan_done(pwdev_priv->scan_request, aborted);
    ^
In file included from drivers/net/wireless/realtek/rtl8192cu/include/osdep_service.h:793:0,
                 from drivers/net/wireless/realtek/rtl8192cu/os_dep/linux/ioctl_cfg80211.c:23:
./include/net/cfg80211.h:4104:6: note: expected 'struct cfg80211_scan_info *' but argument is of type 'bool'
 void cfg80211_scan_done(struct cfg80211_scan_request *request,
      ^
```

**Comment by fran6co** [comment]
I'll check what changed from 4.7 to 4.8, shouldn't be hard to fix.

**Pull request merged**
