### PR TITLE
bcm2709: enable usb gadget functions

### PR DESCRIPTION
**Pull request by t-8ch**
they are already in bcmrpi_defconfig

### CODE REVIEW

**Comment by pelwell** [comment]
Thanks - I don't know what happened there.

**Comment by pelwell** [comment]
Yes I do - DWC2 wasn't enabled in bcm2709_defconfig until recently, and when it was added the gadget support was omitted. I've back-ported the fix to 4.14 and 4.15.

**Comment by t-8ch** [comment]
Thanks!

**Comment by t-8ch** [comment]
Is USB OTG actually supposed to work on a RPI 3 currently/at all?

(Without shields, trying with the power port,
the dcw2 overlay is loaded and the udc detected, but the host does not see anything)

**Comment by lurch** [comment]
The micro-USB power port on the RPi3 is power only, no data lines are connected. The RPi3 has a downstream USB hub chip (LAN9514) connected to the SoC's single USB connection, and this forces the USB connection into master mode.

AFAIK the only way to use USB OTG on bcm2709 (aka BCM2837) is via the Compute Module 3.

**Comment by t-8ch** [comment]
@lurch Thanks for the clarification!

**Pull request merged**
