### PR TITLE
configs: arm64/bcm2711: Add MMC_SDHCI_IPROC

### PR DESCRIPTION
**Pull request by agherzan**
This driver is used in the device tree for the emmc2 node.

See #3032

### CODE REVIEW

**Comment by pelwell** [comment]
Thanks! This must have got lost somewhere along the way.

By the way, the next firmware release should include the ARMv8 + GIC stub.

**Comment by Strit** [comment]
> Thanks! This must have got lost somewhere along the way.
> 
> By the way, the next firmware release should include the ARMv8 + GIC stub.

Awesome. Can't wait for it. Right now we are just hacking it in! :smiley:

**Comment by agherzan** [comment]
Good stuff @pelwell

**Comment by agherzan** [comment]
@Strit if you are using Yocto you will be having the "hack" built in soon. Just waiting on the builds.

**Pull request merged**
