### PR TITLE
imx290 fixes

### PR DESCRIPTION
**Pull request by 6by9**
Minor issues noted from https://github.com/raspberrypi/libcamera-apps/issues/344

### CODE REVIEW

**Comment by naushir** [comment]
Looks like a reasonable set of changes. Not tested it myself though.

**Comment by 6by9** [comment]
I've just been running with these, and if horizontal_blanking is increased to the max of 63615, then I can get just over 7 second exposures.  I've not checked with the exposure pattern generator, but the frame timings certainly all fit with the expected values.

**Comment by pelwell** [comment]
I can't parse the second commit message, but otherwise it look reasonable.

**Comment by 6by9** [comment]
> I can't parse the second commit message, but otherwise it look reasonable.

I think I've lost a line. I'll update and repush with it making sense!

**Comment by 6by9** [comment]
Branch updated. Hopefully the commit text makes more sense now.

**Pull request merged**
