### PR TITLE
[4.18] config: fix media device defconfigs

### PR DESCRIPTION
**Pull request by HiassofT**
A couple of DVB drivers (CX231XX, AF9015, RTL28XXU) now depend
on I2C_MUX so add I2C_MUX=m so we build the same set of
DVB drivers as in 4.14.

IR decoders no longer default to "y" in Kconfig and have
to be enabled in the defconfig.

Also add BPF_SYSCALL=y and BPF_LIRC_MODE2=y to enable support
for eBPF IR decoders which was added in 4.18.

defconfigs have been regenerated with "make savedefconfig"

### CODE REVIEW

**Comment by pelwell** [comment]
I'm happy with the first half of this commit (`I2C_MUX=m`) and the individual decode module enables, but your "Also" is less clear-cut. What is the overhead in terms of free space associated with `BPF_SYSCALL=y` and `BPF_LIRC_MODE2=y`?

**Comment by HiassofT** [comment]
Without BPF_SYSCALL/BPF_LIRC_MODE2 I get this memory info in dmesg
```
[    0.000000] Memory: 939096K/970752K available (8192K kernel code, 623K rwdata, 2140K rodata, 1024K init, 820K bss, 23464K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xbb800000 - 0xff800000   (1088 MB)
                   lowmem  : 0x80000000 - 0xbb400000   ( 948 MB)
                   modules : 0x7f000000 - 0x80000000   (  16 MB)
                     .text : 0x(ptrval) - 0x(ptrval)   (9184 kB)
                     .init : 0x(ptrval) - 0x(ptrval)   (1024 kB)
                     .data : 0x(ptrval) - 0x(ptrval)   ( 624 kB)
                      .bss : 0x(ptrval) - 0x(ptrval)   ( 821 kB)
```

With BPF_SYSCALL=y/BPF_LIRC_MODE2=y it looks like this:
```
[    0.000000] Memory: 939076K/970752K available (8192K kernel code, 646K rwdata, 2188K rodata, 1024K init, 820K bss, 23484K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xbb800000 - 0xff800000   (1088 MB)
                   lowmem  : 0x80000000 - 0xbb400000   ( 948 MB)
                   modules : 0x7f000000 - 0x80000000   (  16 MB)
                     .text : 0x(ptrval) - 0x(ptrval)   (9184 kB)
                     .init : 0x(ptrval) - 0x(ptrval)   (1024 kB)
                     .data : 0x(ptrval) - 0x(ptrval)   ( 647 kB)
                      .bss : 0x(ptrval) - 0x(ptrval)   ( 821 kB)
```

So available memory went down by about 20k ,rwdata+rodata+reserved went up by about 91k.

I also tried to monitor MemFree in /proc/meminfo (looped 20 times, with a second in between), but the results jumped a lot. Withouth BPF options I got 885764 - 886352 kB, with BPF options I got 885864 - 886640.

I'll let you decide if this is fine, if it's not drop me a line and I'll remove those 2 options.

**Comment by HiassofT** [comment]
Forgot to add: uncompressed image size went up by about 23k, compressed one by about 90k.

Without BPF options:
```
$ ls -la arch/arm/boot/*Image
-rwxr-xr-x 1 hias hias 14237180 Aug 20 14:47 arch/arm/boot/Image
-rwxr-xr-x 1 hias hias  5217072 Aug 20 14:47 arch/arm/boot/zImage
```

with BPF options:
```
$ ls -la arch/arm/boot/*Image
-rwxr-xr-x 1 hias hias 14261036 Aug 17 12:47 arch/arm/boot/Image
-rwxr-xr-x 1 hias hias  5310384 Aug 17 12:47 arch/arm/boot/zImage
```

**Comment by pelwell** [comment]
Your memory-usage-measurement experience sounds like mine - a lot of fluctuation and some counterintuitive results (MemFree increasing?).

Any thoughts, @popcornmix ?

**Comment by popcornmix** [comment]
So what exactly does eBPF give us? What can we do that we couldn't do before?

**Comment by HiassofT** [comment]
BPF_SYSCALL, which contributes the majority of kernel code, adds the infrastructure to load bpf programs into kernel space. Historically this has been mainly used for various filtering purposes (debugging/tracing, network packet filtering, restricting syscalls on a per-process basis etc) and is currently becoming more popular in other areas as well as it's a really versatile thing.

BPF_LIRC_MODE2 allows uploading IR protocol decoders into the kernel, which can eg be written in C and compiled to bpf with clang.

Current v4l-utils master version contains several generic, configurable bpf decoders (manchester, pulse_width, pulse_length) and a "lircd2toml.py" script that people can use to convert their existing lircd.conf file into a new ir-keytable "toml" conf file that loads the (usually precompiled) bpf decoder and sets up it's configuration.

The goal is to provide a solution to decode non-standard IR protocols via the kernel infrastructure without having to run userspace lircd and without having to write new in-kernel decoders/modules for each odd-ball remote protocol.

This will mainly be interesting for the people interfacing with home-automation or other specialized stuff as non-standard IR protocols are rather common there.

**Comment by lategoodbye** [comment]
I recommend to separate media fixes and the bpf stuff in 2 commits.

**Comment by HiassofT** [comment]
Fair enough, I removed the BPF config changes from this PR.

**Comment by popcornmix** [comment]
Feel free to submit BPF as a separate PR.
It's not a change we are outright rejecting, and having a PR that other users can comment on may help the decision.

**Pull request merged**
