### PR TITLE
drm/vc4: Fix out of order frames during asynchronous page flips

### PR DESCRIPTION
**Pull request by mripard**
This a port of the PR #4571 for 5.15, with the updated function name that was broken before.

### CODE REVIEW

**Comment by pelwell** [comment]
Did you push the wrong patch? That looks like a direct cherry-pick of f694d1cfee63.

**Comment by pelwell** [comment]
It can wait until next week, though.

**Comment by popcornmix** [comment]
Agreed - this doesn't build on 5.15 due to dma fence api changes.

**Comment by mripard** [comment]
> Did you push the wrong patch? That looks like a direct cherry-pick of [f694d1c](https://github.com/raspberrypi/linux/commit/f694d1cfee63afaaa77e7d9e1f621a83e2f98846).

No, I forgot to commit the changes I had locally... It should be ok now, sorry

**Comment by popcornmix** [comment]
This compiles now and kodi still runs. I don't have a test app that shows the out-of-order issue (but if it worked on 5.10 the odds seem good).

**Comment by bluestang2006** [comment]
> This compiles now and kodi still runs. I don't have a test app that shows the out-of-order issue (but if it worked on 5.10 the odds seem good).

Just tested this patch applied to rpi-5.16.y and it fixes the vsync issue with Quake3e and another OpenGL app I saw this issue with. Thanks for the fix. Closed #4901.

**Pull request merged**
