### PR TITLE
Support hevc frequency boost from rpivid

### PR DESCRIPTION
**Pull request by popcornmix**

### CODE REVIEW

**Comment by popcornmix** [comment]
Requires firmware update.
The boost works, but the unboost fails to work as desired (hevc clock remains boosted), so leaving as PR as draft for now.

**Comment by popcornmix** [comment]
I think this is okay now. Firmware side is merged.
I'm not switching to the clk_set_min_rate as it doesn't behave how we'd desire (reverting clock down when min request is removed).
As only one driver will adjust hevc clock then explicitly setting it is okay.

**Comment by pelwell** [comment]
The changes look fine, and I've tested that Pi 4 still boots with it. I haven't played any H265 videos, but am happy to merge on that basis.

**Comment by popcornmix** [comment]
The trivial test works (using powersave governor). 
```
pi@pi4d:~ $ vcgencmd measure_clock hevc
frequency(76)=249631344
# start video playing
pi@pi4d:~ $ vcgencmd measure_clock hevc
frequency(76)=550006336
# stop video playing
pi@pi4d:~ $ vcgencmd measure_clock hevc
frequency(76)=249631344
```

**Pull request merged**
