### PR TITLE
fix vcsm for multiplatform

### PR DESCRIPTION
**Pull request by invisiblek**

### CODE REVIEW

**Comment by invisiblek** [comment]
the commit i pushed yesterday didn't actually address the multi platform problem, it simply fixed a compiler error

**Comment by popcornmix** [comment]
This seems to stop ``bcm2709_defconfig`` from building:
```
arch/arm/mm/built-in.o:(___ksymtab+dmac_clean_range+0x0): undefined reference to `dmac_clean_range'
arch/arm/mm/built-in.o:(___ksymtab+dmac_inv_range+0x0): undefined reference to `dmac_inv_range'
drivers/built-in.o: In function `.LANCHOR1':
arm_pmu.c:(.rodata+0x93c4): undefined reference to `dmac_inv_range'
arm_pmu.c:(.rodata+0x93cc): undefined reference to `dmac_clean_range'
Makefile:972: recipe for target 'vmlinux' failed
```

**Comment by invisiblek** [comment]
Oh, I think I see what's up. I'll have something up shortly. I was only building multi-platform and overlooked non.

**Comment by invisiblek** [comment]
Ok, should be good now. Squashed that fix in to the first commit (as it really does belong there). The diff: https://gist.github.com/invisiblek/31df3a271854f38b04021b51f33e9d64

**Comment by popcornmix** [comment]
This looks okay to me and builds with bcm2709_defconfig and bcmrpi_defconfig.
@pelwell okay with you?

**Comment by pelwell** [comment]
Considering that we're changing upstream code it's as clean as it can be. I can live with this.

**Pull request merged**
