### PR TITLE
Update i2c-bcm2708.c

### PR DESCRIPTION
**Pull request by jeanlemotan**
Using combined transactions and heavy i2c traffic causes kernel panics and bus errors because the bcm2708_bsc_setup(bi) is not protected by the spin lock while the interrupt routine uses the bus.
This patch fixes the issue and makes combined transactions work again.

### CODE REVIEW

**Comment by popcornmix** [comment]
Looks valid - thanks.

**Comment by plugwash** [comment]
Any chance of seeing this fixed in other branches too, particuarlly 3.16 as that is the kernel version for jessie.

**Comment by popcornmix** [comment]
We're not planning to produce 3.16 kernel binaries as part of the supported firmware (and so on official raspbian sdcard images).
We are currently on 3.12 with wheezy and are likely to next move to 3.18 (still with wheezy). Moving to Jessie is desirable, but probably after the kernel bump (which is needed for device tree and HAT support).

There is no real dependency between kernel version and distribution version, apart from what kernel source gets packaged, but historically the kernel source has always been upstream source, and so not useful for Pi users.

Are you planning on distributing kernel source from this repo? Are you planning on distributing pre-built 3.16 kernel binaries as part of raspbian?

**Comment by plugwash** [comment]
popcornmix wrote:

> We're not planning to produce 3.16 kernel binaries as part of the 
> supported firmware (and so on official raspbian sdcard images).
> We are currently on 3.12 with wheezy and are likely to next move to 
> 3.18 (still with wheezy). Moving to Jessie is desirable, but probably 
> after the kernel bump (which is needed for device tree and HAT support).
> 
> There is no real dependency between kernel version and distribution 
> version, apart from what kernel source gets packaged, but historically 
> the kernel source has always been upstream source, and so not useful 
> for Pi users.
> 
> Are you planning on distributing kernel source from this repo? Are you 
> planning on distributing pre-built 3.16 kernel binaries as part of 
> raspbian?
> 
> Not just planning to, we already are. 3.16 is the kernel version Debian 
> has chosen for jessie and so there WILL be a 3.16 based kernel package 
> in raspbian jessie. Only question is how well supported will it be.

**Comment by popcornmix** [comment]
If the 3.16 kernel source and binaries are already custom for raspberry pi, is it possible to support other kernel versions (e.g. 3.18)?
3.18 is a better choice than 3.16 for raspberry pi, as it allows using more of the upstream device tree and mach-bcm2835 drivers, and it's what we are targeting for HAT support.
In an ideal world, latest kernel source and binaries could be installed/upgraded as a raspbian package, but it's better if the kernel version matches what we are developing and testing against.
There have been requests to support almost every kernel version, but realistically I can't do that. I'll continue to support the stable version (i.e. 3.12 as used on raspbian images) and the latest version (3.18), but other versions would need someone to volunteer to maintain them (I'll accept updates and backports as pull requests).

**Pull request merged**
