### PR TITLE
bcm2708-i2s add mono support

### PR DESCRIPTION
**Pull request by plughplover**
A small patch to enable mono support. Tested for 16/24/32 bit capture, and should also work for playback. All the i2s framing and timings remain the same, just don't enable channel 2 transfers.

### CODE REVIEW

**Comment by popcornmix** [comment]
Looks fine to me. If no objections in the new few days I'll merge.

**Comment by plughplover** [comment]
Obviously I don't understand the system. 

I committed a separate change (sign extension) in my 'fork' that I wanted to open up for discussion here and it now appears it has been linked to the mono one above. It is an independent patch.

**Comment by asb** [comment]
@plughplover it's a common mistake - you want to create a different branch for each active pull request to avoid this.

**Comment by popcornmix** [comment]
@plughplover 
Probably the best way of fixing this is to get this PR merged first.
So:

```
git rebase -i HEAD~2
(follow instructions to delete the sign extend commit)
git push -f
```

That should make this PR look correct. Once that is merged, you can do:

```
git cherry-pick e1a19c7
git push
```

and the second PR should look correct.

As asb says, next time PR a topic branch. E.g.

```
git checkout -b mono_enhancement
(add your commits)
git push
(create PR from branch "mono_enhancement")
```

Now you can have as many outstanding PRs as you want.

**Comment by plughplover** [comment]
@popcornmix I don't have 'git' installed. I did those using the web-site.
fyi - I used "rpi-source" to create source tree / build environment

Is there a way to just delete the rxsex commit? Or just wait and see if rxsex is agreeable to everyone and include it? It looks like I can edit the text labels for the "PR".

Sorry for the fumbles. (I _really_ didn't want to start down this path yet).

**Comment by plughplover** [comment]
@asb - don't know how to create a separate branch. Do know how to select a particular generation of a source file on the web-site. If (in the future) I selected the 'base' generation and edited / committed that, would that give the desired result? (Thinking about it, I _should_ have done that with rxsex patch - I see now how editing the 'mono' commit linked rxsex to it.)

**Comment by plughplover** [comment]
Hold off on this. Over the week-end I put together a completely synthetic test setup to exercise both these patches using _simultaneous_ playback and capture. I'm seeing "something" with the mono case that I need to dig into more deeply (my current suspicions are directed at the TX FIFO). I think next step is to break out my ancient but trusty HP logic analyzer and grab some bit-stream traces off the i2s pins. fwiw, the rxsex patch is passing with flying colors...

IMHO the test setup is pretty 'darn' cool. Only hardware needed is a pi and a jumper. More later...

**Comment by plughplover** [comment]
Found https://help.github.com/articles/github-flow-in-the-browser/ which clarified things a bit.

I'm going to close this PR and (hopefully - fingers crossed) redo it with just the mono part.

**Pull request closed without merging**
