### PR TITLE
katana volume minimum value correction

### PR DESCRIPTION
**Pull request by allo-com**
katana Volume change update to get the exact 0.5 db value in each step.

### CODE REVIEW

**Comment by pelwell** [comment]
Can I have a better commit message? Something like:

```
codecs: Correct Katana minimum volume

Update Katana minimum volume to get the exact 0.5 dB value in each step.

Signed-off-by: ??? <???@???>
```

**Comment by allo-com** [comment]
@pelwell 
 yes

**Comment by pelwell** [comment]
Comment again when it's done.

**Comment by allo-com** [comment]
@pelwell   yes commit message modified

**Comment by pelwell** [comment]
Where is the body of the commit message?

**Comment by allo-com** [comment]
better i remove this and create another pull request ?

**Comment by pelwell** [comment]
No - just post the body (including Signed-off-by:) as a comment here and I'll patch it up.

**Comment by allo-com** [comment]
"Update Katana minimum volume to get the exact 0.5 dB value in each step    Signed-off-by: sudeep <sudeepkumar@cem-solutions.net>"

**Comment by allo-com** [comment]
@pelwell       Thanks.

**Pull request merged**
