### PR TITLE
Remove spi override from merus-amp overlay

### PR DESCRIPTION
**Pull request by AMuszkat**
Previously added override at ["Add configuration override for MSEL0 on merus-amp overlay"](https://github.com/raspberrypi/linux/pull/4027) generates no audio in Raspberry pi 3 and 4 as due to MA12070P MSEL0 pin is only compatible with 5V. For now the solution is to remove the override and to avoid future problems on this board a hardware update will be launched soon.

### CODE REVIEW

**Comment by pelwell** [comment]
Do you have any comments, @shawaj?

**Comment by AMuszkat** [comment]
@pelwell,

Can we merge this? We haven't had any replies from @shawaj.

Best,
Ariel

**Comment by pelwell** [comment]
Sure, but can you call the commit `overlays: merus-amp: remove spi override`, and rebase it? GitHub looks a bit confused.

**Comment by AMuszkat** [comment]
done!

**Pull request merged**
