### PR TITLE
imx327/290/462 backports to 6.2

### PR DESCRIPTION
**Pull request by 6by9**
This patch set hasn't actually been merged upstream as yet, but I'm still hoping it'll hit 6.3.

Reverts all our downstream patches, applies the 2 upstream series, and then updates the overlays.

### CODE REVIEW

**Comment by pelwell** [comment]
Thanks - looks good to me.

**Comment by 6by9** [comment]
Shall I backport to 6.1 as well whilst we're still rebasing and it's going to be LTS?

**Comment by pelwell** [comment]
Yes, if you think it may save us from having to do so later when rebasing is not an option.

**Comment by 6by9** [comment]
Will do then.

**Pull request merged**
