### PR TITLE
Enable NFSv4 with Kerberos

### PR DESCRIPTION
**Pull request by sigmaris**
Building these modules allows use of NFSv4 with Kerberos. (This is the same change as #233 but updated to the current branch.)

### CODE REVIEW

**Comment by sigmaris** [comment]
@popcornmix Was there a reason that pull request #233 was never accepted? This change is fairly low-impact, it should only cause 2 extra in-tree modules to be built, and shouldn't have any effect on users if they don't make use of the modules.

**Comment by popcornmix** [comment]
As far as I can tell the only missing option is CONFIG_CRYPTO_CTS=m. Will add that in next build.
(CONFIG_RPCSEC_GSS_KRB5 and others are selected by other options)

**Comment by popcornmix** [comment]
CONFIG_CRYPTO_CTS is added in last firmware update.
Please confirm if you are missing any options.

**Comment by sigmaris** [comment]
I just updated my firmware with rpi-update, and it looks like all the config is correct and modules built; thanks @popcornmix.

**Pull request closed without merging**
