### PR TITLE
configs: enable pps_core module

### PR DESCRIPTION
**Pull request by lightswitch05**
It seems the pps_core module has disappeared. I've been able to enable the [pps_gpio](https://github.com/raspberrypi/linux/issues/3593#issuecomment-1823795799) module, but not `pps_core`. Perhaps this configuration needs to be added? There is also a chance I'm way off base, thank you in advance for having a look at the PR.

### CODE REVIEW

**Comment by pelwell** [comment]
What you've done is changed PPS from being built-in to being an external module, which is a step backwards. ntp_core (enabled with CONFIG_NTP_PPS) is not supported because we set `CONFIG_NO_HZ_COMMON=y`:
```
config NTP_PPS
	bool "PPS kernel consumer support"
	depends on !NO_HZ_COMMON
	help
	  This option adds support for direct in-kernel time
	  synchronization using an external PPS signal.

	  It doesn't work on tickless systems at the moment.
```
But that just means you need an external program to perform the synchronisation - isn't that what chronyd does?

FYI none of this has changed since 5.10, except for PPS being built-in.

**Comment by lightswitch05** [comment]
Thank you for your response @pelwell. Your example is showing `NTP_PPS`, but this PR is for `CONFIG_PPS`. Is that not a different configuration?

The issue I'm having isn't setting up time sync with either chrony or NTP, but just getting the system to recognize the PPS device and create `/dev/pps0`.

I was torn between the `m` setting and the `y`. Or maybe this `CONFIG_PPS` config is being defaulted to `y` somewhere else?

**Comment by pelwell** [comment]
CONFIG_PPS=y is being selected by something else. For each of the defconfigs, run:
```
$ make ARCH=arm <thing>_defconfig
$ grep PPS .config
$ make ARCH=arm savedefconfig
$ diff <thing>_defconfig defconfig
```
(or ARCH=arm64)
You'll see that CONFIG_PPS=y is set in all cases, and that when the defconfig is regenerated your setting is dropped.

**Comment by lightswitch05** [comment]
Ah ok, thank you for clearing that up for me!

**Pull request closed without merging**
