### PR TITLE
RPI-FT5406: Enable aarch64 support through explicit iomem interface

### PR DESCRIPTION
**Pull request by Gerharddc**
Signed-off-by: Gerhard de Clercq <gerharddeclercq@outlook.com>

### CODE REVIEW

**Comment by popcornmix** [comment]
Needs a rebase after 4.8.12
I can't really see what effect removing regs pointer would have.
Are you sure it doesn't work just with the ``iowrite8`` change?

**Comment by pelwell** [comment]
I'd argue the code is simpler without regs, so why not delete it?

**Comment by popcornmix** [comment]
I'm not against the change, but I'd like to know what in the patch is a bug fix and what is cosmetic.

**Comment by Gerharddc** [comment]
@popcornmix Ok yeah the code is the result of a problem I had as discussed on https://github.com/raspberrypi/linux/issues/1738 with @pelwell . From what I have just seen, the old code seems to actually work with the very latest firmware and the changes were needed for slightly older firmware to cope. I do think this is better than using "regs" though as it then doesn't treat iomem as a regular pointer (which isn't strictly legal but works here with the right firmware it seems) and as @pelwell said it's simpler without that extra pointer. Also, I'm not sure if rebase is a problem, this code should slot like this into any branch really?

I guess with the new firmware then everything is cosmetic but taking into account that this works even with the old firmware I guess it is more "rugged" or something.

**Comment by Gerharddc** [comment]
I don't know what happened to the pull request but I see there is now something like 200 commits in it? Maybe I should resubmit it and then also just submit it as being more cosmetic?

**Comment by popcornmix** [comment]
@Gerharddc it needs rebasing. Run:
```
git pull --rebase upstream rpi-4.8.y
git push -f
```
(assuming raspberrypi/linux repo is called upstream) and the PR should look good again.

**Comment by Gerharddc** [comment]
@popcornmix  O, now I get what you meant, sorry for the misunderstanding. It's been done now though.

**Comment by Electron752** [comment]
Any reason why this PR can't be accepted?

I did something very similar back in the July/August to get the touchscreen to work so I think the change should be safe.  And I think it's relatively safe to say this is a downstream only driver for the future so it makes sense for it to be here.

**Comment by pelwell** [comment]
I'm happy with this change, provided whoever merges it adds a '6' to the commit message.

**Comment by popcornmix** [comment]
Thanks. Added to 4.8 and 4.9 trees.

**Pull request merged**
