### PR TITLE
i2c: designware: Add support for bus clear feature

### PR DESCRIPTION
**Pull request by pelwell**
Newer versions of the DesignWare I2C block support the detection of stuck signals, and a mechanism to recover from them. Add the required software support to the driver.

This change was prompted by the observation that reading a single byte from register 0 of a VEML7700 seems to cause it to issue an ACK too early, and the controller to complain about losing arbitration. There is a suspicion that this may be a more widespread problem, but at least this patch prevents the bus from locking up.

See: https://github.com/raspberrypi/linux/issues/6057

### CODE REVIEW

**Comment by pelwell** [comment]
I can provoke the lockup using a VEML7700 by running:
```
$ i2cget -y 1 0x10 0; i2cget -y 1 0x10 0
```
Reading pairs of bytes, as expected by the device, does not exhibit the problem:
```
$ i2cget -y 1 0x10 0 w; i2cget -y 1 0x10 0 w
```

**Comment by pelwell** [comment]
It's also worth noting that the same sequence also causes an error on Pi 4 (and presumably the other members of the BCM2835 family). For anyone interested, the early ACK makes the read portion of the second access appear as another write, i.e:
```
SW10A00ASR10AvvNP
SW10A00ASW10NP

S=Start, W=Write, A=ACK, R=Read, N=NAK, P=Stop, vv=Variable value
```

**Comment by pelwell** [comment]
The autobuilds have completed - running `sudo rpi-update pulls/6071` will install a trial, beta kernel including this patch. Remember to back-up important data before installing, just in case.

**Comment by JinShil** [comment]
I tested this on a number of different slave devices and did not observe any regressions.

**Comment by pelwell** [comment]
Thanks - that's good to hear.

**Pull request merged**
