### PR TITLE
Add a gpio-fsm driver and some example overlays

### PR DESCRIPTION
**Pull request by pelwell**
The gpio-fsm driver implements simple state machines that allow GPIOs
to be controlled in response to inputs from other GPIOs - real and
soft/virtual - and time delays. It can:
+ create dummy GPIOs for drivers that demand them,
+ drive multiple GPIOs from a single input, with optional delays,
+ add a debounce circuit to an input,
+ drive pattern sequences onto LEDs
etc.

To do:
* Add irqchip support so that soft GPIOs can be waited on.
* Add a sysfs interface to display the current state of each FSM.

Signed-off-by: Phil Elwell <phil@raspberrypi.com>

### CODE REVIEW

**Comment by pelwell** [comment]
Are there any objections to merging this? Apart from some warnings about dt-bindings and documentation it's checkpatch clean, and harmless unless used.

**Comment by popcornmix** [comment]
It looks interesting and I didn't spot anything troubling on a quick read through.
This isn't Pi specific - any thoughts on upstreaming?

But for now, feel free to merge.

**Comment by pelwell** [comment]
The biggest hurdle to upstreaming it is likely to be that the DT devs would object to the fact that I'm using Device Tree to configure some software.

**Comment by JamesH65** [comment]
BURN THE HERETIC!

**Pull request merged**
