### PR TITLE
Update drivers/usb/serial/option.c

### PR DESCRIPTION
**Pull request by ghost**
USB: option: add Telekom Speedstick LTE II

### CODE REVIEW

**Comment by popcornmix** [comment]
In general we are not keen on taking kernel patches as it prodcues a maintenance headache when moving to newer kernel trees and could introduce issues for others.

Is this patch taken from upstream linux kernel source?
If not I'd suggest requesting it is added there, and we will pick up the fix in the future.

**Comment by TenStepsAhead** [comment]
It is a patch out of the 3.7.3 Kernel

**Comment by popcornmix** [comment]
Can you point me at the upstream commit?

**Comment by technion** [comment]
I believe this is the commit he was referring to:
http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=5ec0085440ef8c2cf50002b34d5a504ee12aa2bf

**Comment by popcornmix** [comment]
This was merged from upstream:
https://github.com/raspberrypi/linux/commit/51c2c3f02a8fe447019e26d245e76be084b61480

**Pull request closed without merging**
