### PR TITLE
Add support for multiple AP configurations to rt2x00 wifi devices

### PR DESCRIPTION
**Pull request by rwg0**
rt2x00/ralink devices are very common now - most of the cheap USB wifi dongles on ebay seem to have this chipset. They should support multiple access points on a single device - i.e. run two wireless networks like a private and a guest network from the one device. 

The existing code doesn't cope with this and if you try to set up a second network (wlan0_0) it just tells you the device is already busy. I found a patch for this problem on openwrt which applied cleanly to the source (http://patchwork.openwrt.org/patch/2928/) and works for me.

### CODE REVIEW

**Comment by popcornmix** [comment]
If this patch is good, it would be better if it was submitted to upstream kernel (and we can cherry-pick it from there).
Generally I'm not keen on picking up out of tree patches, as they produce a maintenance headache, and potential instability.

**Comment by rwg0** [comment]
Actually, after a little more digging I found the same changes upstream : 

https://github.com/torvalds/linux/commit/55d2e9da744ba11eae900b4bfc2da72eace3c1e1
https://github.com/torvalds/linux/commit/3e4c4151e56ff367fb1487ea79134eea74104077

so you should be able to cherry-pick them 

hope this helps.

Robin

**Comment by popcornmix** [comment]
These may be in our 3.8.8 kernel:
https://github.com/raspberrypi/linux/issues/225

**Comment by P33M** [comment]
Current branch is 3.12 which has these changes merged.

**Pull request closed without merging**
