### PR TITLE
ARCH_BCM2835 closing in on ARCH_BCM270X

### PR DESCRIPTION
**Pull request by notro**
This PR attempts to close the gap between ARCH_BCM270X and ARCH_BCM2835 when it comes to functionality and drivers.
bcm2835_defconfig should now be similar to bcmrpi_defconfig (except dwc_otg and lirc_rpi).
DT overlays and parameters need testing.
#### Known issues

**Halt**
Halt/poweroff results in reboot. I will take the patch to fix this upstream first.

**vchiq**
vchiq works partially. Onboard sound, which relies on vchiq, works when using `speaker-test`, but omxplayer hangs.
vchiq_test does not produce any output:

```
$ vchiq_test -p
Ping test - service:echo, iters:1000, version 3
^C
```

**dwc_otg**
Because [irq-bcm2835](http://lxr.free-electrons.com/source/drivers/irqchip/irq-bcm2835.c) lacks FIQ support, [dwc_otg/](https://github.com/raspberrypi/linux/tree/rpi-4.0.y/drivers/usb/host/dwc_otg) doesn't work on ARCH_BCM2835. The mainline dwc2 driver is used.

**lirc_rpi**
[lirc_rpi](https://github.com/raspberrypi/linux/blob/rpi-4.0.y/drivers/staging/media/lirc/lirc_rpi.c) fails to build: missing bcm2708_gpio_setpull().

### CODE REVIEW

**Comment by pelwell** [comment]
No objections.

**Comment by notro** [comment]
I see that 'git commit' took away my comments in _bcm2835: Merge bcm2835_defconfig with bcmrpi_defconfig_, so I repost it here. Not terribly important, but anyway:

```
# Get changed and new config values from a merge
./scripts/diffconfig -m arch/arm/configs/bcm2835_defconfig arch/arm/configs/bcmrpi_defconfig > merge.cfg

# Remove these
# USB_DWCOTG needs FIQ which we don't have yet
# LIRC_RPI fails to build
cat << EOF > filter
CONFIG_ARCH_BCM2708
CONFIG_BCM2708_DT
CONFIG_ARM_PATCH_PHYS_VIRT
CONFIG_PHYS_OFFSET
CONFIG_CMDLINE
CONFIG_BCM2708_WDT
CONFIG_HW_RANDOM_BCM2708
CONFIG_I2C_BCM2708
CONFIG_SPI_BCM2708
CONFIG_SND_BCM2708_SOC_I2S
CONFIG_USB_DWCOTG
CONFIG_LIRC_RPI
EOF

# Filter values from the merge
grep -F -v -f filter merge.cfg > filtered.cfg

# Add these
# watchdog is builtin, will later contain restart/poweroff code.
cat << EOF > added.cfg
CONFIG_WATCHDOG=y
CONFIG_BCM2835_WDT=y
CONFIG_MISC_FILESYSTEMS=y
CONFIG_SND_BCM2835_SOC_I2S=m
EOF

# Create new config
ARCH=arm scripts/kconfig/merge_config.sh arch/arm/configs/bcm2835_defconfig filtered.cfg added.cfg
# Verify
ARCH=arm make oldconfig

# Update bcm2835_defconfig
ARCH=arm make savedefconfig
cp defconfig arch/arm/configs/bcm2835_defconfig

# Clean up
rm merge.cfg filter filtered.cfg added.cfg defconfig

# Verify
ARCH=arm make bcm2835_defconfig
ARCH=arm make oldconfig

```

**Comment by pelwell** [comment]
@notro Can you try this (https://gist.github.com/pelwell/b42fa101f209edfd6fbb) patch and see if it fixes your VCHIQ problem. I've tested omxplayer on a BCM2835 build, and on Pi 1 and Pi 2 with and without  DT so it should be OK.

There is some remaining issue (probably a race condition) with vchiq_test -p that causes it to stall on the first few runs, but if you Ctrl-C and repeat it will eventually run, but that's a battle for another day.

**Comment by notro** [comment]
Tried it on ARCH_BCM2835 and omxplayer works now. vchiq_test needs 3-4 tries to get going.

**Comment by pelwell** [comment]
I found that the same is true on 270x builds as well. I'll push this.

**Pull request merged**
