### PR TITLE
Added support for proto i2s DAC board

### PR DESCRIPTION
**Pull request by BBUK**
This is a reworking of (https://github.com/raspberrypi/linux/pull/480) to take account of comments received from koalo.  It implements the changes needed to get Mikroelektronika's Proto i2s DAC board (WM8731 based) working.  It is basically the 3.8 board driver with a couple of 3.10-related changes. 

As koalo indicated, I have split this into 2 commits, one for bcm2708.c and one for the other changed/inserted files.

Sorry for reissuing this as a new pull request, I over-committed on my original fork which made my changes difficult to see.

BBUK

### CODE REVIEW

**Comment by koalo** [comment]
Looks very good to me, thank you!
(Although, a more calling name for the commits would have made it more clear)
One thing that I had forgotten: Please add the codec and machine modules to the default config
(https://github.com/koalo/linux/commit/6a6205d2c7b3a55c94bb7818a3b4a212be8e0dcf)

**Comment by fl4p** [comment]
I have added a module parameter to switch between 11289600 and 12288000. Can I merge into this pull request?
11.x Mhz supports 44.1 kHz sampling rate and the codec shield by openmusiclabs http://www.openmusiclabs.com/projects/codec-shield/ runs at that frequency.

**Comment by koalo** [comment]
@BBUK: You should rename your commits. I assume it will not be merged this way.
@f4bsch: You could merge into this pull request by sending a pull request to BBUK. If he merges your commit, probably it should appear here, too. Although, it would be better to wait for this pull request being merged to avoid confusion.

**Comment by amtssp** [comment]
Hi
Please, could this be pulled into 3.12.y as well?

**Comment by pelwell** [comment]
Superceded by #908.

**Pull request closed without merging**
