### PR TITLE
Make gpio pullup configurable for lirc driver

### PR DESCRIPTION
**Pull request by julianscheel**
This patch series allows users of the lirc_rpi driver to specify the pull behaviour of the gpio_in_pin, which can be very helpful depending on the external IR circuitry.

Please comment on creating `include/linux/platform_data/bcm2708.h` to specify function header and enum. I am a bit unsure if there isn't some better suited place already existing...

### CODE REVIEW

**Comment by julianscheel** [comment]
Any objections on this patchset?

**Comment by popcornmix** [comment]
I believe there is a plan to support this from a pinctl driver which is probably more correct.
It's also possible to configure pull-ups / pull-downs from the dt-blob.bin file.

It may be safer to default to no pulling - this patch looks like it changes the default behaviour.

**Comment by julianscheel** [comment]
At least the pins I used defaulted to pull-down, which is why I chose it as default. Maybe it'd be best to have default=don't touch.

You're probably right that pinctrl is the correct place to deal with this.
Regarding dt-blob.bin: Is the raspberrypi kernel tree fully dt aware in the meantime? I thought it would still not use dt at all and the only parts that have dt support are those for which mainline support was added by Stephen Warren?
Once dt support is fully available it would probably make more sense to have gpio as well as lirc driver configured via dt entirely instead of using module options. But I don't think lirc drivers have any devicetree support yet...

**Comment by popcornmix** [comment]
dt-blob.bin is a GPU only device tree file that can be used to set GPU side gpio configuration.

Some documentation here:
http://www.raspberrypi.org/documentation/configuration/pin-configuration.md

**Comment by popcornmix** [comment]
While I think there are more correct ways of implementing this, it does provide a more straightforward solution to issues like https://github.com/raspberrypi/firmware/issues/319#issuecomment-57659689.

I've added to 3.16.y branch to see any issues are reported.

BTW, the header file has a missing semi-colon and doesn't compile as the patch stands.

**Comment by popcornmix** [comment]
Cherry-picked (with semi-colon added) to 3.12. Closing.

**Pull request closed without merging**
