### PR TITLE
Support for I2S/PCM interface

### PR DESCRIPTION
**Pull request by koalo**
This patch series adds support for the I2S/PCM interface of the Raspberry Pi.

It is a rebased version of #444.

Greetings,
Florian

### CODE REVIEW

**Comment by popcornmix** [comment]
Firmware is updated, so rpi-update should get this. Please confirm it works okay.

**Comment by koalo** [comment]
Works perfectly! Thank you very much!

**Comment by amtssp** [comment]
Would it be possible to include I2S/PCM in kernel 3.12.y also?

**Comment by koalo** [comment]
Would be possible, yes. You could try to apply this patch series to the 3.12 kernel. If you encounter any problems please contact me again.

**Comment by amtssp** [comment]
Hi Koalo and Dom.
Thank you for the positive response, I have looked into this, but frankly I don't know how to proceed.

I would really appreciate that i2s/PCM support was included in kernel 3.12.y , and if I knew how, I would be working on it.

Could you guide me in the process, or make it happen as an official raspberry addition to the 3.12.y version.

Thanks

**Comment by amtssp** [comment]
Thank you, I see It is now official in 3.12.y, thank you so much.

**Comment by popcornmix** [comment]
@amtssp 
Are you able to test it works okay with 3.12?

**Comment by amtssp** [comment]
@popcornmix , yes I just compiled kernel 3.12.6 and the modules without problems or errors. 
The purpose is to make a small audio player based on microcore Linux, so I need probably a day or so to finish it.
I have a hifiberry I2S DAC , so I should be able to test it.

I will report back as soon as I have tested it.

**Comment by amtssp** [comment]
Hi Koalo and popcornmix.

I have a hifiberry I2S DAC from crazyaudio 

I have build the new kernel and the modules (version 3.12.6) (followed the description from crazyaudio http://www.crazy-audio.com/projects/hifiberry-mini/hifiberry-mini-linux-configuration/   - but I have a few problems.

doing a lsmod reveals this (I seem to be missing both: snd_soc_bcm2708    and    snd_soc_rpi_pcm5102a if I compare with the recipe on the crazyaudio site   )

tc@box:~$ lsmod
Module                  Size  Used by    Not tainted
snd_soc_rpi_dac         1933  0
bcm2708_dmaengine       5096  0
virt_dma                2021  1 bcm2708_dmaengine
snd_soc_pcm5102a        1390  0
snd_soc_hifiberry_dac     2091  0
ipv6                  283138 10
snd_usb_audio         116282  0
snd_usbmidi_lib        18748  1 snd_usb_audio
snd_rawmidi            20181  1 snd_usbmidi_lib
snd_seq_device          6034  1 snd_rawmidi
snd_hwdep               5901  1 snd_usb_audio
snd_soc_bcm2708_i2s     5494  0
snd_soc_core          115442  4 snd_soc_rpi_dac,snd_soc_pcm5102a,snd_soc_hifiberry_dac,snd_soc_bcm2708_i2s
snd_pcm_dmaengine       4564  1 snd_soc_core
snd_pcm                75156  4 snd_soc_hifiberry_dac,snd_usb_audio,snd_soc_core,snd_pcm_dmaengine
snd_page_alloc          4684  1 snd_pcm
snd_timer              19242  1 snd_pcm
snd_compress            7926  1 snd_soc_core
snd                    56405  9 snd_usb_audio,snd_usbmidi_lib,snd_rawmidi,snd_seq_device,snd_hwdep,snd_soc_core,snd_pcm,snd_timer,snd_compress
regmap_i2c              1522  1 snd_soc_core
regmap_spi              1774  1 snd_soc_core
regmap_mmio             2673  1 snd_soc_bcm2708_i2s

This is the result of aplay-l
aplay -l
aplay: device_list:268: no soundcards found...

**Comment by amtssp** [comment]
Hi

I think we need this module in 3.12.6:
 snd_soc_bcm2708

I can't find it anywhere.

Steen

**Comment by koalo** [comment]
The module names have changed. The current names that you have to include in /etc/modules are:
snd_soc_bcm2708_i2s
bcm2708_dmaengine
snd_soc_pcm5102a
snd_soc_hifiberry_dac

The snd_soc_bcm2708 is no longer needed because it is replaced by a generic driver.

**Comment by amtssp** [comment]
Thanks

Then I can see all the modules in my build using lsmod:
bcm2708_dmaengine
snd_soc_pcm5102a 
snd_soc_hifiberry_dac 
snd_soc_bcm2708_i2s

But still no sign of the hifiberry DAC using "aplay -l"

I suspect that the card is broken?

Steen

**Comment by koalo** [comment]
Even if the card is broken, aplay would show the sound card (there is no return channel). 
Please post the output of dmesg to a new issue at https://github.com/koalo/linux in order to reduce the noise here.

**Comment by amtssp** [comment]
Hi Koalo and dom. 
Just for your information it is working fine using PCM over i2s to a hifiberry DAC with kernel 3.12.6.
Steen

**Comment by koalo** [comment]
Nice, thanks!

**Pull request merged**
