### PR TITLE
64bit cleanups for V4L2 and bcm2708_fb

### PR DESCRIPTION
**Pull request by 6by9**
These are the (hopefully) non-contentious patches from #2828.

### CODE REVIEW

**Comment by pelwell** [comment]
Looks good to me.

**Comment by 6by9** [comment]
Anything else you want on this before merging then?

**Comment by pelwell** [comment]
@popcornmix?

**Comment by popcornmix** [comment]
Looks fine. Needs a rebase before merging.

**Comment by 6by9** [comment]
> Looks fine. Needs a rebase before merging.

It does? Github says no conflicts. Top commit on rpi-4.19.y is ```8f862ee audioinjector-octo: revert to dummy supplies``` which is the commit onto which these 6 patches have been added. Colour me confused.

**Comment by popcornmix** [comment]
Strange, "Rebase and Merge" button shows:
"This branch cannot be rebased due to conflicts" and button is disabled.

However we can merge with a merge commit (normally avoided on this branch).

**Comment by 6by9** [comment]
OK, no problem, I'll rebase and repush to see if we can make Github happy. Merge commits confuse me no end.

**Comment by 6by9** [comment]
How about now?

**Comment by popcornmix** [comment]
Yes, that was happy.

**Comment by 6by9** [comment]
Thank you.
When in doubt, beat it with a big stick!

**Comment by pelwell** [comment]
Then rebase.

**Pull request merged**
