### PR TITLE
Revert "dwc_otg: Add the dependency on FIQ"

### PR DESCRIPTION
**Pull request by johannes-krude**
This reverts commit 8b68f431a6168c65f67f0c6b645e9c925f90a7c7.

### CODE REVIEW

**Comment by popcornmix** [comment]
This was added for a reason (https://github.com/raspberrypi/linux/issues/1971) so we won't revert it.
But we can probably come up with more accurate dependency.
Does changing it to:
```
depends on USB && (FIQ || ARM64)
```
work for you?

**Comment by johannes-krude** [comment]
Tested it: `depends on USB && (FIQ || ARM64)` leads to a arm64 kernel with working usb.

**Comment by popcornmix** [comment]
Okay - I've pushed that change.

**Comment by johannes-krude** [comment]
Thank you.

**Pull request closed without merging**
