### PR TITLE
Support for I2S/PCM interface

### PR DESCRIPTION
**Pull request by koalo**
This patch series adds support for the I2S/PCM interface of the Raspberry Pi.
The drivers exist since May and are widely tested by the community:
http://blog.koalo.de/2013/05/i2s-support-for-raspberry-pi.html

Greetings,
Florian

### CODE REVIEW

**Comment by popcornmix** [comment]
It's okay in principle (subject to some sanity testing).

Non-upstreamed kernel code can cause a headache when moving to newer kernel versions, so I may have to leave you responsible for fixing that up if things break.
E.g. if these patches break with kernel 3.13, I may drop them until a fixed PR comes in.

**Comment by koalo** [comment]
Thank you!
That sounds like a reasonable approach. I will send you new pull requests for 3.13 then.
Hopefully these drivers will be upstreamed for 3.14, but since it will take some time until 3.14 and many people want to have these drivers in 3.10, I thought it would be good to issue this PR.

**Comment by popcornmix** [comment]
@koalo 
Preumably you also want these modules enabled in bcmrpi_defconfig? Can you add a commit for that?

**Comment by koalo** [comment]
Of course - I will do that.
Since there will be support for multiple extension boards, do you think I should enable the board specific modules in defconfig, too?

**Comment by popcornmix** [comment]
Perhaps if you explain what boards this PR supports (and where you buy them) and what board specific modules are required I'll have a better idea.

**Comment by koalo** [comment]
The majority of this PR is the generic I2S driver itself that can be utilized for all boards very easily - anyone how wants to build an own board just has to add some specific "wiring". There is a module for the generic driver and one for each "wiring" (machine driver in ASoC speech).

Currently there is support for the HifiBerry Mini (http://www.hifiberry.com/). Drivers for the other existing boards (RPi-DAC http://www.tjaekel.com/T-DAC/ and this one: http://www.noiseisgood.co.nz/?p=574) will follow soon.

Maybe it is reasonable to enable all modules, because they have to be loaded by /etc/modules anyway. When the modules are not enabled it would be necessary for all end users to compile these modules on their own.

**Comment by popcornmix** [comment]
I'd say definitely include modules for any chips that are being used in Pi-specific add on boards.
If enabling the remaining modules is relatively small (e.g. adds less than a few hundred K to modules) then just enable them all.

BTW: do you expect this driver to work with this:
http://www.element14.com/community/community/raspberry-pi/raspberry-pi-accessories/wolfson_pi

I'm wondering if there's going to be a competing I2S/PCM driver submitted soon.

**Comment by koalo** [comment]
Ok - the modules will be very small so I will enable them all.
It should be very easy to add support for the Wolfson Pi Board, too, as soon as it is available. Even the codec driver is already available in the kernel.
Although, I don't know if they have implemented an own version of this driver or just used mine. They don't answer my mail. Anyway, they should be completely compatible thanks to the ASoC subsystem.

**Comment by koalo** [comment]
I have added the module config, 24 bit support and a further machine driver.
Furthermore, Wolfson finally replied to me: They use my driver anyway so there will be no competing driver.
Therefore, I would be glad if you could merge this PR.

**Comment by popcornmix** [comment]
Sounds good. Can you rebase? There seem to be some unwanted merge commits.

**Comment by koalo** [comment]
They are intentional, but if you prefer to avoid merge commits, I will
rebase on Monday.

**Comment by popcornmix** [comment]
Yes, I'd prefer to lose the merges.

**Comment by koalo** [comment]
Rebased version in #461

**Pull request closed without merging**
