### PR TITLE
enable several virtual devices for hosting virtual machines

### PR DESCRIPTION
**Pull request by smcavoy**
This enable several features used for hosting virtual machines. The [LXD](https://linuxcontainers.org/lxd/introduction/) platform specifically use these features. 

LXD specifically targets Raspberry Pi as a [platform](https://discuss.linuxcontainers.org/t/lxd-cluster-on-raspberry-pi-4/9076) 

Enabling these features makes it easier for OS packagers to include functional LXD on Raspberry Pi easily.

### CODE REVIEW

**Comment by pelwell** [comment]
This kind of PR is relatively easy to approve, in that it just requests some modules to be enabled - the core kernel is unchanged. Although there are 6 new modules, they aren't huge:
```
31592 drivers/vhost/vhost_vsock.ko
11656 drivers/net/vsockmon.ko
8600  net/vmw_vsock/vsock_diag.ko
59136 net/vmw_vsock/vmw_vsock_virtio_transport_common.ko
68280 net/vmw_vsock/vsock.ko
13760 net/vmw_vsock/vsock_loopback.ko
```
However, I do want you to update the PR to put the new config options into the natural order. You can do this for e.g. `bcm2711_defconfig` by:
```
$ make ARCH=arm64 bcm2711_defconfig
$ make ARCH=arm64 savedefconfig
$ cp defconfig arch/arm64/configs/bcm2711_defconfig
```
Once you've done that for both defconfig files you can either push the changes as a followup commit which I can then squash while merging, or squash/amend it at your end, `git push -f` to update your PR then I can just merge it.

Either way, add a comment here when you're done.

**Comment by pelwell** [comment]
The updated commit looks correct with respect to the file order, but it has lost three modules:
```diff
-CONFIG_VSOCKETS_DIAG=m
-CONFIG_VSOCKETS_LOOPBACK=m
-CONFIG_VIRTIO_VSOCKETS_COMMON=m
```
Is that intentional?

**Comment by smcavoy** [comment]
That was not intentional. I am just looking into that now. will update in just a few.

**Comment by smcavoy** [comment]
with the unsorted modules enabled in the defconfig the .config is configured with the correct modules enabled (specifically the 3 mentioned). When `savedefconfig` is run the modules are not enabled in the `defconfig`  file.
Any thoughts?

**Comment by pelwell** [comment]
It's fine - those options are implied by the others (if you look in the .config file you'll find they are still present).

**Comment by pelwell** [comment]
(I should have spotted that sooner)

**Comment by smcavoy** [comment]
I created another [PR](https://github.com/raspberrypi/linux/pull/4713) for 5.15.y 

Thanks for the help

**Pull request merged**
