### PR TITLE
dtoverlays: Add VCM option to imx519

### PR DESCRIPTION
**Pull request by ArduCAM**
VCM is enabled by default, but you can use 'vcm=off' to disable VCM support.

vcm related PR: #5351

### CODE REVIEW

**Comment by ArduCAM** [comment]
#5351

**Comment by pelwell** [comment]
@6by9 is the expert here, but in my opinion adding the VCM declaration into `imx519.dtsi`, even if it is disabled, breaks the layering. The imx219 support, which I'm sure you are familar with, puts it in the parent overlay `imx219-overlay.dts`.

**Comment by 6by9** [comment]
This takes the same approach as taken by imx708, and that's the only sensor we really care about with VCM (ov5647 and imx219 with VCM are 3rd party products). Having the VCM in the sensor dtsi makes life easier in camera-mux-2port and camera-mux-4port.

Potentially we could have generic VCM dtsi files for each driver chip that get pulled in, but I'm not convinced it is worth it as currently only ov5647 and imx219  use the same VCM.
It would keep the layering clean though, and potentially we could see variants of the same sensor with different VCMs.

**Comment by pelwell** [comment]
I'm going to take that as approval.

**Pull request merged**
