### PR TITLE
Commit upstream ak7375

### PR DESCRIPTION
**Pull request by ArduCAM**
Upstream patch:
https://patchwork.linuxtv.org/project/linux-media/patch/20221209143741.214242-4-y.oudjana@protonmail.com/

### CODE REVIEW

**Comment by 6by9** [comment]
As the commits have made it into an upstream kernel tree that will get merged to master, please add the commit hashes of the upstream patches as had been requested in https://github.com/raspberrypi/linux/pull/5350#issuecomment-1432963342

[6d801f89ad7c485bbb14c0138d991beebd307aa6](https://git.linuxtv.org/media_tree.git/commit/?id=6d801f89ad7c485bbb14c0138d991beebd307aa6) 
[04a79f078329b14f260db15250e84c97022f42cd](https://git.linuxtv.org/media_tree.git/commit/?id=04a79f078329b14f260db15250e84c97022f42cd)
[90f7e76eac50c1ae54a445abc6a286837ade46cf](https://git.linuxtv.org/media_tree.git/commit/?id=90f7e76eac50c1ae54a445abc6a286837ade46cf)

You are also still missing an update to the dtoverlay for imx519.

**Comment by ArduCAM** [comment]
Thank you for your reply,
> You are also still missing an update to the dtoverlay for imx519.

I am going to submit a separate PR for dtoverlay for imx519.
Do I need to submit imx519 in the same PR?

**Comment by pelwell** [comment]
Separate PRs is fine, but the request (and the convention) is for the first line of the commit message for back ports to be:
```
commit <hash> upstream.
```

**Comment by ArduCAM** [comment]
> Separate PRs is fine, but the request (and the convention) is for the first line of the commit message for back ports to be:

> commit <hash> upstream.

Sorry, I misunderstood.
I tried putting the commit on the first line, but it looked weird from the github commits, so I just put it on the second line, and now I've resubmitted with the `commit <hash> upstream`.

**Comment by pelwell** [comment]
I think you need to push your updated commits - these still have the commit upstream message as the subject.

**Pull request merged**
