### PR TITLE
enable mcp2515 CAN controller module plus the corrresponding overlay

### PR DESCRIPTION
**Pull request by msperl**
added mcp251x module to list of modules to get compiled as well as the c...orresponding overlay

Overlay gets loaded like this in /boot/config.txt:

```
dtoverlay=mcp2515-can0-overlay,oscillator=16000000,interrupt=25
```

(remember to enable the spi device)

### CODE REVIEW

**Comment by notro** [comment]
This will be welcomed by a lot of users.
The massive [CAN controller forum thread](http://www.raspberrypi.org/forums/viewtopic.php?f=44&t=7027) is filled with people asking how to build these modules.

> (remember to enable the spi device)

What do you mean?

**Comment by msperl** [comment]
I meant: add the following as well to /boot/config.txt:

```
dtparam=spi=on
```

**Comment by msperl** [comment]
Actually some of this should go into some documentation of the available overlays, but there is none...

**Comment by notro** [comment]
> dtparam=spi=on

This just enables spi0.
The same thing you do in your overlay with: status = "okay";
Ref: https://github.com/raspberrypi/linux/blob/rpi-3.18.y/arch/arm/boot/dts/bcm2708-rpi-b-plus.dts#L103

> Actually some of this should go into some documentation of the available overlays, but there is none...

Phil has done lots of documentation. See /boot/overlays/README
Don't remember where the source of that recides. I have made some overlays that I haven't documented yet...

**Comment by pelwell** [comment]
The canonical source for the README is in the firmware repo, under the boot directory, although I'm starting to think that perhaps the overlay sources and the README should all move elsewhere.

**Comment by notro** [comment]
> although I'm starting to think that perhaps the overlay sources [..] should all move elsewhere

This has crossed my mind as well.

**Comment by msperl** [comment]
We could also just keep that in the wiki...
Or we put it in Documentation/devicetree/overlays

But I think that is a different discussion - so I created issue #869 to track that

**Pull request merged**
