### PR TITLE
Backporting imx219 fixes

### PR DESCRIPTION
**Pull request by 6by9**
3 patches merged into mainline. 1 which is a bug fix of the 2nd patch.

### CODE REVIEW

**Comment by 6by9** [comment]
@naush for review.

**Review by naushir — APPROVED** [review]
LGTM

**Comment by 6by9** [comment]
Ping @pelwell for merging.

**Comment by popcornmix** [comment]
Too slow.

**Comment by 6by9** [comment]
> Too slow.

I was just about to say that too, but was too slow again!

**Pull request merged**
