### PR TITLE
Initial patches to prepare the ground for Element-14 Wolfson audio support

### PR DESCRIPTION
**Pull request by manish-wolfsonmicro**
Hi all,

Wolfson would like to add support for the Element 14 Wolfson audio card.

I will be the main point of contact at Wolfson for the upstreaming of the patches to your kernel. Any support regarding the audio card should still be routed through to Element 14.

I will be pushing more patches over the next few weeks but I wanted to start pushing these particular patches to minimize the differences between the out of tree kernel and the rpi kernel.
The current patches extend the WM8804 and WM5102 drivers in order to have full audio support.

For your reference, the following link takes you to the official product page.

http://www.element14.com/community/community/raspberry-pi/raspberry-pi-accessories/wolfson_pi?CMP=KNC-EU-RPI-ACC-Wolfson

Manish Gupta

### CODE REVIEW

**Comment by popcornmix** [comment]
I wonder if you could explain the reasons for the differences required from the upstream driver?
Are these patches also intended to be submitted upstream?

In general we're not keen on out of tree drivers as it produces a maintenance burden.
However as I've seen multiple requests for official support for this card, I'm willing to be flexible.
I may require you to provide support if there are issues with the patch, or is there are complexities when porting the patch to newer kernel versions (e.g. 3.15 which is used by OpeneELEC).

I do have a Wolfson card for testing, but I guess the patches won't be testable without the future updates.

**Comment by manish-wolfsonmicro** [comment]
Sorry if I confused you, these patches have been merged upstream in the mainline kernel.  I was referring to the machine driver patches which I've not yet pushed here.  The machine driver is not merged with the upstream kernel because of the differences in the bcm layer.

I will certainly provide support for the patches that I am pushing here.

**Comment by popcornmix** [comment]
Okay, can you make it clear when patches are backports of upstream commits and point at the upstream commit. Please indicate if the patches are cleanly applied (i.e. cherry-picked) or required some conflict patches.

If a PR consists purely of backports of upstream commits, then I'm much happier accepting them (as they have already been peer reviewed).

**Comment by manish-wolfsonmicro** [comment]
Hi , 

5- ASoC: arizona: An OUTDIV of 1 is not valid, avoid this
This patch is available in linux upstream and commit id is :
commit   da28ed585b26dc6eb0c8d897a9b842a86dd6a659 (patch)

1-ASOC: WM8804: Add alsa control for SPDIF-RX 
3-ASoC: arizona: Check clocking during hw_params rather than startup 
4-ASOC: arizona: Use virtual IRQs 
6-ASoC: arizona: Disable AIF TX/RX before configuring it
These patches are not upstreamed yet and will be upstreamed to linux kernel soon.

2-ASOC: dapm: add param_fixup callback 
This patch is a short term solution and we have agreed for a long term solution after a discussion in linux community . Its better to push this as of now till we provide another solution in coming time soon.

Manish Gupta

**Comment by FishTest** [comment]
@ manish-wolfsonmicro why closed this issue.
When will we see he new progress?

**Pull request closed without merging**
