### PR TITLE
updated version of SPI driver that now runs with real time priority and ...

### PR DESCRIPTION
**Pull request by msperl**
...makes use of the onemessage interface that is available with 3.6.y

See issue 141.

### CODE REVIEW

**Comment by nneves** [comment]
Just for reference, this pull request is based on this topic discussion, right?

http://raspberrypi.org/phpBB3/viewtopic.php?f=44&t=19489

Really looking forward to see this integrated!

**Comment by msperl** [comment]
yes - correctly.

BTW: Do you have an idea how we could export THE VideoCore Bus addresses in a sane manner to drivers like this?
Because then we could make the Driver work via DMA directly without explicit requirement for allocating Pages explicitly in the DMA range. This might be of advantage the spidev device which then could allow for direct DMA to userspace without additional copying... 
Obviously this could be blocking integration with the upstream kernel...

**Comment by nneves** [comment]
Unfortunately I can not help here, I've been tracking the initial discussion and found this to be pretty interesting to a project that I want to test in near future, for a microcontroller fast data acquisition module that would also take advantage from the direct DMA access to userspace.

I just wanted to make a reference to the original discussion so that others could track all of your previous work and see how important this may be!

BTW, thank you for all your hard work!

**Comment by msperl** [comment]
No Problem - I was actually asking the Foundation if they could not also get the documentation for the Camera interface open as well - it is essentially a differential SPI interface with 2 Data lanes, so we could actually use the interface as well for SPI stuff - and actually read 2 datastreams (for ADCs) in parallel. This would be nice for my long-term-sonar imaging project where i would need to read out multiple ADCs syncronously at high frequencies...

**Comment by msperl** [comment]
What about pulling that patch in?

BTW: as to DMA (from userspace), it seems as if the dmaer (DMAHelper) could get used to make direct DMA to/from userspace a possibility. Again this is a possibility for some sampling needs. With the 512MB RPIs this might be more of interrest, as more pages can get locked in memory...

**Comment by an-roo** [comment]
This looks like great work! I'll be pulling this into my kernel right now and it should help performance for some work I'm doing on getting a radio kernel module up and running. I was worried about the SPI latencies you demonstrated on the RPi forums. 

I'll report back when I've had some time to test everything. Thanks for the good work!

**Comment by msperl** [comment]
I am closing this for now - a newer DMA version based on the upstream spi-BCM2835.c will appear at some point...

**Pull request closed without merging**
