### PR TITLE
Enable Matrix Keyboard support

### PR DESCRIPTION
**Pull request by giggls**
Hello,

Matrix Keyboard support is not enabled by default. However it does work well using a device three overwrite file and has the advantage of linux input device compatibility compared to the widely used userland solutions.

I can provide a dts example file if desired.

Sven

### CODE REVIEW

**Comment by popcornmix** [comment]
Yes, please provide the dts file too.

**Comment by giggls** [comment]
OK, I made up a DTS file for this type of Keyboard as an Example:
4x5matrix

```
    /dts-v1/;
    /plugin/;
    / {
           compatible = "brcm,bcm2835", "brcm,bcm2708", "brcm,bcm2709";

           fragment@0 {
              target-path = "/";
              __overlay__ {
                 keypad: MATRIX4x5 {
                    compatible = "gpio-matrix-keypad";
                    debounce-delay-ms = <10>;
                    col-scan-delay-us = <10>;
                    /* 
		       try to use GPIO only lines
                       to keep SPI and I2C usable
                    */
                    row-gpios = <&gpio 27 0    // 1
                                 &gpio 22 0    // 2
                                 &gpio 10 0    // 3
                                 &gpio 9 0>;   // 4

                    col-gpios = <&gpio 13 0    // 5
                                 &gpio 26 0    // 6
                                 &gpio 16 0    // 7
                                 &gpio 20 0    // 8
                                 &gpio 21 0>;  // 9
                    /*
                      Keycodes from /usr/include/linux/input-event-codes.h
                      converted to hex using printf '%02x\n'
                    */

                    linux,keymap = <
                                    // col0 row0 KEY_LEFT
                                    0x00000069
                                    // col0 row1 KEY_KP0
                                    0x01000052
                                    // col0 row2 KEY_RIGHT
                                    0x0200006a
                                    // col0 row3 KEY_KPENTER
                                    0x03000060
				    // col1 row0 KEY_KP7
                                    0x00010047
                                    // col1 row1 KEY_KP8
                                    0x01010048
                                    // col1 row2 KEY_KP9
                                    0x02010049
                                    // col1 row3 KEY_ESC
                                    0x03010001
                                    // col2 row0 KEY_KP4
                                    0x0002004b
                                    // col2 row1 KEY_KP5
                                    0x0102004c
                                    // col2 row2 KEY_KP6
                                    0x0202004d
                                    // col2 row3 KEY_DOWN
                                    0x0302006c
                                    // col3 row0 KEY_KP1
                                    0x0003004f
                                    // col3 row1 KEY_KP2
                                    0x01030050
                                    // col3 row2 KEY_KP3
                                    0x02030051
                                    // col3 row3 KEY_UP
                                    0x03030067
                                    // col4 row0 KEY_F1
                                    0x0004003b
                                    // col4 row1 KEY_F2
                                    0x0104003c
                                    // col4 row2 KEY_KPSLASH there is no KP_#
                                    0x02040062
                                    // col4 row3 KEY_KPASTERISK
                                    0x03040037>;

                 };
              };
           };
      };
```

To compile use the following command:
./scripts/dtc/dtc -W no-unit_address_vs_reg -I dts -O dtb -o 4x5matrix.dtbo 4x5matrix.dts

Then copy the resulting dtbo file to /boot/overlays/4x5matrix.dtbo and add the following to /boot/config.txt
```
dtoverlay=4x5matrix
```

Regards

Sven

**Comment by timofonic** [comment]
@popcornmix @giggls Any news?

**Comment by giggls** [comment]
Not enabled in raspberrypi-kernel 1.20171029-1

**Comment by w022a** [comment]
+1 for default Matrix Keyboard support.  My project would really benefit from this.

**Comment by pelwell** [comment]
My problem with this PR was the overlay, and the problem with the overlay was the lack of flexibility - it is a fixed size and a fixed key layout. But it is much easier for a user to install or change an overlay than it is to build a module, so that shouldn't be a barrier.

It's enabled in the 4.14 tree now.

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.

**Pull request closed without merging**
