### PR TITLE
Speed up framebuffer console text rendering

### PR DESCRIPTION
**Pull request by hglm**
These changes optimize the console framebuffer monochrome imageblit function used for text rendering in the console for 16bpp and 32bpp pixel depths. A significant speed-up is attained. Only drivers/video/cfbimgblt.c is affected.

Some benchmark results from running cat on a big text file:

Console framebuffer resolution 1280x1024, 8x16 font.

Without patch, 16bpp:

real    1m41.713s
user    0m0.000s
sys     1m41.050s

With patch, 16bpp (speed up 39%):

real    1m12.982s
user    0m0.000s
sys     1m12.840s

Without patch, 32bpp:

real    2m51.666s
user    0m0.000s
sys     2m51.350s

With patch, 32bpp (speed up 52%):

real    1m52.593s
user    0m0.000s
sys     1m52.400s

### CODE REVIEW

**Comment by popcornmix** [comment]
I would slightly prefer just the second commit.
Whilst cfbimgblt benefits from being run through indent, I fear it's going to make rebasing onto future kernels more likely to conflict, so I'd prefer the minimal change.

**Comment by hglm** [comment]
I didn't think of that. I will push a clean patch.

**Comment by hglm** [comment]
The one remaining whitespace change wasn't really intentional. I repushed. The patch should be clean now.

**Comment by popcornmix** [comment]
Thanks.

**Pull request merged**
