### PR TITLE
[8192cu] Fixes

### PR DESCRIPTION
**Pull request by fran6co**
(https://github.com/raspberrypi/linux/pull/1487) Summary of changes:
- Adds support for ISY - Edimax
- Adds support for On Networks - N150MA
- Adds support for Netgear N150 -WNA1000M
- Adds support for TP-Link TL-WN723N
- Suppress spurious messages
- Fixes https://github.com/pvaret/rtl8192cu-fixes/issues/23
- Fixes CONFIG_MULTI_VIR_IFACES
- Fixes compatiblity with 3.13
- Enables compiler warnings and general fixes
- Fixes NetworkManager not finding the device (https://github.com/raspberrypi/linux/pull/1525, https://github.com/raspberrypi/linux/pull/1489#issuecomment-224958014)

Reference repositories:
- https://github.com/pvaret/rtl8192cu-fixes
- https://github.com/diederikdehaas/rtl8812AU (realtek drivers share a common base, that's the latest I could find)

### CODE REVIEW

**Comment by fran6co** [comment]
@MrEngman I added the change you requested over here

**Comment by clivem** [comment]
@popcornmix  Just a FYI, I've been building my rpi-4.4.y kernels with this 9 patch series. Have 6x machines in my I2S test farm with RTL8188CUS dongles, generic Chinese and branded TP-Link/Edimax. Can't vouch for the patch set doing anything useful, but I haven't experienced anything negative by having it applied, FWIW.

**Comment by popcornmix** [comment]
@MrEngman - you're happy with these changes?

**Comment by MrEngman** [comment]
Yes, haven't seen any problems while testing. Been transferring data to and from my Pi and a W7 laptop on my local network using pscp, a set of files 100 x 28.7MB totalling about 2.75 GB, dozens and dozens of times without noticing any problems, unless timing differences between wifi and wired connections indicates some issue.

Typical timings in minutes:seconds:-

```
Via wifi
To Pi   - 49:21
From Pi - 37:50

Via wired cable
To Pi   - 25:15 (eth0)
From Pi - 07:00 (eth0)
```

**Comment by fran6co** [comment]
@popcornmix should I squash this commits? I wouldn't want to lose the other authors contributions.

**Comment by fran6co** [comment]
@clivem Managed to fix the issue in NetworkManager.

Here is the rundown:
- The realtek driver was initializing in NL80211_IFTYPE_MONITOR when cfg80211 is enabled.
- NetworkManager doesn't like monitor mode in cfg80211 as it can be seen here https://github.com/NetworkManager/NetworkManager/blob/1.0.12/src/platform/wifi/wifi-utils-nl80211.c#L204 (it's only parsing NL80211_IFTYPE_ADHOC, NL80211_IFTYPE_AP and NL80211_IFTYPE_STATION)
- When NetworkManager doesn't recognise the mode it just ignores the device

This change is backed up by the newer version of the realtek driver in https://github.com/diederikdehaas/rtl8812AU/blob/driver-4.3.14/os_dep/linux/ioctl_cfg80211.c#L6338

**Comment by clivem** [comment]
@fran6co LOL. I'm not going to even think about this, right now. Got my head in something else. I'll grab the patch and roll it into my next automated/continuous build.

**Comment by clivem** [comment]
@fran6co I've just rebooted 2 of my 6x 8188/8192 dongled Pi's with your patch. They are back on the network, so whatever you did, it's looking good from my POV! Thanks! I'll update the rest of them, leave them overnight, and if I cant see any other issues, I'll post back here tomorrow AM, and suggest that @popcornmix pulls this #1488 patch set, ASAP.

**Comment by fran6co** [comment]
Thanks for testing it!

**Comment by clivem** [comment]
@popcornmix Can you please pull this 10 patch series, or at least the "Starts device in station mode instead of monitor, fixes NetworkManager issues" patch, which resolves the incompatibility with NetworkManager introduced with the #1489 PR.

**Comment by clivem** [comment]
Thank you!

**Pull request merged**
