### PR TITLE
Rename README to README.md

### PR DESCRIPTION
**Pull request by ashwinrase**
File README renamed with README.md, to get visibility of syntax highlighting markdown

### CODE REVIEW

**Comment by popcornmix** [comment]
This is an upstream file untouched by us, so the patch should be directed there.
https://www.kernel.org/doc/html/v5.4/process/submitting-patches.html

**Comment by ashwinrase** [comment]
I tried but could not change it due to following restriction

image

**Comment by popcornmix** [comment]
You need to read the linked submitting patches documentation. They don't use github for merge requests.

**Comment by ashwinrase** [comment]
OK, thank you for the information

**Pull request closed without merging**
